### ISSUE TITLE
[Bug] OpenBoard v1.7.1 keeps displaying slides in larger personalized format, instead of 16:9 or 4:3

### ISSUE THREAD

**Issue by tcagnin** [OpenBoard-org/OpenBoard#1006]
### Describe the bug

On my Wacom One tablet, OpenBoard v1.7.1 keeps displaying slides in larger personalized format, instead of 16:9 or 4:3. Thus, the top, bottom, left and right parts of the slides are outside of the writing surface.
On a secondary display, the slides are displayed correctly

### To Reproduce

Configuration: 
1. Acer Laptop, 14 inches, screen resolution 1920 x 1080, Scale 125%, set as main screen; Screen 1 extended to the other screens
2. Wacom One tablet, plugged to the HDMI port and USB-A port, screen resolution 1920 x 1080, Scale 125%
3. Dell monitor 28 inches, screen resolution 1920 x 1080, Scale 100%; will be shared in Teams or Zoom during training.

How to reproduce
1. Go to Preferences, in Multi-screens, List of screens, enter 3,2; select Start in document mode
2. OpenBoard is now on the Wacom One
3. Go to Documents, create a folder, import a PDF containing a 16:9 presentation (PDF previously created from PowerPoint)

#### Expected behavior
The slides should display in OpenBoard main screen with their actual size, and correctly the 1st time out in the Display monitor

#### Actual behavior
*A clear and concise description of what actually happened*
1. Double click on 1st slide: it opens and OpenBoard displays it in a format larger than the writing zone. The Dell monitor displays a blank page instead of the 1st slide
2. Exit OpenBoard
3. Reopen OpenBoard, go to the folder, double click on 1st slide: it's still displayed in a larger format but now the Dell monitor displays it correctly (see screen capture)

### Additional resources
*PDF, images, sounds... anything useful to reproduce the bug*
![2024-06-07 11-22-22 OpenBoard Main Screen](https://github.com/OpenBoard-org/OpenBoard/assets/25958144/b899d201-1efc-4648-81a1-545ae661e1f9)
![2024-06-07 11-24-15 OpenBoard Display Screen](https://github.com/OpenBoard-org/OpenBoard/assets/25958144/96be886d-78c4-4bdd-908e-8ac9d19af4df)
![2024-06-07 11-25-33 OpenBoard Main Screen with left menu](https://github.com/OpenBoard-org/OpenBoard/assets/25958144/d0a2d33d-0675-4c0c-8cc9-97811e11d861)

### Context

  - reproducibility : `systematic` 
  - OpenBoard version :
      - bug happens with : `1.7.1`, and with previous version as far as I remember
      - didn't check : `1.6.4` `1.7.0` `1.7.1a-x.y.z`
  - OS : 
      - bug happens with : `Windows`
      - didn't check : `Windows` `Linux` `macOS` 
  - Installation source : `OpenBoard download page` `Windows`
  
### Additional context
- tried to update the config files OpenBoard.config and OpenBoardUser.config
- tried verious settings in List of displays...
- Uninstalled OpenBoard, ran Advanced SystemCare 17 Pro to purge the registry and update all pilots
- searched and deleted all OpenBoard folders
- Reinstalled OpenBoard 1.7.1
- tried OpenBoard with only Wacom One as complete slave of laptop
- tried OpenBoard on laptop only, no other devices attached
- added line DefaultPageSize=@Size(1280 960) to OpenBoardUser.config
- OS(es) detailed version (for the ones you reproduced the bug on) 
     - Windows : `Windows 11 Version 23H2`
- number and resolution of monitors : `3`, `1920 x 1080`
- manufacturer and model of graphic tablet input device : ` Wacom One`
- this bug has nagged at me for quite some time, may exist with previous versions of Windows 11 and OpenBoard

**Comment by tcagnin** [comment]
Also, OpenBoard corrupted the size of some slides when I tried to change Page size from Personalized to 16:9

**Comment by kaamui** [comment]
Could you please also attach the document used to reproduce the issue ? (export it as `ubz` (OpenBoard Document) and rename it to .zip so it can be attached here)

**Comment by tcagnin** [comment]
[01 Thriving Digital Age (6.0.1)-FR.zip](https://github.com/user-attachments/files/15740659/01.Thriving.Digital.Age.6.0.1.-FR.zip)
The bug happens with all PPTX 16:9 that I convert to PDF

**Comment by tcagnin** [comment]
Done
Cordialement,

Thierry

**Comment by letsfindaway** [comment]
See also #846, #887 and PR #901

**Comment by tcagnin** [comment]
Thanks Martin,

I'm not familiar with GitHub, how can I install the fix in PR 901?

Best Regards,

Thierry


Le ven. 7 juin 2024 à 16:31, Martin Winter ***@***.***> a
écrit :

**Comment by letsfindaway** [comment]
Sorry, I cannot help you with that, as I'm only working with Linux and cannot build for Windows.

**Comment by tcagnin** [comment]
No problem, thanks anyway :-)


Le ven. 7 juin 2024 à 17:01, Martin Winter ***@***.***> a
écrit :
