### ISSUE TITLE
[Question]How to increase fonts size

### ISSUE THREAD

**Issue by g41797** [OpenBoard-org/OpenBoard#1033]
OpenBoard v1.7.1 Flatpak
Fedora 40 
Kde Plasma 6.1
Display resolution 3840x2160
Scale 150%

Impossible (at least for me) to see text of menu etc.

How to increase font size?

Thanks

**Comment by letsfindaway** [comment]
Please see #927. Does this help?

**Comment by g41797** [comment]
Cannot check because wayland crashed during start of OpenBoard

**Comment by letsfindaway** [comment]
We have seen crashes of OpenBoard with Wayland before. See #617 and #843 for the Wayland problem, some discussions around it and a workaround. But you said that **Wayland crashes**, not only OpenBoard?

**Comment by g41797** [comment]
yes
after crash display is in standby mode

workaround:

- display off
- dislay on
- [alt-tab] alt-f4 for OB close

it's clear that it isn't OB problem
i saw this same for several applications

anyway a **lot of thanks for OpenBoard!!!**

i hope to use it in the near future
