### ISSUE TITLE
[Question] Commands for Display Management in OpenBoard 1.7?

### ISSUE THREAD

**Issue by TBKay** [OpenBoard-org/OpenBoard#1035]
The tooltip under „multi display“ in the settings suggests to me that it should now be possible to enter a list of screens to designate as main screen, expanded view, and previous slides, respectively. However, whenever I try to enter anything but a single screen number, my input is not accepted. I‘ve tried various ways of listing the screen numbers, but cannot figure out the syntax.

Does anybody know the commands or input structure necessary to actually use this feature as intended? Documentation for version 1.7 does not seem to be available yet, so I‘m asking here.

For context: I am working with a setup that uses four displays total (2 projectors, 1 touchscreen, 1 monitor). My ideal outcome is for Openboard to use the touchscreen as main display and the 2 projectors as expanded view (showing the current slide without UI) and previous slide respectively, with the monitor being used to display a zoom meeting. Right now, OpenBoard automatically occupies all four screens in multiscreen mode.

**Comment by letsfindaway** [comment]
The syntax is a comma separated list of screen numbers, no spaces.

You can also click on the grey rectangles with the screen numbers which appear on each monitor when you move the focus on the screen list entry field.

**Comment by TBKay** [comment]
Works perfectly, thank you so much! (I‘m only slightly embarrassed that commas without spaces was not one of the options I tried!)
