### ISSUE TITLE
[Question] Openboards keys have gone blank!

### ISSUE THREAD

**Issue by Bouch76** [OpenBoard-org/OpenBoard#1064]
After first getting openboard I quickly found and installed a script or similar to add swipe typing/ gesture functionality (my preferred input method) but just yesterday the keys have all turned white and illegible. I haven't changed anything either. Just thought I'd ask and see if anyone has ideas, I'm nubile so go hard, cheers.
![signal-2024-08-21-19-39-24-348](https://github.com/user-attachments/assets/248698a5-f09e-4d7b-81ed-6b09389ba332)

**Comment by kaamui** [comment]
Hi,

Wrong repo => https://github.com/openboard-team/openboard
