### ISSUE TITLE
[Bug] shortcut for stylus dont work when it is hidden

### ISSUE THREAD

**Issue by MiltonBalaOfficial** [OpenBoard-org/OpenBoard#1068]
I generally use shortcut keys to switch between stylus tools. but it does not work when stylus is hidden.

for wider writing area hiding stylus is necessary and shortcut keys are also important for quick changing of tools like selection tool, pen, eraser etc

another request: now Ctrl+I is assigned for pen, is it possible to make it Ctrl+g? because pen is used more frequently than leaser pointer, and it is easy to press Ctrl+g by left hand.

**Comment by letsfindaway** [comment]
Thanks for reporting. I'm already working on this issue and hopefully it will be fixed with the next release.

**Comment by letsfindaway** [comment]
This will be fixed in 1.7.2 as #1070 was merged.
