### ISSUE TITLE
FR: Make auto-save frequency a config parameter

### ISSUE THREAD

**Issue by Robert-M-Muench** [OpenBoard-org/OpenBoard#107]
I use OB during web-meetings to scribble things and there saving the scribbles only every 3 minutes is too long. If a crash or whatever happens too much is lost.

How about making the auto-save frequency a configurable setting? I would use something like 30s or even better on every change. With SSDs things are fast enough.

**Comment by freeheel3r** [comment]
Hi,
It already is :)
https://github.com/OpenBoard-org/OpenBoard/wiki/Settings#boardautosaveintervalinminutes

Note that the value must be an integer, so you cannot (currently) select a value of less than 1 minute.
