### ISSUE TITLE
[Bug] alphabetical ordering of documents does not work properly

### ISSUE THREAD

**Issue by MiltonBalaOfficial** [OpenBoard-org/OpenBoard#1071]
alphabetical ordering of documents does not work properly for numbers. I got a solution, but that should not be the proper solution. see the bug and the 'solution'
![image](https://github.com/user-attachments/assets/95a40d42-5fdf-4f6d-a569-08f1acb6a091)
.

**Comment by letsfindaway** [comment]
I think you mix alphabetically sorting with numerical sorting. In fact, in your screenshot both list are perfectly alphabetically sorted. Let's have a look at the pair `1024: mait` and `10: crop` and let's write them down each other:

```
1024: mait
10: crop
```

Alphabetical sorting compares corresponding characters from the left:

- `1` and `1` are equal, so let's check the next character
- `0` and `0` are equal, so let's check the next character
- `2` and `:` are different, and in alphabetical sorting the colon comes after the digit 2. 

Here comparison ends, and `10: crop` is sorted below `1024: mait`.

Your solution to add leading zeroes is the perfect way to handle this if you need numerical sorting, but only have alphabetical sorting at hand.

**Comment by MiltonBalaOfficial** [comment]
Yes, I get it. Thanks for the response.

Isnt it possible to provide manual sorting? Sometimes it is needed to sort manually for rearranging the documents. The all documents have to be renamed to place a document between the existing documents for keeping my wished order of the documents.

**Comment by letsfindaway** [comment]
> Isnt it possible to provide manual sorting? Sometimes it is needed to sort manually for rearranging the documents. The all documents have to be renamed to place a document between the existing documents for keeping my wished order of the documents.

That's your feature request #1062. I think this topic here is completed, so I'm closing it.
