### ISSUE TITLE
[Question] Where are files stored

### ISSUE THREAD

**Issue by sdmorvan** [OpenBoard-org/OpenBoard#1072]
Dear community, I am new to openboard. 
When I am in document mode, I can create folders and pages are created. If I want, I can export in pdf in a folder i can select on my internal drive (I am on OSX). 
But where are stored the raw openboard files? (I may want to backup them in an external drive, for example)
thanks
Simone

**Comment by letsfindaway** [comment]
It depends on the operating system. By default there is a folder called `document` in the same folder as `OpenBoardUser.config`. See https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration where this folder is for the different systems.

For OSX, it is `$HOME/Library/Application Support/OpenBoard/document`.

And: please be so kind to use upper/lowercase for the title of your question. It looks nicer to the reader.

**Comment by sdmorvan** [comment]
Hi thx. It should be in $HOME/Library/Application Support/OpenBoard/, but in $HOME/Library/Application Support/ there is no OpenBoard folder...

**Comment by sdmorvan** [comment]
thx, I think I found it: $Home is username and not HD..I was confused.
