### ISSUE TITLE
[Bug] Camera 

### ISSUE THREAD

**Issue by ch-westphal** [OpenBoard-org/OpenBoard#1081]
### Describe the bug
With OpenBoard 1.7.0 on Linux (debian 12.6, flatpack installation) the camera is not recognised by OpenBoard.

The "select camera" button doesn't do anything and, contrary to what I've seen on Windows descriptions, there's no request for access authorisation.

The description of the bug is very brief but if necessary I can do the tests.

### To Reproduce

1. Drag & drop the camera application
2. Click on the button for selecting camera
3.  ... nothing

![Capture du 2024-09-07 15-31-49](https://github.com/user-attachments/assets/975a710e-3017-4de8-8df7-98978f29fe58)

### Context
  - reproducibility : `systematic`
  - OpenBoard version :
      - bug happens with : `1.7.0`
  - OS : 
      - bug happens with :`Linux`
      - didn't check : `Windows` `macOS` 
  - Installation source : `flatpak`
  
### Additional context

- OS : 
    - Linux : `Debian GNU/Linux 12 (bookworm)`
 
- number and resolution of monitors : `1`  I will test with 2 soon

**Comment by letsfindaway** [comment]
Actually I have not tested that with the Flatpak version of OpenBoard. Have you a change to test it with the `deb` package I provide with my experimental builds?

See https://build.opensuse.org/package/show/home:letsfindaway:experimental/OpenBoard

The download link for the Debian 12 package would be https://download.opensuse.org/repositories/home:/letsfindaway:/experimental/Debian_12/amd64/openboard_1.7.2-rc.240815-1_amd64.deb

**Comment by letsfindaway** [comment]
Another question: X11 or Wayland? Note that OpenBoard has several issues when running with Wayland, so X11 is still recommended.

**Comment by ch-westphal** [comment]
I didn't know about this backport :-) The official debian package is only 1.6.4

The camera works perfectly and I'm running X11

On Monday I'll test it with the document camera but as it's normally recognised by cheese and webcamoid it should work fine.

**Comment by letsfindaway** [comment]
See also https://github.com/letsfindaway/OpenBoard/issues/161 for some background of my experimental builds.

I will also make the Flatpak maintainer @jbruechert aware of this issue. Perhaps he can tweak the permissions to make the webcam available.

**Comment by ch-westphal** [comment]
I'm glad I could be of some help ;-)

**Comment by letsfindaway** [comment]
Closed as updated flatpak is now published
