### ISSUE TITLE
Installation instruction link on website points to unexistent wiki page

### ISSUE THREAD

**Issue by strk** [OpenBoard-org/OpenBoard#111]
This page: http://openboard.ch/download.en.html
Has a link to: https://github.com/OpenBoard-org/OpenBoard/wiki/Install
in the "For developers" section

The wiki page does not exist so user is prompted to create it...

**Comment by strk** [comment]
I guess the correct link would be: https://github.com/OpenBoard-org/OpenBoard/wiki/Build-from-source

**Comment by Arko** [comment]
Thank you for reporting this issue, which is fixed, see: https://github.com/OpenBoard-org/OpenBoard-Website/commit/2adb823ef4a8150e63db72586cec5a968280ccbb
