### ISSUE TITLE
Erreur de compilation OpenBoard (Fedora 27)

### ISSUE THREAD

**Issue by ghost** [OpenBoard-org/OpenBoard#112]
Bonjour tout le monde !

J'ai installé OpenBoard-ThirdParty en compilant les 3 paquets linux sans aucun souci.
Ensuite, pour installer OpenBoard-master, le qmake fonctionne mais pas le make.

J'ai tout d'abord reçu le message d'erreur suivant : 

<pre>In file included from <b>src/core/UBApplication.cpp:66:0</b>:
<b>src/frameworks/UBCryptoUtils.h:34:10:</b> <font color="#CC0000"><b>erreur fatale: </b></font>openssl/evp.h : No such file or directory
 #include <font color="#CC0000"><b>&lt;openssl/evp.h&gt;</b></font>
          <font color="#CC0000"><b>^~~~~~~~~~~~~~~</b></font>
compilation terminée.
make[1]: *** [Makefile.Release:3754: build/linux/release/objects/UBApplication.o] Error 1
make[1] : on quitte le répertoire « /home/user/Documents/OpenBoard »
make: *** [Makefile:40: release] Error 2
</pre>

Erreur résolue en installant openssl-devel, openssl-perl et openssl-static (via "dnf install openssl* ")

Mais ensuite, nouveau message d'erreur lors de la compilation : 

<pre>In file included from <b>src/core/UBApplication.cpp:66:0</b>:
<b>src/frameworks/UBCryptoUtils.h:63:24:</b> <font color="#CC0000"><b>error: </b></font>le champ « <b>mAesEncryptContext</b> » a le type incomplet « <b>EVP_CIPHER_CTX {aka evp_cipher_ctx_st}</b> »
         EVP_CIPHER_CTX <font color="#CC0000"><b>mAesEncryptContext</b></font>;
                        <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~</b></font>
In file included from <b>/usr/include/openssl/evp.h:14:0</b>,
                 from <b>src/frameworks/UBCryptoUtils.h:34</b>,
                 from <b>src/core/UBApplication.cpp:66</b>:
<b>/usr/include/openssl/ossl_typ.h:90:16:</b> <font color="#06989A"><b>note: </b></font>déclaration anticipée de « <b>EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}</b> »
 typedef struct <font color="#06989A"><b>evp_cipher_ctx_st</b></font> EVP_CIPHER_CTX;
                <font color="#06989A"><b>^~~~~~~~~~~~~~~~~</b></font>
In file included from <b>src/core/UBApplication.cpp:66:0</b>:
<b>src/frameworks/UBCryptoUtils.h:64:24:</b> <font color="#CC0000"><b>error: </b></font>le champ « <b>mAesDecryptContext</b> » a le type incomplet « <b>EVP_CIPHER_CTX {aka evp_cipher_ctx_st}</b> »
         EVP_CIPHER_CTX <font color="#CC0000"><b>mAesDecryptContext</b></font>;
                        <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~</b></font>
In file included from <b>/usr/include/openssl/evp.h:14:0</b>,
                 from <b>src/frameworks/UBCryptoUtils.h:34</b>,
                 from <b>src/core/UBApplication.cpp:66</b>:
<b>/usr/include/openssl/ossl_typ.h:90:16:</b> <font color="#06989A"><b>note: </b></font>déclaration anticipée de « <b>EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}</b> »
 typedef struct <font color="#06989A"><b>evp_cipher_ctx_st</b></font> EVP_CIPHER_CTX;
                <font color="#06989A"><b>^~~~~~~~~~~~~~~~~</b></font>
make[1]: *** [Makefile.Release:3754: build/linux/release/objects/UBApplication.o] Error 1
make[1] : on quitte le répertoire « /home/user/Documents/OpenBoard »
make: *** [Makefile:40: release] Error 2
</pre>

J'ai cru comprendre via l'erreur #89 qu'il s'agissait d'un problème de version d'OpenSSL (OpenBoard utilisant la version 1.0 bien que la 1.1 soit sortie pour des raisons de compatibilité avec Ubuntu 16.04).
Est-ce bien le cas ?

Et si oui, comment puis-je résoudre ce problème ?

Bien que je sois en train d'y remédier, je ne suis qu'un grand débutant en programmation et je n'ai compilé que quelques programmes via make jusqu'à présent.

EDIT : J'ai résolu le problème en installant :

sudo dnf install compat-openssl10-devel --allowerasing

Puis, une fois l'installation terminée, on réinstalle :

sudo dnf install openssl-devel --allowerasing

Mais maintenant, le problème est tout autre. OpenBoard a fini de compiler sans aucune erreur supplémentaire mais aucun moyen de le lancer. Que faire ?

Merci d'avance !

**Comment by EQuintard** [comment]
Bonjour tout le monde !

J'ai résolu le problème en installant : 

`sudo dnf install compat-openssl10-devel --allowerasing`

Puis, une fois l'installation terminée, on réinstalle : 

`sudo dnf install openssl-devel --allowerasing`


Mais maintenant, le problème est tout autre. OpenBoard a fini de compiler sans aucune erreur supplémentaire mais aucun moyen de le lancer. Que faire ?

Merci d'avance !

Cordialement,

E. Quintard

**Comment by gagarine** [comment]
This https://github.com/OpenBoard-org/OpenBoard/pull/113 should solve the problem.
