### ISSUE TITLE
How to set 'list of screens' in preferences

### ISSUE THREAD

**Issue by tom3ld** [OpenBoard-org/OpenBoard#1133]
I would be very grateful of help to set 'list of screens' in preferences

by default all screens are used. 

I have 3 screens and I want to select 
Screen 1 main screen, screen 3 to display current slide, (screen 2 last slide - or in fact nothing)

but in the preferences I can set screen 1, 2 or 3 to have the main window, but no idea what the format/protocol/syntax is to select other screens

any help much appreciated

![image](https://github.com/user-attachments/assets/35d5461a-8007-4b46-b660-6e94e032fbc4)

**Comment by kaamui** [comment]
Hi,
by clicking on the input, you'll see display numbers appearing on top-let corners, like following: 
![image](https://github.com/user-attachments/assets/d563e72e-3dd4-42ae-8bd1-8b1b9f152ed7)

Just click on each number in the order you want !

**Comment by tom3ld** [comment]
Thanks so much for your help, really useful, I am going to close this issue, 
I really appreciate your help, thank you... and I really appreciate Openboard, very useful, nice and simple to use.

**Comment by tom3ld** [comment]
Et, un grand merci a vous aussi!
