### ISSUE TITLE
[Bizarre Design Choices] Insert Image feature / Fonts / Close without saving

### ISSUE THREAD

**Issue by vecuccio** [OpenBoard-org/OpenBoard#1135]
I am assessing Openboard as a potential replacement for my school, to replace CreateView. However immediately I ran into some deal breaking limitations that I can't believe have been implemented.

Inserting Images
You have this bizarre and incredibly unproductive way of inserting images, in that you have to drag images into a specific folder in Pictures Folder first. And even more uselessly, you MUST do this BEFORE you start Openboard else it won't even see the pictures (!!) You actually have to close and restart Openboard if you want to add new pictures (!)
Why can't it just open up a standard Windows open file box (as has been standard practice in Windows since the 1990's) and allow me to directly import the image onto the page ??

Fonts
What is going on here ? You have your own fonts folder (with a tiny selection of Adobe fonts) instead of using the installed Windows fonts ??
And worse than that, if you copy a Truetype folder into your font folder, the software doesn't even recognize it !

Close without save.
You click on 'Quit' and the software doesn't ask you if you want to save the document, it literally just quits !!

**Comment by letsfindaway** [comment]
> I am assessing Openboard as a potential replacement for my school, to replace CreateView. However immediately I ran into some deal breaking limitations that I can't believe have been implemented.

OpenBoard is different, but not worse ;)
 
> Inserting Images You have this bizarre and incredibly unproductive way of inserting images, in that you have to drag images into a specific folder in Pictures Folder first. And even more uselessly, you MUST do this BEFORE you start Openboard else it won't even see the pictures (!!) You actually have to close and restart Openboard if you want to add new pictures (!) Why can't it just open up a standard Windows open file box (as has been standard practice in Windows since the 1990's) and allow me to directly import the image onto the page ??

You have many more choices to insert an image:

- Drag-and-drop it from your favorite file manger.
- Or copy/paste it from the file manager.
- Or copy/paste or drag-and.-drop it from any application which can copy an image.
- Go to web browser mode, go to a web page with the image and right click on the image - in the context menu you have the option to add it to the board.

You might say: OpenBoard is fullscreen, how should I drag it from my file manager? Also for that there are several options:

- Use `Ctrl+Tab`  to bring another application in the foreground.
- If you have two monitors, it is even easier.
- And OpenBoard has a "RunInWindow" mode where it is no longer fullscreen, but in a normal application window. See `RunInWindow` in https://github.com/OpenBoard-org/OpenBoard/wiki/Parameters#app-section.

> Fonts What is going on here ? You have your own fonts folder (with a tiny selection of Adobe fonts) instead of using the installed Windows fonts ?? And worse than that, if you copy a Truetype folder into your font folder, the software doesn't even recognize it !

This is on purpose and avoids that documents are no longer interchangeable, e.g. between Windows and MacOS. Have you ever created a PowerPoint presentation with your fancy fonts and when you presented it on another computer all your texts looked different and are scattered around? OpenBoard wants to avoid this by limiting the fonts.

And if you want to install your own fonts anyway, you have to copy them to `customizations/fonts/` and not to `fonts/`.

> Close without save. You click on 'Quit' and the software doesn't ask you if you want to save the document, it literally just quits !!

OpenBoard saves without asking! So nothing is lost when you close the application.
