### ISSUE TITLE
[Bug] active board area shifts every time I switch pages in v1.7.2

### ISSUE THREAD

**Issue by marcopigg** [OpenBoard-org/OpenBoard#1176]
### Describe the bug
when I'm working on a file for a lesson or video, I tend to go back and forth between pages a lot, and this causes an unwanted "shift" towards the bottom right.

### To Reproduce

1. Create a new file (I usually use a black background with grid)
2. create 3-4 pages with content
3. switch back and forth between pages many times (like 20 or more)

#### Expected behavior
every time I land on a page, I expect to have the working area, enclosed in the grey border,perfectly centered

#### Actual behavior
the working area changes every time I land on the same page. The shift amounts to roughly 1 px in the bottom right direction for every page land.

### Screenshots
When I load a file, the top left corner of the page looks, as it should, like this:
![Screenshot 2024-11-27 225647](https://github.com/user-attachments/assets/ce941f56-6766-44d1-aa99-5d5dc2ebe2cc)

after 10 or so page changes, the top left corner looks like this:
![Screenshot 2024-11-27 225725](https://github.com/user-attachments/assets/afd7acce-5f31-4a14-a066-742be8df8447)

### Context
  - reproducibility : `systematic`
  - OpenBoard version :
      - bug happens with : `1.7.2`
      - bug doesn't happen with : `1.7.1`
      - didn't check : `1.6.4` `1.7.0`
  - OS : 
      - bug happens with : `Windows`
      - didn't check : `Linux` `macOS` 
  - Installation source : `OpenBoard download page`
  
### Additional context

- OS(es) detailed version (for the ones you reproduced the bug on) 
    - Linux : ` `
    - Windows : `11 `
    - macOS : ` `
- number and resolution of monitors : `1 (1920x1080) `
- if used, manufacturer and model of graphic tablet input device : ` wacom intuos pro m (PTH 651)`

**Comment by letsfindaway** [comment]
Yes, we know that. It was already reported in #1009 and we tried to analyze it. You may read the discussion we hat there. The problem depends on the Qt version we use, so it might be a Qt bug. But we still need a deeper understanding on what's going on there.

**Comment by marcopigg** [comment]
ok thanks. sorry I thought it was only a 1.7.2 issue, and didn't look back enough.
