### ISSUE TITLE
Background squares are not visible in PDF exported document

### ISSUE THREAD

**Issue by ZioKarl** [OpenBoard-org/OpenBoard#118]
Hi,
 is not proper an issue but will be very useful to have the background squares (when selected) included in the PDF exported document. 
Thanks for this great software!
Carlo.

**Comment by ZioKarl** [comment]
Hi, i see that now the background grid is more customizable.
Good job and thanks but I find this implementation almost useless if it will not appears in the exported PDF document.
Not all the students have Open-board installed on their PC and so we must export to PDF format to let them see the published lessons and, for example, in mathematics the background grid is very important to be there.
Thanks for what you can do!

**Comment by j-mak** [comment]
+1 ... i think this is nice-to-have ability, i want it too.

**Comment by andrewjjolly** [comment]
I also would like this functionality included - I exported my files for my students who like white on black and was surprised to see them all in white.
