### ISSUE TITLE
Can't use keybord shorcuts on Windows10 64bit.

### ISSUE THREAD

**Issue by harupiyo** [OpenBoard-org/OpenBoard#121]
I saw #82, but my computer does not recognize it. 
Is there any hint?

My environment:
- Windows10 Home 64bit
- OpenBoard 1.3.0

Thank you.

**Comment by harupiyo** [comment]
Hi!

I tried the new OpenBoard V1.4.0 the situation is same.
How can i any?

-----
I ❤ this project.

**Comment by ramuntcho** [comment]
See [https://github.com/OpenBoard-org/OpenBoard/issues/117](url)

**Comment by bfranske** [comment]
It's working for me on Win 10 Pro x64 Version	10.0.18362 Build 18362
