### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by Eraldo** [OpenBoard-org/OpenBoard#122]
Is it possible to export a page as an svg file?
I do understand that openboard has features that do not map to svg -- expecially the plugins/widgets.
However I am talking about the writing/drawings mainly.

Alternatively is there a way that I can convert "open board format" to svg? (extracting the vector content)?

Context: I am trying to evaluate open board as a digital whiteboard solution and svg portability is impoartant to me to be able to edit the files even if stopping to use the tool.

**Comment by freeheel3r** [comment]
Hi,
There's no need to export, OpenBoard saves each page as an SVG file natively :) 
Now, the few times I've tried to open a page in Inkscape, it didn't necessarily display correctly, but if you do run into issues with that, please report back, perhaps it would be something that can be fixed...

**Comment by fbarillon** [comment]
When I need a graphic contained in a page, I just export in pdf and open the right page with Inkscape, which is simplier than opening the ubz file.
I think the real plus would be an odg / odp import and export. I will follow a computing trainee soon, perhaps the student could work on that point.
