### ISSUE TITLE
SMARTtech pentray support (help with implementation)

### ISSUE THREAD

**Issue by Mis012** [OpenBoard-org/OpenBoard#123]
Hello,
I am making a driver for SMART 600 series whiteboard (mainly the pentray), https://github.com/Mis012/openSMART/ , and after figuring out how to talk over their lovely 'HID' protocol, I am now wondering how to implement a generic way for applications to talk to pentrays (unless someone has already done that). 

I was investigating uHID, which could probably work for both ir sensors and LEDs, I guess I would make the four pens keypad keys (pen up -> key down) with some unused scancodes (or something), and the LEDs could be 'associated' to the buttons (if I understood the HID docs). btw, multiple pens can be detected, but only one led ca be lit (it seems right now). 

Anyway, you are the one application I assume could use such feature, so I figured I'd ask you what interface you would expect for such a device, before I start making the driver.
If you're wondering, the official drivers communicate with the official app trough some sockets, but I want to do something generic, that any app can use.
Thanks for suggestions :)

**Comment by freeheel3r** [comment]
Hi,
That sounds like a great endeavor, I'm sure many users will appreciate it!

I've never used one of these white boards, what does the pen tray do exactly? From a quick google search it seems like it has buttons to select the current pen color, and similar functions.

If that is most of the functionality, then I suppose the easiest, most generic way for your driver to interact with other applications would be to send keyboard shortcuts -- ideally in a way that could be configured by the user, so that they could decide what key sequence a particular button would trigger. This way, it would immediately work with OpenBoard, with no modification necessary.

**Comment by Mis012** [comment]
The 600 series has four pens laying on IR sensors, and can sense if they are present. Near each pen is a LED that comes on when you take the pen (that is implemented by the official driver, but I can expose it with uHID - what is better?) My idea was to give it some unique scancode, so it can be used with the classic "press the key now" interfaces, but that may not be cross platform / user friendly?

**Comment by Mis012** [comment]
there are also three buttons (right click, help, keyboard) that are reported using their format

**Comment by Mis012** [comment]
OK, right now, if I understand, the most portable approach is emulating a key of choice on pen (or eraser) pickup, and when the tool is put down, emulate the key of choice for the previous tool (or no tool if all tools are down). 'Key of choice' = text config file. The LED will light for the currently selected tool, and the application cannot control the LEDs. Is that alright? 
I will test if it works with OpenBoard transparently, and let you know.
If you think there is a better approach, just let me know, I will probably not start working on it until 15+ hours from now.

**Comment by freeheel3r** [comment]
That sounds like a good approach. 

I think you're right in that OpenBoard would not be able to communicate anything to the driver. Implementing that sort of thing might require more complex communication, either through sockets or shared memory, or [something else](http://doc.qt.io/qt-5/ipc.html).

You might even be able to do both. For example, if your driver sends keystrokes and requires no feedback from the application, but offers the possibility (via some sort of inter-process communication method) for applications to control LEDs or other hardware things, then your driver would be both generic, and able to be more tightly integrated into any application.

Plus, you could start off simple by just emulating keystrokes, then adding fancier features later on.

Good luck! And don't hesitate to ask if you have any questions we can help with :)

**Comment by Mis012** [comment]
I can accept LED commands with uHID, just like a HID keyboard. I guess that there are three bits left to tell the driver that you want LED controll. I'll start working on it tomorrow.
