### ISSUE TITLE
Duplicate masks option ?

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#125]
Hello,

I wonder why masks can't be duplicated as easily as other objects, i.e. with a single click on the upper left corner icon when the object is selected.
I often have texts with many lines or words hidden thanks to masks and that would make it a lot easier/faster to set up :)

Thanks !

**Comment by ramuntcho** [comment]
Hi,

Good question and good proposal. We will look to implement it on a next build if it can be done easily.

**Comment by freeheel3r** [comment]
> if it can be done easily.

Very easily :) Only one line needs to be changed, I've just tested it and it seems to work just fine.

However, I'm not sure where to commit it, I am a bit lost with all the new branches. @kaamui, what is the main development branch now?

**Comment by kaamui** [comment]
Hello @freeheel3r 

Only 1.4-noRTPreview, preprod and master are up-to-date. I'll clean everything when dev for 1.4.1 will start. Maybe you could work on a new 1.4.1-dev branch and I'll switch on it for future work ?

Thanks for your help :)

**Comment by kaamui** [comment]
Will be added to 1.4.1 release

**Comment by celfred** [comment]
Thanks a lot !
