### ISSUE TITLE
Built-in Browser SSL Error

### ISSUE THREAD

**Issue by gagarine** [OpenBoard-org/OpenBoard#127]
OpenBoard Version: 1.4.0

![screen shot 2018-03-27 at 14 20 22](https://user-images.githubusercontent.com/164074/37966931-26663562-31ca-11e8-95b9-f366a48d50d7.png)

**Comment by ramuntcho** [comment]
As it's said in the release notes :

_Internal web navigator
Many errors, mainly on secured sites (https). The internal web navigator may be removed, for security reasons, on a future release of OpenBoard_.

We didn't find the resources to fix this problem which could take a lot of time.

**Comment by gagarine** [comment]
I see. But it's a pretty big security problem. So I agree the browser should be removed. In any case maintaining a built-in browser is complicated and raise a lot of security questions.

A button that open the default browser is certainly enough. In my point of view it's also better in term of education (digital literacy) to show a standard browser while on the web.

On top of that, I hop that schools use ad-block plugin (or better block ads networks directly on firewall). In case of plugin, it's not somethings that is trivial to implement.

So I totally understand you remove the browser. Perhaps this feature shouln't be their at the first place.

**Comment by geaplanet** [comment]
Right now I'm working on OpenSankore and evaluating the option to install Openboard instead, but this thread has made me think about whether the "Navigateur" application will disappear in the future. My document viewer is WIFI and it works through an IP on my LAN (it works like a surveillance camera). I usually drag the NavigateurWeb.wgt application into my document and enter the IP of the camera. My question is, does removing the Openboard browser also involve removing this application?

**Comment by gagarine** [comment]
@geaplanet in my opinion yes, it's a web browser. Now perhaps local IP can be authorized. At least a warning should be displayed. For your specific use case, allowing to directly connect to a USB or IP camera would be a better solution in my point of view.

Generally the question of the widget is a good one. In particular widgets that load external content like the Google Map widget. Perhaps we can allow a widget to connect to specific URL that we know we can trust. But still, it will allow some attacks.
