### ISSUE TITLE
Request: application for document viewer

### ISSUE THREAD

**Issue by introlinux** [OpenBoard-org/OpenBoard#129]
I miss some application to use a document viewer (a webcam). I remember that there was an application in OpenSankoré for this, but I never managed to make it work.

**Comment by ramuntcho** [comment]
Hi,

It's Visualiseur but i didn't use it (visualiseur.wgt). Perhaps a developer could develop such a widget for OpenBoard.

**Comment by kaamui** [comment]
Maybe something could be done easily here.

https://www.html5rocks.com/en/tutorials/getusermedia/intro/
