### ISSUE TITLE
Is it possible compile OpenBoard for 32bit linux system?

### ISSUE THREAD

**Issue by introlinux** [OpenBoard-org/OpenBoard#130]
Hi, I was wondering if it is possible to compile a 32bit version or it is impossible because of incompatibility in the code.

**Comment by ramuntcho** [comment]
Yes, it's possible ! 
But we don't have the financial resources to propose such a build.
Our forum could help you : see http://openboard.ch/forum/viewtopic.php?f=6&t=822&sid=c53f67c6f908481e97b5d6606b914ee2
http://openboard.ch/forum/viewtopic.php?f=6&t=805&sid=c53f67c6f908481e97b5d6606b914ee2

Good luck :-))
