### ISSUE TITLE
Request: please don't remove WebBrowser application

### ISSUE THREAD

**Issue by introlinux** [OpenBoard-org/OpenBoard#131]
I readed something about remove Browser from OpenBoard, please, don't remove the application WebBrowser, to include external web pages enriches presentations.

**Comment by ramuntcho** [comment]
As you can read in https://github.com/OpenBoard-org/OpenBoard/issues/127, we will be facing more and more important security issues. 
Also, to maintain a reliable and secure internal browser, it would require significant resources ... what we don't have, sorry !
As OpenBoard is an open-source project, an external developer can also contribute to the possible development of the internal browser
