### ISSUE TITLE
A query not issue

### ISSUE THREAD

**Issue by neelimafcs** [OpenBoard-org/OpenBoard#144]
Hello there,

I came across this application during my re-search for integrating white-board into one of my website. I just need some queries to be addressed please. They are:
1) Is this application can be integrated in website ? (My website is in wordpress)
2) If yes, if guide me with necessary environment and requirements
3) Also a integration guide please.

Thanks,
Neelima

**Comment by ramuntcho** [comment]
Hi,

OpenBoard is a desktop application ans can't be integrated in a website.
