### ISSUE TITLE
Is OpenBoard a safe bet (ie does it have a future?)

### ISSUE THREAD

**Issue by multixrulz** [OpenBoard-org/OpenBoard#145]
I'm the "computer guy" at a school.  We have a long history with a certain interactive whiteboard vendor that several of us would love to end.  Getting off the hardware is easy, but getting off the software is problematic.  OpenBoard is the most promising alternative I have seen, by far!  I took it for a drive today (macOS 10.13) and am very excited about the design and capabilities of the program.  I also found a number of bugs and missing essential features.

I notice that the last activity in the repo was 3 months ago.  This seems like quite a long time for a program that's supported by a government entity.  I would be keen to contribute to OpenBoard and try to convince my employer to let me work on it, if the project is active and continuing.  I cannot suggest that we move to new software that looks like it might die in the next few years.

**Comment by xdelatour** [comment]
On dev branch, the last activity was 8 days ago. The stable version 1.4.0 was released three months ago.

**Comment by multixrulz** [comment]
Awesome.  I'll start talking to people here and see what sort of commitment I can get to use OpenBoard and contribute to it.

**Comment by ramuntcho** [comment]
OpenBoard is an active project, but despite the fact that the canton of Geneva and the University of Lausanne support it, our financial resources and development time are limited. We have more than 2,000 OpenBoard installations in Geneva, so this project has for now a future !!!
See our [url=https://github.com/OpenBoard-org/OpenBoard/wiki/Roadmap] roadmap[/url]
