### ISSUE TITLE
OpenBoard AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [OpenBoard-org/OpenBoard#147]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__A test AppImage is available at https://github.com/probonopd/OpenBoard/releases. Please test it.__ 

If you are satisfied with it, I will send a pull request that will compile OpenBoard on [Travis CI](https://travis-ci.org/) upon each `git push`, and will upload an [AppImage](http://appimage.org/) to your GitHub Releases page automatically.

**Comment by probonopd** [comment]
Looks like on Fedora 28 libnsl is no longer part of the glibc package, and is no longer installed by default. Please install the `libnsl` from your distribution. I consider things like this [Desktop Linux Platform issues](https://gitlab.com/probono/platformissues).

I am not sure whether bundling a private copy of libnsl (copying the one from the build system into the AppImage) would work, as it used to be part of glibc and glibc is known to not react well to version mismatches of its components. I would appreciate any insigt/tests on this.

References:
* https://github.com/knapsu/plex-media-player-appimage/issues/13
* https://github.com/AppImage/AppImages/issues/336

**Comment by fanningert** [comment]
You are right libnsl2 is installed. But version 1 must be installed manuell. Thanks for your help.
After installation OpenBoard is working.

```
dnf install libnsl
```

**Comment by magicvince** [comment]
I could launch the appimage, but I've somme issues with multiscreen on two differents configurations/
1- On a dual screen where the main desktop is set on the right, the openboard main window open on the left and when I enable multiscreen, the board appear in front of the main openboard's window. Using Alt+F7 is a solution to move the main window on the right screen. But if I used browser or desktop (not working) function, the main window reappears on the left.
2- It's better if my main screen is on the left, but i stil hava a problem with desktop function: the desktop  is uneasy to use and seems to work on the same screen. The "desktop" is a view of the windows back the board, not back the main windowss.

Seems to work if I'm using "duplicate screen".

**Comment by probonopd** [comment]
@magicvince does the same work if you use a non-AppImage version?

**Comment by magicvince** [comment]
I can't tell, the deb doesn't work with debian stretch and I'm unable to compile the source for my stretch without issue

**Comment by artemanufrij** [comment]
Works very well on archlinux (plasma)

**Comment by helge42** [comment]
Hi,
works on Debian 9 ! Thank you very mauch.

Can you make Version 1.4.1 available?

**Comment by magicvince** [comment]
Other issue: when I use "multiscreen function", the cursor doesn't appear on the board screen, but only on the desktop screen (specialy when I use the desktop mode).
(But I'll continue to be happy to test your appimage, and I'm ok with helge to test a new version :))

**Comment by kaamui** [comment]
Thank you a lot for your help. 

Due to our limited resources, we don't have much time to test your work, but we noticed it and will try as soon as we can to see what we can do to integrate it. 

If anybody encounters some issues, please let us know here.

**Comment by Symbian9** [comment]
@probonopd, any news on successful reproducible AppImage builds?

**Comment by probonopd** [comment]
I have it working since a year. The question is, when will @kaamui merge it?

**Comment by ppdouble** [comment]
> Hi, on Fedora 28 I get following error, when I start the AppImage.
> 
> ```
> # ./OpenBoard-x86_64.AppImage 
> ./OpenBoard-x86_64.AppImage: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
> ```
> 
> Fedora 28 is using Glibc 2.27.

fedora 29 x86_64 works after `sudo dnf install libnsl`

```
$ sudo dnf install libnsl
Dependencies resolved.
================================================================================
 Package                   Arch         Version             Repository     Size
================================================================================
Installing:
 libnsl                    x86_64       2.28-33.fc29        updates        89 k
Upgrading:
 glibc                     i686         2.28-33.fc29        updates       3.5 M
 glibc                     x86_64       2.28-33.fc29        updates       3.8 M
 glibc-all-langpacks       x86_64       2.28-33.fc29        updates        25 M
 glibc-common              x86_64       2.28-33.fc29        updates       807 k
 glibc-devel               x86_64       2.28-33.fc29        updates       1.0 M
 glibc-headers             x86_64       2.28-33.fc29        updates       468 k
 glibc-langpack-en         x86_64       2.28-33.fc29        updates       818 k
```

**Comment by probonopd** [comment]
This should no longer be an issue, since we are no longer blacklisting libnsl due to Fedora it shipping with glibc no more.

**Comment by aoloe** [comment]
Yes, please provide an Appimage.

If you need help, please get in touch with me.

For another Qt based project, I'm maintaining an Appimage (with Continuous Integration!) that has been created together with @probonopd .

It's amazing to see how many people uses it, once it's available!

**Comment by dmsoler** [comment]
Hi.
As you can see, I didn't know there already was an AppImage effort and discussion in this project. It's not evident [in your web](http://openboard.ch) or in [this issue](https://github.com/OpenBoard-org/OpenBoard/issues/328). And it's a pitty: the impression users have is you need Ubuntu to use OpenBoard, and many people (including me) will not change distro to get a single app working...

In the past I compiled myself a working *.deb package for Debian Sid, but it is a lot of work... For your last release I tried to make a AppImage and it is working. I contributed the recipe I have for my personal use to [pkg2appimage](https://github.com/AppImage/pkg2appimage/pull/422).

OpenBoard's AppImage just works. And it is a good way of using it for people like me that don't use Ubuntu. Why not an official release of OpenBoard in AppImage format? The work is done by @probonopd ...

**Comment by probonopd** [comment]
Hi, I am happy to help resolve any remaining issues if you can point me at something that I can reproduce. Thank you very much.

**Comment by dmsoler** [comment]
I have the AppImage I built with pkg2appimage + [this recipe](https://github.com/AppImage/pkg2appimage/pull/422) working on a Debian Sid with no issues. I can also try to reproduce any issue you may encounter if it could be useful.
