### ISSUE TITLE
Query: Change podcast save location ?

### ISSUE THREAD

**Issue by anate** [OpenBoard-org/OpenBoard#151]
After creating a podcast, it gets automatically saved to desktop. Is there a means to change the save-to location and also change the podcast name?
Using windows 8.1

**Comment by freeheel3r** [comment]
There is no way to do this from within the app, but you can set a default save location in the settings. 
Open the user settings file (see [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Settings) for where it's located), and add at the end:

    [Podcast]
    RecordingDirectory=/path/to/where/you/want/to/save/your/podcasts

(If there is already a line starting with `[Podcast]` in your settings file, you can just add the `RecordingDirectory` line underneath it)

Unfortunately there is no way to change the default file name.

**Comment by anate** [comment]
yep that worked.. Thanks
