### ISSUE TITLE
openboard_Installer_1.4.1 downloaded from the github seems to contain a trojan/bitcoin miner....

### ISSUE THREAD

**Issue by bveina** [OpenBoard-org/OpenBoard#156]
long time user of openboard, however when installing on a new machine windows 10 will not let the program run.

windows defender detects:
Trojan:Win32/Azden.B!cl
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fAzden.B!cl&threatid=2147723291

i have not tried compiling from source, to see if its a misdiagnosed threat.

im on a windows 10 machine, downloaded the 1.4.1 installer.

**Comment by Arvil** [comment]
Can you validate your file on virustotal ? I do not get any warning https://www.virustotal.com/#/file/8d1e541844ceaf24484738b34ddc3c869bc33b9da61f6a8976364bf6ad94eba2/detection

**Comment by Pascal-KOTTE** [comment]
Just install 1.4.1 windows 10, Windows defender used, update 20 juillet, pas de souci !

**Comment by Cstructor** [comment]
Same here. Virus found.

**Comment by bpiet2000** [comment]
Virus also found.

![capture](https://user-images.githubusercontent.com/7038659/43611548-1831c358-966f-11e8-8b79-112ab42c91da.PNG)

**Comment by kaamui** [comment]
This is probably a false positive from Windows Defender. I sent a submission on the Microsoft site so they can confirm it as a wrong detection. 

The sha256 sum is the same as the build I made, the md5 sum too, I re-scanned it on Virus Total and nor Kaspersky neither F-secure or other solid names in security detected a trojan or anything in it. 

The Microsoft submission details page also seems to check with the current release and a pre-release (internal) build. On the last and newest version of Windows Defender, the detection is no longer positive.

https://www.microsoft.com/en-us/wdsi/submission/8e6b598f-9691-4116-bc87-9e5d06f295e6

**Comment by bveina** [comment]
updated windows defender from july 31 definitions to august 3rd definitions. same install file is no longer recognized as a trojan. this no longer seems to be an issue. Thank you for all your work.

**Comment by kaamui** [comment]
Hello,

Here's the answer for the submission. Please follow the instructions to update your Windows Defender definitions.

Thank you.

> Thank you for your inquiry.
> We have reviewed the file and we have removed the detection. 
> Please try the following steps to clear cached detections and obtain the latest malware definitions.
>  
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 
> The latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Best regards,
> Windows Defender Response
