### ISSUE TITLE
[bug] .desktop file broken

### ISSUE THREAD

**Issue by D1mon** [OpenBoard-org/OpenBoard#157]
`ls -l /usr/share/applications/openboard.desktop`

> lrwxrwxrwx 1 root root 53 Jul  6 02:50 /usr/share/applications/openboard.desktop -> /tmp/yaourt-tmp-dimon/aur-openboard/openboard.desktop

**Comment by artemanufrij** [comment]
Same here. Just installed latest version on ArchLinux

**Comment by kaamui** [comment]
Hi,

The only officially supported operating system on Linux is Ubuntu 16.04 LTS. What package did you download and how ? Did you try without using Yaourt ?

**Comment by D1mon** [comment]
manjaro - yaourt(aur)
