### ISSUE TITLE
Cursor not visible clearly on Openboard

### ISSUE THREAD

**Issue by Veek** [OpenBoard-org/OpenBoard#161]
How do I fix the cursor? [Screenshot of Openboard with no visible cursor](http://pix.toile-libre.org/upload/original/1536038266.png)

**Comment by kaamui** [comment]
Hi,

You can edit this on the preferences, under the "Pen" Tab. Depending on your needs, you can either simply uncheck the preview circle, or make it appear for upper sizes, and also change the three fixed width for the pen.

Hope it helps.

**Comment by rafisics** [comment]
I am also not satisfied with the cursor color. I think it would be better to get different bright cursor-colors (such as red, yellow) corresponding to the different background colors.
