### ISSUE TITLE
Duplication when clicking "next slide" (with laser pointer)

### ISSUE THREAD

**Issue by hkiel** [OpenBoard-org/OpenBoard#163]
When I import a document from pdf, display it, select the laser pointer tool, "draw" with the laser pointer and then click "next page" then OpenBoard crashes. When I restart and open the document that crashed, I see the page on which OpenBoard crashed has been duplicated.

Happens only if I do the actions (laser pointer and click for next slide) with a Pen or finger (not mouse). I'm using 1.4.1 on win10 (Surface Pro with Surface Pen)

In some cases when I played around with the mouse and then switch to pen, the actions seem to duplicate the page, but not crash.

Same on 1.4.0, but seems to work fine on 1.3.6

**Comment by kaamui** [comment]
Hi,

did you try with the latest version of OpenBoard, is it still the same ?

**Comment by hkiel** [comment]
With 1.5.1 OpenBoard does not crash anymore, but it still duplicates the page.
Mind you, I can only reproduce this with finger or pen, NOT with mouse.
