### ISSUE TITLE
Please switch from bundled XPDF to libpoppler (or offer it as alternative at least)

### ISSUE THREAD

**Issue by sunweaver** [OpenBoard-org/OpenBoard#168]
I wrote a patch for the upcoming Debian upload of OpenBoard:
https://salsa.debian.org/debian-edu-pkg-team/openboard/blob/master/debian/patches/1003_build-against-poppler.patch

**Comment by sunweaver** [comment]
I just updated the patch, so it also works with poppler < 0.58 (e.g. with 0.48 as found in Debian stretch).

**Comment by sunweaver** [comment]
I patched the XPDFRenderer.(cpp|h) files in place, but the file should rather be renamed to PopplerPDFRenderer.(cpp|h).

**Comment by sunweaver** [comment]
Gnaaa... the detection of POPPLER_NEW_OBJECT_API does not yet work, as it should. I'll need to take another look on Monday.

**Comment by sunweaver** [comment]
does it work with ``const GooString *gstring = title.getString();`` ? (I am too lazy to re-visit the poppler API documentation right now...).

**Comment by toddrme2178** [comment]
That seems to work.  This seems to be an API change in poppler 0.64.

**Comment by kaamui** [comment]
Thank you for this one. 

Sadly, we cannot investigate on this for the moment, but switching from xpdf to another solution is in our todo list, and when it will become possible, we'll check your work seriously. Can you make a pull request with only this work ?

Also did you do some benchmarks on it ? I am curious to see the impact on performances. Regarding the PDF rendering of some pages (import a PDF as an OpenBoard Document) in heavy documents or ill-structured heavy PDFs

Thanks in advance.

**Comment by sunweaver** [comment]
@kaamui: can you provide a test case PDF? PR will come soonish.

**Comment by sunweaver** [comment]
@kaamui: an atomic PR is not 100% trivial. What I can do is a PR stack with the following changes:

  * don't use ThirdParty repo on linux
  * fix quazip include headers ``<quazip.h>`` as opposed to ``"quazip.h"``
  * copy over QtSingleApplication into openboard repo directly
  * build against poppler

Would that be interesting? IMHO, the Linux OpenBoard should not be using OpenBoard-ThirdParty at all. It is not required (with the xpdf2poppler shift) and then it becomes immediately more distro policy compliant.
