### ISSUE TITLE
Please switch to OpenSSL 1.1.x

### ISSUE THREAD

**Issue by sunweaver** [OpenBoard-org/OpenBoard#169]
Patch available here:
https://salsa.debian.org/debian-edu-pkg-team/openboard/blob/master/debian/patches/1002_support-openssl-1-1.patch

**Comment by juanjosepablos** [comment]
It is not the same as #113 ?

**Comment by kaamui** [comment]
Thank you for the help. 

The support of OpenSSL 1.0, 1.1 or both is going to be discussed internally soon.  With the future support of Ubuntu 18.04, a decision may be made.

Please continue/follow the discussion here => #113
