### ISSUE TITLE
Update system doesn't seem to works

### ISSUE THREAD

**Issue by gagarine** [OpenBoard-org/OpenBoard#171]
Their is a menu to check if their is an update:
![screenshot 2018-09-25 at 18 33 29](https://user-images.githubusercontent.com/164074/46028708-9a1c5700-c0f1-11e8-8653-7a4140ec642d.png)

But it doesn't seem to works. I'm using the 1.4.0 and it say "no update" even 1.4.1 out. 

I'm using the MacOS version.

**Comment by ramuntcho** [comment]
Thank's for this remark, we forgot to update the file listing the latest version. Fixed
