### ISSUE TITLE
nested structure for Documents

### ISSUE THREAD

**Issue by nicoroud** [OpenBoard-org/OpenBoard#172]
Hello
Is there a way to have nested structure like Open-Sankore in OpenBoard ?
Like this :
![screenshot_20180925_193841](https://user-images.githubusercontent.com/17413889/46032088-f9329980-c0fa-11e8-90b0-4c584a80b0b4.png)
Cordially,
Nicoroud

**Comment by ramuntcho** [comment]
The best way is to have money and development time, which is not easy!
But we are working on it and the upcoming version 1.5 will have this feature.
