### ISSUE TITLE
Desktop Mode Problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by audimax85** [OpenBoard-org/OpenBoard#174]
Hi
i have Ubuntu 18.04 running an i tried using Openboard 1.4.1, 1.4.0 and 1.3.4.
When i change into desktop mode everything seems fine and i can scroll windows of other applications by using the mouse wheel or touch pad, copy parts of the screen using the mouse or the stylus....
If i click into a window the toolbox is no longer in the foreground. I can get it back by getting the focus on openboard. The next time i click into a window the toolbox is gone again. It just won't stay on top.
This makes the desktop mode almost unusable.
Any Ideas?
bye max

**Comment by kaamui** [comment]
Thank you for the feedback.

These versions of OpenBoard are no longer supported, as we only focus on supporting the latest release, because of our limited resources. 

However, we are going to start the support of Ubuntu 18.04 soon (1.5.3), so it might help.
