### ISSUE TITLE
Multipage screen. Is it possible?

### ISSUE THREAD

**Issue by Branston18** [OpenBoard-org/OpenBoard#176]
Is it possible to do multi screen display on Openboard please. I would like to be able to show more than one page on the screen at a time similar to the split screen in Notebook.

**Comment by ramuntcho** [comment]
Sorry, it's not possible

**Comment by kaamui** [comment]
As @ramuntcho said, it is not possible, and won't be considered for the moment as we have a lot of things to do first.

Thank you for your support.
