### ISSUE TITLE
OpenBoard for KDE neon (based on Ubuntu 18.04) dependency problems.

### ISSUE THREAD

**Issue by 842Mono** [OpenBoard-org/OpenBoard#177]
Hello! I'm trying to install OpenBoard on KDE neon that is based on Ubuntu 18.04. Neon has "Plasma" as the desktop environment. I have downloaded the Debian package from the website, however I get dependency problems when I try installing it.

```
dpkg: dependency problems prevent configuration of openboard:
 openboard depends on libavformat-ffmpeg56 (>= 7:2.8.14); however:
  Package libavformat-ffmpeg56 is not installed.
 openboard depends on libswscale-ffmpeg3 (>= 7:2.8.14); however:
  Package libswscale-ffmpeg3 is not installed.
 openboard depends on onboard; however:
  Package onboard is not installed.
```

I can't install those dependencies.

```
sudo apt install libavformat-ffmpeg56
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libavformat-ffmpeg56 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavformat-ffmpeg56' has no installation candidate
```

```
sudo apt install libavformat57
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavformat57 is already the newest version (7:3.4.4-0ubuntu0.18.04.1).
libavformat57 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 openboard : Depends: libavformat-ffmpeg56 (>= 7:2.8.14) but it is not installable
             Depends: libswscale-ffmpeg3 (>= 7:2.8.14) but it is not installable
             Depends: onboard but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

```
sudo apt install libswscale-ffmpeg3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libswscale-ffmpeg3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libswscale-ffmpeg3' has no installation candidate
```

```
sudo apt install onboard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 onboard : Depends: onboard-common (< 1.4.1-2ubuntu1.1) but it is not going to be installed
           Depends: onboard-common (>= 1.4.1-2ubuntu1) but it is not going to be installed
           Recommends: onboard-data (>= 1.4.1-2ubuntu1) but it is not going to be installed
 openboard : Depends: libavformat-ffmpeg56 (>= 7:2.8.14) but it is not installable
             Depends: libswscale-ffmpeg3 (>= 7:2.8.14) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by dridk** [comment]
Same for me ! 
But thanks to AppImage, I can run OpenBoard easily  ! see #147 or download the image here https://github.com/probonopd/OpenBoard/releases and run it

**Comment by kaamui** [comment]
Hi everyone,

We are aware of the dependency issues on any newer version than Ubuntu 16.04 LTS. A work on the Ubuntu 18.04 LTS is going to start soon, and should be available for the release of OpenBoard 1.5.3. 

Note that following this release, and due to our limited resources, Ubuntu 16.04 LTS will no longer be delivered. 

For any build on a not directly supported OS, you should consider trying to build it from the sources, or try one of the various alternatives offered by our great community (#58, #138, #147,  #170)

**Comment by sunweaver** [comment]
Please note that starting with Ubuntu 19.10 (that is the plan), OpenBoard will be official packaged and available via Ubuntu's universe repository area.

Of course, Ubuntu will only provide one OpenBoard version per Ubuntu release, if you want to use regular OpenBoard release from an official distro repository, then you can switch to Debian testing.

**Comment by aleixpol** [comment]
You can use it from flathub, no?
https://flathub.org/apps/details/ch.openboard.OpenBoard

**Comment by ytzemih** [comment]
Hi, are there any plans to provide _packages_ working on Ubuntu distributions newer than 18.04 _or guidance_ on how to build OpenBoard on such distros? I have created a [question on SO](https://askubuntu.com/questions/1236551/how-to-install-openboard-on-ubuntu-19-10) if anyone has instructions/experience to share? Thanks
