### ISSUE TITLE
1.5.0 : Dark mode by default

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#179]
Hello,
I've just installed v1.5.0 on my Ubuntu 16.04. Thanks for the great work concerning the Document mode !
I used to start in dark mode. In my config file, I had the DarkBackground=true line and it worked. Now if I manually write this line, OpenBoard always starts with a white background and the line is automatically modified to DarkBackground=false.
It's not a big issue, but I thought I'll let you know :)
Thanks again for the great work !

**Comment by ramuntcho** [comment]
This is not correct and we will examine this problem.

**Comment by kaamui** [comment]
Thank you for the feedback. This issue has been fixed in the 1.5.1 release that is now available. 

Thanks again, your help is precious !
