### ISSUE TITLE
In desktop mode, the built-in virtual keyboard cannot input content into the file. 

### ISSUE THREAD

**Issue by oneday1992** [OpenBoard-org/OpenBoard#182]
In desktop mode, the built-in virtual keyboard cannot input content into the file. Such as a txt file

My use environment is under windows system

Added: And when you click on the keyboard in the desktop toolbar, the brush can't do desktop annotations.

who can help me？

**Comment by kaamui** [comment]
Thank you for your feedback.

 In Desktop mode, the built-in keyboard won't work on external applications (such as a text editor, navigator).

On Windows, when in Desktop Mode, you can directly use the native visual keyboard provided by Windows, by taping "keyboard" on the start menu, but writing a text block is not available in the Desktop Mode. However you will be able to write on text editors and navigators.

hope it helps.

**Comment by yuluhuang** [comment]
I think I need it, writing on the desktop like a note, so I bought a drawing board.

**Comment by oneday1992** [comment]
Now that the problem has been solved, directly call the system's own soft keyboard

**Comment by yuluhuang** [comment]
您好，邮件已收到，尽快给您回复。
