### ISSUE TITLE
Are EcritureA+B fonts still used (they are non-free fonts)?

### ISSUE THREAD

**Issue by sunweaver** [OpenBoard-org/OpenBoard#186]
By grepping through the code, it seems that EcritreA+B fonts are not used anymore. Would it make sense to remove all references to them then? (I About dialog under credits).

I have a similar patch for the Debian package, but it removes credits for all fonts:
https://salsa.debian.org/debian-edu-pkg-team/openboard/blob/master/debian/patches/2006_no-font-credits.patch

Let me know if I shall send a PR.

**Comment by kaamui** [comment]
Hi,

They are used, you can find them as a font choice when using the text tool. 

These two fonts are under CC so you can totally use them I think. They are provided by the French Ministry of Education  as you can see by clicking the link in the credits. 

Why would you remove the credits for all the fonts by the way ?

**Comment by sunweaver** [comment]
Hi,

On  Mi 23 Jan 2019 09:12:58 CET, kaamui wrote:

> Hi,
>
> They are used, you can find them as a font choice when using the text tool.
>
> These two fonts are under CC so you can totally use them I think.

They are licensed under CC BY-ND [1]. And CC BY-ND violates Debian  
Free Software Guideline #3 [2]. See [3] for discussions on  
debian-legal mailing list back in 2013 (situation still applies today).

> They are provided by the French Ministry of Education  as you can  
> see by clicking the link in the credits.

Yes. And those fonts are free as in free beer, not free as in freedom.  
Unfortunately. (Maybe people on your team have connections to the  
French Ministry of Education and can invoke a license change [4]). If  
the French Ministry of Education is the copyright holder of the fonts,  
then they can change the license, if they want to.

> Why would you remove the credits for all the fonts by the way ?

Because in Debian, we have /usr/share/doc/ and the official OpenBoard  
Debian package won't bundle those fonts. In fact, I remove all fonts  
from the upstream tarball (with many other files) and repack the  
tarball. So, those fonts are not bundled, why should I credit for  
them? They are in Debian anyway and have their own section under  
/usr/share/doc/.

Hope this explains my DFSG reasonings behind things.

Mike

[1]  
http://eduscol.education.fr/cid72979/polices-de-caracteres-cursives-pour-l-enseignement-de-l-ecriture.html
[2] https://www.debian.org/social_contract
[3] https://lists.debian.org/debian-legal/2013/08/msg00012.html
[4] https://wiki.debian.org/DFSGLicenses
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by kaamui** [comment]
Thank you for your quick reply. 

I'm not sure we'll be able to do something on this, sadly...
I'll see this with the team, and let you know here if we find a solution about it.

**Comment by sunweaver** [comment]
On  Mi 23 Jan 2019 11:00:35 CET, kaamui wrote:

> Thank you for your quick reply.
>
> I'm not sure we'll be able to do something on this, sadly...
> I'll see this with the team, and let you know here if we find a  
> solution about it.

Thanks for discussing it with the team.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by kaamui** [comment]
Hi,

These fonts are strongly used by the end-users and cannot be removed.
