### ISSUE TITLE
Porting from Qt Webkit to Qt WebEngine

### ISSUE THREAD

**Issue by kaamui** [OpenBoard-org/OpenBoard#193]
Hello everybody, 

we are currently studying the possibility to upgrade OpenBoard to the latest qt build. It is not going to happen in the really next releases, but it is really something  we are thinking of. 

The main issue of upgrading the qt version of OpenBoard relies on the fact that starting Qt 5.6, the WebKit dependency of Qt has been replaced by the use of the WebEngine. 

Apart from the obvious rework/adaptation needed on the internal navigator, the main issue with this porting is the rework/adpatation of the UBGraphicsWidgetItem class. This class inherits from QGraphicsWebView witch has not been replaced by anything in the WebEngine, as explained [here](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html)

The advantage of this class, as described [here](http://doc.qt.io/archives/qt-5.5/qgraphicswebview.html#details), was to allow web content to be attached to a view, but also to be handled as a QGraphicsItem (very important in OpenBoard). 

In the WebEngine, but maybe there is some good reason, no such class is provided and I actually don't have much time to investigate on what type of class could replace it, or to study why it is no longer available and if we should reconsider this UBGraphicsWidgetItem or not. 

Do somebody have any clue about this ? Any help is welcome !

Thank you.

**Comment by JBBgameich** [comment]
Porting to QtWebEngine is not a strict requirement for upgrading Qt. OpenBoard runs perfectly fine on Qt 5.12, if you compile QtWebKit from source. You can find it on https://github.com/qt/qtwebkit/releases.

Of course, porting to the QtWebEngine is a better solution in the long run :)

**Comment by JBBgameich** [comment]
A workaround for replacing QGraphicsWebView could be https://forum.qt.io/topic/73381/qwebengineview-inside-qgraphicsview-with-qgraphicsproxywidget/2

**Comment by Apteryks** [comment]
Hello! Could this issue be reopened?  It seems qtwebkit has been obsoleted by qtwebengine by Qt, and the community maintained fork (https://github.com/qtwebkit/qtwebkit/releases) hasn't seen a fresh release nor commits in a while (the last one was in 2020).

Because of this, it's is scheduled to be removed from the GNU Guix distribution, and I expect it's happening elsewhere too; this will prevent Openboard from being packaged for such distributions, which is a pity.

Thank you!

**Comment by letsfindaway** [comment]
This work is already on the way! Please have a look at

- Branch [1.7-dev](https://github.com/OpenBoard-org/OpenBoard/tree/1.7-dev) which is based on `QWebEngine`
- My [project](https://github.com/letsfindaway/OpenBoard/projects/1) making these modifications
- An additional [pull request](https://github.com/OpenBoard-org/OpenBoard/pull/545) fixing some issues and adding a better cookie handling
- These [builds](https://build.opensuse.org/project/show/home:letsfindaway:experimental) of experimental versions of this branch with some more of my pull requests included

**Comment by Apteryks** [comment]
I've tried it, and it worked better than the older qtwebkit based one, at least on Guix! Thanks.
