### ISSUE TITLE
latest update losing some images 

### ISSUE THREAD

**Issue by edmondns** [OpenBoard-org/OpenBoard#197]
Hello and thank you for the great work
I didn't use opensankore due to the same issue but I used openboard without any problem for more than 2 years now and it was great.
After the latest update, I go to the pages I prepared and I see in the thumbnail all the pictures, parts of screenshots but as soon as I open the page, I can only see the handwritten notes and text but no pictures.
it's especially problematic for a moved page, if I use cut and paste in ordrer to rearrange my board.
Can you please find a solution because all my course is on openboard now and I don't want to lose it.
Is it a good idea if i go back to an earlier version?
thank you

**Comment by kaamui** [comment]
Hello,

It could be related to the fact that we introduced the "open-sankore" document mode since 1.5.0, can you provide us at least one document that causes the issue to appear ? 

Thank you.

**Comment by edmondns** [comment]
Thank you for your reply
Do you think it's better for me to revert back to the pre 1.5.0 version? As I never had any issue before.
It's annoying because before the document is closed eveything seems fine, but as it's opened some photos get lost, but not all, i really don't know how to reproduce it.
As soon as it happens again, i will export the file and send it to you.
Thank you very much

**Comment by kaamui** [comment]
Hello,

Can you try to re-open the document with the missing content in a 1.4.1 release ? I try to understand if the document still contains the missing content but cannot display it or if the content has been erased totally. 

Do you have any clue to reproduce it ?

**Comment by edmondns** [comment]
thank you, I just got a new error, it really appears randomly, as an image is available I can use it for several days and out of nowhere I find an image missing
as in this example: I can see an image in the thumbnail but nothing at all in the last page.
I'm happy it doesn't affect every image. It's more than annoying if it's lost during class time.

[Les fonctions 2.zip](https://github.com/OpenBoard-org/OpenBoard/files/2952042/Les.fonctions.2.zip)
it concerns the last page
![{12E5A442-7D4D-4C94-BB38-4FF46F11285D} png](https://user-images.githubusercontent.com/22116530/54122361-1cc57400-43fd-11e9-9e8e-30c2bdd98c93.jpg)

I will keep on using 1.5.2 but it's very stressful
I hope I won't get any more lost images.

Thank you for your help

**Comment by edmondns** [comment]
I checked in the document folder
the image appears to be still here.
Maybe the link got corrupted?
![image](https://user-images.githubusercontent.com/22116530/54123194-5bf4c480-43ff-11e9-997f-5c632954888d.png)
Thanks again

**Comment by kaamui** [comment]
hello,

thank you for your help. Some work has been done on images loss and may be related to the issues you encountered. The 1.5.3 release is now available on github.

Let us know if it helped.

**Comment by edmondns** [comment]
Thank you again,
I downloaded it, I'll report back in both cases resolved or not.

**Comment by kaamui** [comment]
Hello,

Do you still experience image loss ?

**Comment by edmondns** [comment]
Hello, I don’t think it occurs anymore and if it does it’s more than rare.
Thank you so much for your help

Provenance : Courrier pour Windows 10

De : kaamui
Envoyé le :lundi 29 juillet 2019 10:09
À : OpenBoard-org/OpenBoard
Cc : edmondns; Author
Objet :Re: [OpenBoard-org/OpenBoard] latest update losing some images (#197)

Hello,
Do you still experience image loss ?
