### ISSUE TITLE
Version number missing on windows

### ISSUE THREAD

**Issue by juanjosepablos** [OpenBoard-org/OpenBoard#202]
The version number is missing on windows. Apply this simple patch to fix it:

--- OpenBoard.iss	2019-02-24 12:14:22.336684297 +0100
+++ OpenBoard.iss.new	2019-02-24 12:10:13.514696287 +0100
@@ -10,7 +10,7 @@
 ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
 AppId={{8CCA6AC7-BBF9-4DD2-8E70-A907E0FCA38F}}
 AppName=OpenBoard
-AppVerName=OpenBoard {#ApplicationVersion}
+AppVersion={#ApplicationVersion}
 AppPublisher=Open Education Foundation
 
 AppPublisherURL=http://www.oe-f.org

**Comment by juanjosepablos** [comment]
I have add a pull request on #203

**Comment by kaamui** [comment]
Hello,

Your timing is perfect ! It is actually something we were planning to handle for the next release. I'll merge you request with the dev branch soon.

Thank you for your help.

**Comment by juanjosepablos** [comment]
I just download openboard 1.5.3 to test this issue, and still not showing up the version number.
Download innounp to decompiler the installer, and the install_script.iss does not have the AppVersion parameter. ¿Maybe you had the old version on the build system?

**Comment by kaamui** [comment]
Hello,

I was running out of time for the 1.5.3 release, and I encountered some difficulties with the changes you made (AppVerName still required even with the AppVersion and the AppName defined). It might be due to my innoSetup version. I'll check it again soon.

Thanks for your help.

**Comment by kaamui** [comment]
A fix has been found and will be added in 1.5.4
