### ISSUE TITLE
OpenBoard Sleep Screen configurable to show a webpage

### ISSUE THREAD

**Issue by janklostermann** [OpenBoard-org/OpenBoard#205]
### Current state
If you switch to Sleep mode (via OpenBoard menu) you get the Openboard-Icon and a text telling you to get back by clicking. Simple and easy.

### Desired behavior
You have a configuration option to configure a webpage that will be shown in Kiosk-mode if you switch into Sleep mode.
No interaction with the webpage intended. If you click, you get back to Openboard.
The browser/webengine should be able to show dynamic webpages, e.g. having a WebCam (in Full-Screen?).

### Implementation ideas
I am not sure, if it would be better to start an external browser (like Chromium/Firefox - for higher compatibility with webpages), maybe creating an even more generic interface by allowing whatever application (e.g. slideshow) to be started (configurable via config-file, with browser as most versatile as default?); or to use the OpenBoard/QT internal (WebKit) for more control and maybe easier integration.

**Comment by juanjosepablos** [comment]
I think that this feature is out of scope of this project, but I was curious so I search a way to accomplish. 
Have a look https://github.com/cwc/web-page-screensaver/

**Comment by janklostermann** [comment]
Thanks for the hint. I already stumbled over it as well (for another part of my activities). But it is not really cross-platform and I am currently trying to integrate OpenBoard in my project on a Raspberry Pi. I got it installed via the Flatpak package on Raspian Jessie. (Trying to compile from scratch I run into troubles with the OpenSSL code that I could not resolve yet...)

I think that there is a very easy solution, not too complicated to implement:
Just give the user the choice of showing the current screen (default) or run an arbitrary command (e.g. a shell script) instead (while showing the desktop).
To maintain control in OpenBoard it would ideally keep all mouse and keyboard events for Openboard to jump back and kill (TERMinate) the command process when Enter is pressed. 
For an even easier solution one could leave everything to the command (leaving the desktop without OpenBoard visible), and as soon as the command terminates it comes back to Openboard (which launched the command anyway). I use a similar construct now with an enhanced version of xtrlock (https://github.com/jarun/xtrlock), but it will not get as integrated.
A small enhancement could enable many creative solutions. ;-)
Thanks for considering!
I realized that the resources for that project are apparently quite tight. A pity. 
But please consider the least-effort way of implementing it. Maybe with some hints on where to look at, I could even dare myself (out of coding for a long time...)
