### ISSUE TITLE
Hotkey for color switch?

### ISSUE THREAD

**Issue by iwasherefirst2** [OpenBoard-org/OpenBoard#213]
Is there a hotkey for switching colors? I use a WACOM tablet for openboard and it would help a ton if I could switch between red/yellow/blue/green  by just pressing the button. Moving the curser to the color and moving back is pretty difficult and time-consuming.

**Comment by UtkarshVerma** [comment]
I'd also like this feature.

**Comment by EdePC** [comment]
I have a simple AutoHotKey Script:

![OpenBoard_pen_colors](https://user-images.githubusercontent.com/42040201/121421727-16a00400-c934-11eb-9e89-58734240abd3.png)

```
#IfWinActive ahk_class Qt5QWindowIcon
SetControlDelay -1

F1::
ControlClick, x75 y25, OpenBoard
Return

F2::
ControlClick, x110 y25, OpenBoard
Return

F3::
ControlClick, x145 y25, OpenBoard
Return

F4::
ControlClick, x175 y25, OpenBoard
Return

F5::
ControlClick, x205 y25, OpenBoard
Return
```

**Comment by elbecerrasoto** [comment]
I would love this!

**Comment by letsfindaway** [comment]
Pull request #460 would bring this feature, even as configurable keyboard shortcuts. So - stay tuned! 😃

**Comment by YongLipTeh** [comment]
> I have a simple AutoHotKey Script:
> 
> ![OpenBoard_pen_colors](https://user-images.githubusercontent.com/42040201/121421727-16a00400-c934-11eb-9e89-58734240abd3.png)
> 
> ```
> #IfWinActive ahk_class Qt5QWindowIcon
> SetControlDelay -1
> 
> F1::
> ControlClick, x75 y25, OpenBoard
> Return
> 
> F2::
> ControlClick, x110 y25, OpenBoard
> Return
> 
> F3::
> ControlClick, x145 y25, OpenBoard
> Return
> 
> F4::
> ControlClick, x175 y25, OpenBoard
> Return
> 
> F5::
> ControlClick, x205 y25, OpenBoard
> Return
> ```

**Comment by Hosseinf2012** [comment]
[EdePC](https://github.com/EdePC)
How can we use these codes?
I want to i can make hotkeys pen color for openboard

**Comment by EdePC** [comment]
AutoHotKey Script, now AutoHotKey is v2: https://www.autohotkey.com/download/ahk-v2.exe install and create new file (use notepad or notepad++ or other).

Script for AutoHotKey v2 for OpenBoard v1.6.4 and Screen resolution 1920x1080:

```
#HotIf WinActive("ahk_class Qt5150QWindowIcon")
SetControlDelay -1

F1:: ControlClick  "x75 y25", "OpenBoard"
F2:: ControlClick "x110 y25", "OpenBoard"
F3:: ControlClick "x145 y25", "OpenBoard"
F4:: ControlClick "x175 y25", "OpenBoard"
F5:: ControlClick "x205 y25", "OpenBoard"
```

Save file and double click for open, test F1 to F5 HotKeys on OpenBoard

**Comment by Hosseinf2012** [comment]
thank you for your help.I made this file. but i don't know how to use it. when i double click on it, anything happened.the exe file cant be sent
Hossein Farhani 

    On Sunday, April 2, 2023 at 06:19:34 PM PDT, EdePC ***@***.***> wrote:  
 
 


AutoHotKey Script, now AutoHotKey is v2: https://www.autohotkey.com/download/ahk-v2.exe install and create new file (use notepad or notepad++ or other).

Script for AutoHotKey v2 for OpenBoard v1.6.4 and Screen resolution 1920x1080:
#HotIf WinActive("ahk_class Qt5150QWindowIcon")
SetControlDelay -1

F1:: ControlClick  "x75 y25", "OpenBoard"
F2:: ControlClick "x110 y25", "OpenBoard"
F3:: ControlClick "x145 y25", "OpenBoard"
F4:: ControlClick "x175 y25", "OpenBoard"
F5:: ControlClick "x205 y25", "OpenBoard"

Save file and double click for open, test F1 to F5 HotKeys on OpenBoard

**Comment by Hosseinf2012** [comment]
Sorry. Can you help me more? I am really weak in computer science. I am master of astrophysics.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 3, 2023 at 22:55, ***@***.***> wrote:   


Creating Shorcuts for OpenBoard with AutoHotKey v2
   
   - Defautl script = 1920x1080 screen size, use Windows Spy Tool for others screen size
   - The script run in background, check your windows notification area for H icon

**Comment by Hosseinf2012** [comment]
dear friendSorry. unfortunately it didn't work.when i pressed f1 to f5 no color changed.
Hossein Farhani 

    On Monday, April 3, 2023 at 08:06:02 PM PDT, Hossein Farhani ***@***.***> wrote:  
 
 Sorry. Can you help me more? I am really weak in computer science. I am master of astrophysics.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 3, 2023 at 22:55, ***@***.***> wrote:   


Creating Shorcuts for OpenBoard with AutoHotKey v2
   
   - Defautl script = 1920x1080 screen size, use Windows Spy Tool for others screen size
   - The script run in background, check your windows notification area for H icon

**Comment by Hosseinf2012** [comment]
I sent an email to you. please check

**Comment by Hosseinf2012** [comment]
This is my windows spy. please help me. I really need it
Hossein Farhani 

    On Monday, April 3, 2023 at 12:25:13 PM PDT, EdePC ***@***.***> wrote:  
 
 


Creating Shorcuts for OpenBoard with AutoHotKey v2
   
   - Defautl script = 1920x1080 screen size, use Windows Spy Tool for others screen size
   - The script run in background, check your windows notification area for H icon

**Comment by EdePC** [comment]
Do you have the FN key on your keyboard?, try pressing the FN + F1 key combination, try FN + F2, FN + F3 ...

**Comment by Hosseinf2012** [comment]
Dear friend first I really appreciate for your kindness about my problem.No. this is my keyboard



Sent from Yahoo Mail on Android 
 
  On Wed, Apr 5, 2023 at 17:03, ***@***.***> wrote:   


Do you have the FN key on your keyboard?, try pressing the FN + F1 key combination, try FN + F2, FN + F3 ...

**Comment by Hosseinf2012** [comment]
dear friends
I really need an autohotkey for changing color in openboard software.
last codes didn't work. 
Who can help me?

**Comment by letsfindaway** [comment]
The keys 1, 2, 3, 4, 5 act as hotkeys for switching color since OpenBoard version 1.7.0.

**Comment by alexandrepaulitec-ai** [comment]
#IfWinActive, ahk_exe OpenBoard.exe
CoordMode, Mouse, Window

; Função que envia um clique oculto para coordenadas (x, y) dentro da janela ativa
ClickAt(x, y) {
    hwnd := WinExist("A")  ; janela ativa (OpenBoard)
    PostMessage, 0x201, 1, (y << 16) | (x & 0xFFFF), , ahk_id %hwnd% ; WM_LBUTTONDOWN
    PostMessage, 0x202, 0, (y << 16) | (x & 0xFFFF), , ahk_id %hwnd% ; WM_LBUTTONUP
}

; Hotkeys F1–F5
F1::ClickAt(75, 25)
F2::ClickAt(110, 25)
F3::ClickAt(145, 25)
F4::ClickAt(175, 25)
F5::ClickAt(205, 25)
return
