### ISSUE TITLE
Widget to embed live UVC image

### ISSUE THREAD

**Issue by hkiel** [OpenBoard-org/OpenBoard#214]
I use ELMO document camera. Maybe it is possible to have a widget that can show the image of (any?) UVC camera. Best would be to also have a button to freeze the image and save it to the OpenBoard document for later reference.

**Comment by cwilms** [comment]
I would also like to see UVC camera support. We use Hovercam document cameras and it would be helpful to annotate over the document camera feed. Have a way to freeze the live image and save it would be helpful too.

**Comment by letsfindaway** [comment]
I think such a widget could be feasible for the upcoming version 1.7.0 of OpenBoard. Any volunteers? There are various examples on the Internet on how to access the camera with Javascript and play it on the screen, e.g. https://www.webdevdrops.com/en/how-to-access-device-cameras-with-javascript/. I assume such code could be wrapped in a widget.

Note that such a widget is not feasible for 1.6.4, as the browser engine used in this version does not support camera access.

**Comment by letsfindaway** [comment]
A "Camera" widget is available in OpenBoard since version 1.7.0.
