### ISSUE TITLE
Distro agnostic `podcast.pri`

### ISSUE THREAD

**Issue by bartoszek** [OpenBoard-org/OpenBoard#217]
Could we replace this conditional with something distro agnostic? 
I presume it's about chacking version of `ffmpeg` above 2.8 :thinking: 
https://github.com/OpenBoard-org/OpenBoard/blob/bb60925bddf6633e15238536d4c929a46d4d9cd8/src/podcast/podcast.pri#L72

**Comment by JBBgameich** [comment]
Could you try whether this approach works on your distribution? https://gitlab.com/JBBgameich/OpenBoard/commit/077cfe80b2ee09dfc061323ae984c896b50d01f8
