### ISSUE TITLE
Selected locked objects appear as in front plan

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#22]
When you select an object, it appears as if it was in front plan (masking other objects)

If you lock the object, it still appears as in front plan when selected. This is not easy when you want to drag little objects over a locked image. Any time you click on the image, other objects seem to disappear.

More: if you select a locked image with other objects, you can effectively move the whole.

A locked object should be less responsive.

![locked01](https://cloud.githubusercontent.com/assets/18069837/14411696/fa8b15ba-ff4f-11e5-9a5d-159c370c6480.png)
![locked02](https://cloud.githubusercontent.com/assets/18069837/14411695/fa8367b6-ff4f-11e5-89c0-81b825482a09.png)
![locked03](https://cloud.githubusercontent.com/assets/18069837/14411697/fa8bd78e-ff4f-11e5-874e-eb17ec4323a4.png)

**Comment by freeheel3r** [comment]
Is it possible you created the small objects before the image? Or manually moved them down?

Normally, the z-level of objects should be kept when they are locked. The other objects will only be behind the locked object if they were created before it, or if they were manually moved down (using the down-facing arrow on the bottom-left of the frame).
And when an object is locked, it can still be moved up/down in Z, to avoid this sort of problem.

This is at least the behaviour I see on my side: for example I added an image, locked it, then drew above it. When I then select the image, it does pop to the front, but it goes back to its normal layer when I deselect it.

I do however see the problem with moving multiple items. We should fix this

**Comment by fbarillon** [comment]
Le 11/04/2016 11:06, Craig a écrit :
>
> This is at least the behaviour I see on my side: for example I added 
> an image, locked it, then drew above it. When I then select the image, 
> it does pop to the front, but it goes back to its normal layer when I 
> deselect it.
>
> I do however see the problem with moving multiple items. We should fix 
> this
>
This is a problem when using OpenBoard with pupils or non aware adults : 
every time  they miss a little object and click on the locked image, 
this image appears as in front and hides anything else.

The activity "move objects over a fixed image" is very common and sould 
be easy to perform.

On Inkscape, a locked object is no more selectable and there is a 
"unlock all" menu item.

On Openboard, an option "lock with the background" could be useful, but 
I don't know if the structure of the background plan allows that.

Regards,

François

I'd like to propose enhancements for a future version of OpenBoard, is 
it a good idea to write it on Github interface?

**Comment by freeheel3r** [comment]
Ok, thank you for your feedback.

> I'd like to propose enhancements for a future version of OpenBoard, is
> it a good idea to write it on Github interface?

Sure, please do! You can assign the "Enhancement" label for feature requests

**Comment by SamuelLongchamps** [comment]
I think @fbarillon has great insights on a major usability problem common to these types of documents. Some softwares have an edition mode and a presentation mode in order to facilitate this. The edition mode allows to set states such as locked, but the behaviour isn't effective until it is in the presentation mode. This could be an avenue to facilitate the dual use case of editing a document and presenting a document. On the other hand, I've had comments that this whole "mode" story can be confusing at times, so it should be done with precaution (especially when user tend to edit things in the presentation mode and the save option is then disabled...).

I dislike the "unlock all" option because of the one way it represents, having to unlock everything in order to edit them and relock everything again after.

**Comment by fbarillon** [comment]
Le 14/04/2016 06:11, SamuelLongchamps a écrit :
>
> I think @fbarillon <https://github.com/fbarillon> has great insights 
> on a major usability problem common to these types of documents. Some 
> softwares have an edition mode and a presentation mode in order to 
> facilitate this. The edition mode allows to set states such as locked, 
> but the behaviour isn't effective until it is in the presentation 
> mode. This could be an avenue to facilitate the dual use case of 
> editing a document and presenting a document. On the other hand, I've 
> had comments that this whole "mode" story can be confusing at times, 
> so it should be done with precaution (especially when user tend to 
> edit things in the presentation mode and the save option is then 
> disabled...).
>
The difference betwin Edition mode and presentation mode could be 
materialised with the arrow and the finger cursors witch could be 
visible alternatively :
- the cursor mode could present no restrictions (even if object are locked)
- the finger mode could have restrictions (today this mode allows only 
moving objects)

In the preferences pane, the teacher could choose what is allowed in 
finger mode (move, select, edit, group/ungroup, delete, rotate), 
depending of the activity and pupils age. It could be possible to choose 
what is possible after a single clic and what is possible after a long 
clic (ie: the delete fonction).
>
> I dislike the "unlock all" option because of the one way it 
> represents, having to unlock everything in order to edit them and 
> relock everything again after.
>
I agree.

François
