### ISSUE TITLE
Massive memory leak in ffmpeg podcast on Linux.

### ISSUE THREAD

**Issue by bartoszek** [OpenBoard-org/OpenBoard#222]
I have a problem with the `podcast` feature on Linux. After ~10 minutes `OpenBoard` memory consumption exceeds my rig capability (it takes more RAM than Titanic took water...). I've looked for mem leaks with `heaptrack` and narrowed the problem to `av_malloc` call.
![Zrzut ekranu z 2019-04-10 19-29-57](https://user-images.githubusercontent.com/1213348/55900392-60132e00-5bc7-11e9-9ce4-48db7827947f.png)

`sysinfo: {os=ArchLinux, OpenBoard=1.5.3, ffmpeg=4.1.2, gnome=3.32.0, qt=5.12.2}`
[heaptrack.openboard.7466.zip](https://github.com/OpenBoard-org/OpenBoard/files/3065034/heaptrack.openboard.7466.zip)

**Comment by bartoszek** [comment]
I've found and test the solution, check the PR #223

**Comment by kaamui** [comment]
Hello,

thank you for this I'll try to integrate it for the next release.
