### ISSUE TITLE
The build doesn't find splash/SplashBitmap.h and xpdf/Object.h headers

### ISSUE THREAD

**Issue by yurivict** [OpenBoard-org/OpenBoard#224]
I patched ```OpenBoard.pro```:
```
--- OpenBoard.pro.orig  2019-04-15 01:09:47 UTC
+++ OpenBoard.pro
@@ -88,6 +88,7 @@ isEmpty(USE_SYSTEM_QUAZIP) {
     isEmpty(QUAZIP_INCLUDE): QUAZIP_INCLUDE = $${PREFIX}/include/quazip
   }
   INCLUDEPATH += $${QUAZIP_INCLUDE}
+  INCLUDEPATH += $${POPPLED_INCLUDE}
   LIBS += $${QUAZIP_LIB}
 }
```
but then it also doesn't find xpdf/Object.h.

grepping through the FreeBSD ports tree only finds one port, ```pdfedit```, that contains ```xpdf/Object.h```:
```
$ grep -r xpdf/Object.h /usr/ports/*
/usr/ports/editors/pdfedit/pkg-plist:include/pdfedit-0.4.5/xpdf/Object.h
```

Is ```pdfedit``` supposed to be a dependency?

Could you please make the ```Dependencies``` section in the top-level README more detailed, listing all project dependencies?

For example, in my project I did it like this: https://github.com/yurivict/ChemWiz#Dependencies

**Comment by JBBgameich** [comment]
You will need to change the import names from xpdf to poppler if you want to avoid the xpdf source dependency. Of course the poppler dependency is also required. Maybe it would be helpful to try my collection of patches on the dev branch of my repository (https://gitlab.com/JBBgameich/OpenBoard/tree/dev), which at least allows compiling against system dependencies without thirdParty prebuilts or similar on linux. It might be neccesary to change `linux` to `unix` in the `*.pro` and `*.pri` files, and if it improves the situation on freebsd, I'd by happy to do so at least in my patched repository (which I still try to upstream).

**Comment by JBBgameich** [comment]
I prepared a branch which should have better support for non-linux unix based operating systems. Feel free to try it (https://gitlab.com/JBBgameich/OpenBoard/tree/non-linux-unix).

**Comment by ttrindade80** [comment]
Hello, I have same issue for compiling branch dev-qt5.1x on linux system, the SplashBitmap.h do not exist. I tried to find patchs no dev branch of your repository, but I do not have successful. I do not have others problems with qt version or dependencies.

**Comment by JBBgameich** [comment]
Is your plopper built with -DENABLE_UNSTABLE_API_ABI_HEADERS=ON?

**Comment by ttrindade80** [comment]
Hello, I have same issue for compiling branch dev-qt5.1x on linux system, the SplashBitmap.h do not exist. I tried to find patchs no dev branch of your repository, but I do not have successful. I do not have others problems with qt version or dependencies.

**Comment by ttrindade80** [comment]
I can fix this issue with 
linux-g++* {
 INCLUDEPATH += "/usr/include/poppler"

Now I have some problems with XPDFRender.cpp, somes referês are do not defined.

**Comment by JBBgameich** [comment]
You probably also need to link to poppler.
something like `LIBS += -lpoppler`

If you are compiling OpenBoard from this repository, did you also clone OpenBoard-ThirdParty into the right directory?

**Comment by ttrindade80** [comment]
Hello JBB, after include the lib to Openboard.pro I finally build the OpenOboard. Now, I am going to test the software, and if all works well I will create a ebuild to Gentoo Portage. Gentoo is more a linux distribution, because support another kernels and tools, for example, Gentoo do not uses Systemd as a standard, the philosophy came from BSD and all are do by scripts. The packages are distributed as a source code, in a ebuild system, managed by portage. If you have a testbench for OpenBoard a can do something to execute it.

**Comment by kiefernforst** [comment]
I've got this error with poppler 26.08.0:

```
In Datei, eingebunden von ./build/openboard_autogen/QM7XBKFLFB/moc_XPDFRenderer.cpp:9,
                 von ./build/openboard_autogen/mocs_compilation.cpp:111:
./build/openboard_autogen/QM7XBKFLFB/../../../OpenBoard/src/pdf/XPDFRenderer.h:37:10: schwerwiegender Fehler: splash/SplashBitmap.h: Datei oder Verzeichnis nicht gefunden
   37 | #include <splash/SplashBitmap.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
```

**Comment by jbruechert** [comment]
does your poppler build enable/expose the internal headers?

**Comment by kiefernforst** [comment]
The header is present at `/usr/include/poppler/splash/SplashBitmap.h` ( https://archlinux.org/packages/extra/x86_64/poppler/ )
