### ISSUE TITLE
Crash in MultiScreen mode on Windows

### ISSUE THREAD

**Issue by gsuberland** [OpenBoard-org/OpenBoard#226]
Upon launching the freshly installed application on a Windows 10 machine running 3x 4K monitors and a Wacom tablet, the application window appears on the middle screen briefly and the left and right screens go white, then the application exits to desktop.

No log file is created in the `%localappdata%\OpenBoard\log\` directory. A new document appears to be created in `%localappdata%\OpenBoard\document\` each time the program runs.

**Comment by kaamui** [comment]
Hello,

Can you try with two screens, or different resolutions, or any relevant combination to see if we can target this one more precisely please ? Also, please make sure that your title is the more accurate possible next time.

Thank you for your help.

**Comment by gsuberland** [comment]
I'm getting the same problem even with a 4K monitor and the tablet connected. I can check lower resolutions on the 4K monitor at a later time.

**Comment by gsuberland** [comment]
@kaamui Was this bug actually resolved, or did you close it as stale?

**Comment by kaamui** [comment]
Stale and from 2019, a lot of new releases since. Please reopen it if you can reproduce with the latest build
