### ISSUE TITLE
Écriture saccadée

### ISSUE THREAD

**Issue by moutarde77** [OpenBoard-org/OpenBoard#23]
Bonjour,
sur TabletPC hybrides avec écrans Wacom, la dernière version qui permet une écriture manuscrite "lisse" est la version 1.30 d'Open-Sankoré. Depuis lors (passage aux tracés manipulables multi layer?) et dans toutes les versions ultérieures (y compris Openboard), l'écriture est crénelée et les contours sont irréguliers.
S'agit-il d'un problème de compatibilité avec les drivers Windows ou Wacom?
Si vous aviez l'occasion de vous pencher sur ce problème, ce serait super. Vu le prix très avantageux et la disponibilité de ces TabletPC hybrides/convertibles/2-in-1 sur le marché, il s'agit d'un excellent outil qui intéresse grandement les profs de mon école.
Merci! Samuel Torche, Suisse

**Comment by freeheel3r** [comment]
J'y travaille ; )

![screenshot from 2016-04-12 09 39 22](https://cloud.githubusercontent.com/assets/686868/14453046/a09a5658-0092-11e6-9460-5de8921cf958.png)


En fait il n'y a rien qui permette spécifiquement une écriture plus lisse dans Open-Sankoré 1.30 (en tout cas, pas que je sache) si ce n'est que le programme était peut-être plus rapide, ce qui rendrait le problème moins visible.
Les traits ont toujours été simplement constitués de segments linéaires, tracés entre les points où la souris (ou le stylet) est passée. 
Du coup, je suis en train de travailler sur une nouvelle solution qui calcule des courbes, pour donner un tracé plus lisse.

Ceci dit, les drivers Wacom peuvent avoir un effet: selon la tablette et le driver, la vitesse de rafraîchissement peut varier. Et si elle est trop basse, OpenBoard recevra moins de points dans un même laps de temps, ce qui résultera en une courbe moins lisse. Dans ce cas-là, le problème n'apparaîtrait pas qu'avec OpenBoard mais aussi avec d'autres logiciels de dessin.

**Comment by fbarillon** [comment]
Le 12/04/2016 09:41, Craig a écrit :
> Du coup, je suis en train de travailler sur une nouvelle solution qui 
> calcule des courbes, pour donner un tracé plus lisse.
Bonjour,

Attention : le tracé par courbe est la solution choisie pour LibreOffice 
draw et cela produit des transformations de tracé assez désagréables.

J'en profite pour questionner la possibilité d'autogrouper les tracés 
consécutifs : quand on écrit à la main le mot "chat" ou "2016", c'est 
bien l'ensemble que l'on souhaite pouvoir déplacer.
Il faut par contre choisir un délai après lequel le tracé suivant fera 
partie d'un nouveau groupe (2 secondes?).

François

**Comment by moutarde77** [comment]
@freeheel3r merci beaucoup pour votre réactivité et pour votre magnifique travail!
Bonne journée,
Samuel Torche

**Comment by gagarine** [comment]
https://evernote.com/skitch/ is pretty good. They smooth the curve when you release the pointer/mouse:
![rhgnhzt1f5](https://cloud.githubusercontent.com/assets/164074/15985397/f782e66e-2feb-11e6-909b-0cf2dc1936a1.gif)

The gif is jerky, but in reality it's 100% fluid.

**Comment by lauhub** [comment]
Bonjour,
Ce problème est présent également sous macOS
Y a-t-il un travail prévu prochainement sur ce sujet ?
