### ISSUE TITLE
OpenBoard Ubuntu 18 release (experimental)

### ISSUE THREAD

**Issue by kaamui** [OpenBoard-org/OpenBoard#231]
Hello everyone,

With the release of this version, we thought it necessary to make a point on the status of OpenBoard and the next things that are coming. We are very thankful of every feedback you take time to do and hope that you will appreciate all the things to come. We apologize for the time it took and for any inconvenience you might encounter. As a lot of you know, we have very limited resources (approximatively 80 days of development a year) but are working on finding more (it will take time, though). Good read ! 

Edit : Some members reported issues installing this release. Until a better package can be provided (with the 1.5.4 and hopefully qt 5.9 !), follow the instructions below to install it on a clean install of Ubuntu 18 : 
```
sudo apt install libqt5webkit5
sudo apt install libqt5xml5
sudo apt install libqt5script5
sudo apt install gdebi-core
sudo gdebi openboard_ubuntu_18.04_1.5.3_amd64.deb
```

### Disclaimer
This version is not in a production-ready state. It comes with no SWF support and you are encouraged to give us as many feedbacks (or solutions if you have ! ;)) as you can, to find every new issue that could have appeared with this release.

### Bug fixes
* When quitting OpenBoard, a crash could occur in Ubuntu 16.04 because of the qt-singleapplication API used to prevent multiple instances. 
* The other fixes are directly related to the porting and were not appearing in the previous versions.

### Known issues
* SWF Animations are no longer working. See details below.

#### Qt 5.5 supports SWF but ...
... in Ubuntu 18, flash plugins were needed to make the animations work. We needed to enable Canonical Partners Repository and install adobe-flashplugin and browser-plugin-freshplayer-pepperflash
#### Qt 5.5 needs libgstreamer 0.10...
... which is no longer officially supported by Ubuntu 18, as libgstreamer1.0 is now the official package. But in order to make Openboard compile with qt5.5, we had to install it. 
#### With libgstreamer 0.10 and qt5.5 libs, videos and sounds are not working anymore ...
... and this is a really big issue. 
#### Qt 5.9 needs libgstreamer 1.0 ...
... and videos and sounds work as expected with it. Because of this, a solution was to set BUNDLE_QT=false in the packaging script, and let openboard built with qt5.5 use the Qt5.9 libraries on Ubuntu 18. 
#### Qt5.9 no longer support swf... 
... or at least it seems to no longer support the NPAPI. Thus, according to a Qt developer¹, SWF support depends on the platform, the multimedia framework, and even the installed codecs, where openboard works on MacOS, Windows and Linux. 
#### Videos+Sounds vs SWF animations...
... and the winner is videos and sounds, of course.

#### Because of this (the good news) ...
... we decided that porting to qt5.9.5 (at least) was no longer an option, and are currently working on building openboard with it, and with qtwebkit as a third dependency. We'll also start studying swf replacement with HTML5 soon.

### QtWebEngine vs QtWebKit
If you follow the issues board you could have seen that as exposed in #193, porting from QtWebKit to Qt WebEngine is not trivial. Especially with OpenBoard functionnalities, WebEngine can not be easily seen as the best choice in the long term. After some readings² and discussions³ with Konstantin Tokarev, the current developer of the qtwebkit, it seems that we could make the good choice by maintaining the "webkit approach" in OpenBoard. As @watsaig and I already mentioned, It could result in the long term with the removal of the internal navigator, which is exposed to major security vulnerabilities at this time (don't use it on non-secured pages !), and we don't have the resources to upgrade to the latest qt version every time a new security patch for the webengine arrives.

¹ Source : https://www.qtcentre.org/threads/66723-How-to-play-swf-files-in-QT
² Source : https://github.com/annulen/webkit/wiki/Use-cases-of-QtWebKit
² Source : https://blog.qt.io/blog/2017/01/19/should-you-be-using-qgraphicsview/
³ Source : https://github.com/annulen/webkit/issues/812
³ Source : https://github.com/annulen/webkit/issues/797

**Comment by cjdg** [comment]
Maybe will be better to think into modular approach, right now im testing the flatpack version and the codec to stream doesnt work

**Comment by sammdu** [comment]
I tried it, but it won't install and says
```
Dependency is not satisfiable: openboard (>= 1.5.3)
```

My distro:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by kaamui** [comment]
Hello @sammdu,

That is weird. I just did a 

```
dpkg --info openboard_ubuntu_18.04_1.5.3_amd64.deb | grep Depends

Depends: libavformat57 (>= 7:3.4.6), libavcodec57 (>= 7:3.4.6) | libavcodec-extra57 (>= 7:3.4.6), libswresample2 (>= 7:3.4.6), libswscale4 (>= 7:3.4.6), libavutil55 (>= 7:3.4.6), zlib1g (>= 1:1.2.11), libssl1.1 (>= 1.1.0), libx11-6 (>= 2:1.6.4), openboard (>= 1.5.3), libc6 (>= 2.27), libstdc++6 (>= 8.3.0), libgomp1 (>= 8.3.0), libgcc1 (>= 1:8.3.0), libgcc-7-dev (>= 7.4.0),  onboard,  libqt5multimedia5-plugins
```

and it seems your are right, but I don't know how it came here, and why it is working on my installation.... Thank you for the report, I'll try to figure it out quickly.

**Comment by kaamui** [comment]
Until then, you can modify the deb file to remove this strange dependency like this : 

```
mkdir my_new_folder
mv openboard_ubuntu_18.04_1.5.3_amd64.deb  my_new_folder/
cd my_new_folder
ar x openboard_ubuntu_18.04_1.5.3_amd64.deb
tar xf control.tar.xz
*** open the "control" file in a text editor and remove the openboard dependency, then save and exit the text editor ***
tar c postinst prerm md5sums control | xz > control.tar.xz
ar rcs openboard_ubuntu_18.04_1.5.3_amd64.deb debian-binary control.tar.xz data.tar.xz
```

**Comment by kaamui** [comment]
@sammdu Try with this package : 
[openboard_ubuntu_18.04_1.5.3_amd64.zip](https://github.com/OpenBoard-org/OpenBoard/files/3596676/openboard_ubuntu_18.04_1.5.3_amd64.zip)

**Comment by helge42** [comment]
@kaamui @sammdu 
the dependency for  libqt5webkit5 is in the deb missing.
Try `sudo apt install libqt5webkit5` before installing the deb.

**Comment by sammdu** [comment]
```
openboard: error while loading shared libraries: libQt5Script.so.5: cannot open shared object file: No such file or directory
```

even after installing your appended dependency

**Comment by kaamui** [comment]
I've replaced the package in the releases page with the fixed one and updated the first post of this thread with the instructions above. Thanks again for reporting this.

**Comment by sammdu** [comment]
@kaamui no worries. After installing your new recommended packages and installing the new deb, the installation was successful.

**Comment by Gvf63** [comment]
The font selection don't work. Color and font size (+  -) work.
Old pages with various fonts are displayed correctly and can be changed.
Tested on xubuntu 18.04

**Comment by kaamui** [comment]
I can confirm it on Ubuntu 18.04... I experienced the same issue while building OpenBoard with qt 5.9 on Mac, but I don't know what happens for the moment, because with the same version (built with 5.9 on Ubuntu 18.04) the problem doesn't show up...

**Comment by kaamui** [comment]
Related to the font selection not working on Mac and Ubuntun 18.04+, a workaround has been applied in the 1.5.4 release (https://bugreports.qt.io/browse/QTBUG-79637)

**Comment by vitaminace33** [comment]
`gdebi-core` is actually not needed.
```
sudo dpkg -i openboard_ubuntu_18.04_1.5.3_amd64.deb
sudo apt install -f libqt5{webkit,xml,script}5
```
