### ISSUE TITLE
OpenBoard in Ubuntu 19.04

### ISSUE THREAD

**Issue by e-dub** [OpenBoard-org/OpenBoard#232]
Any tips on how to get OpenBoard working in Ubuntu 19.04.

I have tried the following:
-building: missing QtWebKit/QWebView
-installing deb for Ubuntu 18: missing libavformat57 (have libavformat58)
-installing deb for Ubuntu 16: missing libavformat-ffmpeg56

**Comment by JBBgameich** [comment]
If you want to get it working quickly, you can try the flatpak https://flathub.org/apps/details/ch.openboard.OpenBoard.

If you prefer building yourself, try merging in the "dev" branch of https://gitlab.com/JBBgameich/OpenBoard before, which should solve the QWebView issue + some other issues.

**Comment by e-dub** [comment]
I did not know about flatpak so thank you!  I installed and followed the instructions here: [https://flathub.org/apps/details/ch.openboard.OpenBoard](url)
