### ISSUE TITLE
Change Abbreviation for Associative audio and Images for English Translations

### ISSUE THREAD

**Issue by cfikes** [OpenBoard-org/OpenBoard#241]
In the english translations there is an abbreviation for associative audio and associative images that is considered a derogatory word. "Ass audio" and "Ass images" need to be changed to "Assoc audio" and "Assoc images" to be used in any english speaking classroom environment.

Thank you so much.

**Comment by juanjosepablos** [comment]
Just rename the OpenBoard\library\interactivities\Ass audio.wgt folder and you are done.

**Comment by cfikes** [comment]
Thank you so much, and thank you for the great software.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Juan Jose Pablos <notifications@github.com> Date: 9/7/19  07:59  (GMT-06:00) To: OpenBoard-org/OpenBoard <OpenBoard@noreply.github.com> Cc: Christopher Fikes <cfikes@fikesmedia.com>, Author <author@noreply.github.com> Subject: Re: [OpenBoard-org/OpenBoard] Change Abbreviation for Associative audio and Images for English Translations (#241) Just rename the OpenBoard\library\interactivities\Ass audio.wgt folder and you are done.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenBoard-org/OpenBoard/issues/241?email_source=notifications\u0026email_token=AANSK3Y56YVQWJAJMUQOU7DQIOQS7A5CNFSM4IT75CRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6EYJKQ#issuecomment-529106090",
"url": "https://github.com/OpenBoard-org/OpenBoard/issues/241?email_source=notifications\u0026email_token=AANSK3Y56YVQWJAJMUQOU7DQIOQS7A5CNFSM4IT75CRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6EYJKQ#issuecomment-529106090",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
