### ISSUE TITLE
1.5.3 does not work on WinXP

### ISSUE THREAD

**Issue by juanjosepablos** [OpenBoard-org/OpenBoard#242]
openboad 1.5.2 works fine on windows XP.
1.5.3 stop working with this message:
"This application has failed to start because bcrypt.dll was not found. Re-installing the application may fix this problem."
reports from other projects suggest that the use of [Crypto API Next Generation](http://msdn.microsoft.com/en-us/library/windows/desktop/aa376210(v=vs.85).aspx)
produces this error, and maybe this library is not needed for openboard.
In any case, at least a note on the release notes to reflect this change would be nice to have it.

**Comment by kaamui** [comment]
Hello,

Windows XP is not supported sorry. Your issue might be related to OpenSSL [(see changelog)](https://github.com/OpenBoard-org/OpenBoard/wiki/Changelog)

**Comment by juanjosepablos** [comment]
I did not explain myself well enough. I am asking to put some notes on the release note

**Comment by kaamui** [comment]
hello,

Sorry for the late reply. In order to maintain releases notes as simple as possible, we only note changes directly related to the officially supported platforms. 

Thank you for your understanding.
