### ISSUE TITLE
OpenBoard 1.5.3 doesn´t start Win 10

### ISSUE THREAD

**Issue by filler74** [OpenBoard-org/OpenBoard#243]
OpenBoard 1.5.3 does not start on Windows 10. vcruntime140.dll is supposed to be missing. re-installing vcruntime140.dll does not fix the problem. It happens on 2 different Computer. OpenBoard 1.4.1 works fine on both.

**Comment by kaamui** [comment]
Hello,

vcruntime140.dll comes with "Redistribuable Microsoft Visual C++ 2015" which should have been installed automatically, if missing, by OpenBoard's Installer. 

Try installing it manually following this link : https://www.microsoft.com/fr-fr/download/details.aspx?id=53840

**Comment by filler74** [comment]
Hello kaamui, 
many thanks. 
installing Redistribuable Microsoft Visual C++ 2015 (X86) fixed the problem (testet on 1 device)

greetings & have fun
