### ISSUE TITLE
Request: Allow Holding Right Mouse To Turn Cursor To Eraser

### ISSUE THREAD

**Issue by miversen33** [OpenBoard-org/OpenBoard#244]
A simple enough idea, this would allow you to hold the right click button on your mouse, and turn your cursor to an eraser.

**Comment by ramuntcho** [comment]
OpenBoard is mainly used in ours schools with a pen (and interactive screen like Wacom) or with white inteactive board. Due to our low financial resources, we will not be able to implement this idea. Sorry.

**Comment by kaamui** [comment]
If you aim to implement it yourself, it could be easily done I think (no technical difficulties, just needs time).

The idea would be to handle in Desktop Mode and in Board Mode, a simulated longPressEvent, and, right button was pressed but not released, to change tool to what it has been choosen by the user in the preferences (via a new option in it, linked to a new option in the config file)

if you try to implement it and you have questions, put them in this thread and I'll try to help.

**Comment by pwab** [comment]
Hey @kaamui if someone wants to implement this, would it be possible to also allow mouse scroll wheel to zoom in and out (maybe by also pressing shift)?

I saw that mouse interaction (e.g. #245) and shortcuts (e.g. #283) are often asked for and I would like to know how feasible it is.
