### ISSUE TITLE
Request: Allow Holding Mouse Wheel Down To Move Page

### ISSUE THREAD

**Issue by miversen33** [OpenBoard-org/OpenBoard#245]
In a similar vein to request [#244](https://github.com/OpenBoard-org/OpenBoard/issues/244), holding the mouse wheel (I believe its button 3 on the mouse) in, should enable us to pane/move the whiteboard around.

**Comment by ramuntcho** [comment]
OpenBoard is mainly used in ours schools with a pen (and interactive screen like Wacom) or with white inteactive board. Due to our low financial resources, we will not be able to implement this idea. Sorry.
