### ISSUE TITLE
How to Increase Frame rate recording of openboard Podcast?   

### ISSUE THREAD

**Issue by Ashish45351** [OpenBoard-org/OpenBoard#251]
Deafult value is 10 fps.
I want to change it to 20 fps.
Please suggest me stepwise.

**Comment by kaamui** [comment]
Hello,

In the OpenBoard.config (locations depends on your OS, for example in Windows it is located in <path/to/where/you/installed/OpenBoard>/etc/OpenBoard.config if I remember well), you just have to change this line

```
[Podcast]
FramesPerSecond=10
```
