### ISSUE TITLE
How do I manually Save my work?

### ISSUE THREAD

**Issue by Veek** [OpenBoard-org/OpenBoard#258]
Sez it all.. 
I don't like the autosave and have disabled it in cfg because it can run at an inconvenient time and my usb stick freezes till the write completes.

Just doing Ctrl-d doesn't autosave so.. what should I do to manually save my work? (without exiting every time)

**Comment by kaamui** [comment]
Hello,

You just have to click on a thumbnail, or previous/next page or add page or go to document mode, etc.
