### ISSUE TITLE
Pasteing text, drawing and Undo doesn't work as expected

### ISSUE THREAD

**Issue by Veek** [OpenBoard-org/OpenBoard#261]
1. If I paste some text
2. then draw a few lines
3. then hit undo - the text-paste disappears even though it's the drawing that should undo

Also,
I did something with the mouse while trying to paste into the text box from a desktop/terminal selection and my entire page blanked out as if a new page had been created. Fortunately it had not deleted my page and exiting and restarting restored things to normal.

**Comment by kaamui** [comment]
Hello,

I'm not able to reproduce it. Do you have a more accurate scenario ? What is your OS ?
