### ISSUE TITLE
Can't install under Linux Mint 19.3

### ISSUE THREAD

**Issue by masac** [OpenBoard-org/OpenBoard#269]
openboard_ubuntu_16.04_1.5.4_amd64.deb

I get the following error when trying to install on Linux Mint 19.3 Mate 64 bit:
Error: Dependency is not satisfiable: libavformat-ffmpeg56 (>=7:2.8.15)

**Comment by kaamui** [comment]
Hello,

you can edit the control file of the package to make it the ffmpeg libraries match the available packages : 

```
mkdir my_new_folder
mv openboard_ubuntu_16.04_1.5.4_amd64.deb  my_new_folder/
cd my_new_folder
ar x openboard_ubuntu_16.04_1.5.4_amd64.deb
tar xf control.tar.xz
*** open the "control" file in a text editor and edit the dependencies, then save and exit the text editor ***
tar c postinst prerm md5sums control | xz > control.tar.xz
rm openboard_ubuntu_16.04_1.5.4_amd64.deb
ar rcs openboard_ubuntu_16.04_1.5.4_amd64.deb debian-binary control.tar.xz data.tar.xz
```

If I understood correctly [this page](https://reposcope.com/package/libavformat-ffmpeg56) the satisfiable dependency in linux Mint 19.3 is 7.2.8.6

Hope it helps.

**Comment by masac** [comment]
Thanks!

openboard_ubuntu_20.04_1.6.0-a.0_amd64.deb

I get the following error when trying to install on Linux Mint 19.3 Mate 64 bit:
Error: Dependency is not satisfiable: libavformat58(>=7:4.2.1)

**Comment by kaamui** [comment]
Same answer as above. Good luck.
