### ISSUE TITLE
library header name conflict (poppler and xpdf both contain SplashTypes.h)

### ISSUE THREAD

**Issue by tangruize** [OpenBoard-org/OpenBoard#272]
Hello,

Recently I build OpenBoard from source.  My build environment is:
```
Ubuntu 19.10
g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
OpenBoard branch dev-qt5.1x
```

I encountered a compile error:
```
In file included from src/pdf/XPDFRenderer.h:41,
                 from src/pdf/PDFRenderer.cpp:35:
/usr/include/poppler/SplashOutputDev.h:197:5: error: 'SplashThinLineMode' has not been declared
  197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
/usr/include/poppler/SplashOutputDev.h:197:39: error: 'splashThinLineDefault' was not declared in this scope
  197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
```

It seems that `SplashThinLineMode` has not been declared, but it is decleared in `/usr/include/poppler/splash/SplashTypes.h:74`.  The poppler library version is `0.80.0-0ubuntu1.1`.

I find that there are two `SplashTypes.h` files. The other is `../OpenBoard-ThirdParty/xpdf/xpdf-3.04/splash/SplashTypes.h`. Their include guard is the same (`SPLASHTYPES_H`) and their contents are similar.

However, `SplashTypes.h` in `xpdf` does not declare `SplashThinLineMode`. I copied its delaration and then successfully built openboard.

**Comment by kaamui** [comment]
Hello,

Are you on the dev-qt51-x branch both on OpenBoard and OpenBoard-ThirdParty ?

**Comment by tangruize** [comment]
Ohhhh, I didn't notice OpenBoard-ThirdParty has a dev-qt5.1x branch. I checked `OpenBoard-ThirdParty/xpdf/xpdf-3.04/splash/SplashTypes.h` in that branch on my browser. And it seems that the file has no change. I will try to compile on that branch later. Thanks!
