### ISSUE TITLE
Multi-screen mode: slow and lagging duplicated display (desktop mode)

### ISSUE THREAD

**Issue by lauhub** [OpenBoard-org/OpenBoard#274]
Hi,

The multi-screen desktop mode is slow on my computer and I don't remember Open-Sankoré was so slow: there is a half-second to one second latency when duplicating my screen.

My computer has a 3.1GHz i7 with 16Gb RAM and a SSD device, so I don't think hardware is involved.

I use macOS 10.14.6 (18G3020) Mojave but this issue is present with previous versions.

Whatever the tool, the animation is not smooth (drawing, laser pointer, writing text) so the trainees sometimes feel unconfortable with this.

I mainly use OpenBoard to share computer screens. Aim is to demonstrate console/computer tasks.

Thanks again for your excellent work

**Comment by diegocaja** [comment]
Hi, I a few months ago, I found me with the same "problem" but when a change the parameter "RefreshRateInFramePerSecond" in the "OpenBoard.config" file to the number 25 then everything worked fine. Maybe you can try this solution.

**Comment by lauhub** [comment]
Thank you @diegocaja 

I followed instructions given [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Settings) to find the configuration file.

I added the following to my `OpenBoardUser.config` file:

```
[Mirroring]
RefreshRateInFramePerSecond=16
``` 

The default value is 2, which far not enough for a smooth display

It worked , thanks again
