### ISSUE TITLE
Debian 10 (stable) version?

### ISSUE THREAD

**Issue by shemminger** [OpenBoard-org/OpenBoard#276]
Any hints on getting a version that works on Debian stable?
The old Ubuntu versions won't work because of missing out dated dependencies.

**Comment by JBBgameich** [comment]
You can use the flatpak from flathub.org

**Comment by maehne** [comment]
I tested the flatpak version and was not fully satisfied. Making screenshots of the desktop did not work, i.e., resulted in black rectangles instead. Also, the transparent panels had in some situations a black background instead. It would be great if there would be an official DEB package, which in an ideal world would be also submitted into the Debian distribution itself.

**Comment by JBBgameich** [comment]
sunweaver is working on a package for debian, but I don't think there are ready to install builds already. The screenshot / transparency issues do not sound packaging related, but rather desktop environment related.

**Comment by maehne** [comment]
> The screenshot / transparency issues do not sound packaging related, but rather desktop environment related.

I am using KDE Plasma running on X11. My experience so far has been that it works still more reliable than Wayland. Anyway, do you have any recommendations where to look to fix the transparency/screenshot issue? I forgot to mention, i.e., also not possible to display the desktop on the second screen if you click on the eye tool. That's a pity, as I find it a very powerful feature allowing to seamlessly demonstrate software tools while also presenting slides and making sketches.

**Comment by JBBgameich** [comment]
I can reproduce the issues with the flatpak and a native, non-flatpak binary. Honestly I didn't even notice the eye-tool exists until now, so I didn't miss it. (I'm not upstream maintainer of this project but just maintainer of the flatpak)

**Comment by maehne** [comment]
Thanks @JBBgameich for confirming my observations. Is it specific to KDE Plasma or are also other desktop environments (Gnome, XFCE) affected? Should we create a separate issue? The eye tool of OpenBoard lets it stand out compared to, e.g., Xournal++.
