### ISSUE TITLE
qmake on Ubuntu 19.10 fails

### ISSUE THREAD

**Issue by dinojr** [OpenBoard-org/OpenBoard#278]
I've successfully managed to build the ThidParty software but the main Openboard build fails with:

make OpenBoard.pro -spec linux-g++-64
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected

**Comment by toehold** [comment]
Same for me on Ubuntu 18.04

**Comment by sarsorus** [comment]
Was the command "make" or "qmake" ? Readme suggests qmake. I just compiled and had these errors as well when using cmake, but it didn't stop the compilation process.

**Comment by dinojr** [comment]
My bad. It is indeed qmake in the docs and that's what I ran:
```
qmake OpenBoard.pro -spec linux-g++-64
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected
```

According to the docs, the next step is make, which failed too.
```
make
make -f Makefile.Release
make[1]: Entering directory '/home/wilk/git-repositories/OpenBoard'
make[1]: *** No rule to make target 'QtWebKit/QWebView', needed by 'build/linux/release/ui/ui_trapFlash.h'.  Stop.
make[1]: Leaving directory '/home/wilk/git-repositories/OpenBoard'
make: *** [Makefile:42: release] Error 2
```

I also tried running the build.sh script in release_scripts/linux which failed with the same error message about QWebView

**Comment by kaamui** [comment]
hello,

you need to go to the dev-qt5.1x branch to build with latest qt releases

**Comment by dinojr** [comment]
kaamui <notifications@github.com> writes:

> hello,
>
> you need to go to the dev-qt5.1x branch to build with latest qt releases

Thanks. It got much farther in the build process but it stopped at:

> In file included from src/pdf/XPDFRenderer.h:41,
>                  from src/pdf/PDFRenderer.cpp:35:
> /usr/include/poppler/SplashOutputDev.h:197:5: error: ‘SplashThinLineMode’ has not been declared
>   197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
>       |     ^~~~~~~~~~~~~~~~~~
> /usr/include/poppler/SplashOutputDev.h:197:39: error: ‘splashThinLineDefault’ was not declared in this scope
>   197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
>       |                                       ^~~~~~~~~~~~~~~~~~~~~
> make[1]: *** [Makefile.Release:6058: build/linux/release/objects/PDFRenderer.o] Error 1
> make[1] : on quitte le répertoire « /home/wilk/git-repositories/OpenBoard »
> make: *** [Makefile:42: release] Error 2

Julien.

**Comment by mdeguzis** [comment]
Same on Pop!_OS 19.10
```
In file included from src/pdf/XPDFRenderer.h:41,
                 from src/pdf/PDFRenderer.cpp:35:
/usr/include/poppler/SplashOutputDev.h:197:5: error: ‘SplashThinLineMode’ has not been declared
  197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
      |     ^~~~~~~~~~~~~~~~~~
/usr/include/poppler/SplashOutputDev.h:197:39: error: ‘splashThinLineDefault’ was not declared in this scope
  197 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
      |                                       ^~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.Release:6067: build/linux/release/objects/PDFRenderer.o] Error 1
make[1]: Leaving directory '/home/mikeyd/github-repos/OpenBoard'
make: *** [Makefile:42: release] Error 2

```

**Comment by jojijoy15** [comment]
sh: 1: Syntax error: "&" unexpected
This error is popping up. I am on branch dev-qt5.1x.
Any update?

My system configuration
Ubuntu 20.04.1 LTS(Focal Fossa) 
Installing qt-5.14.0

**Comment by GavinSmith0123** [comment]
`sh: 1: Syntax error: "&" unexpected`

I get the same. Can the requirement to switch to the `dev-qt5.1x` branch be added to `README.md`?

**Comment by GavinSmith0123** [comment]
It doesn't work:
```
$ git status
On branch dev-qt5.1x
Your branch is up-to-date with 'origin/dev-qt5.1x'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .qmake.stash

nothing added to commit but untracked files present (use "git add" to track)
$ rm .qmake.stash 
$ qmake OpenBoard.pro -spec linux-g++-64
Info: creating stash file /home/g/extsrc/openboard/OpenBoard/.qmake.stash
sh: 1: Syntax error: "&" unexpected
Project ERROR: Unknown module(s) in QT: webkit svg script xmlpatterns uitools multimedia webkitwidgets multimediawidgets
$ 
```

**Comment by GavinSmith0123** [comment]
Running `qmake -d OpenBoard.pro -spec linux-g++-64 |& tee qmake.log` and then looking at the log file, there are the lines:

```
DEBUG 1: /home/g/extsrc/openboard/OpenBoard/src/podcast/podcast.pri:61: DEPENDPATH := /usr/lib/x86_64-linux-gnu
DEBUG 1: /home/g/extsrc/openboard/OpenBoard/src/podcast/podcast.pri:63: LIBS := -lavformat -lavcodec -lswscale -lavutil -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lX11 -lasound -lSDL -lx264 -lpthread -
+lvpx -lvorbisenc -lvorbis -ltheoraenc -ltheoradec -logg -lopus -lmp3lame -lfreetype -lfdk-aac -lass -llzma -lbz2 -lz -ldl -lswresample -lswscale -lavutil -lm
DEBUG 1: /home/g/extsrc/openboard/OpenBoard/src/podcast/podcast.pri:70: calling built-in $$system("ffmpeg --version|& grep -oP version.*?\\K[0-9]\\.[0-9]")
sh: 1: Syntax error: "&" unexpected
DEBUG 1: /home/g/extsrc/openboard/OpenBoard/src/podcast/podcast.pri:70: FFMPEG_VERSION :=
DEBUG 1: /home/g/extsrc/openboard/OpenBoard/src/podcast/podcast.pri:71: evaluating test function "equals"

```

The issue appears to be the `|&` in the call to `ffmpeg`. I am guessing that this only works with `bash` and does not work with the`sh` program that is being run here.

**Comment by GavinSmith0123** [comment]
I had a long list of Qt modules that were missing:

`Project ERROR: Unknown module(s) in QT: webkit svg script xmlpatterns uitools multimedia webkitwidgets multimediawidgets`

On Linux Mint 19.2 (which is mostly the same as Ubuntu), I resolved most of these by installing various packages:

`sudo apt-get install libqt5webkit5-dev libqt5svg5-dev  libqt5xmlpatterns5 qt5-default qttools5-dev-tools qtmultimedia5-dev  libqt5xmlpatterns5-dev libqt5script5 qtcreator`. (I don't know which of these were necessary.)

But there is still the "script" module that I can't install. Any ideas where I would get this?

Someone else had the same problem 4 years ago: https://github.com/OpenBoard-org/OpenBoard/issues/58#issuecomment-257157513

**Comment by GavinSmith0123** [comment]
I found it was `sudo apt-get install qtscript5-dev`. With this qmake runs successfully.

**Comment by GavinSmith0123** [comment]
After getting a lot further after making one or two changes, `make` runs for a long time, but breaks with the output below.

It is a pity, I was interested at looking at the source code of OpenBoard and possibly making a few changes, but building it from source is at the moment an impenetrable obstacle.

```
g++ -c -m64 -pipe -std=c++11 -fopenmp -O2 -std=gnu++1y -w -D_REENTRANT -fPIC -DNO_THIRD_PARTY_WARNINGS -DUBVERSION="\"1.6.1-a.1116."\" -DUBVERSION_RC=1,6,1,160,1116 -DPRE_RELEASE -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -Isrc -Isrc/web/browser -Isrc/qtsingleapplication/src -Isrc/pdf-merger -Iplugins/cffadaptor/src -isystem /usr/include/quazip5 -isystem /usr/include/poppler -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/linux/release/moc -isystem /usr/include/libdrm -Ibuild/linux/release/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/linux/release/objects/XPDFRenderer.o src/pdf/XPDFRenderer.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h:44:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from src/pdf/XPDFRenderer.h:32,
                 from src/pdf/XPDFRenderer.cpp:30:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h: In instantiation of ‘void QVector<T>::defaultConstruct(T*, T*) [with T = XPDFRenderer::PdfZoomCacheData]’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:580:41:   required from ‘void QVector<T>::reallocData(int, int, QArrayData::AllocationOptions) [with T = XPDFRenderer::PdfZoomCacheData; QArrayData::AllocationOptions = QFlags<QArrayData::AllocationOption>]’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:677:20:   required from ‘void QVector<T>::append(T&&) [with T = XPDFRenderer::PdfZoomCacheData]’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:261:35:   required from ‘void QVector<T>::push_back(T&&) [with T = XPDFRenderer::PdfZoomCacheData]’
src/pdf/XPDFRenderer.cpp:60:78:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:322:13: error: no matching function for call to ‘XPDFRenderer::PdfZoomCacheData::PdfZoomCacheData()’
             new (from++) T();
             ^~~~~~~~~~~~~~~~
In file included from src/pdf/XPDFRenderer.cpp:30:0:
src/pdf/XPDFRenderer.h:92:13: note: candidate: XPDFRenderer::PdfZoomCacheData::PdfZoomCacheData(double)
             PdfZoomCacheData(double const a_ratio) : splashBitmap(nullptr), cachedPageNumber(-1), splash(nullptr), ratio(a_ratio), hasToBeProcessed(false) {};
             ^~~~~~~~~~~~~~~~
src/pdf/XPDFRenderer.h:92:13: note:   candidate expects 1 argument, 0 provided
src/pdf/XPDFRenderer.h:91:16: note: candidate: XPDFRenderer::PdfZoomCacheData::PdfZoomCacheData(const XPDFRenderer::PdfZoomCacheData&)
         struct PdfZoomCacheData {
                ^~~~~~~~~~~~~~~~
src/pdf/XPDFRenderer.h:91:16: note:   candidate expects 1 argument, 0 provided
Makefile.Release:5952: recipe for target 'build/linux/release/objects/XPDFRenderer.o' failed
make[1]: *** [build/linux/release/objects/XPDFRenderer.o] Error 1
make[1]: Leaving directory '/home/g/extsrc/openboard/OpenBoard'
Makefile:40: recipe for target 'release' failed
make: *** [release] Error 2
$ 
```

**Comment by GavinSmith0123** [comment]
Is it possible to disable features in OpenBoard to make it easier to build? For example, could you disable pdf support, having an embedded web browser, and the feature to create podcasts? You could have a functional interactive whiteboard program without these.

**Comment by GavinSmith0123** [comment]
The errors I posted in a previous message appear to be related to recent changes in the code which means that a constructor is missing. According to https://doc.qt.io/qt-5/containers.html#assignable-data-type:

`
The values stored in the various containers can be of any assignable data type. To qualify, a type must provide a copy constructor, and an assignment operator. For some operations a default constructor is also required. This covers most data types you are likely to want to store in a container, including basic types such as int and double, pointer types, and Qt data types such as QString, QDate, and QTime, but it doesn't cover QObject or any QObject subclass (QWidget, QDialog, QTimer, etc.). If you attempt to instantiate a QList<QWidget>, the compiler will complain that QWidget's copy constructor and assignment operators are disabled. If you want to store these kinds of objects in a container, store them as pointers, for example as QList<QWidget *>.`

I am going to try building using an earlier version in git.

**Comment by GavinSmith0123** [comment]
I successfully built it with the `master` branch (`85eb094e`) - the `dev-qt5.1x` branch is a red herring. I just needed one change for qmake to run:

```
diff --git a/src/podcast/podcast.pri b/src/podcast/podcast.pri
index e96263fa..26042429 100644
--- a/src/podcast/podcast.pri
+++ b/src/podcast/podcast.pri
@@ -69,7 +69,7 @@ linux-g++* {
             -lxcb-xfixes \
             -lxcb-render -lxcb-shape -lxcb -lX11 -lasound -lSDL -lx264 -lpthread -lvpx -lvorbisenc -lvorbis -ltheoraenc -ltheoradec -logg -lopus -lmp3lame -lfreetype -lfdk-aac -lass -llzma -lbz2 -lz -ldl -lswresample -lswscale -lavutil -lm
 
-    FFMPEG_VERSION = $$system(ffmpeg --version|& grep -oP "version.*?\K[0-9]\.[0-9]")
+    FFMPEG_VERSION = $$system(ffmpeg -version | grep -oP "version.*?\K[0-9]\.[0-9]")
     equals(FFMPEG_VERSION, 2.8) {
         LIBS -= -lswresample
         LIBS += -lavresample

```

**Comment by fallenflint** [comment]
Hi everyone. I'm quite outdated to Qt/qmake/stuff, so sorry if my questions are silly.

Just tried to build 1.7.1 from source on Ubuntu 22.04.5 along with the official guide and met the same error (the same result on master and v1.7.1 branches):
```
make OpenBoard.pro
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected
sh: 1: Syntax error: "&" unexpected
```
Thanks to [https://github.com/OpenBoard-org/OpenBoard/issues/278#issuecomment-735273208](Gavin's comment) i figured out what's wrong and succeeded to build the app.

But now I would like to clarify for myself (and hope it would be helpful for others who met the same issue), how it works.

AFAIK, the trouble is `$$system(ffmpeg --version|& grep -oP "version.*?\K[0-9]\.[0-9]")` works well in bash, and won't work in sh. Although my system shell is bash (as stated in /etc/passwd, chsh and others) What is the standard way to tell qmake to use bash instead of sh to use for $$system?

**Comment by scoulondre** [comment]
To solve the 
`sh: 1: Syntax error: "&" unexpected`
error, just change 
`$$system(ffmpeg --version|& grep -oP "version.*?\K[0-9]\.[0-9]"`
by
`$$system(ffmpeg -version| grep -oP "version.*?\K[0-9]\.[0-9]"`
in the `/src/podcast/podcast.pri` file.
Watch out there must be only one minus sign before version
