### ISSUE TITLE
[question] HiDPI support?

### ISSUE THREAD

**Issue by iGormilhit** [OpenBoard-org/OpenBoard#280]
Hi,
I've installed OpenBoard on the laptop of a teacher. The laptop is running Archlinux with Gnome and has a HiDPI screen. So the OpenBoard menus are very small. Is there a setting somewhere, or a workaround?

**Comment by maehne** [comment]
The only workaround I know, which works reliably is to set the screen to a lower resolution, e.g., Full HD 1920 x 1080 during usage of apps, which have not been adapted to HiDPI.

**Comment by JBBgameich** [comment]
You can set QT_SCALE_FACTOR=2 or similar in the environment. That will scale everything but pixmaps, so you'd have to live with pixelated icons for now until this is fixed in openboard.

**Comment by JBBgameich** [comment]
Technically it probably scales pixmaps correctly, but the icons in the openboard repository simply have a very low resolution.

**Comment by iGormilhit** [comment]
Sorry, I was first busy, then seek. I changed the screen resolution, I think it's the better approach for now.

I know about the `QT_SCALE_FACTOR` but didn't think that OpenBoard is a QT application. :slightly_smiling_face: 

OpenBoard seems to save files (like podcast) on the Desktop. With the Gnome environment that get rid of the desktop metaphor, it's a bit strange. :smile: I thought the user could configure this behaviour.

Most importantly, it's nice that this software is free and open source. Thanks !

I think this issue can be closed.

**Comment by Amr-Ibra** [comment]
Maybe please keep this issue open as long as it's not fixed in the code, so that people can easily find it to either upvote it or for contributors if they want to contribute code.

https://github.com/OpenBoard-org/OpenBoard/issues/384 is a duplicate issue.
