### ISSUE TITLE
Win 10: OpenBoard 1.5.4 doesn't start (0xc000007b)

### ISSUE THREAD

**Issue by uwezi** [OpenBoard-org/OpenBoard#281]
I am running a fresh install of Windows 10 on a Lenovo laptop. When starting OpenBoard 1.5.4 an error is displayed: 

![image](https://user-images.githubusercontent.com/8582807/76911315-dd075700-68b0-11ea-8647-094fec1ffac1.png)

**Comment by kaamui** [comment]
Hello,

On a fresh install it might be due to vcredit not installing (it happens a lot with the last builds I don't know why. see #243 to fix it
