### ISSUE TITLE
Shapes and Interactivities not show up, Do I miss something to build?

### ISSUE THREAD

**Issue by bishangshuo** [OpenBoard-org/OpenBoard#284]
![image](https://user-images.githubusercontent.com/49298329/77500939-71fde780-6e91-11ea-89f5-86508caea7cb.png)
![image](https://user-images.githubusercontent.com/49298329/77501058-cb661680-6e91-11ea-9715-5d786ce06ea1.png)

**Comment by kaamui** [comment]
hello,

you have to copy the library folder in the resources directory to your build directory
