### ISSUE TITLE
Library viewer not updated until openboard is restarted

### ISSUE THREAD

**Issue by madworm** [OpenBoard-org/OpenBoard#286]
When I copy e.g. a new file to the video library in my home directory with explorer, the file doesn't show up in the library browser until I restart the application. This is odd.

Folders created in the library browser on the other hand immediately show up in explorer.

OS: W10 EDU 1909
openboard 1.5.4.240

**Comment by kaamui** [comment]
Hello,

you can copy your new video files directly on the right panel on Desktop Mode
