### ISSUE TITLE
Release 1.6.0 for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by vitaminace33** [OpenBoard-org/OpenBoard#288]
Dependencies cannot be satisfied.[ OpenBoard 1.6.0a](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a) depends on [`libpoppler90`](https://packages.ubuntu.com/search?keywords=libpoppler9) which is no longer available in Focal but `libpoppler97`. Editing the control file and symlinking won't work (in case anyone tries). A new release is in order to alpha-test.

I recall that to install a .deb package with missing dependencies (but available), simply do as follows.
```
sudo dpkg -i package.deb
sudo apt install -f
```
UPDATE: might change again before [final freeze (April 16th)](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule).

**Comment by dinojr** [comment]
Is there a .deb available for 1.6.0a ? I'm currently running Ubuntu 19.04 and having trouble buiding from source (see https://github.com/OpenBoard-org/OpenBoard/issues/278).

**Comment by vitaminace33** [comment]
That I know, they won't give support to Ubuntu releases prior to Eoan (19.10-) and they will focus on Focal (20.04) since its a LTS that will be released at the end of this month. So far, the only OpenBoard releases supporting Ubuntu are

- [1.6.0a](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.0a/openboard_ubuntu_20.04_1.6.0-a.0_amd64.deb) for 20.04 (currently broken)
- [1.5.4](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.5.4/openboard_ubuntu_16.04_1.5.4_amd64.deb) for 16.04
- [1.5.3](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.5.3-ubuntu18/openboard_ubuntu_18.04_1.5.3_amd64.deb) for 18.04

Sadly they are release specific, so you won't be able to install 1.5.4 on 18.04 directly.

**Comment by vitaminace33** [comment]
#292

**Comment by vitaminace33** [comment]
Here you'll find a workaround to this problem. #292

**Comment by dinojr** [comment]
Just a side note : The solution in #292 is for openboard 1.5.4 in in Ubuntu 19.10. For openboard 1.6.0a in Ubuntu 20.04 you need to enable the eoan repos with something like:
```
echo -e "# Eoan repositories to satisfy OpenBoard v1.6.0 dependencies\n"\
"deb http://archive.ubuntu.com/ubuntu xenial main universe\n"\
"deb http://security.ubuntu.com/ubuntu xenial-security main universe"\
| sudo tee /etc/apt/sources.list.d/openboard-eon.list
```

**Comment by Gvf63** [comment]
`echo -e "# Eoan repositories to satisfy OpenBoard v1.6.0 dependencies\n"\
"deb http://archive.ubuntu.com/ubuntu xenial main universe\n"\
"deb http://security.ubuntu.com/ubuntu xenial-security main universe"\
| sudo tee /etc/apt/sources.list.d/openboard-eon.list`

**Comment by dinojr** [comment]
of cours, my bad.

**Comment by vitaminace33** [comment]
Ubuntu 20.04 final release is due 23 April and final freeze is there since 16 April. It is perhaps time for a build against `libpoppler97` so we may try 1.6.0.

**Comment by boospy** [comment]
So hope for a new package :) for 20.04 that is working.

**Comment by boospy** [comment]
Ok, working version with workaround for 20.04 in us repo: https://apt.iteas.at

Have fun :+1:  :100:

**Comment by cyberorg** [comment]
Hi, deb packages for Focal(20.04) amd64 and arm64(for Raspberry Pi 4) are available in this ppa  https://launchpad.net/~jigish-gohil/+archive/ubuntu/education
