### ISSUE TITLE
Issue with crashing at the end of a recording.

### ISSUE THREAD

**Issue by cbnsb** [OpenBoard-org/OpenBoard#289]
When I create a podcast/screen recording with openboard about 20% of the time when I press stop to stop the recording openboard will crash forcing me to close it in the task manager. It will still create the recording but when this occurs the audio and video will be out of sync. I am using the most recent version on Windows 10.

**Comment by kaamui** [comment]
Hello,

Sadly we have a lot of issues with podcast recording. It's not the most simple thing to handle as it depends a lot of low level technologies. Can you tell me if it still happens with the 1.6.0a build ?
