### ISSUE TITLE
Multi-screen is broken on Linux

### ISSUE THREAD

**Issue by stanford-scs** [OpenBoard-org/OpenBoard#291]
I'm using OpenBoard on linux with the fvwm window manager, and have found that the multi-screen option basically does the opposite of what I want.

Ideally, OpenBoard would just open two windows, and I could have my window manager place them and handle them however I want.  In practice, I'm running OpenBoard on a desktop machine and using an android VNC client to draw with a stylus, and I'm projecting my lectures using OBS, so neither my control window nor my display window needs to be on-screen.  Ideally they could be on different X displays, so the control window would be on a VNC server at :1, and the display window would be on my main server where I'd move it to a different desktop and import it into OBS as an Xcomposite source.  However, there are multiple other ways I could deal with this if OpenBoard would just give me the two windows (e.g., I can make a big Xorg virtual desktop, or use Xinerama, or use fvwm desktops or whatever).

Unfortunately, OpenBoard seems to be trying to outsmart me by completely disabling multi screen (option grayed out) unless I actually create another X screen.  Using X screens is not my favorite, because they are less convenient for me than Xinerama or Twinview or other ways of supporting multiple monitors, but I decided I could live with it if I got the OpenBoard display window.

However, with multiple X screens, OpenBoard does not do the right thing either.  If I start the control window on display `:0.0` when there's also a `:0.1` screen, then it will at least give me the option of starting multi-screen.  But when I do, the display screen also starts on `:0.0`.  And since multiple screens (unlike Xinerama) won't let you move existing windows between screens, one of my display outputs is now useless, and I have to revert to the tricks I would have used with a single screen anyway.  So what was the point of disabling multi screen with only a single screen?

In theory, I could configure my window manager to place the projector window and control window on different screens at the time the windows are created.  Unfortunately, they both have the exact same resource and class, so there's no easy way for the window manager to differentiate them.

So my bug fix/feature request is this:

- Allow a "force multi screen" option so that the user can override OpenBoard when OpenBoard thinks it shouldn't open a display window.  (This would be the best and simplest thing for me, but is not mutually exclusive of the others.)

- Use a different X Resource on the two windows, so that window managers can place the display window and control window differently.

- Allow the display window to run on a different X display (e.g. `:1` for the display and `:0` for the control window).

Other than this one problem, OpenBoard is really fantastic.  Like many people right now, because of the COVID19 pandemic, I abruptly had to start teaching classes remotely with no experience or guidance doing so.  I don't know what I'd do without OpenBoard.  So thanks for the great software!

**Comment by kaamui** [comment]
hello,

thank a lot for your support. About this window managers issues, I'm not sure I can help, but what I can say is that we experienced the screen overlapping in cinamon and x11 and that it seems to be resolved with a commit present in the 1.6.0a release.

Did you tried with it ?
