### ISSUE TITLE
Openboard on debian?

### ISSUE THREAD

**Issue by mrjive** [OpenBoard-org/OpenBoard#293]
Hi, is it possible to have a debian version?
I cannot install the ubuntu version on my debian (bullseye), since it has unmet dependencies

dpkg: problemi con le dipendenze impediscono la configurazione di openboard:
 openboard dipende da libavformat-ffmpeg56 (>= 7:2.8.15); tuttavia:
  Il pacchetto libavformat-ffmpeg56 non è installato.
 openboard dipende da libavcodec-ffmpeg56 (>= 7:2.8.15) | libavcodec-ffmpeg-extra56 (>= 7:2.8.15); tuttavia:
  Il pacchetto libavcodec-ffmpeg56 non è installato.
  Il pacchetto libavcodec-ffmpeg-extra56 non è installato.
 openboard dipende da libswresample-ffmpeg1 (>= 7:2.8.15); tuttavia:
  Il pacchetto libswresample-ffmpeg1 non è installato.
 openboard dipende da libswscale-ffmpeg3 (>= 7:2.8.15); tuttavia:
  Il pacchetto libswscale-ffmpeg3 non è installato.
 openboard dipende da libavutil-ffmpeg54 (>= 7:2.8.15); tuttavia:
  Il pacchetto libavutil-ffmpeg54 non è installato.
 openboard dipende da onboard; tuttavia:
  Il pacchetto onboard non è installato.
 openboard dipende da libqt5multimedia5-plugins; tuttavia:
  Il pacchetto libqt5multimedia5-plugins non è installato.

Thank you!

**Comment by maximilianduell** [comment]
I managed to build it (from source) during the weekend on debian testing.

I just created a debian package from what I've built, but I have not tested it. 
I attached it nevertheless, maybe it can help you. Due do dependency problems I could not install and test it on my work laptop right now (It runs ubuntu 18.04).

[openboard_debian_9.12_1.5.4_amd64.deb.zip](https://github.com/OpenBoard-org/OpenBoard/files/4437191/openboard_debian_9.12_1.5.4_amd64.deb.zip)

**Comment by maximilianduell** [comment]
Note, for some reason it seems to depend on zoom, which I have installed.

**Comment by mrjive** [comment]
Thank you very much for the try! I couldn't install it anyway.
Same thing for zoom here:
dpkg: problemi con le dipendenze impediscono la configurazione di openboard:
 openboard dipende da zoom (>= 3.5.374815.0324); tuttavia:
  La versione di zoom nel sistema è 3.5.361976.0301.

**Comment by maehne** [comment]
You could also give the OpenBoard Debian packages a try, which are provided by the [IT-Zukunft Schule](https://wiki.it-zukunft-schule.de) project. Though, currently OpenBoard packages seem to be not yet provided for bullseye, but only up to buster. Installation instructions are lacking somewhat. I used the following steps.

1. Download and install the [itzks-keyring](http://packages.it-zukunft-schule.de/debian/pool/main/i/itzks-keyring/itzks-keyring_2019.09.06.1~0deb10+1_all.deb) package.

2. Create a suitable apt sources list file `` with the following content:
   ```
   deb http://packages.it-zukunft-schule.de/debian buster main contrib non-free
   deb http://packages.it-zukunft-schule.de/debian buster-backports main contrib non-free
   ```
3. Install openboard and openboard-fonts-nonfree:
   ```
   sudo apt install openboard openboard-fonts-nonfree
   ```

**Comment by mrjive** [comment]
Thank you very much.
I still have one issue:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 openboard : Dipende: libvpx5 (>= 1.6.0) ma non è installabile

so libvpx5 is not installable. I'll try to understand more on that

**Comment by maximilianduell** [comment]
I think this issue can be closed.
