### ISSUE TITLE
windows:Can't insert video for playback normally

### ISSUE THREAD

**Issue by oneday1992** [OpenBoard-org/OpenBoard#294]
Windows in version 1.6.0-a.0, insert the MP4 format video, the bottom left corner prompts "media resource couldn't be resolved", this should be due to video decoding problems? Do I need to find and install the video codec separately? Is there any other solution to make the user more convenient to use. 
I used on win10.
![20200407185259](https://user-images.githubusercontent.com/39475297/78661558-903bfc80-7901-11ea-85bc-95b14ade90c9.png)
![20200407185323](https://user-images.githubusercontent.com/39475297/78661565-9336ed00-7901-11ea-80cd-a9c601bb7277.jpg)

**Comment by kaamui** [comment]
hello,

In its current state, you have to install the K-lite codec application in order to make videos work, as described in the release notes.
