### ISSUE TITLE
How to inactivate flash content on linux -note and question

### ISSUE THREAD

**Issue by brobr** [OpenBoard-org/OpenBoard#297]
Hi,

Short:
On Slackware linux flash-content crashes Openboard-1.6.0a 
(in the web browser when loading the adobe site, on the board when loading the example /Libary/Animation/Suma de los angulos de un triangulo.swf, or when loading captured/created(?) web-content from /Library/Applications/Web/).

a) Removing or renaming the Suma de los angulos de un triangulo file to a .mov prevents the crash.
b) For captured webcontent, changing the application type calling the swf file prevents the crash.
(see: [flash-mimetype-patch.txt](https://github.com/OpenBoard-org/OpenBoard/files/4461965/flash-mimetype-patch.txt) )

Still somewhere in the program, swf content is linked to a wrong call that crashes the program (say when aiming for the adobe website). Any idea where that could be or how to prevent this??

Ideally, if there's no program on the computer able to deal with flash-movies, the call to load a swf file should be ignored (and not allowed to be passed on, which blows up the application).

Long:
Thanks for the OpenBoard program; a while back it crashed too much (QT5-linked incompatabilities I guess) to be usable on Slackware linux (unless one used extra ubuntu libraries it depended on), but Openboard-1.6.0a runs fine on  current (64bit in my case) with qt5-5.13 and  qt5-webkit-5.212.0_alpha4. Currently, [a build script for OpenBoard made by willysr ](https://www.linuxquestions.org/questions/slackware-14/please-recommend-a-handwriting-pad-4175635693/page3.html#post6108323) is being tested (leading to this post).

The possibility to capture sites from the web and play them inside the document on the board is quite interesting but maybe not helpful when they can crash the program. Web-captured sites with interactivity are stored in the right pane within library/Applications/Web/ and on the (linux) computer in:  ~/.local/share/OpenBoard/interactive content/Web/

Somehow I managed to generate 'interactive webcontent' that ended up without an icon as  a draggable {grey blob} with a long name ({f44c67c3-6c7c-402f-8069-11fb0f14f9ed}.wgt/).
 ![before-Screenshot_2020-04-09_14-47-17](https://user-images.githubusercontent.com/3693709/78988295-77f9f680-7b28-11ea-8418-32b79a267d6a.png)

Dragging this {blob} onto the board immediately crashed the program, while dragging one with a webpage-image linked to it worked fine and played its content.

The crash yielded this in the terminal:
>QIODevice::read (QFile, "/home/rob/.local/share/OpenBoard/interactive content/Web/The Slackware Linux Project.wgt"): device not open
QIODevice::read (QFile, "/home/rob/.local/share/OpenBoard/interactive content/Web/YouTube.wgt"): device not open
QIODevice::read (QFile, "/home/rob/.local/share/OpenBoard/interactive content/Web/{f44c67c3-6c7c-402f-8069-11fb0f14f9ed}.wgt"): device not open
>
>(openboard:18970): GLib-GObject-WARNING **: 15:00:53.443: cannot register existing type 'GdkDisplayManager'
>
>(openboard:18970): GLib-CRITICAL **: 15:00:53.443: g_once_init_leave: assertion 'result != 0' failed
...

The {blob}.wgt folder contained a .swf file, a webpage (index.htm) and a config.xml (like in the case of all other captured web-content). An icon could be used instead of the blob; the swf file could be deleted or renamed, and still the program crashed.
Deleting all folder content prevented the crash. It turns out that editing or removing the "type =application/x-shockwave-flash" bit in the index.htm was sufficient to prevent the crash:
>
![crash-causing-bit_2020-04-10_13-24-02](https://user-images.githubusercontent.com/3693709/78997794-2f016c80-7b3f-11ea-8d09-d1d71be7576f.png)

Th attached patch might help to prevent creation of board-bombs via the interactive content catcher and these lines in the build script before compiling, removes the Suma de los angulos de un triangulo.swf example
>#remove swf-file causing crash
rm resources/library/animations/*.swf

but still somewhere else in the program a wrong call is made to deal with swf content.
If we could patch that on linux that would be a nice solution (if it can work on windows).

hth

**Comment by kaamui** [comment]
hello,

With qtwebkit alpha 3, I never experienced anything else with swf reading than a "Missing plugin" message when not working. I wonder if it could not be due to your build of webkit (as webkit alpha 4 doesn't provides qt513 snapshots). Did you try to enable SWF when compiling it ? Or disabling it ?

**Comment by brobr** [comment]
Hi kaamui,
Thanks for the anwser and the suggestion.

Qtwebkit is now an 'official' skackware package. In the script used to build qtwebkit is:
>\# Use -reduce-relocations only on i?86 and x86_64 architextures.
\# https://bugreports.qt-project.org/browse/QTBUG-36129
if echo $ARCH | grep -q '\(i.86\|x86_64\)' 2>/dev/null; then
  RELOCATIONS="-reduce-relocations"
else
  RELOCATIONS=""
fi

But I have no clue how to explore this further
Searches with duckduckgo on the error message came up with gtk-related stuff, for example here:
[https://stackoverflow.com/questions/60992051/glib-critical-142714-210-g-once-init-leave-assertion-result-0-faile](url)
