### ISSUE TITLE
desktop mode on MAC

### ISSUE THREAD

**Issue by RYG81** [OpenBoard-org/OpenBoard#298]
Hi I am trying to use OpenBoard on MAC and under desktop mode if I am playing video in full screen the tool bar is not visible. Any solution for this? I want to draw on video. and record it.

**Comment by RYG81** [comment]
any one checking the issues here?

**Comment by kaamui** [comment]
hello,

Sorry for the late answer, I'm busy with other projects. I don't think what you want is possible. 

You could simply increase the video player size, so it takes almost all your screen ?

Good luck,
