### ISSUE TITLE
Openbaord does not open after quitting on Windows 10

### ISSUE THREAD

**Issue by aushawk** [OpenBoard-org/OpenBoard#299]
Hi there,

Openboard does not open again if I quit out of the program and then try to open it again. The program doesn't load but I can see it in Task Manager. If I kill it via task manager and open it up again it won't start. I can see it in Task Manager though.

Basically, if I quit out of openbaord I have to reboot my computer to use it again.

Any suggestions?

**Comment by kaamui** [comment]
hello,

On what OS are you ? And what version are you using ?

**Comment by aushawk** [comment]
Hi.

I am running windows 10
Version 1909 os build 18363.778

**Comment by aushawk** [comment]
Also the version of Openbaord that I am running is 1.5.4. I tried loading 1.6.0a and it solved the open/quitting/open problem but the alpha version crashes when I create a podcast as I can't select my microphone. I understand it is still in alpha stage. Just need 1.5.4 to be able to re-open the program.
