### ISSUE TITLE
openboard 1.6.0.a on Linux: system keyboard problem

### ISSUE THREAD

**Issue by Gvf63** [OpenBoard-org/OpenBoard#301]
on my test systems  (xubuntu 20.04 daily 12/04/20202 - VirtualBox & ubuntu 20.04 daily 13/04/20202 - VirtualBox)  if the system virtual keyboard is activated, openboard disappears (the process remains active but cannot be reached).

**Comment by kaamui** [comment]
hello,

I'll try to look at it soon, to see if I can reproduce it. Thanks for reporting this.

**Comment by kaamui** [comment]
Hello,

I can confirm it when the keyboard is anchored at the edges of the screen. Just disable it to make it work correctly (until we figure out why it is not working when anchored).

The difficulty is that openboard is not crashing. Maybe it's an onboard issue.

**Comment by Gvf63** [comment]
Ok, even in previous versions of openboard if keyboard is anchored at the edges of the screen there are problems, but openboard remains in the foreground and usable. In version 1.6.0a instead you lose control of the application. A workaround could be to check (or set) the onboard configuration parameter. For example from terminal:
`gsettings set org.onboard.window docking-enabled false`

**Comment by ciampix** [comment]
Bug confirmed with Ubuntu 20.04. Confirmed workaround of disable docking, also with Preferences->Window->(disable) Dock to screen edge.
