### ISSUE TITLE
Fine drawing or writing with drawing pen does not work

### ISSUE THREAD

**Issue by mintty** [OpenBoard-org/OpenBoard#302]
Writing text with a drawing pen (Wacom Intuos) skips initial line segments.
For example small letters i or n appear broken, Σ misses the upper line, = misses the upper line.
(Could be related to #64, not sure.)

**Comment by kaamui** [comment]
hello,

I'll try to ask the team whose familiar with wacom if they ever experienced such issues. 

What is your version of openboard and OS ?

**Comment by mintty** [comment]
Latest versions, Windows 10 build 19035, OpenBoard downloaded a few days ago (1.5.4).

**Comment by ootwch** [comment]
Can yo try with OpenBoard-org:dev-qt5.1x  and my PR? 

https://github.com/OpenBoard-org/OpenBoard/pull/342

=> Works for me, at least..

**Comment by mintty** [comment]
> Can yo try with OpenBoard-org:dev-qt5.1x and my PR?

Is a patched binary available for download as a drop-in replacement?

**Comment by FrancoisSchnell** [comment]
v1.6.0a1 solves the problem for me, thanks! (Wacom One Medium, Windows 10)
https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a1

**Comment by mintty** [comment]
Great, works fine, thank you!

**Comment by FrancoisSchnell** [comment]
Any ETA on 1.6 release? Or an 1.5 update with this fix? For a stylus app I suspect the shaky lines is a major issue on Windows/Wacom and discourage newcomers who download OpenBoard from the official site. Keep it up :)

**Comment by psisquared2** [comment]
I still have issues where short line segments (like drawing a bold point) are being recognized as button presses (as mentioned in https://github.com/OpenBoard-org/OpenBoard/issues/64#issuecomment-626916505). I tried the binaries for 1.6.0a1 and 1.6.0a3, with no success. I am using an Acer Switch Alpha 12 (convertible laptop with pen, kinda like a Microsoft Surface).

Do the aforementioned versions contain the PR #342? Or would it be best if I compile the PR myself?

**Comment by psisquared2** [comment]
The problem is fixed for me in pre-release https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1a-1102 , though I am not exactly sure why. Pressure sensitivity also works for me now, which didn't work at all before.
