### ISSUE TITLE
Porting webkit to webengine problem

### ISSUE THREAD

**Issue by bishangshuo** [OpenBoard-org/OpenBoard#305]
I‘d tried to display courseware such as ppt, doc files on QWebEnginView, which added into QGraphicsScene, using QGraphicsProxyWidget. The documents shows well, But could't be pressed by mouse.
could anybody fingure it out , so thankful to be help.

![image](https://user-images.githubusercontent.com/49298329/79558738-3bee0500-80d7-11ea-855a-db0997a9a73f.png)

**Comment by bishangshuo** [comment]
testing code is out there:

UBGraphicsWidgetItem.cpp

UBGraphicsWidgetItem::UBGraphicsWidgetItem(const QUrl &pWidgetUrl, QGraphicsItem *parent, QGraphicsScene *scene)
    : QGraphicsWidget(parent)
    , mInitialLoadDone(false)
    , mIsFreezable(true)
    , mIsResizable(false)
    , mLoadIsErronous(false)
    , mCanBeContent(0)
    , mCanBeTool(0)
    , mWidgetUrl(pWidgetUrl)
    , mIsFrozen(false)
    , mIsTakingSnapshot(false)
    , mShouldMoveWidget(false)
    , mUniboardAPI(0)
    , m_pScene(scene)
{
    setData(UBGraphicsItemData::ItemLayerType, QVariant(itemLayerType::ObjectItem)); //Necessary to set if we want z value to be assigned correctly

//    QGraphicsWebView::setPage(new UBWebPage(this));
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::JavaEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::PluginsEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::LocalStorageDatabaseEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::OfflineWebApplicationCacheEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::OfflineStorageDatabaseEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::JavascriptCanAccessClipboard, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::DnsPrefetchEnabled, true);
//    QGraphicsWebView::settings()->setAttribute(QWebSettings::LocalContentCanAccessRemoteUrls, true);

//    page()->setNetworkAccessManager(UBNetworkAccessManager::defaultAccessManager());

    setAcceptDrops(true);
    setAutoFillBackground(false);

//    QPalette pagePalette = page()->palette();
//    pagePalette.setBrush(QPalette::Base, QBrush(Qt::transparent));
//    pagePalette.setBrush(QPalette::Window, QBrush(Qt::transparent));
//    page()->setPalette(pagePalette);

    QPalette viewPalette = palette();
//    pagePalette.setBrush(QPalette::Base, QBrush(Qt::transparent));
    viewPalette.setBrush(QPalette::Window, QBrush(Qt::transparent));
    setPalette(viewPalette);

    setDelegate(new UBGraphicsWidgetItemDelegate(this));

    setFlag(QGraphicsItem::ItemSendsGeometryChanges, true);
    QGraphicsWidget::setAcceptHoverEvents(true);


        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::AutoLoadImages, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::JavascriptEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::JavascriptCanOpenWindows, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::JavascriptCanAccessClipboard, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::LinksIncludedInFocusChain, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::LocalStorageEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::LocalContentCanAccessRemoteUrls, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::XSSAuditingEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::SpatialNavigationEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::LocalContentCanAccessFileUrls, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::HyperlinkAuditingEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::ScrollAnimatorEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::ErrorPageEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::PluginsEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::FullScreenSupportEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::ScreenCaptureEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::WebGLEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::Accelerated2dCanvasEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::AutoLoadIconsForPage, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::TouchIconsEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::FocusOnNavigationEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::PrintElementBackgrounds, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::AllowRunningInsecureContent, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::AllowGeolocationOnInsecureOrigins, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::AllowWindowActivationFromJavaScript, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::ShowScrollBars, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::PlaybackRequiresUserGesture, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::WebRTCPublicInterfacesOnly, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::JavascriptCanPaste, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::DnsPrefetchEnabled, true);
        QWebEngineSettings::defaultSettings()->setAttribute(QWebEngineSettings::PdfViewerEnabled, true);

    if(m_pScene)
    {
        int win_Width = 1280;
        int win_hei = 800;
        m_pWebBrowser = new UBWebEngineView();
        QUrl url("https://view.officeapps.live.com/op/view.aspx?src=https://hdketang-1251579959.cos.ap-shenzhen-fsi.myqcloud.com/2%20%E6%AC%A7%E7%BE%8E%E6%B8%85%E6%96%B0%E6%B7%A1%E9%9B%85%E5%95%86%E4%B8%9A%E8%AE%A1%E5%88%92%E4%B9%A6.pptx");
        m_pWebBrowser->load(url);
        m_pWebBrowser->resize(win_Width, win_hei);

        UBGraphicsProxyWidget_webengine * proxyView = new UBGraphicsProxyWidget_webengine(this, Qt::Window);
        proxyView->setFlag(QGraphicsItem::ItemIsMovable);
        proxyView->setFlag(QGraphicsItem::ItemIsSelectable);
        proxyView->setFlag(QGraphicsItem::ItemIsFocusable);
        proxyView->setGeometry(QRectF(0,0,win_Width,win_hei));
        proxyView->setFocusPolicy(Qt::StrongFocus);
        proxyView->setWidget(m_pWebBrowser);

    }
}

**Comment by kaamui** [comment]
hello,

It would be a cool feature, for sure. Did you try to see if you don't miss a connect on the urlChanged signal maybe ?

**Comment by hmartinez82** [comment]
I'll try to help. I was about to start doing this myself. I'm trying to get OpenBoard to Qt 5.15 since it will be the last 5.x LTS.
