### ISSUE TITLE
Whiteboard Collaboration

### ISSUE THREAD

**Issue by ovari** [OpenBoard-org/OpenBoard#308]
Could OpenBoard be used in a real-time collaborative video conferencing setting as described at https://github.com/jitsi/jitsi-meet/issues/6202?

If so, could this be added to https://github.com/OpenBoard-org/OpenBoard/issues/253?

Thank you

**Comment by kaamui** [comment]
Hello,

Thank you for your participation. I think this is a feature request, if relevant, to ask to jitsi, not OpenBoard.
