### ISSUE TITLE
Virtual Keyboard access to accents, diacritics, diaeresis, umlauts, ligatures etc.

### ISSUE THREAD

**Issue by ovari** [OpenBoard-org/OpenBoard#310]
Press and hold a letter on the Virtual Keyboard to show a popup with variations for that letter.

The will enable entering accents, diacritics, diaeresis, umlauts, ligatures etc. for letters.

For example, pressing and holding the letter `O` could bring up:

![kép](https://user-images.githubusercontent.com/17465872/79701413-43ccc580-82e0-11ea-8d2a-3c4ed36f028c.png)

The image above is missing `Ő` in the list, which should also be included when pressing `O`.

What do you think?

Thank you

**Comment by kaamui** [comment]
Hello,

Dur tu our limited resources, we will not be able to prioritize on this feature. You can use the system keyboard, that may probably do it already.
