### ISSUE TITLE
Using shortcuts to select tools in desktop mode fools the stylus palette

### ISSUE THREAD

**Issue by ghost** [OpenBoard-org/OpenBoard#312]
Hi,

Enter desktop mode. **Using the mouse**, select the arrow tool. Then **in the keyboard** press in sequence:

1. Ctrl-i (selects the pen)

1. Ctrl-i (again, deselects the pen, there's no tool selected now)

1. Ctrl-e (to select the eraser, but now both pen and eraser are selected, being the eraser the working one)

1. Ctrl-e (again, to deselect the eraser, now the pen is marked as active, but it erases instead of draw)

1. Ctrl-f (to select the arrow. The pen remains marked as active, the eraser also turns active! so all three pen, eraser and arrow are active, although the working one is the Arrow)

1. You can also press Ctrl-m and Ctrl-g to also play with the two other remaining tools.

Thanks & regards.

OpenBoard 1.5.4 tested on Win10-1909

**Comment by kaamui** [comment]
hello,

funny one ^^

Thanks for reporting it.
