### ISSUE TITLE
Having a screen with a different aspect ratio breaks the drawing area

### ISSUE THREAD

**Issue by multun** [OpenBoard-org/OpenBoard#313]
I just built openboard for ubuntu 19.04 on the dev-qt-5.1x branch on wayland, and I get this weird view unless I disable my vertical screen:

![openboard-bug](https://user-images.githubusercontent.com/5047140/79913494-8c67aa00-83d8-11ea-8e7d-852cc52ccdb8.png)

I can probably try to fix it given a pointer to the component that computes the size of the canvas
it also only happens in multi screen mode

it seems like using xwayland works the bug around

**Comment by kaamui** [comment]
hello,

I have no idea what could make this happen. Openboard is an old app, that may be too hardly written to work with X11 (or maybe Qt5 is not supporting wayland properly at this time).
