### ISSUE TITLE
Missing background in pdf

### ISSUE THREAD

**Issue by Gvf63** [OpenBoard-org/OpenBoard#315]
When you export a lesson in pdf the background (grid or rows) is not present. This would be especially useful for primary school lessons. This affects all available versions and all operating systems.

**Comment by kaamui** [comment]
Hello,

Yes, it has been designed like this. Even without grids or rows, a dark background, when exported to a pdf, is converted to a light background. I didn't implement it so I don't know why, but I'm sure it must be not easy to do it. Even the background color is not preserved (a document with a dark background is converted to a whiteboard when exported to PDF).

**Comment by letsfindaway** [comment]
The above-mentioned pull request #465 is now merged and will make this available with the upcoming 1.6.2 release using the configuration options described in the pull request.

**Comment by prabaljainn** [comment]
hey @letsfindaway I can still not export my PDF in dark mode, changed my config files in /etc and user folder.
using windows, can you please guide me.

**Comment by letsfindaway** [comment]
That it is merged means that it is scheduled to be included in the next release, You still have to wait until 1.6.2 comes out - or build the current `dev` branch on your own.

**Comment by prabaljainn** [comment]
Building of my own 🥺, I'll wait for next release. Thank you for this wonderful software

**Comment by letsfindaway** [comment]
Closing this issue as completed with PR #465
