### ISSUE TITLE
Build instructions for Ubuntu are outdated

### ISSUE THREAD

**Issue by keddad** [OpenBoard-org/OpenBoard#318]
The only binary Linux release is marked for 16.04, and there are no instructions on building it running 20.04. Apperently, build instructions for 18.04 are not compatible:
```
/usr/bin/ld: cannot find -lxcb-shm
/usr/bin/ld: cannot find -lxcb-xfixes
/usr/bin/ld: cannot find -lxcb-render
/usr/bin/ld: cannot find -lxcb-shape
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.Release:1314: build/linux/release/product/OpenBoard] Error 1
make[1]: Leaving directory '/home/keddad/build/OpenBoard'
make: *** [Makefile:42: release] Error 2
```
Can you consider updating the build instruction, or, even better, setting up a PPA or Snap? (I don't like snaps, but at least they work)

**Comment by keddad** [comment]
Apparently, there [is](https://snapcraft.io/openboard) a snap release, but it is outdated

**Comment by kaamui** [comment]
Hello,

Un up-to-date release is available for Ubuntu 20.04 => https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.0a1/openboard_ubuntu_20.04_1.6.0-a.1_amd64.deb

**Comment by viorato** [comment]
I believe that you need to modify your build instructions; there are a couple of libraries missing. In my fresh installation of Ubuntu 20.04 I had to install also libbz2-dev and libxcb-shm0-dev.

Awesome app by the way.

Best,
Jesus

**Comment by kaamui** [comment]
Hello;

Did you try with these instructions ?

https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04

**Comment by viorato** [comment]
No, I did not. I used these ones: 

https://github.com/OpenBoard-org/OpenBoard/wiki/Build-from-source

I did not noticed that you created another special publication for Ubuntu-20.04

Sorry, my bad!

**Comment by kaamui** [comment]
It's partly my fault, I didn't communicate about it as I want to first produce the same instructions for windows and mac

**Comment by kaamui** [comment]
I close the issue since it is no longer relevant
