### ISSUE TITLE
Ability to change what pen buttons do

### ISSUE THREAD

**Issue by sandorex** [OpenBoard-org/OpenBoard#325]
The request is simple, option to change action of pen buttons to other tools like eraser, drag tool.. etc

I absolutely love openboard, i've been using xournal++ for a while and the quality of drawing is good but interface is a nightmare and there are random input from pen, openboard is working great for me so far (installed using flatpak), this is the only thing bothering me so far as xournal++ has that option and works fine with my one by wacom

**Comment by kaamui** [comment]
Hello,

I think it is related to #283  and #82, so I'll close your issue, but I agree. 

I think that the ability to edit some shortcuts should be prioritized soon after the migration is done.

**Comment by sandorex** [comment]
@kaamui are you sure that pen buttons count as keyboard shortcuts?
