### ISSUE TITLE
Installation Assistance - Ubuntu 18.04

### ISSUE THREAD

**Issue by Spinksrick** [OpenBoard-org/OpenBoard#326]
I'm having difficulty getting OpenBoard installed.on Ubuntu 18.04 Apparently, I don't have a dependency installed properly (see attachment- libavformat-ffmpeg56)- .I think I successfully installed a newer version, but I still receive errors during installation. Also, I tried installing OpenBoard with sudo apt install openboard. It appears to have installed, but I do not see it in the Mat Menu, nor can I find a command that work to initiate (i.e., $openboard)

Any assistance is appreciated.

![Openboard](https://user-images.githubusercontent.com/64115544/80520876-145d2f00-8958-11ea-9e32-f9f908389e82.PNG)

![Libavformat-ffmpeg56](https://user-images.githubusercontent.com/64115544/80523034-7703fa00-895b-11ea-9263-745a30712823.PNG)

**Comment by Gvf63** [comment]
You are trying to install openboard 1.5.4 for Ubuntu 16.04 on Ubuntu 18.04. To do this you must follow the instructions given here: #292

**Comment by Spinksrick** [comment]
Thank you so much....I will try your suggestions.
Regards
Rick
