### ISSUE TITLE
Please provide OpenBoard as AppImage/Snap/Flatpack for Linux

### ISSUE THREAD

**Issue by Guex** [OpenBoard-org/OpenBoard#328]
dear maintainers

many thanks for this great open source tool, but please provide it in a more usable way than the outdated .deb package for Ubuntu/Debian. I cannot install it on the new Ubuntu 20.04 without solving dependencies manually by picking ffmpeg, openssl and others from previous releases.

I have the capability to do that, but it's also a question if i want to do these package hacks. It's also far away of being user friendly and it hinders the adoption and reach to bigger user base.

As the title says, i'd recommend to provide it in format which is portable across multiple Linux distributions and version.

many thanks
Guex

**Comment by maehne** [comment]
OpenBoard is already available as a Flatpak:

https://www.flathub.org/apps/details/ch.openboard.OpenBoard

**Comment by kaamui** [comment]
And an up-to-date package has been released this morning for Ubuntu 20.04 :+1: 

https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a1

**Comment by Seluba** [comment]
The website should perhaps refer to the Flatpak. Others may be smarter, but I had to come here to find out that there was a Flatpak. Nice work btw!

**Comment by dmsoler** [comment]
Just contributed a working recipe to generate an AppImage using [pkg2appimage](https://github.com/AppImage/pkg2appimage/), see its [pull #422](https://github.com/AppImage/pkg2appimage/pull/422) Tested and working on Debian Sid.

**Comment by colombojrj** [comment]
Still waiting for AppImage package! Please distribute an AppImage! I want to use it in my gentoo!!!

**Comment by letsfindaway** [comment]
see above, there is a flatpak maintained by a community member: https://www.flathub.org/apps/details/ch.openboard.OpenBoard
