### ISSUE TITLE
Text tool ergonomy

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#33]
Français :
- Afin de limiter les icônes, un seul menu contextuel (ou une icône) permettrait de modifier la police, la couleur, l'alignement du texte. 
- Au lieu des boutons + et -, la poignée redimensionnement sans déformation pourrait agrandir ou réduire la taille d'écriture comme cela se passe quand le texte est groupé avec d'autres objets.
- Les propriétés  "fond" et "bordure" seraient bien utiles.
- Les objects texte devraient s'adapter en largeur au contenu jusqu'à la largeur d'un demi écran par exemple.
- De même, la hauteur du pavé devrait s'adapter au contenu.
- un texte non éditable ne devrait pas montrer de boutons de mise en forme.

English:
- To limit the number of icons, there could be just one "text properties" icon.
- The plus and minus button could be replace by the use of the homothetic distort handle as is works when text is grouped with other objects.
- "background" and "border" properties could be useful.
- Text objects should adapt their width to the content as far as half a screen for example.
- idem for the rectangle height.
- A non editable text should'nt show format icons.

**Comment by lauhub** [comment]
Any news about this ? Any roadmap ?

**Comment by freeheel3r** [comment]
Hi,

> Any news about this ? Any roadmap ?

No, there are currently no plans to implement any of these features.
