### ISSUE TITLE
When we open/import a document, it always goes to the center with no option

### ISSUE THREAD

**Issue by mayankmaheshwari-bettermeai** [OpenBoard-org/OpenBoard#331]
When we open/import a document, it always goes to the center with no other option.
Sometimes when you are teaching maths or some other science subject that forces you to move it manually to the left or right to give more space to explain the topic and this hence hampers learning.
How, when you move to the next slide all has to be done again!

Happy to fix this on my branch, if someone can highlight where the code for this importing to displaying is.. can try something on my end and share with the boarder group with my outcome.
Less, gods themselves can pick and resolve this, hopefully should not need lot of effort on their end!

**Comment by kaamui** [comment]
Hello,

Using the hand selector to move the page, the position on every page is preserved during the session, but not preserved (to avoid chaos on shared documents)

But you can totally compile OpenBoard yourself and add this feature if you need it.
