### ISSUE TITLE
GNU/Linux is unsupported

### ISSUE THREAD

**Issue by Hierosme** [OpenBoard-org/OpenBoard#332]
Have choose Ubuntu style package for publish OpenBorad , is not a ideal choise.

The end result is simple OpenBoard don't work a GNU/Linux. (RedHat, Suse, Debian that mean a big part of GNU/Linux distribution.)

Ubuntu is totaly not a universal GNU/Linux system, don't think about popularity but compatibility.

It have many approche for that, but in general, that is .rpm .tar.gz and .deb format .
Where .tar.gz is a static binding, and .deb a pure Debian style (not ubuntu style)

I hope it end user  feed back will help.

PS: don't kick be, because i feedback a trouble, i have test, understand the trouble and before move on a other solution, i have take time to inform devellopers about why i not use OpenBoard.

**Comment by multun** [comment]
What would be a better packaging format then?
deb and rpm packages aren't universal either, and **must be rebuilt for every single distribution**.

Actually, most packages aren't made available by tool developers, but by **package maintainers**.
As an example, [somebody maintains an AUR package for archlinux](https://aur.archlinux.org/packages/openboard/), and I personally maintain a small number of packages in NixOS.

There are so many distributions that developers just can't make these available for every single distribution out there.

The OpenBoard team is already kind enough to provide an ubuntu package (outdated, but at least there). From my experience, ubuntu is the most common linux distribution as of today, even though not universal. The team made the right choice by making an ubuntu package available.

If you want an OpenBoard package for your distro, make one!

https://docs.fedoraproject.org/en-US/packaging-guidelines/
https://wiki.debian.org/Packaging
https://en.opensuse.org/openSUSE:Packaging_guidelines

Packaging software is not a developer only burden :-)

**Comment by kaamui** [comment]
> The OpenBoard team is already kind enough to provide an ubuntu package (outdated, but at least there).

no longer outdated :) => https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a1

@Hierosme I know a lot of things are expected on OpenBoard, but I'm the only developer on the project, at this time, with only some days per month as I also work in other projects.

You can find why we choose to deliver an Ubuntu package in #253 : 

> At the same time, it has been decided that Ubuntu 20.04 will be deployed in our Linux machines (in Geneva schools), so OpenBoard will have to support it.

**Comment by Hierosme** [comment]
Hello,

Thanks for you response.
I don't blame anyone, i just feedback about a a static binary will be more efficient for cover the majority of GNU/Linux distribution, without need to provide Packages for every existing GNU/Linux

If you have a "Popularity" approch i recommend you to see Distrowatch and target directlly the distribution it have best popularity score. Actually MX Linux have double score copare to Unbunty. (And support Debian package)

Personnaly i prefert and recommand **Compatibility** approch. Where the Static binary is finally a good option.
It have never been the job of a project to port the project to every system packages. Genraly project provide a baisc .deb (Pure Debian), a .rpm (Pure Redhat) and a static binary.

In you case Ubuntu have been choose, unfortunally that is why i can't use OpenBoard.

In fact by use **Compatibility** approch, if you provide Debian package it will automatically work for Unbuntu and MX Linux ... And unfortunally by use **popularity** approch that finish in a cornner.

Debian and Redhat are the grand parent's of they **popular** GNU/Linux system, when Debian or Redhat update something everyone follow. That exactelly for that you should target Debian and Redhat, The gain is compatibility.

Unfortunally i'm actually really busy for take a look on the Debian packages. (but that just edit debian/control file for align version and packages name.)

I hope my point can help .

Regards
---
PS:
I'm developper too,  **Heriosme** is just my GitHub account, for can open issue or commit patch. I totally understand the lake of human ressource.

**Comment by kaamui** [comment]
We didn't choose a popularity approach. Our system team has to look for the best OS regarding every software, usage our teachers may do with, keep in mind user experience, etc. The choice is not made because of OpenBoard or vice-versa. Openboard is one of the many software deployed in the linux configurations delivered in our schools context. 

Btw, I take note of your pov, and I'll keep it in mind in the future. Thanks for reporting it.
