### ISSUE TITLE
Auto-save loses focus when typing text

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#333]
Hello,

Auto-save is cool but a little annoying when typing in a text zone since it loses focus. You then have to click on the text zone again to continue typing.

I have OB 1.5.4 on Ubuntu 16.04

Cheers,

**Comment by kaamui** [comment]
Hello,

We also discovered this really annoying bug. We'll try to fix it after the migration is over. 

Thanks for reporting it.

**Comment by celfred** [comment]
Thanks ! And you're very welcome. Thank YOU for all the work !
