### ISSUE TITLE
Possibility to run on a separate window 

### ISSUE THREAD

**Issue by vitsca** [OpenBoard-org/OpenBoard#340]
HI. I would like the openboard to be run on a separate (i.e. resizable) window. I have read the forum thread at  https://openboard.ch/forum/viewtopic.php?t=931 and I think I disagree with the arguments there. I understand the "default" full screen mechanism (for unexperienced users), but an experienced user should be able to have one (or both windows) to be windowed. 
Nowadays, with the COVID19 emergency it is even more important: on the "control" screen with the online teaching we all do, it is important to have the control of the class (via Zoom, Microsoft Teams, Meet or others) AND the editing of the board, while the other screen is used to show slides, the whiteboard etc. 
It would really make a hit if, at least, the editing window could be resizable. Thanks a lot!

**Comment by profejuanca** [comment]
I read the post, windowed is a difficult thing? no sense in this point I think, every program is windowed and every person assumes this as a fact.

**Comment by profejuanca** [comment]
Maybe for interactive whiteboards this approach is the best because Openboard don't coexist with other software at the same time or don't need to be streamed over Internet, but in many situations in the actual context window option is very important.

**Comment by kaamui** [comment]
Hello,

As I already said, if the option is configurable, disabled by default, and editable via a checkbox in the display tab of the preferences, I'm sure it will not bother anyone. 

@fsckawk already made a PR. I think He found an issue with multi-screen mode, though.  Just clean it up, add the "default disabled" configuration option, add logic to be able to modify it from the preferences, and I'll add it. 

What we don't want is to make changes that force our teachers to relearn how to use OpenBoard at every patch. So all you need is to make it transparent for standard users, but available for the advanced ones.

There's a ton of examples in the commits history where I add a configurable option, it's quite easy. 

The only difficulty may reside in making this feature behave properly in multi-screen (go back to full screen (and disable the option if multi-screen activated)), or make it work with multi-screen (but not sure we want that for secondary screens), or maybe maintain main screen windowed but others full-screen (but again, not sure if it a useful use case).

**Comment by vitsca** [comment]
> What we don't want is to make changes that force our teachers to relearn how to use OpenBoard at every patch. So all you need is to make it transparent for standard users, but available for the advanced ones.

Absolutely agree on that. Just to put the feature request in context... I am doing a technology review for my department about setting up an environment for online teaching that is completely portable in Windows, Mac, Linux.. and I found that a nice writing pad (up to Wacom one, for example) plus OpenBoard plus "your favourite remote meeting tool" could really be perfect for the purposes of our department (and of our school)... 

Looking forward to it.. we are really in need for it.. so I will count the hours :-) Thanks a lot!

**Comment by fsckawk** [comment]
For those of you who need to use that option now, there are precompiled binaries with my patch applied here:
http://webdiis.unizar.es/~spd/openboard/

**Comment by vitsca** [comment]
> For those of you who need to use that option now, there are precompiled binaries with my patch applied here:
> http://webdiis.unizar.es/~spd/openboard/

Thank you very much .. I tried it but is only a partial solution to my problem.. in fact, I would need the "presentation" screen to be in a window so that it can be shared without taking the entire screen (which I also use to manage the class in Zoom). 
As an aside note: today I tried what looked a potential workaround: I noticed that I had the "window" of the application presentation in the list of the shareable windows in Zoom and shared it. And it worked: I was sharing it but could partially cover it with the zoom window without this covering being  noticed by the remote students. But an unexpected behaviour occurred with this setting: my pen writing was shown with a 10-20 seconds lag. Which did not occurred if I shared the presentation as a "screen" (with the problem again of taking the entire screen). 

Thanks again all for the help on this issue.. I really do want to use Open Board and present it to my colleagues in the department.. thanks

**Comment by fsckawk** [comment]
Strange. I've used "my" OpenBoard with Google Meet, and I haven't noticed this behaviour. I will try with Zoom.

**Comment by profejuanca** [comment]
Muchas gracias José, lo pruebo ahora mismo y te digo como me va.

**Comment by profejuanca** [comment]
The context is similar to me, it's practicle if both windows have the option separately, is exactly like Ardour does, in dual monitor configuration many posibilitys are available with this option for each window separately.

**Comment by profejuanca** [comment]
> For those of you who need to use that option now, there are precompiled binaries with my patch applied here:
> http://webdiis.unizar.es/~spd/openboard/

José, with this comand:

env LD_LIBRARY_PATH=$PWD/lib ./OpenBoard

i have the error:

env: «./OpenBoard»: No existe el archivo o el directorio

the same error if I try only ./OpenBoard

and if I try the same with W at end


env LD_LIBRARY_PATH=$PWD/lib ./OpenBoardW

this other

./OpenBoardW: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory

the same if  I try only: 
./OpenBoardW

**Comment by vitsca** [comment]
> Strange. I've used "my" OpenBoard with Google Meet, and I haven't noticed this behaviour. I will try with Zoom.

Sorry .. I was reporting what happened with the "standard" OpenBoard.. will try with yours :-) 
Thanks!

Vittorio

**Comment by fsckawk** [comment]
> env LD_LIBRARY_PATH=$PWD/lib ./OpenBoard
> 
> You have an idea on this errors?

> env: «./OpenBoard»: No existe el archivo o el directorio

Right, in the instrucctions the final "W" is missing. I've fixed that.

> and if I try the same with W at end
> 
> env LD_LIBRARY_PATH=$PWD/lib ./OpenBoardW

> ./OpenBoardW: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory
Try this:
sudo apt-get install libquazip-dev
If after that you get new missing shared libraries, you could try to install the ones listed in the compilation instructions for ubuntu.

**Comment by fbarillon** [comment]
sudo apt-get install libquazip-dev
E: Impossible de trouver le paquet libquazip-dev
On Ubuntu 20.04 the library doesn't exist with this name.

**Comment by kaamui** [comment]
You can find a new page to help building OpenBoard on Ubuntu 20.04 here : 
https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04

```
#C++ wrapper for ZIP/UNZIP (development files)
sudo apt install libquazip5-dev
```

**Comment by fbarillon** [comment]
Does this version allow a windowed mode ?

**Comment by fbarillon** [comment]
sudo apt install libquazip5-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les paquets supplémentaires suivants seront installés : 
  libquazip5-1
Paquets suggérés :
  libquazip-doc
Les NOUVEAUX paquets suivants seront installés :
  libquazip5-1 libquazip5-dev
But :
~/OpenBoardW$ env LD_LIBRARY_PATH=$PWD/lib ./OpenBoardW
./OpenBoardW: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory

**Comment by fsckawk** [comment]
I don't know which package is libquazip5-dev, in bionic is called libquazip-dev.
Perhaps is that a newer version. In that case, I'm afraid you will need to compile the sources. There are instructions in my page, it is not too difficult.

**Comment by profejuanca** [comment]
Yes, your brach works on bionic with LibQuazip, but not in Focal :( I recently updated the system and don't work for now.

**Comment by sagredo-dev** [comment]
I modified @fsckawk (thanks for his work!) patch to let user to enable/disable window/fullscreen mode with no need to adjust the running mode at compilation time. On linux just edit /opt/openboard/etc/OpenBoard.config or (even better) 
~/.local/share/OpenBoard/OpenBoardUser.config and adjust this option 

`RunInWindow=true`

[https://notes.sagredo.eu/files/hacks//openboard//run-in-a-window.patch](https://notes.sagredo.eu/files/hacks//openboard//run-in-a-window.patch)

**Comment by pbakes** [comment]
@profejuanca You have any plans on recompiling the latest version? Yours doesn't currently have up-to-date dpi awareness for multi-monitor setups, so the icons are large and pixelated

**Comment by lucasmazzetto** [comment]
Why is there no possibility to run in window mode?

**Comment by lucasmazzetto** [comment]
why is there no possibility to run in window mode without patching?

**Comment by lucasmazzetto** [comment]
Why is there no possibility to run in window mode without patching?

**Comment by fsckawk** [comment]
> @profejuanca You have any plans on recompiling the latest version? Yours doesn't currently have up-to-date dpi awareness for multi-monitor setups, so the icons are large and pixelated

I'd like to try it, but I don't know when I'll find some free time to do it.

**Comment by fsckawk** [comment]
> Why is there no possibility to run in window mode without patching?

The main developers team doesn't like that. Therefore we need a patch for the source code. I'd like to make a better patch, that would enable the windowed mode thru normal preferences, instead of at compiling time.

**Comment by kaamui** [comment]
That is not true. I'd like to look at it but it's just not a priority at this time. It's one of the most requested features so of course it will be added, probably after 1.6.1 hits a stable state (as a disabled-by-default option in the config file probably), but it must be widely tested, and due to our limited resources (1 developer and 3 testers, nobody in full-time), it will take time.

I'll try to look at your PR as soon as I can.

**Comment by fsckawk** [comment]
Ok, thanks a lot. I'm happy to find out I was wrong.
Perhaps you could consider also the posibility of implementing this as a runtime option.

**Comment by fsckawk** [comment]
> I modified @fsckawk (thanks for his work!) patch to let user to enable/disable window/fullscreen mode with no need to adjust the running mode at compilation time. On linux just edit /opt/openboard/etc/OpenBoard.config or (even better)
> ~/.local/share/OpenBoard/OpenBoardUser.config and adjust this option
> 
> `RunInWindow=true`
> 
> https://notes.sagredo.eu/files/hacks//openboard//run-in-a-window.patch

Great!
Thanks a lot.

**Comment by kaamui** [comment]
Can you integrate this patch and refactor its name to windowedMode and place it (if not) in the [App] section ?

> Perhaps you could consider also the possibility of implementing this as a runtime option

Yep, in a second time though, again for resources management reasons

**Comment by e-t-l** [comment]
> I modified @fsckawk (thanks for his work!) patch to let user to enable/disable window/fullscreen mode with no need to adjust the running mode at compilation time. On linux just edit /opt/openboard/etc/OpenBoard.config or (even better)
> ~/.local/share/OpenBoard/OpenBoardUser.config and adjust this option
> 
> `RunInWindow=true`
> 
> https://notes.sagredo.eu/files/hacks//openboard//run-in-a-window.patch

@sagredo-dev  Just to clarify, if I install the default, up-to-date build of of Openboard then set this switch in openboarduser.config, it will work?

**Comment by sagredo-dev** [comment]
yes, but I tested my patch up to version 1.6.1rc-0309

**Comment by e-t-l** [comment]
Okay I see where I misunderstood how the patch was implemented, but theanswer to my question is definitely actually, "No." First the patch has to be downloaded and used to compile a completely new package. It requires a number of prerequisites, and the instructions are only for Linux. The patch is not included in the default 1.6.1 package and adding the RunInWindow switch to the config files will do absolutely nothing.

**Comment by kaamui** [comment]
RunInWindow PR added to 1.7 branch

**Comment by jayakanthan-r** [comment]
I am not able to see this flag in the settings window in the latest version(1.6.3).
Was this removed for some reason? Thanks!

**Comment by letsfindaway** [comment]
See one comment above yours:

> RunInWindow PR added to 1.7 branch

So this feature will only be available from 1.7.0 upwards.

**Comment by jayakanthan-r** [comment]
Thanks for the update @letsfindaway

**Comment by yanjankaf** [comment]
i mean why in the hell, anyone would not add support for windowing by default, and what's there to learn new - the guy is saying he doesn't want teachers to learn new things, what is there to learn - every app has window, and your has a icon, so you can jump to desktop with bunch of icons still dangling - where did you learn User experience from, i ask ? 

Furthermore there is no option is display in preferences tab, to display it as a window.

Don't make it, if you cant add support for window, just add a button on the top bar that says full screen, and when your users need full screen support they will enter it.
