### ISSUE TITLE
No working correctly in desktop mode 

### ISSUE THREAD

**Issue by jegarfa** [OpenBoard-org/OpenBoard#347]
Dear all, 
Thanks for this amazing tool.

I'm under linux. The issue I have is when I try to draw something in desktop mode, I cannot draw nothing on the screen after select whether the pointer, pen etc, only appears the icon but is not working (in desktop mode). It seems to me like it's drawing in background, because when I switch to whiteboard and then again to desktop mode the tracers in the screen appear.
I tried with the version provided via flatpack and with the .deb but the issue is the same.  

Thanks!
J

**Comment by kaamui** [comment]
Hello,

On what OS are you and what version did you use ? T

**Comment by jegarfa** [comment]
Hi, 
I am using OpenBoard 1.5.4 on Linux Mint 19.3 with cinammon environment.

**Comment by kaamui** [comment]
Ok. This bug has been fixed in the 1.6 versions. You can download the latest release [here](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.0a3)

It is still in an alpha state, but mostly because we don't have ended our internal tests.
