### ISSUE TITLE
compilation of Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by npettiaux** [OpenBoard-org/OpenBoard#349]
I try to compile on Ubuntu 20.04 and get :
/usr/bin/ld : ne peut trouver -lquazip
/usr/bin/ld : ne peut trouver -lxcb-xfixes
/usr/bin/ld : ne peut trouver -lxcb-shape
/usr/bin/ld : ne peut trouver -lbz2

What do I have to do ?

**Comment by kaamui** [comment]
Hello,

I just published  the new page on the wiki : 

https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04#install-needed-packages

**Comment by npettiaux** [comment]
Thanks. I'll try when I can
