### ISSUE TITLE
Build fail for android using QT for android

### ISSUE THREAD

**Issue by dhirajkpathak** [OpenBoard-org/OpenBoard#351]
I am trying to compile OpenBoard for android, using below tools on ubuntu 18.04 LTS
QT for android (v5.14)
QT creator (v4.12.1)
(I am using clang to compile it for android)
I think it's possible to compile it for android as QT does have support for android.
or does it depend on a specific hardware or software feature not supported by Android?

**Comment by mark-stopka** [comment]
I don't believe Android is supported platform, but either way you should include the errors (log-files,...) when reporting an issue.

**Comment by kaamui** [comment]
Hello,

Android is not supported. Some dependencies are not satisfied (like Qtwebkit) so I don't think it is possible without a lot of work.
