### ISSUE TITLE
White line border when importing a pdf

### ISSUE THREAD

**Issue by SamirSaidani** [OpenBoard-org/OpenBoard#353]
Steps to reproduce:
- create a plain black 16:9 slide with libreoffice impress
- export it to PDF
- import it to OB
- move around the slide with the hand, you'll see a white lining surrounding the black slide

Tested both with 1.5.4 and 1.6.0a3 Windows version (W10 - dual screen)

**Comment by kaamui** [comment]
Hello,

Thank you for reporting. 

Due to our limited resources, we won't be able to prioritize on this one.
