### ISSUE TITLE
Eraser outline left on canvas when you switch via C-e C-i (Eraser to Pen switch)

### ISSUE THREAD

**Issue by Veek** [OpenBoard-org/OpenBoard#354]
[https://i.imgur.com/vNfiMOs.png](https://i.imgur.com/vNfiMOs.png)

It disappears when the screen is redrawn - desktop switching but it could interfere with screen recording.

**Comment by kaamui** [comment]
Hello,

Thank you for reporting this.

**Comment by toeben** [comment]
The same happens when switching pen and eraser using the buttons on my Wacom pen (Wacom One digitizer). Also the first line drawn after switching back to the pen is not pressure-sensitive.

**Comment by jolars** [comment]
I am getting similar problems with a Wacom Cintiq 16 and using the eraser part of the pen.
