### ISSUE TITLE
no output in display window

### ISSUE THREAD

**Issue by jmriego** [OpenBoard-org/OpenBoard#356]
Hi! I'm just starting to use OpenBoard and loving it. I'm running into an strange issue though.

The display window is not working properly for me. The only thing I see is a black screen. The only way I can make it refresh and show something is by duplicating the page and then the output will show. But new changes I make (drawing or any other) won't show in the display window until I create a new page again

This error is only happening if OpenBoard opens a control and a display window. In my case this happens when I connect two separate screens to the laptop. If I start the program with none or just one screen connected, OpenBoard is opening in single window mode and everything works as expected for me

I have tried in Ubuntu 18 and 20. Also the flatpak versions, dev branches, compiling and binaries since 1.5.4 but no luck

**Comment by diegocaja** [comment]
Hi, I just another user of OpenBoard on Linux. One year ago I found me with a similar problem and then I look at google and I found something related to the "Compositor" (https://askubuntu.com/questions/642219/how-to-enable-drop-shadows-in-plasma-5), for my experience I suggest you can try to change between XRender, OpenGL 2  and OpenGL3.

**Comment by kaamui** [comment]
Hello,

If understood correctly, you are in extended mode withe multiple screens. In this configuration (not in clone mode), what you see on the display window is the n-1 page. So if you are on the page 14, the display window shows page 13. It is the expected behavior
