### ISSUE TITLE
Building Openboard on Ubuntu 20.04

### ISSUE THREAD

**Issue by cheapskate-mj12** [OpenBoard-org/OpenBoard#362]
Following these instructions:
https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04

I get all the way to
qmake OpenBoard.pro

And I get the following output:
Cannot read /home/teamlaptop/Documents/openboard/OpenBoard-ThirdParty/libs.pri: No such file or directory
sh: 1: Syntax error: "&" unexpected
sh: 1: cannot create build/linux/release/version: Permission denied
sh: 1: cannot create build/linux/release/longversion: Permission denied
sh: 1: cannot create build/linux/release/svnversion: Permission denied
sh: 1: Syntax error: "&" unexpected
sh: 1: cannot create build/linux/release/version: Permission denied
sh: 1: cannot create build/linux/release/longversion: Permission denied
sh: 1: cannot create build/linux/release/svnversion: Permission denied
sh: 1: Syntax error: "&" unexpected

Tried running as sudo, no better result

**Comment by jegilles** [comment]
To solve the OpenBoard-ThirdParty problem, go in the OPenboard folder you created and run
`git clone https://github.com/OpenBoard-org/OpenBoard-ThirdParty.git`

In my case, it solved the issue ;-)

I didn't get the permission denied issues so you might want to check you have read/write permissions on your folders.
I did get the  Syntax error: "&" but it seems to not be a problem.

However, after I started the compilation I got an error stating that the file aconf.h was missing. I found it online here :
[https://github.com/lefteous-tc/xPDFSearch/issues/2](https://github.com/lefteous-tc/xPDFSearch/issues/2)

After restarting the compilation, it goes further but then I get the error:

/usr/include/poppler/SplashOutputDev.h:202:5: error: ‘SplashThinLineMode’ has not been declared
  202 |     SplashThinLineMode thinLineMode = splashThinLineDefault,
      |     ^~~~~~~~~~~~~~~~~~
/usr/include/poppler/SplashOutputDev.h:202:39: error: ‘splashThinLineDefault’ was not declared in this scope
  202 |     SplashThinLineMode thinLineMode = splashThinLineDefault,


and here no solutions so far ... does anybody have an idea?

**Comment by kaamui** [comment]
Hello,

I though it was possible to compile without the third-party repository. I'm pretty sure I did when I created the wiki. 

Are you sure you were on the right branch (dev-qt5.1x) ?

If so, I might have forgotten to push some modifications.

About the permissions issues, you probably made some attempts in root. Just modify the permissions, owner on the build folder

**Comment by viorato** [comment]
I confirm that I got the same errors: 

"Cannot read "../OpenBoard-ThirdParty/libs.pri" and "Syntax error: "&" unexpected". 

I did make sure to be on branch dev-qt5.1x .

About the "cannot create: Permission denied" message, It started to show after the second time that I run "qmake  OpenBoard.pro". It has to do with the fact that the folders are already created.

**Comment by kaamui** [comment]
I entirely reproduced the steps on a new virtual machine on Kubuntu and had no issues so far. Please verify that your branch is up to date

on the "Openboard" directory :

```
git fetch --all
git pull origin dev-qt5.1x
```

For your permission issue, as I said, you probably tried to do it as root. Try : 
```
sudo chown -R <replace this by your user name>: .

sudo rm -fr build
```
then try to recompile

for `Syntax error: "&" unexpected"` you can ignore it

**Comment by kaamui** [comment]
You're right I didn't noticed this warning. You can ignore it and launch `make`

I'll move this line soon.

Thank you for reporting it.
