### ISSUE TITLE
Unknown module(s) in QT: webkit webkitwidgets (Ubuntu 18.04)

### ISSUE THREAD

**Issue by jojoGabriel** [OpenBoard-org/OpenBoard#363]
When running (a) qmake OpenBoard.pro -spec linux-g++-64 (b) qmake OpenBoard.pro -spec linux-g++, I'm getting the following messages:

sh: 1: Syntax error: "&" unexpected
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

**Comment by kaamui** [comment]
Hello,

you need to install qtwebkit (that is not part of Qt). Please try with the instructions you can find [here](https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04)
