### ISSUE TITLE
Switching to Show Desktop on Fedora 31 renders a black screen

### ISSUE THREAD

**Issue by johnphilby** [OpenBoard-org/OpenBoard#365]
Openboard: v 1.5.4
Installed on FC26 and FC31 KDE using flatpak

When clicking on the "Show Desktop" icon and then clicking on the "Annotate Document" button, Openboard switches to a black screen. It should show the current desktop and the user should have the ability to drawn using the stylus on that screen. Does not work at the moment.

![image](https://user-images.githubusercontent.com/36290964/91634694-d8260200-ea0f-11ea-8a95-6330bd88e7f6.png)

**Comment by johnphilby** [comment]
The comments from here https://github.com/OpenBoard-org/OpenBoard/issues/66#issuecomment-561560059 helped solve the problem.

`# dnf install xcompmgr`

And xcompmgr should be running in the background. OpenBoard should include xcompmgr as a prerequisite for installation.

**Comment by johnphilby** [comment]
Linked to issue https://github.com/OpenBoard-org/OpenBoard/issues/66

**Comment by maehne** [comment]
I observed the same on Debian Buster using KDE Plasma as desktop environment and X11. Installing `xcompmgr` as suggested by @johnphilby solved the problem for me. Thanks a lot for that hint!

**Comment by lucasbianchi** [comment]
I'm running Fedora 34 with KDE. I had `xcompmgr` installed and observed the same black screen behavior. Reinstalling `xcompmgr` didn't worked.
I could solve it after changing the compositing backend from OpenGL to XRender inside the System Settings menu. I'm sorry I have the menus in Spanish and I'm not sure about the path to this option in English. In Spanish it is `Preferencias del sistema -> Compositor -> Motor de renderizado`.
Hope it helps someone else!

**Comment by maehne** [comment]
I faced again the issue on Debian Bullseye using KDE Plasma. This time installing a compositor like `xcompmgr` was not enough, because it got not started automatically when launching the KDE Plasma session. Compositing had to be enabled explicitly in the KDE Plasma's system settings. On my laptop, also OpenGL is working very well besides XRender.
