### ISSUE TITLE
Allow user to name pages, display in Thumbnail panel

### ISSUE THREAD

**Issue by Shoes01** [OpenBoard-org/OpenBoard#366]
In SMART Notebook, I used to rename all my pages to help me keep things organized.

Here is an example of what I mean:
![image](https://user-images.githubusercontent.com/3358624/91733655-38d44c80-eb80-11ea-9daf-a24631e29750.png)

The page number is displayed, and underneath is the page name. I named it "Bienvenue".

Can this feature be added to OpenBoard? I have limited experience with C++, if you point to which files I would need to modify, I may implement this myself.

**Comment by kaamui** [comment]
Due to our limited resources, we won't be able to help with this feature request
