### ISSUE TITLE
We are searching a Qt/C++ expert to help us in a short mission (20-30 days)

### ISSUE THREAD

**Issue by kaamui** [OpenBoard-org/OpenBoard#367]
Hello everyone,

We're currently searching a Qt/C++ expert (for a short mission, 20-30 days) to help us improving PDF rendering and finish the current migration from Qt 5.6 to Qt 5.14 (where some issues on OSX and Windows remain).

If you are a freelance, preferably working in Switzerland, or working on a society that can answer to the offer, please contact me.  

Strong skills in C++ and Qt are mandatory, and an experience with OpenBoard and French is a plus :)

**Comment by agriche** [comment]
Dear,

In the past, I have contributed for this project in 2015.
Could you please contact me for this Qt/C++ expert (for a short mission,
20-30 days).

Thank you for your response.

Best regards

Abdel
