### ISSUE TITLE
Color selection widget does not show current color

### ISSUE THREAD

**Issue by a3nm** [OpenBoard-org/OpenBoard#368]
Hi,

On OpenBoard 1.5.3, the "Color" widget (second item from the left at the top of the screen) does not show the currently selected color, unlike the "Line" and "Eraser" immediately at the left.

This is a problem when using OpenBoard with a tactile screen or tablet: when tapping the color button, it is not clear whether the tap was correctly registered or not. The workaround is to try drawing, notice it's the wrong color, cancel (Ctrl-Z) and tap again.

Would it be possible to make the "Color" widget show the current color, so that it is easy to tell if changing to a different color has worked?

Many thanks for your work on this vitally useful software!

**Comment by kaamui** [comment]
Hello,

thanks for your feedback. We already have been notified about this bug, and it is in our todo list for the next release.
