### ISSUE TITLE
Desktop display has low framerate

### ISSUE THREAD

**Issue by DurandA** [OpenBoard-org/OpenBoard#369]
Using OpenBoard 1.5.4 on Windows, the framerate is very low when displaying desktop on extended display (~5 fps). This is inadequate for displaying media content or live software demonstrations.

Is there any option like GPU acceleration that could be enabled in order to improve this?

**Comment by kaamui** [comment]
Hello,

I think you are talking about screen mirroring (the "eye" icon is opened in Desktop Mode). If so, you can modify `RefreshRateInFramePerSecond` in your configuration file (on the `[Mirroring] Seciton) to increase the refresh rate

**Comment by DurandA** [comment]
Thank you very much for the clarification. @pasquiej @polchky
