### ISSUE TITLE
Box object (enhancement)

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#37]
Français:
OpenBoard n'ayant pas gardé les données Enseignant, il serait utile de disposer d'un objet "boîte" ayant pour caractéristiques un état fermé (simple icône) et un état ouvert (vue du contenu). Ce contenu pourrait être:
- du texte (consignes, indices)
- des documents (images, étiquettes) qui pourraient être glissés sur la page.

English:
A "box" object could be useful. It could have a closed state (simple icon) and an opened state. The content could be:
- text (instructions, tips...)
- draggable documents.

**Comment by pgilfernandez** [comment]
It would be nice to have not only a box (rectangle) object but a circle (ellipse) one.
It's very common to use these figures when wanting to mark something at class.

Thanks

**Comment by fbarillon** [comment]
On Blois, a student is working on this object as a widget.
I can ask him to add an elipse.
I'll send you the state-of-art as soon as possible.

**Comment by pgilfernandez** [comment]
Nice!
If it's a widget, would it be listed on the main object panel?

**Comment by fbarillon** [comment]
Hi! We are proud to present the box widget, realised by Corentin.
[Box widget.wgt.zip](https://github.com/OpenBoard-org/OpenBoard/files/1112277/Box.widget.wgt.zip)
François

**Comment by pgilfernandez** [comment]
Nice... how can I edit the lock picture inside the box and how I can change its settings (background color, line stroke, ...)?
Anyway, I was talking about an "extension" of the line tool but for drawing boxes:
<img width="432" alt="box" src="https://user-images.githubusercontent.com/5942369/27714254-1ac67c36-5d30-11e7-8e48-8fe9f57a451d.png">


Thanks

**Comment by fbarillon** [comment]
At the present state, you can only set a title and choose the background color. The aim is not drawing a box, but gathering graphics elements as in a folder.
The code for drawing shapes is in Open-Sankoré 2.51 but "someone" has to adapt it to the Qt5 libraries used by OpenBoard.
![sankore-graphic-tools](https://user-images.githubusercontent.com/18069837/27723539-f44d8a70-5d6d-11e7-8bb5-bb20879a435c.png)

**Comment by pgilfernandez** [comment]
Oh, "drawing shapes" are what I was looking for... well, we'll have to wait for someone to adapt it to Qt5...

Thanks!
