### ISSUE TITLE
Export to png

### ISSUE THREAD

**Issue by ftorradoc01** [OpenBoard-org/OpenBoard#371]
Hi, I'm a math teacher that is trying to move from smartboard notebook to openboard. 
Right now i'm widely using the exportation to png to create contents. 
So as soon as this option is implemented i will change to openboard

Thank you

**Comment by Gvf63** [comment]
It is possible to convert a whole lesson (all pages) into a pdf file. Instead, if you want to convert a page or part of it into a png just use the "capture a part of the screen" function and save in the library. You will find the file in the images / openboard folder.

**Comment by ftorradoc01** [comment]
Thank you for the answer but what I would apreciatte to be included is a batch process (that all board sofware include) to convert every page into a png file, so that, if you have 20 sheets in your session you'll automatly obtain 20 png files.
Thank you very much for your work

**Comment by Gvf63** [comment]
You can export the lesson to pdf and then convert it to a series of pngs using one of the many sites that do the conversion or to linux using poppler in terminal ($ pdftoppm png file.pdf outfile)

**Comment by kaamui** [comment]
It could be very easy imo to implement what you want, but due to our limited resources, we won't be able to help on this one. Please consider @Gvf63 advices.
