### ISSUE TITLE
Windows 10 - Openboard won't launch and no error given.

### ISSUE THREAD

**Issue by ckza** [OpenBoard-org/OpenBoard#372]
When I open Openboard, it starts for a second before terminating and no error given. Use a lot of VCRedist's so not sure if it's contributing at all.

Latest Windows (non dev) - everything is updated. Norton AntiVirus (tried in silent mode, no luck).

Any ideas? How can I get a crash / error log when this fails to launch?

**Comment by kaamui** [comment]
Sadly there's actually no log system in OpenBoard. I never experience such issue. What version did you try ?
