### ISSUE TITLE
Poor Mac optimization

### ISSUE THREAD

**Issue by SoPat712** [OpenBoard-org/OpenBoard#374]
I understand that a large portion of the user base uses other OS', but Mac is a pretty large OS, and there are some weird interactions that cause other apps to work poorly with Open Board. First of all, most Mac apps utilize the menu Bar.

![image](https://user-images.githubusercontent.com/30350506/94021698-501ee800-fd82-11ea-9d1c-ad2724ac7b34.png)

One of the most crucial parts of the menu bar is providing keyboard shortcuts for accessibility purposes, as it allows people with disabilities to still be able to access the keyboard shortcuts without the keyboard.

To continue, while the interface is nice and has a "retro" kind of feel, there is still no way to rebind keyboard shortcuts. As a note, adding all shortcuts to the menu Bar would mean that the keyboard shortcut issue wouldn't even need to be addressed, as Mac OS already has an integrated way to rebind keyboard shortcuts.

Finally, in external app interactions, the only commands for Open Board are hide in mac, and show in Mac. This causes problems with window managers and means that you can't even see Open Board in mac's Cmd+tab shortcut. This is by far the largest issue. I'm not sure if Open Board is ported from Linux, but the fact that you can't even see that the app is open and Cmd+tab to it is a major issue.

Thanks for any help in advance!

**Comment by lwouis** [comment]
Referencing the issue in AltTab's repo: https://github.com/lwouis/alt-tab-macos/issues/621

**Comment by macaroon75** [comment]
Mac's are used extensively by teachers. I love open board but it crashes continually on a MacBook pro.

**Comment by SoPat712** [comment]
Ok, so the problem isn't just for me! Thanks for reassuring my fears.

**Comment by macaroon75** [comment]
I will say I have never used Github, logged in specifically to report this because I think this software is one of the most important teaching tools I have come across in a long time. It is only that it crashes that I can't use it. I really hope this issue can be addressed. In terms of design it is 9/10.

**Comment by SoPat712** [comment]
Have you looked into the smart board lineup of apps? Those are also teacher oriented, but are expensive and lack OSX optimization. I'm not a teacher, but I've - heard good things about the intuitiveness of SMARTBoard.

**Comment by macaroon75** [comment]
Thanks for that. Education sector uses Mac OS a lot. Would be great to find one useful for Mac.

**Comment by kaamui** [comment]
Catalina is not officially supported at this time. If you want to use Openboard on it, please consider using the latest release on Github, not the 1.5.4 version
