### ISSUE TITLE
Erratic annotations in Show Desktop

### ISSUE THREAD

**Issue by kzembower** [OpenBoard-org/OpenBoard#376]
Hello,

I experience erratic Pen and Eraser actions when trying to annotate the display of another programs, or even just my window manager's Desktop, with Show Desktop. By 'erratic,' I mean:

- When drawing with the Pen, lines don't appear immediately, as they do with the OpenBoard screen itself. Instead, the lines only appear when the OpenBoard toolbar (bar that contains the Pen, Eraser, etc) is moved, even slightly.

- The cross-hair cursor for the Pen disappears.

- When using the Eraser (with the medium size, to see the effect easily), the erasure circle can be flattened on one or more sides, and can be used to trace the outline of a many-sided polygon, that seems to exist invisibly on the screen, but can be detected by moving the erasure circle cursor around. 

I am using Ubuntu 18.04, and installed version 1.5.4 using the directions at https://gitmemory.com/issue/OpenBoard-org/OpenBoard/292/615432314 (without any problems). These problems also existed in verison 1.5.3, with some small variations.  Here's some data on my graphics system:
```
~$ inxi -xzG
Graphics:  Card: NVIDIA GT218 [GeForce 210] bus-ID: 02:00.0
           Display Server: x11 (X.Org 1.19.6 ) drivers: nouveau (unloaded: modesetting,fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: NVA8 version: 3.3 Mesa 20.0.8 Direct Render: Yes
```
Please let me know if there's any other information I can give you to help resolve this issue. I'd really like to use OpenBoard in Linux, because it's the only program I can find to annotate displays.

-Kevin

**Comment by kaamui** [comment]
this issue is fixed on the dev-qt5.1x branch, but Ubuntu 18.04 package is not provided as we officially maintain OpenBoard for Ubuntu 20.04.  

Please follow the wiki to compile OpenBoard yourself, it's pretty simple => https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04
