### ISSUE TITLE
Feature request: keyboard shortcuts for all commonly used actions

### ISSUE THREAD

**Issue by kzembower** [OpenBoard-org/OpenBoard#377]
I would like to request that all commonly used actions have a keyboard shortcut, that would enable or disable them with one or a few keystrokes. Common actions could include:

- changing pen colors
- changing from pen to eraser and back
- next page/previous page
- erase all
- etc.

The purpose of these shortcuts would be for the operator to use the pen and tablet with their dominant hand, and select various actions with the keyboard with their non-dominant hand.

These keyboard shortcuts could also be used in 'macros' that might map to tablet buttons or to other operating system abilities.

Thanks for considering this request.

-Kevin

**Comment by SoPat712** [comment]
This is actually one of the major problems with OpenBoard, keyboard shortcuts are really a must, and the fact that it doesn't have it, really sucks.

**Comment by kaamui** [comment]
This is the most requested feature, and we will prioritize on it as soon as we can.
