### ISSUE TITLE
Panel for Presenter-Notes

### ISSUE THREAD

**Issue by 0x48S** [OpenBoard-org/OpenBoard#38]
First of all thank you for this really nice piece of software. The only thing I really do miss is an extra left panel for presenter-notes like there is in open-sankore. For teaching/presenting this is feature is very, very helpful.

I occasionally got some crashes after I inserted a video file and then changed pages. I'll write a bug report if I can reproduce it consistently. BTW if you need some additional testers (Linux, Windows) just write me a note.

Thanks,
Henning

**Comment by fbarillon** [comment]
Il faudrait a minima pouvoir noter (mode document?) qui a fait un document pour permettre la mutualisation.
_At least, it would be useful to have a metadatas field somewhere (document mode?) to answer the who? what? where? when? information when you use a file made by another one._

Si un champ "enseignant" est ajouté pour chaque page, l'édition doit être plus simple que pour Open-Sankoré (texte enrichi façon blog, possibilités de copier-coller).
_If the "teacher" field enhancement is retained, it should be simplier than the Open-Sankoré way, allowing basic text editing and cut-pasting from a page to another._

**Comment by 0x48S** [comment]
> If the "teacher" field enhancement is retained, it should be simplier than the Open-Sankoré way, allowing basic text editing and cut-pasting from a page to another.

I agree, a basic text editing window would be fine

**Comment by lauhub** [comment]
If this enhancement is implemented, I would suggest something that allows to extract automatically presenter notes from an external file (e.g. text file with a specific format) or using LaTeX Beamer "note" feature (as described [here](http://tex.stackexchange.com/questions/48402/personal-notes-when-preparing-a-talk-with-latex-beamer-class)).

In this last case, importing should be able to retrieve and link both PDF documents: viewer mode and presenter mode.

Something like a "real" presentation mode with elapsed time and a preview of the next slide to come would be a nice thing too (but perhaps I should open another issue for this specific enhancement ?)
