### ISSUE TITLE
Updating quazip breaks OpenBoard

### ISSUE THREAD

**Issue by Larson40** [OpenBoard-org/OpenBoard#381]
Updating quazip to the latest version quazip-1.0.1-x86_64 breaks the OpenBoard installation. By reverting back to quazip-0.9.1-1-x86_64, Openboard works again.

**Comment by iyanmv** [comment]
I don't think this is an OpenBoard issue. I also had that problem recently in Archlinux when I tried to compile, and after checking the latest version of `quazip`, there is a new data structure (probably a bug). As a temporary solution (I am assuming you are using the PKGBUILD from AUR), just create the following symbolic link:

```
sudo ln -s /usr/include/QuaZip-Qt5-1.0/quazip/ /usr/include/quazip5
```

**Comment by Larson40** [comment]
I have been speaking with the developer of quazip. According to him, the newest update of quazip should not effect the installation of the quazip that OpenBoard uses. It may be an issue concerning how the new instance of quazip is installed. If OpenBoard wants to make use of the new quazip update, there may need to be adjustments to where it searches for the files.

I am not a developer, just a teacher who loves OpenBoard, so I wouldn't know how much effort that would be.

Thanks for replying Iyanmv.

**Comment by Larson40** [comment]
I made the symbolic link to /usr/include/quazip5. If OpenBoard is already installed when quazip is updated, OpenBoard will still not function. By removing OpenBoard, and reinstalling after making the symbolic link, the installation process seems to work as it should, but towards the end gives an error that -lquazip5 cannot be found.

**Comment by iyanmv** [comment]
I think you are confusing installation and compilation. But anyways, I can replicate your error. I think OpenBoard is not prepared to use the last version. I will create a new PKGBUILD in AUR using the 0.9.x version.

**Comment by iyanmv** [comment]
Okay, so I uploaded a PKGBUILD to AUR with the [legacy 0.x version of quazip](https://aur.archlinux.org/packages/quazip-legacy/). The only thing you need to do is go to the depends list and replace quazip with quazip-legacy. If you are using any AUR helper, you are done and it should work.

For any OpenBoard developers reading this, this is not a OpenBoard bug and you can close it. Archlinux does not package OpenBoard (yet) in their official repos.
