### ISSUE TITLE
How to use Openboad on Ubuntu Server?

### ISSUE THREAD

**Issue by rakibulinux** [OpenBoard-org/OpenBoard#383]
Hello, All,
I want to know how I can use OpenBord on a Ubuntu Server. I want to use it as my school whiteboard. Any help will appreciate it. 
Thanks

**Comment by kaamui** [comment]
You need to compile OpenBoard by yourself, if you want to make it launch on an OS that is not officially supported. 

You can try to start with the Ubuntu 20.04 wiki to see if it can help you go through => https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04
