### ISSUE TITLE
HiDPI display.

### ISSUE THREAD

**Issue by osbama** [OpenBoard-org/OpenBoard#384]
I am running Windows 10 with a HiDPI display. 
The application does not honor the UI scaling of Windows fully. The text is O.K. but the icons and menu items are very small and illegible. The only viable resolution I can use the app is 1920x1080

![image](https://user-images.githubusercontent.com/15921496/95662254-421ce580-0b3e-11eb-8d2f-2040b30a948a.png)

**Comment by kaamui** [comment]
Hi,

This is the seconde most requested feature. We plan to prioritize on it soon. Thanks for reporting it.

**Comment by VolkerWilkens** [comment]
We have the same issue in Munich:
When using Windows and a 4K-Display, the text is O.K. but the icons and menu items are very small and illegible.
We are using OpenBoard in schools in Munich.

Best regards
Volker Wilkens
LHM Services GmbH Munich

**Comment by Amr-Ibra** [comment]
Maybe please keep this issue open as long as it's not fixed in the code, so that people can easily find it to either upvote it or for contributors if they want to contribute code.
