### ISSUE TITLE
[Feature request] Please include an option for the eraser to eraze whole strokes

### ISSUE THREAD

**Issue by Photon89** [OpenBoard-org/OpenBoard#386]
I used Xournal++ for teaching so far but now got the hint to have a look at OpenBoard which has many nifty features specifically for teaching.

A feature which I like in Xournal++ a lot is that there is an option for the eraser to delete complete strokes rather than the parts which are directly below the eraser. It would be great to have this eraser mode in OpenBoard as well!

Thanks!

**Comment by Gvf63** [comment]
Each stroke is an openboard object, if you select it you can delete it by pressing the X icon

**Comment by Photon89** [comment]
@Gvf63: Thanks for the workaround! But it is much quicker to use my stylus' eraser button than switch to select tool, select object, press the X icon, switch back to the pen tool...

**Comment by Larson40** [comment]
You can also use Ctrl/cmd + z to remove the last open stroke.

**Comment by Photon89** [comment]
@Larson40 Sure, I could actually use the undo button which is quick to access with the pen, but as you already mentioned it only works for the last stroke.

**Comment by kaamui** [comment]
Hi,

You already can do that by performing a long press on the erase icon.

**Comment by Photon89** [comment]
As far as I can see "Erase annotations" is just the label of the erase icon. Unfortunately, I don't see any change when doing a long press on the erase icon, still only erases what is below the eraser circle, not whole strokes...
