### ISSUE TITLE
Libquazip5.so.1 not exit

### ISSUE THREAD

**Issue by kogeletey** [OpenBoard-org/OpenBoard#388]
Hello, I can't run openboard on archlinux. Returns an error 
```sh
openboard: error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory
```

**Comment by Larson40** [comment]
Openboard requires an older version of quazip. Install quazip-legacy from the AUR

**Comment by kogeletey** [comment]
Now he's swearing at another lib.
```sh
openboard: error while loading shared libraries: libpoppler.so.102: cannot open shared object file: No such file or directory
```

**Comment by Larson40** [comment]
That sounds like your /usr/share/lib folder might be missing, or have issues.

**Comment by kogeletey** [comment]
Oh,no. Other programs work fine

**Comment by FernandoVelcic** [comment]
I have the same problem running on archlinux

![image](https://user-images.githubusercontent.com/7217340/126586984-cd8f1539-c09b-4874-808a-c6f83dc9f115.png)

**Comment by Anindyadeep** [comment]
> yeah I have the same issue 
![Uploading image.png…]()
