### ISSUE TITLE
Personal Dictionary only recognizes "English (United States)"

### ISSUE THREAD

**Issue by KeronCyst** [OpenBoard-org/OpenBoard#390]
I had a ton of typing shortcuts in "English (US)" and they're unavailable in OpenBoard despite having been available in Gboard (which I'm otherwise trying to move away from); they won't show up on my Android 8.0.0, while "English (United States)" is empty and unfamiliar.

**Comment by kaamui** [comment]
Customizing shortcuts is the most requested feature, and we hope to be able to work on it soon. Not sure it will help with your issue though.
