### ISSUE TITLE
Dedicated clipboard-pasting button?

### ISSUE THREAD

**Issue by KeronCyst** [OpenBoard-org/OpenBoard#391]
So in the latest versions of Gboard, you can press arrows in the upper-left (above the "1") and invoke quick controls to paste without having to first hold your finger over the text field in which you're currently typing.

Is there any way for us to get a " paste" button, similarly? It was super-convenient.

Off-topic: while I'm at it, what is the point of the voice input key if voice dictation is disabled (I'm guessing due to privacy reasons), or am I missing something in the settings? It doesn't do anything for me, though it did when I was on Gboard just before coming here.

**Comment by kaamui** [comment]
you can copy paste objects in OpenBoard using ctrl+C/V shortcuts
