### ISSUE TITLE
Problems with three screens

### ISSUE THREAD

**Issue by enriqueartal** [OpenBoard-org/OpenBoard#395]
I am running OpenBoard 1.6.0a3 on a computer with Fedora 32. I have two screens plus a wacom tablet with screen. When I open Openboard, it appears in either one or both screens (depending on settings) but the wacom tablet, where OpenBoard is useful stop working and goes black. Is there a solution?
Thanks for your work, Enrique.

**Comment by kaamui** [comment]
I think your are referring to the normal behavior of the application if there's only one page to display, but two secondary screens. The behavior of the secondary screens is that the first displays the same page as the primary screen, the second the "n-1" page, etc.

**Comment by enriqueartal** [comment]
I think I understand now. If I open a second page the second secondary screen becomes active. Thanks.
