### ISSUE TITLE
doesn't install on Ubuntu 20.10

### ISSUE THREAD

**Issue by julianuu** [OpenBoard-org/OpenBoard#396]
Hi, I cannot install v.1.6.0a3 on Ubuntu 20.10, it says `Depends: libpoppler97 (>= 0.86.1) but it is not installable`. I checked, Ubuntu 20.10 has `libpoppler102`. 

This is not a big deal as I can install OpenBoard also via flatpak https://github.com/OpenBoard-org/OpenBoard/issues/328 and it seems to run fine. So if there is no immediate way to make it available for Ubuntu 20.10 now, please close the issue again, I don't want to distract.

**Comment by brunomnsilva** [comment]
You can create a symlink for a quick fix (for your particular situation)

libpoppler97 -> libpoppler102

**Comment by julianuu** [comment]
Thanks. How do I symlink packages? Or what exactly should I symlink?

**Comment by brunomnsilva** [comment]
Find where libpoppler102 resides (I'm on Manjaro, Ubuntu may be different), `cd` into directory ; then `sudo ln -s libpoppler102 libpoppler97`

It's just a "fake" version of libpoppler through a symbolic link. Hope this helps.

**Comment by jrangelardila** [comment]
Descargate el libpoppler que necesites de forma directa
http://security.ubuntu.com/ubuntu/pool/main//p/poppler/

**Comment by julianuu** [comment]
Thanks, installing `libpoppler97` manually helped. I didn't try symlinking. I can install openboard now, but it doesn't run, I get the same error as in https://github.com/OpenBoard-org/OpenBoard/issues/397.

**Comment by jrangelardila** [comment]
Después de tanto buscar encontré la solución la instalación de forma manual del paquete

La versión que viene en ubuntu 20.10 es mas actualizada. La solución consiste en desactualizar el paquete al instalarlo de forma manual:

http://archive.ubuntu.com/ubuntu/pool/universe/libq/libquazip/libquazip5-1_0.7.6-6build1_amd64.deb

**Comment by redcodemohammed** [comment]
Installing this
[libpoppler97](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libpoppler97_0.86.1-0ubuntu1_amd64.deb.html)
worked in my case.

**Comment by julianuu** [comment]
@jrangelardila thanks, downgrading `libquazip5-1` worked.

**Comment by sjn** [comment]
Hei!

Can we get a new release of OpenBoard that relies on dependencies that are actually available on Ubuntu 20.10? While this workaround might "solve" OP's problem, the real issue persists - namely that OpenBoard has no simple and easy-to-install package available for recent versions of Ubuntu.

**Comment by jgrnst** [comment]
> Hei!
> 
> Can we get a new release of OpenBoard that relies on dependencies that are actually available on Ubuntu 20.10? (in this case, ubuntu offers libquazip5 version 0.9.1-1). While the workarounds above might "solve" OP's problem, the real issue persists - namely that OpenBoard has no simple and easy-to-install package available for recent versions of Ubuntu.

Unfortunately, this is true. One can get the source tree from GitHub and build a package from it, but even that requires a bit of work. I was able to build a package that installs on 20.10; after the upgrade to 21.04, I rebuilt it, and it works on 21.04 as well.
