### ISSUE TITLE
Openboard en Ubuntu 20.10 Qt_5.14

### ISSUE THREAD

**Issue by jrangelardila** [OpenBoard-org/OpenBoard#397]
Buen dia

Al actualizar Ubuntu de repente Openboard presenta el siguiente error:
/opt/openboard/OpenBoard: /opt/openboard/qtlib/libQt5Core.so.5: version `Qt_5.14' not found (required by /usr/lib/x86_64-linux-gnu/libquazip5.so.1)
Igualmente observo que qt5-default esta en la versión 5.14.2+dfsg-6.

No se si existe alguna forma de solucionar este error

**Comment by jrangelardila** [comment]
Despues de tanto buscar encontre la solución la instalación de forma manual del paquete

**Comment by hexdecimal16** [comment]
Hey I am not able to understand. Can you explain how you downgraded?
