### ISSUE TITLE
Cannot Open on OSX

### ISSUE THREAD

**Issue by msadek** [OpenBoard-org/OpenBoard#398]
when opening on Mac OSX, i get this message:

“OpenBoard.app” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Chrome downloaded this file today at 1:00 PM from openboard.ch.

**Comment by kaamui** [comment]
in OSX, you must choose the signed or unsigned version depending on your version of OSX, as explained in openboard.ch
