### ISSUE TITLE
How to compile OpenBoard

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#40]
Ceci n'est pas un vrai bug, mais une demande.
Un étudiant de Blois va travailler en mai et juin sur le code d'OpenBoard afin de faire des propositions sur quelques "améliorations" décrites ici.
Serait-il possible d'avoir un "how to" qui permette de compiler le source sur Windows et sur Ubuntu?
francois point barillon at ac-orleans-tours point fr

**Comment by freeheel3r** [comment]
Bonjour,
Le readme explique comment compiler OpenBoard, c'est normalement très simple. Les instructions sont pour la compilation depuis le terminal, mais on peut tout aussi facilement (voire plus facilement) compiler avec Qt Creator.

Il faut juste savoir qu'actuellement, dans le dépôt "OpenBoard-ThirdParty", le code le plus récent se trouve dans la branche dev. Mais je vais bientôt mettre tout ça à jour sur la branche master.

**Comment by fbarillon** [comment]
Bonjour,
L'étudiant de Blois, Alexandre, a pu obtenir sous Ubuntu une version compilable avec Qt Creator et a pu commencer à travailler. Malheureusement, il peine à reconstituer la liste des bibliothèques qu'il a chargées et autres bidouilles. S'il existe un "comment faire" pour obtenir une compilation  à partir de zéro, je suis preneur.

**Comment by NT07** [comment]
Bonjour,

 J'ai tenté de compiler OpenBoard pour Fedora 24 et j'ai eu un certain nombre d'erreurs. On dirait que le compilateur ne trouve pas certains fichiers. J'ai pourtant téléchargé le dépôt 3rd Party et ai renommé certains dossiers où se trouvaient les fichiers demandés (plus de détails par la suite).

 `[root@MONNOM OpenBoard-1.3.3]# /usr/lib64/qt5/bin/qmake OpenBoard.pro -spec linux-g++-64
Cannot read /home/nt/Logiciels/OpenBoard-ThirdParty/libs.pri: No such file or directory
Cannot read /home/nt/Logiciels/OpenBoard-ThirdParty/quazip/quazip.pri: No such file or directory
Cannot read /home/nt/Logiciels/OpenBoard-ThirdParty/qt/singleapplication/qtsingleapplication.pri: No such file or directory
Cannot read /home/nt/Logiciels/OpenBoard-ThirdParty/qt/lockedfile/qtlockedfile.pri: No such file or directory
Project ERROR: Unknown module(s) in QT: webkit svg script xmlpatterns uitools multimedia webkitwidgets multimediawidgets`

 Le dossier _qt_ cherché à la compilation semble être nommé _trolltech_ dans le dossier téléchargé. Je l'ai renommé. Ensuite les dossiers -~OpenBoard-ThirdParty/qt/lockedfile/_ n'existe pas, le fichier recherché étant dans le dossier _qt_. Mais même les fichiers normaux le changent pas.

 Faudrait-il changer le makefile ? Recréer tous les dossiers manuellement en lisant ce dernier pour être guidé ?

 Et pourquoi ne pas faire appel aux versions de ces bibliothèques déjà présentes dans les dépôts de la distribution ?

 Je suis un peu perdu. Je suis utilisateur avancé et non programmeur.

 Merci d'avance !

**Comment by freeheel3r** [comment]
Salut,

Je pense que le problème est que vous êtes sur la branche `master` d' OpenBoard-Importer et OpenBoard-ThirdParty. Ce code n'est pas à jour, d'où les références à des anciennes librairies.
Je vais mettre à jour ces dépôts bientôt mais en attendant, il suffit de passer sur la branche `dev`. (commande `git checkout dev` dans ces deux dépôts ou, si vous avez juste téléchargé le code depuis ce site, il faut d'abord sélectionner la branche dev puis re-télécharger le .zip).

**Comment by NT07** [comment]
Merci, là les chemins sont bons, en enlevant le _dev_ dans le nom du dossier, mais l'erreur persiste et pourtant les fichiers sont bien présents.

 Après, peut-être faut-il construire chaque bibliothèque indépendamment, mais je lis le fichier _readme.md_ come disant que la commande que j'ai exécutée automatise tout le processus de compilation. Sinon, pourquoi l'erreur se rapporte-t-elle à un appel à des fichiers _pri_ présents dans les sources et non directement à un fichier _so_ qui aurait été préalablement construit ?

**Comment by fbarillon** [comment]
Oui, il faut d'abord construire les Third-party en suivant les readme inclus. puis compiler OpenBoard en veillant à ce que
- le  dossier de compilation de nomme bien "OpenBoard"
- que le dossier "OpenBoard-ThirdParty" se trouve bien à côté du dossier "OpenBoard"
- que l'arborescence qui mène au dossier "OpenBoard" n'inclue pas des noms de dossiers comportant des espaces.

**Comment by NT07** [comment]
Merci beaucoup !

 Plus d'erreur de bibliothèques, mais toujours l'erreur suivante :

 `[root@MONNOM OpenBoard-master]# /usr/lib64/qt5/bin/qmake OpenBoard.pro -spec linux-g++-64
Project ERROR: Unknown module(s) in QT: webkit svg script xmlpatterns uitools multimedia webkitwidgets multimediawidgets`

 Ce que j'ai trouvé correspondrait à des erreurs de version de Qt. Effectivement Fedora 24 le propose en 5.6 et non 5.5. Dois-je installer Qt 5.5 sur ma machine ?

**Comment by fbarillon** [comment]
Le 09/07/2016 11:35, NT07 a écrit :
>
> |Project ERROR: Unknown module(s) in QT: webkit svg script xmlpatterns 
> uitools multimedia webkitwidgets multimediawidgets|
>
> Ce que j'ai trouvé correspondrait à des erreurs de version de Qt. 
> Effectivement Fedora 24 le propose en 5.6 et non 5.5. Dois-je 
> installer Qt 5.5 sur ma machine ?
>
Peut-être que ces librairies doivent être chargée séparément.

Sur Ubuntu, j'ai "libqt5webkit5" dans mes paquets, ainsi que libqt5svg5, 
libqt5multimedia5, libqt5script5, libqt5svg5, libqt5widgets5, 
libqt5xmlpatterns5,
Je ne sais plus si je les ai chargés séparément.

François

**Comment by evantill** [comment]
Ca serait bien de préciser dans le README actuel que les branches dev sont à utilisées pour la compile.

**Comment by NT07** [comment]
Quelques nouveautés: le paquet manquant était _qt5-qttools-static_. J'ai aussi du installer _openssl-devel_.

 Il reste une erreur de compilation:
 `rc/frameworks/UBGeometryUtils.cpp: Dans la fonction membre statique ‘static QPolygonF UBGeometryUtils::arcToPolygon(const QLineF&, qreal, qreal)’:
src/frameworks/UBGeometryUtils.cpp:191:42: **erreur :** call of overloaded ‘abs(qreal&)’ is ambiguous
     bool overlap = abs(spanAngleInDegrees) > 360 - angle;
                                          ^
In file included from /usr/include/c++/6.2.1/cstdlib:75:0,
                 from /usr/include/c++/6.2.1/bits/stl_algo.h:59,
                 from /usr/include/c++/6.2.1/algorithm:62,
                 from /usr/include/qt5/QtCore/qglobal.h:88,
                 from /usr/include/qt5/QtCore/qnamespace.h:37,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/qt5/QtCore/qobject.h:40,
                 from /usr/include/qt5/QtCore/qabstractanimation.h:37,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from /usr/include/qt5/QtGui/QtGuiDepends:3,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from src/frameworks/UBGeometryUtils.h:33,
                 from src/frameworks/UBGeometryUtils.cpp:30:
/usr/include/stdlib.h:774:12: note : candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/6.2.1/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6.2.1/algorithm:62,
                 from /usr/include/qt5/QtCore/qglobal.h:88,
                 from /usr/include/qt5/QtCore/qnamespace.h:37,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/qt5/QtCore/qobject.h:40,
                 from /usr/include/qt5/QtCore/qabstractanimation.h:37,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from /usr/include/qt5/QtGui/QtGuiDepends:3,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from src/frameworks/UBGeometryUtils.h:33,
                 from src/frameworks/UBGeometryUtils.cpp:30:
/usr/include/c++/6.2.1/cstdlib:185:3: note : candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/6.2.1/cstdlib:180:3: note : candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/6.2.1/cstdlib:172:3: note : candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
Makefile.Release:4655 : la recette pour la cible « build/linux/release/objects/UBGeometryUtils.o » a échouée
make[1]: *** [build/linux/release/objects/UBGeometryUtils.o] Erreur 1
make[1] : on quitte le répertoire « /home/nt/Logiciels/OpenBoard-dev »
Makefile:38 : la recette pour la cible « release » a échouée
make: *** [release] Erreur 2
`

**Comment by evantill** [comment]
Je continue a essayer de compiler sous mac os x.

J'en suis à cette erreur:

> ```In file included from src/core/UBSettings.cpp:37:
> src/frameworks/UBCryptoUtils.h:34:10: fatal error: 'openssl/evp.h' file not found
> #include <openssl/evp.h>```
> 

Je vais explorer la piste `openssl-devel`...

**Comment by NT07** [comment]
À noter, une erreur similaire à la mienne notée sous OpenSuse :

 [http://readlist.com/lists/suse.com/suse-linux-e/54/272659.html](url)

**Comment by freeheel3r** [comment]
Pour OS X, j'ai un brouillon de guide pour l'installation, basé sur une installation "fraîche" d'OS X.
Ce n'est peut-être pas absolument complet mais ça devrait être un bon point de départ, notamment pour résoudre l'erreur avec SSL

> Here is a guide to starting development on OS X. This was tested on OS X 10.11 (El Capitan), but should apply to pretty much any version
> 
> 1. Install XCode (can be done via the App Store, or downloaded via Apple's developer website; either way, you'll need an Apple developer account)
> 2. Install Qt 5.5. (qt.io/download-open-source/) Make sure to include the Webengine and Script modules in the installation.
> 3. Add qmake (and other Qt tools) to PATH:
>     
>     $ export PATH=/Users/username/qt/5.5/clang_64/bin:$PATH
> 
> (Adjust the path depending on the location of your Qt install, and add this to your .bashrc to make the change persistent)
> 
> 
> 3. Install Github desktop. This isn't necessary, but it makes things easier.
> 4. Clone the repositories:
>     
>     $ git clone git@github.com:OpenBoard-org/OpenBoard.git
>     $ git clone git@github.com:OpenBoard-org/OpenBoard-Importer.git
>     $ git clone git@github.com:OpenBoard-org/OpenBoard-ThirdParty.git
> 
> 5. Checkout the dev branch, on **all three** repositories
> 
> 6. In the OpenBoard-ThirdParty repository, compile freetype, quazip and xpdf, according to the instructions in each of their folders.
> 
> At the configure step of xpdf: If you are missing Motif and X, install them using homebrew:
> 
>     brew install Caskroom/cask/xquartz
>     brew install homebrew/x11/openmotif
> 
> If you don't already have homebrew installed, you can get it at http://brew.sh
> 
> 
> If at the configure step, Motif still can't be found, use the following configure command instead of the one in README.txt:
> 
>     ./configure --with-freetype2-library="../../freetype/lib/macx" --with-freetype2-includes="../../freetype/freetype-2.6.1/include" --with-Xm-library=/usr/local/opt/openmotif/lib --with-Xm-includes=/usr/local/opt/openmotif/include --with-Xpm-library=/opt/X11/lib
> 
> 
> 7. Install openssl (brew install openssl)
> 
> If you intend to build .dmg packages, you will also need to install iceberg

**Comment by evantill** [comment]
j'ai cette erreur maintenant:

`src/podcast/quicktime/UBQuickTimeVideoEncoder.cpp:32:10: fatal error: 'QuickTime/QuickTime.h' file not found`

J'ai essayé avec la branche ```master```et la branche ```dev``` : même résultat.

**Comment by celfred** [comment]
Bonjour,

Pour ma part, sous Ubuntu 16.04, j'obtiens cette erreur : 
`Unknown module in QT: script.`
Si vous avez un conseil, je suis preneur. Merci !

**Comment by freeheel3r** [comment]
`sudo apt-get install libqt5script5 qtscript5-dev` ?

**Comment by celfred** [comment]
Merci ! J'ai pu aller un peu plus loin, mais ça coince toujours avec : 
`[...] -lQt5UiTools -lQt5MultimediaWidgets -lQt5PrintSupport -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5XmlPatterns -lQt5Network -lQt5Xml -lQt5Script -lQt5Core -lGL -lpthread 
/usr/bin/ld : ne peut trouver -lpaper
collect2: error: ld returned 1 exit status`

C'est la 1ère fois que je tente ces manips, alors désolé d'être ignorant à ce point... Je cherche de mon côté, bien entendu, mais si vous avez une piste, je gagnerais du temps !

**Comment by freeheel3r** [comment]
En général les erreurs du style `-lpaper not found` sont résolues en installant la librairie de développement correspondante: `-lpaper` signifie la librairie `paper`, qui peut être installée par la commande:

    sudo apt-get install libpaper-dev

... sauf erreur :)

**Comment by celfred** [comment]
Merci encore ! Je progresse, mais ce n'est pas encore gagné :(
Toujours une erreur bloquante, et là, je sèche à nouveau : 
`
/home/celfred/OpenBoard-ThirdParty/quazip/lib/linux/libquazip.a(qioapi.o) : Dans la fonction « qiodevice_seek_file_func(void*, void*, unsigned long, int) » :
qioapi.cpp:(.text+0x2b2) : référence indéfinie vers « qWarning(char const*, ...) »
/home/celfred/OpenBoard-ThirdParty/quazip/lib/linux/libquazip.a(qioapi.o) : Dans la fonction « qiodevice64_seek_file_func(void*, void*, unsigned long long, int) » :
qioapi.cpp:(.text+0x35a) : référence indéfinie vers « qWarning(char const*, ...) »
collect2: error: ld returned 1 exit status
Makefile.Release:1265 : la recette pour la cible « build/linux/release/product/OpenBoard » a échouée
make[1]: *** [build/linux/release/product/OpenBoard] Erreur 1
make[1] : on quitte le répertoire « /home/celfred/OpenBoard »
Makefile:48 : la recette pour la cible « release-install » a échouée
make: *** [release-install] Erreur 2
error: OpenBoard build failed
`
Je n'en mets qu'une petite partie ici, mais j'ai des dizaines de ligne de la sorte mentionnant une 'référence indéfinie' en appelant quazip.cpp. J'ai bien fait la compilation de quazip auparavant dans OpenBoard-ThirdParty.
Je ne sais donc pas quoi faire de plus.
J'espérais parvenir à satisfaire toutes les dépendances nécessaires pour compiler à partir des sources, mais visiblement il manque encore quelque chose...

**Comment by celfred** [comment]
Bonjour,

Je cherche toujours, mais rien à faire, je n'arrive pas à compiler depuis les sources :( Toujours les mêmes erreurs avec Quazip.
Je me demande si mon problème ne viendrait pas de ma compilation des bibliothèques ThirdParty. Quand je fais mon 'qmake' / 'make' dans les dossiers 'freetype', 'quazip' et 'xpdf', j'obtiens simplement 4 lignes du genre : 
`
make -f Makefile.Release
make[1] : on entre dans le répertoire « /home/celfred/OpenBoard-ThirdParty/freetype »
make[1]: rien à faire pour « first ».
make[1] : on quitte le répertoire « /home/celfred/OpenBoard-ThirdParty/freetype »
`
Je ne sais pas si c'est vraiment suffisant...
Encore une fois, désolé de mon ignorance de débutant en la matière, mais si quelqu'un peut m'aider à m'en sortir, ce serait cool :)

**Comment by freeheel3r** [comment]
Vous êtes bien sur Ubuntu 16.04, avec Qt 5.5.1?

Je vais partir d'une nouvelle installation, et écrire un guide plus détaillé sur comment compiler OpenBoard depuis les sources pas-à-pas, y compris tous les paquets à installer.
Ca devrait être plus clair que les instructions actuelles, et peut-être que ça nous permettra aussi de savoir quelle étape exactement pose problème chez vous.

(Actuellement je ne saurais pas dire ce qui cause l'erreur qui mentionne qWarning)

**Comment by freeheel3r** [comment]
Les instructions détaillées sont disponibles ici: https://github.com/OpenBoard-org/OpenBoard/wiki/Install#ubuntu-1604

Bonne chance :)

**Comment by celfred** [comment]
Bonjour,
Merci pour votre aide ! Mais ça coince toujours... Je suis bien sur Ubuntu 16.04 et Qt 5.5.1 et j'ai refait toutes les étapes des instructions une par une... et toujours les mêmes erreurs quazip au final :(

Pour info, si je fais qmake --version, j'obtiens : 
`QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
`

**Comment by celfred** [comment]
À tout hasard, je joins le résultat complet de mon 'make'.

[debug-compil.txt](https://github.com/OpenBoard-org/OpenBoard/files/967513/debug-compil.txt)

**Comment by fbarillon** [comment]
Une idée à tout hasard : j'ai eu des soucis de compilation à cause d'un nom de répertoire extérieur qui contenait un espace.

**Comment by celfred** [comment]
Merci, mais tous mes chemins sont les chemins par défaut et n'ont pas d'espace :(

**Comment by fbarillon** [comment]
Le sujet m'intéresse aussi : je vais suivre le tuto à la lettre et voir si je vais au bout.

**Comment by freeheel3r** [comment]
@celfred le résultat du make m'intrigue, il ne liste pas d'erreurs spécifiques...

Vous aviez également une erreur lors de la compilation de quazip, c'est ça? Quel est le résultat complet de la commande?

**Comment by celfred** [comment]
Pour la compilation de quazip, voici ce que j'obtiens à l'issue de 'make' : 
[make-quazip.txt](https://github.com/OpenBoard-org/OpenBoard/files/972535/make-quazip.txt)

**Comment by J-MH** [comment]
Bonjour,
Je ne parviens pas à compiler openboard dev sur ubuntu 16.04 64 bits. J'ai suivi les instructions mais j'ai le code d'erreur suivant au make final: 
`libavcodec/avcodec.h: Aucun fichier ou dossier de ce type
`
J'ai essayé d'installer ffmpeg mais je n'ai toujours pas avcodec.h.
Avez-vous une solution?

**Comment by lebardix** [comment]
il faut installer libavcodec-dev
`apt-get install libavcodec-dev`

**Comment by J-MH** [comment]
Merci, maintenant l'install est faite mais, côté utilisation sur un TNI, le stylet ne fonctionne pas. J'ai consulté le site Epson du projecteur (EB 475 W connectique: VGA + usb), il n'y a pas de pilote à installer car le stylet est détecté normalement comme une souris.
D'autre part en mode "Multi-écrans"  la barre "stylus", comme la barre des taches, restent sur l'écran de l'ordi. Il est impossible de déplacer l'une au l'autre sur l'écran de projection.
Dans l'attente d'une solution, J-M

**Comment by lebardix** [comment]
J'ai posé la question sur le forum de openboard [(http://openboard.ch/forum/viewtopic.php?p=1224&sid=9e76a1bfbc473abbf5aa9a5b8505f639#p1224)], 
leur réponse est que cette fonctionnalité ne semble pas prévue (à lire ce n'est pas tout à fait la meme demande...)
cependant dans le cas où tu voudrais avoir toutes les fonctions de l'écran maitre vers le projecteur, il y a 2 solutions
- le première consiste à ne pas utiliser la fonction multi-écrans mais simplement avoir des écrans dupliqués (configuration de ubuntu)
- la seconde tu peux croiser à la demande les affichages des 2 écrans depuis le menu préférences -> affichage -> inverser la disposition des écrans....

**Comment by J-MH** [comment]
Oui, j'ai testé tout cela mais sur un tableau où seul le stylet peut être utilisé, je ne peux rien faire.
Le minimum serait que le stylet fonctionne. Il fonctionnait sur OpenSankoré donc cela ne doit pas être trop difficile.
J'utiliserais toujours OpenSankoré si le format de fichier n'avait pas changé! Mais j'ai fait, chez-moi donc sans pouvoir tout tester, des exos sur Openboard ....
Il faudrait peut-être simplement publier une version dev...
Bon courage à tous

**Comment by lebardix** [comment]
je ne comprends pas...
si tu ne lances pas openboard et que tu configures ton ubuntu pour etre dans le mode  "meme image sur tous les écrans" est-ce que ton stylet fonctionne ?
j'utilise une tablette wacom avec un stylet celui-ci fonctionne (à condition d'avoir installer le pilote  Xorg) donc si ton stylet ne fonctionne pas il faut installer  un pilote Xorg pour celui-ci...

**Comment by J-MH** [comment]
Pour comprendre il faut parler de la même chose:
X.org est forcément présent sur Ubuntu 16.04.
Une tablette n'est pas un TNI (ou TBI ou TVI bref, le tableau n'est pas tactile).
Le stylet ne peut pas fonctionner si Openbord (ou Interwiter sous windows) n'est pas ouvert.
Pour le projecteur, le stylet est assimilé à une souris et n'a donc pas besoin de pilote.
Avec Opensankoré aucun pilote n'est à installer.

Maintenant, s'il faut configurer X.org, j'aimerais bien connaître la manip.
Quel est ton OS?

**Comment by lebardix** [comment]
bonsoir,
un pointeur est un pointeur, qu'il provienne d'une souris d'une tablette d'un tni....
je suis sous debian stretch - primtux qui propose tout un environnemt pour  l'école... il y avait dans la version précédente "Open-Sankoré" qui n'est plus vraiment maintenu... et donc j'ai compilé openboard qui a été inclus dans la dernière version en tant que "deb" package ...

Mais sans mettre en oeuvre openboard ou opensankoré, si tu connectes sur ton PC un TBI/TNI c'est comme si tu connectais un videoprojecteur, je ne sais pas quelle connexion tu utilises pour ton tableau (vga, hdmi, usb, wifi, reseau, autre ?) ainsi ton TNI doit etre détecté en temps qu'écran par ton système et donc tu peux afficher soit le meme contenu (bureau)  sur ton écran PC et ton TNI (version plus haut "écrans dupliqués") soit un écran étendu de ton bureau (les 2 se rajoutent pour faire un bureau plus grand) (position que tu configures par l'application préférence->systeme->ecran)

Maintenant comment fonctionne ton pointeur, il devrait etre connecter par un moyen quelconque au PC (s'il est annoncé comme étant une souris ce devrait étre par USB)

Maintenant avec 
- ma souris , elle se déplace sur l'étendu des 2 écrans
- ma tablette wacom , itou à la souris
- un dispositif de pointage infrarouge "wmmarker" retourne la position du stylo dans l'espace qu'il prend en compte. Cet espace se parametre depuis une application particulière lié au pilote de ce fameux pointeur infra-rouge.
- ton TNI , s'il est suffisament "intelligent" il n'y a peut-etre pas de réglage spécifique, il devrait renvoyer vers le PC la position du pointeur dans l'espace qu'il affiche.
A la lecture de la doc epson la configuration peut entrainer des fonctionnements "bizarre" (p41 de /EB-475Wi-480-480i-485W-485Wi_Manuals_1.00_ALL_EN/Manual/ OperationGuide.pdf)

En relisant le sujet complet, je vois qu'il y a une connection usb, sans doute souris, tu pourrais donc connaitre à quoi elle est affecté avec open-sankore et comparer avec openboard 

`# lsusb`

Sans lancer aucune application, vois-tu sur le TNI se déplacer le pointeur normal du PC (souris ou touchpad)  dans la partie de ton  bureau affichée sur le TNI?

Pour terminer, quelle différence entre Open-Sankoré et OpenBoard...
peut-etre qu'avec open-sankoré les développeurs avaient inclu un pilote pour des TNI et donc la connexion matérielle du systeme de pointage est lue directement  par l'application sans avoir à rajouter un pilote au niveau de X

**Comment by J-MH** [comment]
Au niveau pointeur, tout fonctionne. Même avec deux souris et un seul pointeur, deux écrans etc... Touche Windows + p, c'est pas mal aussi pour modifier l'affichage, même sur Ubuntu.
C'est juste le stylet qui pose problème. 
Je vais tester cela lundi: https://doc.ubuntu-fr.org/mpx.

**Comment by lebardix** [comment]
salut
Dond j'ai vérifié avec mon stylet vmarker (http://vmarker.org/fr/) sur une debian stretch.
**1er point** : il faut préciser une règle dans un fichier (/etc/udev/rules.d/99-EB 475 W.rules)
 SUBSYSTEM=="hidraw", ATTRS{idVendor}=="val1", ATTRS{idProduct}=="val2", MODE="0666"
avec val1 et val2 les 2 informations obtenues par un lsusb 
par exemple pour mon vmarker 
# lssub
```
Bus 002 Device 003: ID 0c45:627f Microdia PC Camera (SN9C201 + OV965x + EEPROM)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 003: ID 056a:0319 Wacom Co., Ltd 
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 003: ID 08ff:2580 AuthenTec, Inc. AES2501 Fingerprint Sensor
Bus 004 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```
**Bus 003 Device 008: ID 2572:0011**  
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

val=2572 et val2=0011

**2me point:** ajouter les packages
aptitude install xinput libhidapi-hidraw0 libhidapi-libusb0
debrancher la connexion udb, redemarrer pour être plus sùr 
surveiller les logs dans /var/log/syslog lancer  dans un terminal tail -f  /var/log/syslog
# tail -f  /var/log/syslog
connecter le cable usb
il devrait apparaitre la prise en charge du port usb, quelquechose comme 
```
Nov 27 12:00:33 nimbus kernel: [21226.912064] usb 3-1: new full-speed USB device number 9 using uhci_hcd
Nov 27 12:00:33 nimbus kernel: [21227.098137] usb 3-1: New USB device found, idVendor=2572, idProduct=0011
Nov 27 12:00:33 nimbus kernel: [21227.098143] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Nov 27 12:00:33 nimbus kernel: [21227.098147] usb 3-1: Product: VMARKER SENSOR2
Nov 27 12:00:33 nimbus kernel: [21227.098151] usb 3-1: Manufacturer: ELECGATOR BVBA    
Nov 27 12:00:33 nimbus kernel: [21227.098154] usb 3-1: SerialNumber: VMRK2
```
avec des parametres correspondant au pointeur EPSON
puis la prise en charge par Xorg

```
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) config/udev: Adding input device ELECGATOR BVBA     VMARKER SENSOR2 (/dev/input/event12)
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (**) ELECGATOR BVBA     VMARKER SENSOR2: Applying InputClass "libinput touchscreen catchall"
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) Using input driver 'libinput' for 'ELECGATOR BVBA     VMARKER SENSOR2'
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) systemd-logind: got fd for /dev/input/event12 13:76 fd 54 paused 0
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (**) ELECGATOR BVBA     VMARKER SENSOR2: always reports core events
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (**) Option "Device" "/dev/input/event12"
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (**) Option "_source" "server/udev"
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) input device 'ELECGATOR BVBA     VMARKER SENSOR2', /dev/input/event12 is tagged by udev as: Touchscreen
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) input device 'ELECGATOR BVBA     VMARKER SENSOR2', /dev/input/event12 is a touch device
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.1/usb3/3-1/3-1:1.2/0003:2572:0011.002B/input/input70/event12"
Nov 27 12:00:34 nimbus /usr/lib/gdm3/gdm-x-session[862]: (II) XINPUT: Adding extended input device "ELECGATOR BVBA     VMARKER SENSOR2" (type: TOUCHSCREEN, id 11)

```
ensuite il ne reste plus qu'à faire l'étalonnage (application dédiée pour vmarker) ou utiliser xinput et xinput-calibrator (sans doute inutile pour l'epson

**Comment by J-MH** [comment]
Merci pour ces infos. Je testerai dès que possible.
Voila ce que j'obtiens avec lsusb.

`j-m@jm-1001PXD:~$ lsusb
Bus 001 Device 003: ID 13d3:5711 IMC Networks 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 078c:0403 GTCO/CalComp 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
j-m@jm-1001PXD:~$ 
`

**Comment by lebardix** [comment]
cela doit etre celui-ci (0400 whiteboard annoncé dans les bases USB)
Bus 002 Device 002: ID 078c:0403 GTCO/CalComp
donc fichier /etc/udev/rules.d/99-EB475W.rules
`SUBSYSTEM=="hidraw", ATTRS{idVendor}=="078c", ATTRS{idProduct}=="0403", MODE="0666"`

a voir la suite

**Comment by lebardix** [comment]
ben il faut le créer ce fichier...99-EB475W.rules ou tout  autre nom , un nombre devant pour la prise en compte de l'ordre de chargement si il y en a d'autres...
donc 99-EB475W.rules ou 01-lemien.rules ...... c'est le contenu qui est important ....
