### ISSUE TITLE
Marker and the background is black

### ISSUE THREAD

**Issue by jun-zhang** [OpenBoard-org/OpenBoard#400]
When Marker are used and the background is black, the brush contacts will have distinct lines
![image](https://user-images.githubusercontent.com/6859306/98323294-747a0f80-2024-11eb-9d88-86a59d624da6.png)

**Comment by kaamui** [comment]
Hello,

Thanks for reporting it. It's the actual behavior, not a bug. It has been changed to this one during the migration from Open-Sankoré
