### ISSUE TITLE
Linking errors on Fedora 32

### ISSUE THREAD

**Issue by mahrud** [OpenBoard-org/OpenBoard#401]
I was able to compile OpenBoard after installing various dependencies, but the final binary failed to link. The error is long, so I made a gist: https://gist.github.com/mahrud/a80d974947a709b91ff627c8e55f9230

I'm using Fedora 32 on:
```
Linux noether 5.8.17-200.fc32.x86_64 #1 SMP Thu Oct 29 18:14:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kaamui** [comment]
Hi, 

No idea sorry. Maybe try to follow the guidelines of the Ubuntu version to see if you find some differences with your setup ?
