### ISSUE TITLE
Write with stylus, move with touch

### ISSUE THREAD

**Issue by gabrc52** [OpenBoard-org/OpenBoard#402]
It would be nice to be able to write with the stylus, but scroll through the canvas using the touch screen (fingers). This would be a configurable setting, ideally used by default when using a stylus.

Apps like Xournal++, Microsoft Whiteboard, Apple Notes, GoodNotes, Notability, etc. have this functionality implemented.

**Comment by kaamui** [comment]
Hi,

It's a good idea, but due to our limited resources, we won't be able to prioritize on it.

**Comment by gabrc52** [comment]
Ok, thanks. I think it would be better to give it a low priority label than close it.
