### ISSUE TITLE
Grid in PDF, infinity board

### ISSUE THREAD

**Issue by Programtica** [OpenBoard-org/OpenBoard#403]
Hello creators and others!

Is it possible to export the document of pages in PDF with a grid? Also, is it possible to set "infinity" board? For my students I need this options implemented...

![obraz](https://user-images.githubusercontent.com/20724159/99468579-2a0c6300-2941-11eb-804b-6f59587f09f3.png)

![obraz](https://user-images.githubusercontent.com/20724159/99468513-119c4880-2941-11eb-9e89-491837001f9f.png)

**Comment by kaamui** [comment]
Hello,

It's actually not possible, sorry. Due to our limited resources, we won't be able to prioritize on these features. 

Also, what do you mean by "infinity" board ?

**Comment by Programtica** [comment]
Hello @kaamui ! Sorry that I response after nearly two months, I forgot about it...

I understand... Sad thing, but I got it... Infinity? When you are scrolling screen by mouse, you would be able to move the "scene" !

**Comment by letsfindaway** [comment]
Hi @kaamui
I would volunteer to implement the "grid on PDF" option as a configurable feature. However I struggle where to put this option on the settings:

- Together with the PDF rendering checkbox on the first tab of the settings or,
- together with other grid options on the second tab.

The first tab is already quite full, and adding another line would probably resize the dialog or require a scroll pane. But what is your opinion?
