### ISSUE TITLE
Do not require downloading OpenBoard-ThirdParty to build. Use system xpdf etc. instead.

### ISSUE THREAD

**Issue by GavinSmith0123** [OpenBoard-org/OpenBoard#405]
When I run `qmake OpenBoard.pro -spec linux-g++-64` I got the errors:

```
Cannot read /home/g/extsrc/openboard/OpenBoard-ThirdParty/libs.pri: No such file or directory
```

I had to download the files from https://github.com/OpenBoard-org/OpenBoard-ThirdParty which as a zip file is a massive 106M. It contains files for packages like xpdf, openssl, and freetype which I already have installed on my computer, or which would be easily available via my OS package manager (I use Linux Mint 19.2). Could already installed programs or libraries be used instead?

Can instructions be provided for how to download OpenBoard-ThirdParty from github? When you download as a zip it extracts with the filename `OpenBoard-ThirdParty-master` which needs to be renamed to `OpenBoard-ThirdParty`.

**Comment by GavinSmith0123** [comment]
Although libquazip is included in the third party download, it doesn't work.

After running `qmake OpenBoard.pro -spec linux-g++-64` and `make`:

```
src/adaptors/UBExportDocument.cpp:46:14: fatal error: quazip.h: No such file or directory
     #include "quazip.h"
              ^~~~~~~~~~
compilation terminated.
Makefile.Release:3122: recipe for target 'build/linux/release/objects/UBExportDocument.o' failed

```

`OpenBoard.pro` has

```
    LIBS += -lquazip5
    INCLUDEPATH += "/usr/include/quazip"
```

although it is installed for me under `/usr/include/quazip5`. The build got further when I changed `INCLUDEPATH` to this value. (On Linux Mint 19.2 this file is provided by the `libquazip5-headers` package.)

**Comment by kaamui** [comment]
Hi,

[wiki](https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04)

**Comment by Kayalvizhi-ui** [comment]
I got the binary of Openboard but it is not opening! what I should do?
