### ISSUE TITLE
Missing yawn and plead emojis

### ISSUE THREAD

**Issue by KeronCyst** [OpenBoard-org/OpenBoard#407]
These can't be found and come up as crossed boxes:

🥱
🥺

**Comment by Gvf63** [comment]
I think it depends on the font you have installed. For example, using Linux it is necessary to install a special font. As far as I know however OpenBoard uses only monochrome fonts. Alternatively you can find emojis as images (preferably svg) on the web

**Comment by KeronCyst** [comment]
You can install fonts on Android? How?

**Comment by kaamui** [comment]
Hello,

I think it is related to the OpenBoard keyboard application, right ? This github is for OpenBoard, the interactive whiteboard application ^^ 

-> https://github.com/dslul/openboard <-

**Comment by KeronCyst** [comment]
Oops, thanks!
