### ISSUE TITLE
open board with graphical tablet

### ISSUE THREAD

**Issue by nerdunit** [OpenBoard-org/OpenBoard#408]
Hi, my teacher has an xp pen tablet with a screen, is there any way they can place open board on that screen? if they select the open board screen (screen 1) from the settings app called (pentablet) it won't show openboard, any fix for this?

**Comment by grx1us** [comment]
Your teacher must share his screen/window from the meeting aplication (Google Meet/Zoom/etc.), e.g. Google Meet>right down corner - Present now>Full screen/Window.
