### ISSUE TITLE
Can't change default files directory

### ISSUE THREAD

**Issue by JPUnD** [OpenBoard-org/OpenBoard#409]
Having a folder created directly into the user home directory `~/OpenBoard` by default isn't very nice.

Also the program appears to have 3 different config files, one in `/opt/openboard/etc/OpenBoard.config`, another in `.config/Open Education Foundation/OpenBoard.conf` and another in `.local/share/OpenBoard/OpenBoardUser.config`. I've modified the last two to include the lines:
```
[App]
DataDirectory={Home}/.cache/openboard
```

But it still creates the default home directory folder. It's really annoying by default and not being able to change that is even worst. I might be changing it the wrong way but that's the solution I saw in a forum post. Also the default config in `/opt` doesn't have any line that tells me what the config to change that folder looks like so it's probably hard coded somewhere?

I'm using the version 1.5.4 on Manjaro.

**Comment by rudi1969** [comment]
Hi,

I "solved" that by symlinking ~/Openboard to the path I want my files in. Not nice though.

Also Openboard ignores the directories I added to .local/share/OpenBoard/OpenBoardUser.config:

[IntranetPodcast]
Author=RMR
PublishToIntranet=true
PublishingUrl=file:///home/rudi/Documents

[Podcast]
AudioRecordingDevice=Default
RecordingDirectory=/home/rudi/tmp

All podcasts are saved to my home directory.

Regards

**Comment by kaamui** [comment]
Hello,

> 
> Also the program appears to have 3 different config files, one in `/opt/openboard/etc/OpenBoard.config`, another in `.config/Open Education Foundation/OpenBoard.conf` and another in `.local/share/OpenBoard/OpenBoardUser.config`. I've modified the last two to include the lines:
> 
> ```
> [App]
> DataDirectory={Home}/.cache/openboard
> ```
> 

This setting can only be set in the first file you mentioned ^^. Please notice that it is used to modify what the UBSettings::userDataDirectory() function returns. This directory is not only used for OpenBoard documents.
