### ISSUE TITLE
Show taskbar while running OpenBoard

### ISSUE THREAD

**Issue by Ray-Ven** [OpenBoard-org/OpenBoard#41]
Would be nice to have the possibility to start openboard in windowsmode to be able to access the taskbar more easily

**Comment by fbarillon** [comment]
The solution is the switch in desktop mode. The only lack is not being able to switch back in Board mode when dragging a file on the toolbar.

**Comment by gagarine** [comment]
+1 for adding a windows mode. This is very helpful when you create a course or when have a very big screen.

For my point of view we should follow the OS's conventions for full screen and windows mode. The desktop mode is the only special mode.
