### ISSUE TITLE
What optimizations have been made to the strokes?

### ISSUE THREAD

**Issue by oneday1992** [OpenBoard-org/OpenBoard#410]
When using it, I found that the writing of openboard and opensankore is somewhat different. In sankore, the writing strokes are actual, no matter how I change the handwriting, curves or straight lines, although its strokes are a bit uneven.
In openboard, its writing is very smooth. I know that it has made a lot of optimizations, but during the writing process, some strokes will change a little compared to the original handwriting, especially some curves, such as wavy curves. , Auto-optimization will make my writing look a little jumpy. These are especially obvious when I write English letters and the fonts are relatively small. I want to know what is the key code for this processing? I know there is a simplify(), but it is not obvious that I blocked it here, can you help me? Thank you.

**Comment by oneday1992** [comment]
The last stroke will be lost
The strokes will move, resulting in the inability to write English words smoothly, the writing effect is very poor, and my handwriting cannot be displayed truly

**Comment by GavinSmith0123** [comment]
I've had the same problem. I found it impossible to write a lower case g, it coming out like a j without a dot instead. (This was under Windows - under Linux Mint, it was better, possibly due to different graphics tablet drivers. There is a UBGraphicsStroke::simplify() function under domain/UBGraphicsStroke.cpp with some comments in it, although I haven't tested the effects of changing this function.

**Comment by GavinSmith0123** [comment]
I made a change to a different function: https://github.com/GavinSmith0123/OpenBoard/commit/6df3d2f0bde9904af893b2ad15921733e86e8342

This fixes the issue of parts of strokes disappearing. If you draw a line in one direction, stop, and then reverse in the opposite direction, the end of the line disappears. This is bad for certain letters like "i" and "n".

On the downside, with this change the strokes look a bit "pixellated". There should be some way of smoothing strokes that avoids this issue.

**Comment by kaamui** [comment]
Hello,

Sorry for the late reply. There are some options in the config file you can play with : 

- SimplifyPenStrokes=true
- SimplifyPenStrokesThresoldAngle=3
- SimplifyPenStrokesThresoldWidthDifference=2

Hope it helps.

@GavinSmith0123 I think the best way would be to add the MIN_DISTANCE to the settings, so it can be adjusted at anyone's conveniance. But thanks for your active support !

**Comment by oneday1992** [comment]
> Hello,
> 
> Sorry for the late reply. There are some options in the config file you can play with :
> 
> * SimplifyPenStrokes=true
> * SimplifyPenStrokesThresoldAngle=3
> * SimplifyPenStrokesThresoldWidthDifference=2
> 
> Hope it helps.
> 
> @GavinSmith0123 I think the best way would be to add the MIN_DISTANCE to the settings, so it can be adjusted at anyone's conveniance. But thanks for your active support !

Setting the SimplifyPenStrokes value to false can indeed disable simplifyPenStrokes(), which can solve the problem of losing the last stroke.

But I still have a similar problem, that is, when drawing a wavy line, the line segment will jump, where is this handled?

 I sincerely ask, thank you.

**Comment by oneday1992** [comment]
@kaamui
