### ISSUE TITLE
Big Sur icon

### ISSUE THREAD

**Issue by SoPat712** [OpenBoard-org/OpenBoard#411]
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

Apple has introduced new requirements for app icons. I will create a basic one with the catalina icon in a white rounded square, but a redesign of the icon might be in order. I'd love to work with the openboard team in creating one that fits with your design styles.

**Comment by kaamui** [comment]
Hello,

thank you for the suggestion. Nothing's planned actually though.
