### ISSUE TITLE
two errors in openboard_1.6.1-a.1102

### ISSUE THREAD

**Issue by Gvf63** [OpenBoard-org/OpenBoard#412]
I am trying the new version with xubuntu 20.04 and i noticed two errors:
- "Color4" has been written in the toolbar instead of "Color", this obviously also affects the translations
- a dependency is missing: qt5dxcb-plugin (the program crash without it)

**Comment by kaamui** [comment]
Hello,

thank you for the report. The first one was fixed. 

For the dependency missing when installing in Xubuntu, `apt install ...` fixed it ?
