### ISSUE TITLE
Improve instructions for building OpenBoard on Windows 10

### ISSUE THREAD

**Issue by GavinSmith0123** [OpenBoard-org/OpenBoard#419]
I have been trying to follow these instructions:

https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows-10

and lost a lot of time because this part

> 
> Be sure to use the msvc 2017 compiler
> search for "Developer Command Prompt for VS 2019" on Windwos searchbar, click on it, and launch the following command (adapt to the path you set for VS 2019) :
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x64 -vcvars_ver=14.16
> After this, you can verify that you correctly configured qmake and nmake by respectively taping qmake -v and nmake/? these commands should show something like following :

wasn't clear about what to do if running `vcarsall.bat` failed. It didn't work for me because the `-vcvars_ver` option had the wrong version for the version of Visual Studio downloaded by the link earlier on in the page. I did run `qmake -v` and `nmake/?` and the output looked good, and I didn't understand the significance of `vcvarsall.bat` for specifying 64-bit compilation. Hence I managed to get a lot of the compilation done, but at the end could not finish due to `x86` and `x64` mismatch. Please explain that the `-vcvars-ver` option can be omitted, or if not what it should be set to.

**Comment by GavinSmith0123** [comment]
Also, could it be mentioned that when downloading Qt, you need the "Qt Script (deprecated)" component in addition to the core Qt component?

**Comment by GavinSmith0123** [comment]
Once I managed to get OpenBoard.exe produced, I could not run it due to missing DLLs. I went onto the next step in the instructions, "Package OpenBoard", which appeared to recompile OpenBoard from scratch, making me wonder if the time I spent before that was wasted. The release script ran Inno which gave errors about missing `vcredist` files. I had to copy `vcredit_x64.exe` from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\v142` into `OpenBoard-ThirdParty/microsoft` along with the following change to OpenBoard.iss:

```
diff --git a/release_scripts/windows/OpenBoard.iss b/release_scripts/windows/OpenBoard.iss
index a64559c0..011cd464 100644
--- a/release_scripts/windows/OpenBoard.iss
+++ b/release_scripts/windows/OpenBoard.iss
@@ -56,8 +56,9 @@ Type: files ; Name: "{app}\*.dll"
 #define QtDir GetEnv('QT_DIR')

 [Files]
-Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2013.x64.exe"; DestDir:"{tmp}"
-Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2015_2019.x64.exe"; DestDir:"{tmp}"
+Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_x64.exe"; DestDir:"{tmp}"
+; Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2013.x64.exe"; DestDir:"{tmp}"
+; Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2015_2019.x64.exe"; DestDir:"{tmp}"
 Source: "{#ProjectRoot}\build\win32\release\product\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

 ;OpenSSL
@@ -167,8 +168,9 @@ Root: HKLM64; Subkey: "SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Low Righ
 Root: HKLM64; Subkey: "SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Low Rights\DragDrop\{{E63D17F8-D9DA-479D-B9B5-0D101A03703B}"; ValueType: string; ValueName: "AppPath"; ValueData: "{app}"; Flags: uninsdeletevalue; Check: isProcessorX64

 [Run]
-Filename: "{tmp}\vcredist_2013.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2013...
-Filename: "{tmp}\vcredist_2015_2019.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2015-2019 ...
+; Filename: "{tmp}\vcredist_2013.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2013...
+; Filename: "{tmp}\vcredist_2015_2019.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2015-2019 ...
+Filename: "{tmp}\vcredist_x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing vcredist_x64.exe
 Filename: "{app}\OpenBoard.exe"; Description: "{cm:LaunchProgram,OpenBoard}"; Flags: nowait postinstall skipifsilent

 [UninstallDelete]
```

I was able to produce the installer, run the installer and run OpenBoard with this change. There must be something I'm missing though, as vcredist popped up a message when the installer was run that had to be dismissed to continue.

**Comment by GavinSmith0123** [comment]
`vcredist_x64.exe` was popping up a message because the CRT was already installed.

According to https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-160&viewFallbackFrom=vs-2019  the vcredist file may not be needed at all on Windows 10. I took the lines out about vcredist from `OpenBoard.iss`, uninstalled the CRT from System Settings, rebuilt and ran the installer, and OpenBoard runs fine.

**Comment by GavinSmith0123** [comment]
In fact, it is necessary to run `vcredist_x64.exe`. Otherwise I had errors that `vcruntime140_1.dll` was missing. I don't know if there is a way to only run it if necessary but at least interaction can be avoided when the installer is run by passing the `/passive` flag.

```
--- a/release_scripts/windows/OpenBoard.iss
+++ b/release_scripts/windows/OpenBoard.iss
@@ -56,8 +56,9 @@ Type: files ; Name: "{app}\*.dll"
 #define QtDir GetEnv('QT_DIR')

 [Files]
-Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2013.x64.exe"; DestDir:"{tmp}"
-Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2015_2019.x64.exe"; DestDir:"{tmp}"
+Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_x64.exe"; DestDir:"{tmp}"
+; Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2013.x64.exe"; DestDir:"{tmp}"
+; Source: "{#ProjectRoot}\..\OpenBoard-ThirdParty\microsoft\vcredist_2015_2019.x64.exe"; DestDir:"{tmp}"
 Source: "{#ProjectRoot}\build\win32\release\product\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

 ;OpenSSL
@@ -167,8 +168,9 @@ Root: HKLM64; Subkey: "SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Low Righ
 Root: HKLM64; Subkey: "SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Low Rights\DragDrop\{{E63D17F8-D9DA-479D-B9B5-0D101A03703B}"; ValueType: string; ValueName: "AppPath"; ValueData: "{app}"; Flags: uninsdeletevalue; Check: isProcessorX64

 [Run]
-Filename: "{tmp}\vcredist_2013.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2013...
-Filename: "{tmp}\vcredist_2015_2019.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2015-2019 ...
+; Filename: "{tmp}\vcredist_2013.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2013...
+; Filename: "{tmp}\vcredist_2015_2019.x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart"; StatusMsg: Installing CRT 2015-2019 ...
+Filename: "{tmp}\vcredist_x64.exe";WorkingDir:"{tmp}"; Parameters: "/norestart /passive"; StatusMsg: Installing CRT...
 Filename: "{app}\OpenBoard.exe"; Description: "{cm:LaunchProgram,OpenBoard}"; Flags: nowait postinstall skipifsilent

 [UninstallDelete]
```

I couldn't find when or if the other vcredist executables were ever included in OpenBoard-ThirdParty.

**Comment by kaamui** [comment]
Hello,

sorry for the late reply. 

Did you place OpenBoard-ThirdParty repo on the dev-qt5.1x branch ?

**Comment by GavinSmith0123** [comment]
On Wed, Feb 10, 2021 at 08:02:58AM -0800, kaamui wrote:
> Hello,
> 
> sorry for the late reply. 
> 
> Did you place OpenBoard-ThirdParty repo on the dev-qt5.1x branch ?

Yes I did:

$ cd OpenBoard-ThirdParty/
$ git status
On branch dev-qt5.1x
Your branch is up-to-date with 'origin/dev-qt5.1x'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        freetype/.qmake.stash
        quazip/.qmake.stash
        quazip/release/
        xpdf/.qmake.stash

nothing added to commit but untracked files present (use "git add" to track)
$

**Comment by kaamui** [comment]
try 

```
git fetch --all
git pull origin dev-qt5.1x
```

if the branch is correctly up-to-date you can find the new binaries on the microsoft folder.

**Comment by kaamui** [comment]
> wasn't clear about what to do if running `vcarsall.bat` failed. It didn't work for me because the `-vcvars_ver` option had the wrong version for the version of Visual Studio downloaded by the link earlier on in the page.

Also, did you select the mscv 2017 compiler while installing VS 2019  as suggested in the tutorial ?

**Comment by GavinSmith0123** [comment]
I will try updating the branch next time I build the program on Windows (it takes several hours to do once everything is done so I have only been doing it every few weeks). I don't remember having the option of MSVC 2017 when I installed VS 2019 so it's possible that I never picked it.
