### ISSUE TITLE
Can not record video

### ISSUE THREAD

**Issue by gurpreetsinghsodhi** [OpenBoard-org/OpenBoard#421]
whenever tried to start podcast , it says 'Fail To Start Encoder' , initially it worked fine but ever after doing unistall and install it still not working kindly fix that as its very important.

**Comment by kaamui** [comment]
Hello,

On what Operating System are you ? What Version of OpenBoard ?

**Comment by sadiksnm** [comment]
I am also facing same issue on windows 10

**Comment by andreychaves** [comment]
Same problem here - I have installed Openboard 1.6.1 in Ubuntu 22.04 LTS via Software Manager; when I try to start recording in the podcast feature, it says "failed to start encoder", the red dot representing "record" turns into a black square (as in a "stop" button), but the chronometer stays fixed at 0:00 and nothing is recorded.
