### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by vio4** [OpenBoard-org/OpenBoard#423]
I need to have background transparency of main window on all white/black background checkered or not. 
Already there are 3 opacity settings: 2 on the grid menu and 1 on the marker menu, yet none for the main white/black background.
Clicking on "Show Desktop" from OpenBoard main menu, gives only complete transparency and not one adjustable, and a limited functionality like no undo/redo ...
I need to see the kids in Meet/Zoom (joining/exiting/reacting...), so a little transparency adjustment will be very convenient.
On other software the background transparency is awesome but i prefer OpenBoard software.
I tried to use 2 displays but is extremely demanding therefore it is not an option.

**Comment by kaamui** [comment]
Hello,

This could be an interesting feature, if possible, but due to our limited resources we won't be able to work on this one. The 2 displays is maybe the only solution at this time.
