### ISSUE TITLE
OpenBoard GNOME/Cinnamon problems

### ISSUE THREAD

**Issue by MuhammedTaha02** [OpenBoard-org/OpenBoard#426]
https://yadi.sk/i/kCKbSTnDLrNqLA

Openboard does not work properly on all gnome based desktops (gnome and cinnamon). First of all, I tested it in archlinux gnome (openboard aur package) and fedora gnome (openboard pkgs.org package) respectively. Both of them there was an error on the link above. My last stop was on gentoo (openboard flatpak package). The same error occurred here.

Edit : Same problem occurs for both Wayland and Xorg

Edit2 : Distros where I tested OpenBoard;
1 ) ArchLinux 5.10.4 kernel
OpenBoard Package > https://aur.archlinux.org/packages/openboard
2 ) Fedora 5.9 kernel
OpenBoard Package > https://pkgs.org/download/openboard
3 ) Gentoo 5.10.4 kernel
OpenBoard Package > https://flathub.org/apps/details/ch.openboard.OpenBoard

MyPC : Dell Inspiron 3593 > Intel iris plus graphics / Nvidia MX230

**Comment by kaamui** [comment]
Hello,

this issue is fixed on the dev-qt5.1x branch, that will be merged into master in a month or two.
