### ISSUE TITLE
Installing Qt in Ubuntu 20 | default.conf not working

### ISSUE THREAD

**Issue by nicomeza** [OpenBoard-org/OpenBoard#427]
Hello, 

I was following the steps the install openboard and when trying to do 

> echo "<path_to_your_Qt_folder>/<Qt_version>/gcc_64/bin/" >> default.conf
> echo "<path_to_your_Qt_folder>/<Qt_version>/gcc_64/lib/" >> default.conf
> sudo mv default.conf /usr/lib/x86_64-linux-gnu/qtchooser/

And then doing qmake -v I got an error: 

qmake: could not exec '/home/Qt/Tools/QtCreator/lib//qmake': No such file or directory
I've tried other directories but I got the same. 

How do I know the right one ? 

If I open the Qt creator API  I found on system information the following : 

Library info:
  PrefixPath: /home//Qt/Tools/QtCreator/lib/Qt
  DocumentationPath: /home/Qt/Tools/QtCreator/lib/Qt/doc
  Heade	rsPath: /home/Qt/Tools/QtCreator/lib/Qt/include
  LibrariesPath: /home/Qt/Tools/QtCreator/lib/Qt/lib
  LibraryExecutablesPath: /home/Qt/Tools/QtCreator/lib/Qt

Thanks

**Comment by kaamui** [comment]
Hello,

Sorry for the late reply. You are attempting to use the libs of QtCreator. You need to add paths to the libs used by the compiler. For example : /home/dev/Qt/5.xx.y/gcc_64/lib
