### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Ray-Ven** [OpenBoard-org/OpenBoard#43]
I'm a teacher and administrator and we enjoy using openboard in our school in germany.
Is there a way to contribute somehow? I'm not a programmer but could imagine some translation, writing documentations or something like that. Or probably you have something else in mind?

Ray

**Comment by fbarillon** [comment]
Hello, 
I'm not a programmer neither. As you say there is  work in translating, writing documentation, reporting bugs, proposing enhancements...
Even if, in fact, we need programmers to do the job.
François

**Comment by gagarine** [comment]
Thanks for your interest.

We are organizing the tools for the community. We want the development to be open and will accept pull request has long has it keep OpenBoard simple and easy to use.

For the moment, testing the last version and reporting bug it's very helpful: https://github.com/DIP-SEM/OpenBoard/releases For the moment we are focusing on improving stability and performance.

I also created a new wikipage: https://en.wikipedia.org/wiki/OpenBoard than need some love.

More information will follow.

**Comment by ChPey** [comment]
Hi, 
I'm just an interested contributor and neither a programmer. But to enhance the interest I'm actualising the wikipedia page in [French](https://fr.wikipedia.org/wiki/Open-Sankoré_/_OpenBoard). I tried to complete the German version too (I'm living in Berlin since 10 years now). If you are ready to correct me, I could try to translate it more.
I also tried to awake the interest of developer for 5 month but I wasn't very persuasive. If we could coordinate our effort to contact people it could be fun.

**Comment by gagarine** [comment]
@ChPey thanks for your help! I created a new page https://fr.wikipedia.org/wiki/OpenBoard because Open-Sankoré and OpenBoard are not the same software anymore. We want to be clear about that.

**Comment by si2mev** [comment]
No programmer here either, but very interested in this project. I was a happy OpenSankoré user. But understand this change.

I made te alternative.to page of OpenBoard, but you replaced OpenSankore entry. So mine will be deleted.

Hope to be able to help in the future, with testing for example.

**Comment by gagarine** [comment]
@si2mev yes testing will help a lot, specially from peoples than are not afraid by github.

The new website is on the way and should be published in the following days :). Is going to look like that:

![screen shot 2016-06-27 at 22 49 00](https://cloud.githubusercontent.com/assets/164074/16395313/7e3e5e0c-3cb9-11e6-967e-3a2e3a78e4d1.png)

**Comment by jondo** [comment]
I guess this issue should be closed.

**Comment by kaamui** [comment]
The wiki will be updated soon with new explanations on how to contribute (how to build openboard in three platforms).
