### ISSUE TITLE
Don't use the github's wiki for documentation, use a "real" repository.

### ISSUE THREAD

**Issue by gagarine** [OpenBoard-org/OpenBoard#44]
Github's Wiki are also repository. But you can't use branch for version, you can't create pull request, you can't reference commit in bug.

I think is better to use a /doc folder in this repository or create a repository just for the documentation (their is + and - in both choices).

For example http://symfony.com/doc/2.4/book/controller.html is the following page https://github.com/symfony/symfony-docs/blob/2.4/book/controller.rst .

**Comment by celfred** [comment]
This comment seems well-thought. Since documenting OpenBoard could be something easier to help with for many people rather than programming it, maybe having a pull-request option, versioning and so on could be better than Github Wiki.

Maybe another solution : https://www.gitbook.com/ ?
