### ISSUE TITLE
Cursor color is not visibly proper with the background colors

### ISSUE THREAD

**Issue by rafisics** [OpenBoard-org/OpenBoard#441]
I am using OpenBoard version [v1.6.1a-1102](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1a-1102) on Windows 10. 
I am not satisfied with the cursor color. The current cursor color is set to a grey type color. It's barely visible in the black-white backgrounds. I think it would be better to have visibly bright cursor-colors (such as red, yellow) corresponding to the background colors.

**Comment by kaamui** [comment]
Hello,

thank you for your feedback. We recently changed this background color of the preview circle to make it more visible in white/dark background when zooming out. 

It can also depend on your display settings, like brightness, contrast. Did you try to play a bit with it to see if it makes it better ?

Here's an example of what I see on my own screen. Another option is to disable the preview circle in the preferences, so you always have the default cursor (the cross)

![image](https://user-images.githubusercontent.com/11720903/109058708-9e466780-76e3-11eb-8a85-a28a04a3dec0.png)

**Comment by rafisics** [comment]
Thank you, @kaamui
