### ISSUE TITLE
UBUNUTU 20.04.2

### ISSUE THREAD

**Issue by richardharbord** [OpenBoard-org/OpenBoard#442]
Solved
I fount that installing QT5 and following installing the openboard_ubuntu_20.04_1.6.0-a.1_amd64.deb worked. Without QT5 I couldn't see the installation and no app. So, I think,  the problem is solved :-)

**Comment by kaamui** [comment]
Hello,

>openboard_ubuntu_20.04_1.6.0-a.1_amd64.deb

This is quite an old version now :)

Did you try with the latest package ? you can find it on the releases page => [here](https://github.com/OpenBoard-org/OpenBoard/releases)

The current latest version release officially on Github is the version "1.6.1a-1102".
