### ISSUE TITLE
"The code execution cannot proceed because VCRUNTIME140.dll was not fount"

### ISSUE THREAD

**Issue by brabadzhiev** [OpenBoard-org/OpenBoard#443]
We cannot open the file because of the following issues:

"The application was unable to start correctly 0xcc000007b"

"The code execution cannot proceed because VCRUNTIME140.dll was not fount"

Please help. We need to install the program ASAP.
Thank you in advance.

**Comment by kaamui** [comment]
hello,

please try this => https://github.com/OpenBoard-org/OpenBoard/issues/243
