### ISSUE TITLE
syntax error trying to compile OpenBoard for Ubuntu 20.04

### ISSUE THREAD

**Issue by davdesmo** [OpenBoard-org/OpenBoard#447]
Hi all, I'm totally newbie on Github so I apologize for every mistake I'll do
I was trying to compile OpenBoard for an Ubuntu 20.04 system, I'm not use to compile software by myself so I've done everything step by step as described in the page. All seems to go right until I've launched the command "qmake OpenBoard.pro" that make a syntax error
sh: 1: Syntax error: "&" unexpected
Project ERROR: Unknown module(s) in QT: script
I'm totally stopped and hope you can help me
Regards

**Comment by letsfindaway** [comment]
Probably it is better not to compile it by yourself. If you look at the release page of the latest pre-release https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1a-1102 then you already find a pre-built package for Ubuntu 20.04. Did you try it with this?

But be aware of the disclaimer on that page: There is currently no officially released version for Ubuntu 20.04 and the pre-release is marked as non-production ready.

**Comment by davdesmo** [comment]
Hi Martin, many thanks for your fast answer
I didn't found the compiled versione, for sure I'll try with it 👍

For the disclaimer, thanks again but luckily it's not a difficult because I
need Openboard only for my wife to learn it, not to produce anything, so
even if there will be some malfunction it'll be not an issue

Regards

Il mar 23 feb 2021, 08:00 Martin Winter <notifications@github.com> ha
scritto:

**Comment by kaamui** [comment]
Hello,

You need to pick the Script plugin on the Qt installer. I'm not sure why I didn't precise it in the wiki. I need to find time to integrate @JBBgameich's work on it, so we no longer need this deprecated plugin.

**Comment by davdesmo** [comment]
Many thanks 👍

Il mar 23 feb 2021, 13:02 kaamui <notifications@github.com> ha scritto:
