### ISSUE TITLE
OpenBoard-ThirdParty\xpdf\xpdf-3.04\splash/SplashBitmap.h(12): fatal error C1083:  “aconf.h”: No such file or directory

### ISSUE THREAD

**Issue by Hoke** [OpenBoard-org/OpenBoard#455]
hi，i build this project have same error：

OpenBoard-ThirdParty\xpdf\xpdf-3.04\splash/SplashBitmap.h(12): fatal error C1083:  “aconf.h”: No such file or directory

my build platform:
win10
qtcreator 5.14.2

**Comment by kaamui** [comment]
Hi,

It's fixed. You'll just have to place you on the dev-qt5.1x branch and make a `git pull`
