### ISSUE TITLE
Ubuntu 18.04 improvements

### ISSUE THREAD

**Issue by giancarlopanizzo** [OpenBoard-org/OpenBoard#457]
Ubuntu 18.04.5 
Gnome 3.28.2
OS :64 bit
Openboard: 1.5.4

Openboard installs nicely, both from the Software center and from flatpak. Differently than under Windows, though, it shows small issues when using the (really welcome!) "Show Desktop" feature. Under Windows 7, showing the desktop allows to freely e.g. annotate pdfs. Under Ubuntu, instead, once switching to "Show Desktop" no annotation on the underlying pdf is shown at first: if switching back to "Show Openboard" and forth again to "Show Desktop", the previous annotations show up, and it seems possible to interactively annotate *only* the area very close to the previous annotation. It would be very nice either to have a bug fix, or to have suggestions on how/where to look to try to fix the code.

Thanks ;)

**Comment by firelane404** [comment]
I believe this has something to do with the fact that Gnome uses GTK and OpenBoard is written for Qt. I have the same issue as you when I ran OpenBoard under Gnome, but annotating the desktop works as expected when I run it under KDE. I think the first thing to check would be that you have all the proper packages installed for Qt 5.5. There is some more detailed information on how to go about that under the "README".

**Comment by kaamui** [comment]
Ubuntu 18.04 is not officially supported, but you should be able to build OpenBoard from source for it, following [instructions for Ubuntu 20.04](https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04).

the bug with Gnome is supposed to be fixed on the 1.6.1 release (avaialbe for Ubuntu 20.04 [here](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/openboard_ubuntu_20.04_1.6.1_amd64.deb))
