### ISSUE TITLE
Version 1.6.1rc-0309

### ISSUE THREAD

**Issue by Gvf63** [OpenBoard-org/OpenBoard#458]
I tried to install Open Board 1.6.1rc-0309 on ubuntu 20.04.2 (just installed) with the command
` sudo gdebi  openboard_ubuntu_20.04_1.6.1-rc.0309_amd64.deb`
As reported in the issue #412 also in this version by launching the program this crashes with the error:
`Could not load the Qt platform plugin "xcb" in "" even though it was found.`
To eliminate the error it is necessary to install the missing dependency via apt
`sudo apt install qt5dxcb-plugin`
 or better to modify the file "control" in the .deb package by adding the required dependency (qt5dxcb-plugin)

I also tried the new features:
laser pointer diameter: to enable it you need to add a new key in [Board] section of OpenBoard.config 
`PointerDiameter=<value>`
not indicated in your communication.

intermediate lines: to enable it you need to add a new key in [Board] section of OpenBoard.config
`EnableIntermediateLines=true`
'EnableIntermediateLines' and not 'enableIntermediateLines' as indicated by you.
The key is not present in the installation file, you need to add it, do not modify it.
The teachers I spoke with say that it would be interesting to be able to set alternative patterns for the background (svg files?) To obtain various types of grids suitable for various subjects: staff for music, graph paper for scientific subjects, lines for primary school (different in the various countries). The papier application covers only a few possibilities and requires to be applied and set to each page. @letsfindaway want to respond to this challenge? :-) 

new application "Axes": to enable it you need to add a new key in [Board] section of OpenBoard.config
`EnableToolAxes=true`
' EnableToolAxes' and not 'enableToolAxes' as indicated by you.
The key is not present in the installation file, you need to add it, do not modify it.

**Comment by letsfindaway** [comment]
> @letsfindaway want to respond to this challenge? :-)

There are way too many options. But have you tried to create all these grids or other backgrounds as images and then:

- Looong click on "Add page"
- Select "Import Page"
- Select your image

I think this is quite a good workaround for all such stuff -- well, most of it.

**Comment by kaamui** [comment]
Hi @Gvf63,

Thank you I'll fix the config file. 

For the error on Ubuntu, the package you mention is for Deepin environment. It's not needed by other environments (the ones we officially support).

**Comment by Gvf63** [comment]
@letsfindaway : The workaround you suggest has problems: 
- The image is inserted with an ample white margin 
- It is scaled by losing sharpness
- It requires a series of operations for each new page and is not usable for the first page 
- To have different grid sizes it is necessary to prepare several images 
An advantage is that the background is reported by exporting as pdf (choice / problem already reported in the past #403, #357, #315, #118)

**Comment by Gvf63** [comment]
I checked: the missing dependency appears to be: libxcb-xinerama0

**Comment by kaamui** [comment]
Thanks, I'll add it for the next release
