### ISSUE TITLE
Converting with SVG files in OpenBoard

### ISSUE THREAD

**Issue by ChPey** [OpenBoard-org/OpenBoard#46]
OpenBoard document are UBZ files. If UBZ is manualy changed into ZIP, the archive file contain SVG files. Every page has 2 SVG file : one for the Thumbnail, the second for the real page. 
SVG files could be a good basis to work on the conversion of files from PPT, PDF, ... into UBZ

PPT and PDF files can be opened in OpenBoard, but there are two layers. Every work on the uploaded PPT or PDF document can't be saved as a UBZ document. Only solution is to save every slide as an image.

Importation - exportation [software table](https://fr.wikipedia.org/wiki/Open-Sankor%C3%A9_/_OpenBoard#Classification)

**Comment by ramuntcho** [comment]
PPT files can't be opened in OpenBoard, only PDF files
