### ISSUE TITLE
"Show Desktop" working unproperly on Regolith desktop environment (i3)

### ISSUE THREAD

**Issue by Average-user** [OpenBoard-org/OpenBoard#461]
When using the functionality of "Show Desktop" on [Regolith](https://regolith-linux.org/), everything is shown (considerably) darker, like looking
through a dark glass. But this only happens when using the mouse-like mode, not when using pencil, eraser or any other thing. I switched to xfce4, and it works correctly there.

I realize this might be i3's fault, but I decided to create the issue anyway, so that at least it serves as record.

Thanks.

I'll leave some screenshots also (first with the mouse-like mode, and another without it):

![Screenshot from 2021-03-15 13-02-06](https://user-images.githubusercontent.com/22183323/111183653-e6dc9c80-858e-11eb-8fb3-01c99d204996.png)
![Screenshot from 2021-03-15 13-02-13](https://user-images.githubusercontent.com/22183323/111183662-e93ef680-858e-11eb-93a9-d867e6007c74.png)

Edit: Added a link and some clarification.

**Comment by kaamui** [comment]
Hi,

Not sure what could cause it.  It could be related to some code in the updateMask function.
