### ISSUE TITLE
impossibile avviare il programma perchè VCRUNTIME140.dll non presente nel computer (Windows7)

### ISSUE THREAD

**Issue by sab758** [OpenBoard-org/OpenBoard#462]

**Comment by Gvf63** [comment]
Devi installare le dll  redistribuibili di Microsoft. Si scaricano dal sito Microsoft, trovi il link facendo una ricerca sul sito stesso.

**Comment by sab758** [comment]
Avevo provato, ma nonostante averle scaricate, il problema persiste.
Dovevo inserirle in una cartella specifica?

Il giorno mar 16 mar 2021 alle 18:21 Giovanni Fasano <
***@***.***> ha scritto:

**Comment by Gvf63** [comment]
Devi scaricarle e eseguirle (installarle).

**Comment by sab758** [comment]
È quello che ho fatto.
Ritenterò

Il giorno mar 16 mar 2021 alle 18:34 Giovanni Fasano <
***@***.***> ha scritto:

**Comment by Gvf63** [comment]
Comunque non sarebbe questo il luogo più adatto per queste richieste. Puoi usare il forum o eventualmente scrivermi a gvf@risorseprimaria.it Non sono uno degli sviluppatori, ma posso aiutarti anche se normalmente uso Linux...

**Comment by kaamui** [comment]
Hi,

please try to install [the latest version](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/OpenBoard_Installer_1.6.1.exe). 

Hope it helps.
