### ISSUE TITLE
Crosshair cursor doesn't match location where drawing or selection occurs.

### ISSUE THREAD

**Issue by gpetty** [OpenBoard-org/OpenBoard#463]
I'm running OpenBoard 1.5.4 under MacOS 11.2 with the windowed modification [OpenBoardW](https://webdiis.unizar.es/~spd/openboard/).   I understand the latter modification doesn't affect anything except for the ability to run OB in a window rather than dedicated full screen, which is essential for my remote teaching via conference software, so I don't know whether that part is relevant to this problem.

[**EDIT:**  I just checked the standard (non-windowed) version of OpenBoard, and it does NOT have this problem.  Neverthless, if anyone has any insight, please let me know, as I cannot use the non-windowed version for remote teaching.  I do wish the windowed version were offered as an official option.]

The problem is that when I'm using the pen tool, the crosshair incorrectly shows the drawing location to be displaced noticeably below where drawing or writing actually occurs.  The attached image shows where a red line appears if I start drawing rightward with the cursor initially positioned at a grid intersection.

![IMG_3630](https://user-images.githubusercontent.com/2342020/111370411-2f1abe00-8666-11eb-8d4b-2769c2ba3a8b.jpg)

This mismatch makes writing difficult, especially when trying to add subscripts or accents to existing letters.

I've noticed that the displacement also affects the selection of menu items, so that I have to click a few pixels below the item to actually select it.   The problem is unrelated to whether I use the trackpad on the laptop or an external mouse.

I have not seen anyone else complain about this problem, so it may be specific to my setup.  Either way, is there a way to fix this?

**Comment by fsckawk** [comment]
That is really strange. It could be related to a similar problem, which is only present in macOS versions of OpenBoardW.
I'm talking about the "waves" when using pencil tool with a digitizer tablet. The "fix" here is to disable "pencil is pressure sensitive" check box.

I've no idea why this happens. I mean, source code is the same, but the problem affect only macOS. It could be a problem with Qt5 libraries, but the "El Capitan" version (which uses a different version of QT) reproduces this problem too.

Anyway, I couldn't reproduce (using just a mouse, and macOS High Sierra) the behaviour you've described. What's your macOS version?

Some things you could try:
- Use the "El Capitan" version instead.
https://webdiis.unizar.es/~spd/openboard/OpenBoardW-ElCapitan.dmg
- Disable "pencil is pressure sensitive"

**Comment by gpetty** [comment]
My version is Big Sur.  I'm not certain whether the problem existed prior to upgrading to Big Sur, as I had not used OpenBoard much before then.   I did disable the "pressure sensitive" option prior to the demonstration I posted.

I just tried the "El Capitan" version, and I'm happy to report that it appears to have solved the problem — thank you for that suggestion!
