### ISSUE TITLE
I tried fixing openboard error 0xc000007b with fix #243 but it still says the same thing,eventough I installed vcruntime140.dll and Microsoft Redistributable C++ 2015 (x86)

### ISSUE THREAD

**Issue by GFov** [OpenBoard-org/OpenBoard#466]
![image](https://user-images.githubusercontent.com/81033018/111875707-cc962a80-89a3-11eb-8362-0b6513192973.png)

**Comment by venkat-gvk** [comment]
Download that from [](https://www.dll-files.com) website and paste it in the open board folder.

**Comment by kaamui** [comment]
Please try to install [the latest version](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/OpenBoard_Installer_1.6.1.exe)
