### ISSUE TITLE
How do I share a board?

### ISSUE THREAD

**Issue by rochakagrawal** [OpenBoard-org/OpenBoard#467]
Hi - first time user

thanks for the software

how do I share a live url of the board while I am creating for people to view?

thanks

**Comment by letsfindaway** [comment]
Hi,

please be aware that OpenBoard is a whiteboard application and does not offer to share a board by itself. OpenBoard can however perfectly be used in combination with any video conference or screen sharing application as BigBlueButton, Jitsi, Zoom, or whatever to share the screen. So

* use OpenBoard to work on your board, and
* use a screen sharing application to share your screen!

**Comment by Kryptos-123** [comment]
Also , OpenBoard can export the board to PDF so you can share that file after finishing your presentation.
