### ISSUE TITLE
Create a hide/reveal toggle button in text, images or other objects.

### ISSUE THREAD

**Issue by tunnes** [OpenBoard-org/OpenBoard#468]
Hello folks, how are you?

I have just found this app as an alternative to Activinspire but I miss the feature of hiding or showing an object on the board just toggling it. I'm not familiar with C++ and C codebase, but I'm really willing to add this feature if it makes sense to your team, if this feature makes sense could you folks share with me some kind of briefing, onboarding material, or any other stuff to help me to contribute with this feature, please? 😬

**Comment by kaamui** [comment]
there are several ways to achieve that on Openboard 

If you have two screens (let's say screen 1 is your pc and screen 2 a projector in extended mode), you can use the "show/hide" action to show/hide it on the second screen.

You can alsi find an application in the library to pit a grey rectangle above another object.

Finally, there is another application to hide everything. You can then click to "light" what's under the mouse

Hope it helps
