### ISSUE TITLE
Add an option for making a trail with lasor pointer

### ISSUE THREAD

**Issue by Kryptos-123** [OpenBoard-org/OpenBoard#469]
An option that lets you enable trails in lasor pointer could be helpful. It would behave similar to how it behaves in Microsoft Powerpoint or Google Jamboard.
![pu4aQvEfMw](https://user-images.githubusercontent.com/76696071/113185435-15879200-9274-11eb-83f3-2e8e060a6dbb.gif)

**Comment by kaamui** [comment]
Hi,

Seems interersting, but due to our limited resources, we eon't be able to prioritize on it.
