### ISSUE TITLE
Support for multiple Monitors (Ubuntu) [bug]

### ISSUE THREAD

**Issue by andrewasd** [OpenBoard-org/OpenBoard#471]
When i connect another monitor on the screen , i want the app to stay only on one monitor, 
but it becomes buggy the moment i connect it.

for example i would like to draw on one monitor, while on the other i could have a browser open, but it doesnt work

**Comment by letsfindaway** [comment]
- What do you mean with "buggy"? Could you please describe this in more detail? It is difficult to help you without a more precise description of the problem.
- When you have two monitors connected, how does the multi-monitor setting look like? Could you select there to use only one monitor?
- You can also use the "swap monitors" setting to define which monitor to use when two are connected.

**Comment by cchen1882** [comment]
Hi, I have similar issue on Windows 10. I have more than 2 monitors connected to the PC and one monitor will be active and the rest of them are dark/black/blank. Everything on the desktops are not visible. It feels like OpenBoard just took control over every single monitor, except the one it allows you to draw. Also, there is no control which monitor OpenBoard will be activated on. It just happen randomly. For me, it is not the main display.

**Comment by kaamui** [comment]
The default behavior of Openboard is to display a "student view" of the teacher's  screen on the second screen and then to display the previous page on the remaining screen or a black screen if there is no previous page to display. 

You can disable multi screen by clicking on the dedicated button on the Openboard menu
