### ISSUE TITLE
Language change on Arch Linux / Manjaro Linux

### ISSUE THREAD

**Issue by sp39chorzow** [OpenBoard-org/OpenBoard#472]
Hello,

In our school we use in all classrooms OpenBoard on KDE Neon (based on Ubuntu 20.04) and it is working OK. Teachers are happy and use this tool because it is easy to learn. On KDE Neon we have this version installed: `v1.6.0a3/openboard_ubuntu_20.04_1.6.0-a.3_amd64.deb`. System language is set to PL (Polish) and OpenBoard launches also in PL language.
I am planning change distro to Manjaro/Arch. Now I am testing OpenBoard in this distribution and everything is OK except language. System in Arch/Manajro also is in PL but OpenBoard starts always in EN. 
I tried all version available in AUR Arch repository: https://aur.archlinux.org/packages/?O=0&K=openboard- but no luck.
It is connected somehow with QT and compilation process on this OS?
1. All localization files are present after build in the same directory like in Ubuntu.
2. Force from terminal `openboard  -lang=pl` doesn't work also.

Any help would be appreciated - because teachers for sure will complain that software language changed (even if it is simple software).

**Comment by letsfindaway** [comment]
Hi,

I took a short look at the Arch packages and from what I have seen I do not have an explanation. It look squite ok. What you might however do is to track down from where OpenBoard is trying to read the language files. Start openboard using the following command:

```bash
strace /usr/bin/openboard 2>&1 | grep i18n
```

This will give you some output about attempts of OpenBoard to access files in the `i18n` directory. You will see successful and unsuccessful attempts. Perhaps this can help further in the analysis of the problem?

Good luck!

**Comment by sp39chorzow** [comment]
Thank you for quick reply. Indeed something is different between Ubuntu/Arch, but I don't know what can I do more...

```
[sp39@arch-vm ~]$ strace /usr/bin/openboard 2>&1 | grep i18n
openat(AT_FDCWD, "/usr/lib/libicui18n.so.68", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/openboard/i18n", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 10
[sp39@arch-vm ~]$
```
```
[sp39@kdeneon-vm ~]$ strace /usr/bin/openboard 2>&1 | grep i18n
[sp39@kdeneon-vm ~]$
```
Also this strace is different on Ubuntu nothing, on Arch:
```
[sp39@arch-vm ~]$ strace /usr/bin/openboard 2>&1 | grep PL
read(6, "pl_PL.UTF-8\npp\t\t\t\t\t\tpp_AN.ISO885"..., 4096) = 4096
read(6, "pl_PL.UTF-8\npp\t\t\t\t\t\tpp_AN.ISO885"..., 4096) = 4096
read(6, "_PL.ISO8859-2\niso8859-1/XLC_LOCA"..., 4096) = 4096
```

**Comment by letsfindaway** [comment]
Hi,

that means on KDE Neon you do not get any output? That's strange. The language files are also in a subdirectory `i18n`? Then you should get some output when grepping for that string. And the interpretation of the output on Arch is as follows:

```
openat(AT_FDCWD, "/usr/lib/libicui18n.so.68", O_RDONLY|O_CLOEXEC) = 3
// a library called libicui18n is found and loaded. File descriptor is 3

openat(AT_FDCWD, "/opt/openboard/i18n", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 10
// the directory at /opt/openboard/i18n is found and opened, file descriptor is 10
```

But then I would expect an access attempt for the language file! If you're not afraid of the large output, you could redirect it to a file:

```
strace /usr/bin/openboard >strace.log 2>&1
```

and then inspect the `strace.log` file with an test editor. First search for the `openat(AT_FDCWD, "/opt/openboard/i18n"` call and then see what is immediately following. The next about 30 lines might be interesting.

**Comment by sp39chorzow** [comment]
After deeper investigation with strace, I found the issue.
In Ubuntu package localization files located in `/opt/openboard/i18n/` are in ***.qm** format:
```
...
OpenBoard_en.qm
OpenBoard_pl.qm
...
qt_en.qm
qt_pl.qm
...
```

In Arch/Manjaro are in different ***.ts** format (downloaded directly from github):
```
...
OpenBoard_en.ts
OpenBoard_pl.ts
...
```

When I copied these ***.qm** files directly from Ubuntu deb package to Arch `/opt/openboard/i18n` directory everything works as expected - language changed (strace output also).

Can the software maintainer check this and add these ***.qm** localization files in the github source?

Thanks!

**Comment by letsfindaway** [comment]
Hi,

glad you found it! Adding these `.qm` files should be done when building the package. `.qm` files are generated from the `.ts` files and as they are derived, binary files, they should never be in a git repository. Instead the maintainer of the Arch package has to add some commands to the build step in the PKGBUILD script similar to

```bash
pushd resources/i18n
for i in *.ts; do \
lconvert-qt5 -if ts -i $i -of qm -o ${i/.ts/.qm}; \
done
popd
```

`lconvert` is used to do this compilation process. So you should direct your request to the Arch maintainer. You can find him at the top of the PKGBUILD script, e.g. at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openboard-develop.

**Comment by bartoszek** [comment]
@letsfindaway I've updated PKGBUILD for Arch/Manjaro.

If I might suggest something, please adopt a [patch from `Debian` for auto-generation translation files]( https://salsa.debian.org/debian-edu-pkg-team/openboard/-/blob/master/debian/patches/1005_auto-build-translations.patch)
On the other hand, you can include `.qm` files in the repo 
>  e.g: Freecad did this when integrating with `crowdin` translation service: https://wiki.freecadweb.org/Crowdin_Scripts https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language )

**Comment by letsfindaway** [comment]
> @letsfindaway I've updated PKGBUILD for Arch/Manjaro.
> 
> On the other hand, you can include `.qm` files in the repo
> 
> > e.g: Freecad did this when integrating with `crowdin` translation service: https://wiki.freecadweb.org/Crowdin_Scripts https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language )

Yes, it is possible, but I would argue agains it for two reasons:

- They are derived files. I won't commit them as I would never commit an `.o` file.
- They are binary files, and git cannot handle them very smart, e.g, there is no "compare with previous version" possible.

> btw. aren't `qm/ts` files required only during compilation and installing them is unnecessary (disclaimer: not qt developer here, I'm dealing with `ts/qm`s for the first time. )

- `.ts` files are the files you work on when creating a translation. QtLinguist loads these files and stores the translated strings there.
- `.qm` files are compiled language files created by `lconvert`, optimized for string lookup during runtime. They are loaded during startup of a program when the language to be used is selected.

So the translations are not contained in the program binary, they have to be provided as `.qm` files and are loaded at runtime. In a package for a distribution you only have to provide the `.qm` files. The `.ts` files are not necessary. They can be seen as source files.

**Comment by bartoszek** [comment]
@letsfindaway Thanks for pointing me to the right direction, yep `strace` shows `qm` files being read.
```
openat(AT_FDCWD, "/opt/openboard/i18n", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 17
openat(AT_FDCWD, "/opt/openboard/i18n/OpenBoard_pl.qm", O_RDONLY|O_CLOEXEC) = 17
```
_Now I have to figure out how `Frecad` is packaging its modules so they have translations inside shared objects..._
