### ISSUE TITLE
css grid not supported

### ISSUE THREAD

**Issue by 5alidshammout** [OpenBoard-org/OpenBoard#473]
I opened the web, then entered a website I had built using CSS grid, but it wasn't like what I coded, not everything was like what I arranged

**Comment by letsfindaway** [comment]
The built-in web browser is currently based on WebKit, which is no longer developed and is missing some features you would expect from a modern web browser. As far as I know there are currently discussions within the OpenBoard team how to resolve this:

- by removing the built-in web browser from OpenBoard, or
- by migrating to the Chrome-based `QWebEngine`.

See also #435 which already discusses this issue

**Comment by letsfindaway** [comment]
See also my approach to port WebKit to WebEngine at https://github.com/letsfindaway/OpenBoard/tree/refactor-webengine. Those interested in details may also look into https://github.com/letsfindaway/OpenBoard/issues/14 and https://github.com/letsfindaway/OpenBoard/issues/15.

Alpha-testers are already welcome, but be aware that this work is not finished by now, and there are no concrete plans on when, how, and whether at all these changes will find their way into an OpenBoard release in the future.

**Comment by kaamui** [comment]
Hi,

Thanks to @letsfindaway's help,I'll soon be able to start integration of his work on migration from webkit to webengine. CSS grid and other modern HTML/CSS/JS features will be way better supported.
