### ISSUE TITLE
Font list shows very few fonts (Text tool, OpenBoard 1.6.1, Linux)

### ISSUE THREAD

**Issue by sparrac** [OpenBoard-org/OpenBoard#474]
Since last update (1.6.1) the font dialog shows very few fonts:

- deb package (openboard_ubuntu_20.04_1.6.1_amd64.deb): it shows "Andika Basic", "BSTGreek", "Ecolier_court", "Ecolier_lignes_court", "Ecriture A", "Ecriture B", "GE Typo Libre". Those fonts are not installed on my system.
- flatpak ("ch.openboard.OpenBoard"): it shows "Z003 [UKWN]". This one is installed on my system.

Running both versions from the command line (`openboard` and `flatpak run ch.openboard.OpenBoard`) doesn't show any font-related messages.

Operating system: Linux (Kubuntu 20.04.2 LTS)

**Comment by sparrac** [comment]
After checking both installations, I see that OpenBoard only uses its own fonts. Why doesn't it use the system ones?

This version of the Flatpak installation doesn't include any fonts. So I copied a few to the following directory:

`/var/lib/flatpak/app/ch.openboard.OpenBoard/current/.../files/share/OpenBoard/customizations/fonts`

And the fonts from the deb package are located in:

`/opt/openboard/customizations/fonts`

Is it possible to use a user directory for this?

**Comment by rhabarbersaft** [comment]
I have the same Problem after installing the flatpack version. But I recognize, that Openboard uses my .fonts directory. I have no fonts available, but one. Although it is a directory with many fonts, Openboard only offers a single font. Unfortunately, it is a symbolic font and absolutely unsuitable for use. If I empty the .font directory, Openboard offers the font Z003. It is previewed as a kind of script, but the font shown is a printed one. The directory "customizations" does not exist for me. Can I just create it? 
I'm a little bit confused about this behaviour. I don't want to empty my system (user) font directory, but using Openboard with only a symbolic font is useless.

**Comment by kaamui** [comment]
> After checking both installations, I see that OpenBoard only uses its own fonts. Why doesn't it use the system ones?

So documents can be share regardless of the operating system they were created on.

**Comment by stratus-ss** [comment]
I have the same issue/question as rhabarbersaft
I ran
```
 sudo mkdir -p /var/lib/flatpak/app/ch.openboard.OpenBoard/current/active/files/share/OpenBoard/customizations/fonts
```

And then copied in the liberation TTFs and they seem to show up

**Comment by professoranato2uff** [comment]
I'm using Zorin and I had the same problem. I managed to solve it by copying the system font files to the OpenBoard customization folder using the command:

`sudo cp -r /usr/share/fonts/* /usr/share/openboard/customizations/fonts
`

Now all the system fonts are available on Open Board.

**Comment by petersonespacoporto** [comment]
> > After checking both installations, I see that OpenBoard only uses its own fonts. Why doesn't it use the system ones?
> 
> So documents can be share regardless of the operating system they were created on.

Wouldn't it be easier - or at least _better_ - to embed any fonts used in the document when it is exported?
