### ISSUE TITLE
OpenBoard crashes when right-clicking on a text box

### ISSUE THREAD

**Issue by I027614** [OpenBoard-org/OpenBoard#479]
OpenBoard (both 1.5.4 and 1.6.1 versions) on Linux (Mageia 8, x-64) crashes when right-clicking on a text box.

From console:

openboard
libpng warning: iCCP: known incorrect sRGB profile
Persisting document; path is "/home/katnatek/.local/share/OpenBoard/document/OpenBoard Document 2021-04-19 21-34-45.133/metadata.rdf"
/usr/bin/openboard: line 17: 19305 Segmentation fault      (core dumped) env QT_PLUGIN_PATH=$QT_PLUGIN_PATH:/usr/lib/openboard/plugins LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openboard/plugins/cffadaptor /usr/lib/openboard/OpenBoard "$@"

**Comment by letsfindaway** [comment]
Cannot reproduce that on openSUSE. 

Which package did you install? Where did you download the package?

**Comment by I027614** [comment]
I installed https://rpmfind.net/linux/mageia/distrib/8/x86_64/media/core/release/openboard-1.5.4-5.mga8.x86_64.rpm from Mageia repositories.

**Comment by david-geiger** [comment]
Hi,

I'm the Mageia maintainer of openboard package and I confirm that it segfault for us after right-clickinging on the text box.

I tried the latest 1.6.1 release without success it also segfault, so here attached the full backtrace:

[backtrace_openboard.txt](https://github.com/OpenBoard-org/OpenBoard/files/6360703/backtrace_openboard.txt)

**Comment by david-geiger** [comment]
Here our package structure for Cauldron:
http://svnweb.mageia.org/packages/cauldron/openboard/current/

And the one for mageia 8:
http://svnweb.mageia.org/packages/updates/8/openboard/current/

**Comment by david-geiger** [comment]
Attached more backtrace:
[full_backtrace_openboard.txt](https://github.com/OpenBoard-org/OpenBoard/files/6363109/full_backtrace_openboard.txt)

**Comment by letsfindaway** [comment]
Thanks, but this looks really strange to me: the complete traceback does not contain a single "UBxxx" class, only Qt classes are referenced (besides the main application). Seems to happen during the delivery of the right-click event to a widget through all those Qt internal classes. Also the `this` pointer looks ok to me. So currently I have no further ideas...

**Comment by david-geiger** [comment]
Have you tested as this attached screenshot?


![openboard-screenshot-carsh](https://user-images.githubusercontent.com/4344460/116535592-362f2000-a8e4-11eb-9949-75cd0fbc91ac.png)

**Comment by I027614** [comment]
Just like that (even the same text). It crashes when right-clicking in the text box. :-(

**Comment by kaamui** [comment]
Hi,

thanks for reporting this. I quickly checked and It's also happening on the official release on the three platforms...

Seems reported, and fixed : https://bugreports.qt.io/browse/QTBUG-88309, or maybe it's another one. 

I can't understand why but it seems that the fix was not added to the latest Qt 5.15.3 release (maybe it will on the 5.15.4)

Please use the key shortcuts until it is fixed, as it seems the issue is related to the context menu.

**Comment by david-geiger** [comment]
Confirmed rebuilding qtbase 5.15.2 with QTBUG-88309 patch fixes this text box issue!

Thanks a lot @kaamui

**Comment by kaamui** [comment]
the bug appeared with Qt 5.15.1 so compiling with 5.15.0 binaries also works.
