### ISSUE TITLE
OpenBoard error 0xc000007b, solution in https://github.com/OpenBoard-org/OpenBoard/issues/243 dosen´t help

### ISSUE THREAD

**Issue by MunkC117** [OpenBoard-org/OpenBoard#480]
I have the error  0xc000007b, and i all ready tried the solution in  https://github.com/OpenBoard-org/OpenBoard/issues/243, that is to reinstall Visual C++, that didn´t work, i tried the comand "chkdsk" and nothing, tried to change the files in system WOW64 and nothing, i need help, i use the app to my class :c

**Comment by kaamui** [comment]
Did you try with the latest release (Openboard 1.6.1) ?
