### ISSUE TITLE
[Feature request] add Figure Recognition

### ISSUE THREAD

**Issue by Torkin1** [OpenBoard-org/OpenBoard#485]
Hi, first of all thank you for doing an amazing job with delivering a software like OpenBoard!

I think OpenBoard could use a "Figure Recognition" feature. When enabled, if i try to draw a straight line but it comes up a little crooked, the software would correct it and draw a straight line in place of it. Same with circles, triangles, squares, arrows, ...

For istance, this would be very useful for writing math expressions with tons of fractions in it. 

You could use [Xournal](http://xournal.sourceforge.net/) as an example.

**Comment by kaamui** [comment]
Hi,

It could be interesting, but due to our limited resources, this won't be a priority.
