### ISSUE TITLE
Make it possible to change language via gui.

### ISSUE THREAD

**Issue by LeSnake04** [OpenBoard-org/OpenBoard#486]
For plugin testing and bilingual clases a option to change languages might be useful!

The current workaround of renaming the translation file of your system language only allows switing between system language and English !

**Comment by letsfindaway** [comment]
You can determine the language by invoking OpenBoard from the command line with the `-lang` switch, e.g.:

```bash
OpenBoard -lang de
```

or any other language code supported by OpenBoard. You don't need to rename any files!

**Comment by MIMAXUZ** [comment]
@kaamui On Windows how can i change Default language? On my CMD openboard command doesn't work.
Where are language settings stored? Is it in the registry? I need change language. I don't want use system's default language.
I installed build and tested openboard -lang en, but system didn't find openboard command.
