### ISSUE TITLE
Imported PDF placed twice in ubz file

### ISSUE THREAD

**Issue by fbarillon** [OpenBoard-org/OpenBoard#49]
Testing pdf imported in ubz file, I notice that the file weights twice as it should.
In fact, the pdf file exists at the root and in the /objects folder.
[test-openboard-pdf.zip](https://github.com/DIP-SEM/OpenBoard/files/323468/test-openboard-pdf.zip)
The root file seems useless...

**Comment by ramuntcho** [comment]
Hello,
When you export a ubz document which contains a pdf, the pdf exists normally only in objects folder, not at root. That the first time i see, in your document, a pdf at root.

**Comment by fbarillon** [comment]
I've tested with 
- Open-Sankoré 2.5 => the pdf is in the root
- Open-Board 1.3.1 (ubuntu 14.04 64b) => the pdf is in the root AND in the /object folder
NB : I tried to manualy 
[test-pdf-openboard no-objects.zip](https://github.com/DIP-SEM/OpenBoard/files/325751/test-pdf-openboard.no-objects.zip)
[test-pdf-openboard -no-root.zip](https://github.com/DIP-SEM/OpenBoard/files/325749/test-pdf-openboard.-no-root.zip)
[test-pdf-openboard -nothing.zip](https://github.com/DIP-SEM/OpenBoard/files/325750/test-pdf-openboard.-nothing.zip)


erase one or even the two locations => the pdf always appears (some cache effect?).
I join the files, someone else can try...
