### ISSUE TITLE
character corruption in textbox

### ISSUE THREAD

**Issue by AmaneTsukishiro** [OpenBoard-org/OpenBoard#493]
Some non-ASCII characters such as greek letters (and their ambient characters) are corrupted when
1. copying&pasting a textbox; (the original is fine, while the copy is corrupted)
2. duplicating a slide; (same as above)
3. importing *.ubz.

OS: Win10 Home. App Ver: 1.5.4.

**Comment by kaamui** [comment]
Hi,

Thanks for reporting it.
