### ISSUE TITLE
Shortcut for Pan/Scroll page in OpenBoard

### ISSUE THREAD

**Issue by SouravSarkhel** [OpenBoard-org/OpenBoard#494]
Is there any shortcut key to select the Pan/Scroll option? ctrl+(arrow keys) can move the page until we add a new page. If a new page is added the command moves the page as well as changes the page.

**Comment by letsfindaway** [comment]
Crazy! But you're right!

This is definitely a bug. Thanks for reporting!

And no, there is currently no other shortcut for panning, so I cannot offer a workaround.

Hint for someone fixing it: Here
https://github.com/OpenBoard-org/OpenBoard/blob/dd19e75211b0baa29aed783fdea19ad5c328dd03/src/board/UBBoardView.cpp#L201
should be a check that no modifier key is pressed before interpreting these keys.

**Comment by SouravSarkhel** [comment]
> Crazy! But you're right!
> 
> This is definitely a bug. Thanks for reporting!
> 
> And no, there is currently no other shortcut for panning, so I cannot offer a workaround.
> 
> Hint for someone fixing it: Here
> https://github.com/OpenBoard-org/OpenBoard/blob/dd19e75211b0baa29aed783fdea19ad5c328dd03/src/board/UBBoardView.cpp#L201
> 
> 
> should be a check that no modifier key is pressed before interpreting these keys.

Hello mate, Thank You for the reply. But unfortunately I dont know much about coding. Could you please explain about what you meant. And how to solve the issue. May be a step-by-step guide if possible. Thanks again. Have a nice day.🙂

**Comment by kaamui** [comment]
Hi,

thanks for reporting it. I'll try to fix it asap
