### ISSUE TITLE
Show desktop needs to return to main openboard app to show annotation (ubuntu 20.04)

### ISSUE THREAD

**Issue by bagustris** [OpenBoard-org/OpenBoard#496]
I am experiencing this problem (bug). Steps:  
1. Show Desktop
2. Make some annotation

Expected result: Showing annotation
Current result: no annotation, except back to main openboard and back again to desktop

See screenshot below for detail.
![Peek 2021-06-18 16-39](https://user-images.githubusercontent.com/3158361/122525167-ed7a2480-d053-11eb-82fa-2603622e65f1.gif)

Update:  
- I already set gnome dock in the bottom

**Comment by kaamui** [comment]
Hi,

are you using [the latest release of OpenBoard](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/openboard_ubuntu_20.04_1.6.1_amd64.deb) ?

**Comment by bagustris** [comment]
Yes, I am using version 1.6.1.

~~~
OpenBoard 1.6.1

OpenBoard is copyright © 2021. All rights reserved.

OpenBoard is derived from Open-Sankoré. Open-Sankoré is copyright © 2010-2015 Groupement d'Intérêt Public pour l'Education Numérique en Afrique (GIP ENA). All right reserved.

OpenBoard is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 3 of the License, with a specific linking exception for the OpenSSL project's "OpenSSL" library (or with modified versions of it that use the same license as the "OpenSSL" library). You can find the source code of this software at  github.com/OpenBoard-org. 
OpenBoard is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License below for more details.

Contact :
Service écoles-médias
Rue des Gazomètres 5
Case Postale 241
1211 Genève 8
Switzerland
openboard.ch
~~~

I installed using provided .deb version in the [release page](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1).

Gnome version:

    GNOME Shell 3.36.9

**Comment by kaamui** [comment]
Sorry I have no idea. Some people mentionned in #66 that installing xcompmgr had helped. Is there something specific on your config regarding X or Wayland, mazybe ? Something else ? 

If you can, try to install kvm, then create a standard ubuntu 20.04 VM, and install openboard on it to see if it still doesn't work.
