### ISSUE TITLE
Please Improved Bengali language

### ISSUE THREAD

**Issue by Pranab009** [OpenBoard-org/OpenBoard#498]
Please sir improve Bengali language
Too many things are missing. Otherwise it is work well.

![Bengali k](https://user-images.githubusercontent.com/65340361/123682697-f36cc400-d810-11eb-9857-14cc3168d47e.png)
![bengalij](https://user-images.githubusercontent.com/65340361/123682718-f9fb3b80-d810-11eb-9325-68ccedbf9a3e.png)

**Comment by kaamui** [comment]
Hi,

wrong github => https://github.com/dslul/openboard
