### ISSUE TITLE
whiteboards needed for education

### ISSUE THREAD

**Issue by manouchk38** [OpenBoard-org/OpenBoard#502]
Openboard consist in sharing a whiteboard but in schools what is needed is something more complex as when using whiteboard with small group activities during teaching. Therefor it is needed to have a possibility to create whiteboard for groups of students that a teacher can watch and share for discussion. Students may also be allowed to share their whiteboard to other groups. There is the possibility to do so on a single whiteboard by dividing it into "subwhiteboard" but it does not seem to be a working solution.

**Comment by letsfindaway** [comment]
What you probably need is some kind of collaboration tool with a shared whiteboard. This is however different from what OpenBoard is and wants to be.

OpenBoard provides you with a whiteboard specially tailored to the needs of education. It aims to be easy to use, to some extend mimic a real whiteboard (e.g. with ruler and circle), options to add images, sound, or other content from the web etc.

OpenBoard does however not care about remote sharing. You can use it together with some screen sharing software often found in web conference tools, but this does not make a collaborative whiteboard out of OpenBoard.

Examine the features OpenBoard provides. If you need something different, then probably another solution will fit better to your needs.

**Comment by manouchk38** [comment]
No in fact, in interactive teaching approach which is widely recommended in
science education research and in particular physics education research,
what is useful is portable whiteboard that students uses in groups to solve
problems. The whiteboard allow an efficient teacher-student and
student-student communication. The teacher can see rapidly some
representations used by students in the discussion and can decide to
interact with them etc. This is heavily used in physics teaching.I think it
was "first" used in work done by Hestenes with one his very good PHD
student. It seems to be sometimes called whiteboarding like in this
article:
https://scholar.google.fr/scholar?cluster=8835968255287368522&hl=fr&as_sdt=2005&sciodt=0,5
This approach promote easy visualization of student representations which
can improve significatively communication. The only tentative
implementation of this idea has been done on https://whiteboard.fi/, but it
not opensource. I do really think that the "monolithic whiteboard" is
obsolete when considering we can do much better in principle with
individual boards that can be shared. Well, I'm wrtting quite fast. This
should be discussed more calmly. Infact, I'm trying to share this way of
thinking whiteboard so that maybe some great programmer may adopt this idea
and built a open-source version of that...

Em ter., 20 de jul. de 2021 às 10:55, Martin Winter <
***@***.***> escreveu:

**Comment by sjtosco** [comment]
Hi! This app looks like just what i need. I used Jamboard some times ago, but lag is annoying sometimes. 
With this app i can realize my teorical exposition and share and interact with students using videoconference tool like Meet.
I will try this year and we will see how...
Regards
