### ISSUE TITLE
Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by alexrsoares** [OpenBoard-org/OpenBoard#504]
I have finished an updated version for Brazilian Portuguese (pt_BR) based on English (en_GB) and French (fr_CH) versions.
It's available here:
[https://docs.zoho.com/file/oifyxceec5eff3751418187839da9f3c58a79](https://docs.zoho.com/file/oifyxceec5eff3751418187839da9f3c58a79)

_Originally posted by @alexrsoares in https://github.com/OpenBoard-org/OpenBoard/issues/39#issuecomment-866243249_

**Comment by alexrsoares** [comment]
Also, some interactivities do not load the local language. Seems to work fine when changing "**var lang = (window.sankore)?sankore.locale().substr(0,2):"en"; //local language**" to "**var lang = window.parent.sankore ? window.parent.sankore.locale() : "";**" (see line 12 of index.html in OpenBoard/resources/library/interactivities/Constrast.wgt/)

**Comment by kaamui** [comment]
Hi,

thank you for your help. Can you make a pull request with your ts file ? I'll be happy to integrate it for the next release.
