### ISSUE TITLE
Can't play audio files Openboard 1.6.1

### ISSUE THREAD

**Issue by takadahugo** [OpenBoard-org/OpenBoard#505]
Hi,
I installed Openboard 1.6.1 on Mac OS 10.14.6 and just can't play audio files.
I reinstalled 1.5.4 to make it work again.

Is there any workaround for this issue? 

Regards
Hugo

**Comment by kaamui** [comment]
Hi,

thanks for reporting it. I'll try to see if I can reproduce it.
