### ISSUE TITLE
Openboard issue with archlinux

### ISSUE THREAD

**Issue by FernandoVelcic** [OpenBoard-org/OpenBoard#508]
Hello, I have an issue when I try to open openboard in archlinux (manjaro), I got the following error message:

![image](https://user-images.githubusercontent.com/7217340/130296466-f195ff3e-4099-4989-baca-935201fd30a9.png)

openboard: error while loading shared libraries: libpoppler.so.110: cannot open shared object file: No such file or directory

Sometimes I reinstall openboard and works well but when I made a system upgrade it breaks again.

**Comment by letsfindaway** [comment]
**Disclaimer:** I'm not an ArchLinux user, but that is what I assume to be the cause of such problems.

Issues like that are inherent to a rolling release like ArchLinux. If a system update upgrades a library to a higher version, then you have to recompile all dependent packages. For those installed from AUR you have to do it by yourself.

"Reinstalling" OpenBoard will do a recompilation using the new library versions. That's exactly what _you_ have to do. There is nothing the OpenBoard team can do with this.
