### ISSUE TITLE
Guide to build from source on Mac OS

### ISSUE THREAD

**Issue by htakada** [OpenBoard-org/OpenBoard#509]
Hi,
Where can I find documentation to build from source on Mac OS?

Regards

**Comment by takadahugo** [comment]
Hi again @kaamui 
Do you have at least a draft of it? 

Best regards

**Comment by diogoborges14** [comment]
I did that (on MacOS version is 10.3.6):

### → Install [Xcode](https://developer.apple.com/download/all/)
### → Install [HomeBrew](https://brew.sh/)
### → Install curl
(some packages need the HomeBrew specifc version of curl)
```bash
$ brew install curl
```

### → Install OpenBoard dependencies
(this could take a long time and some erros :) to fix)
```bash
$ brew install ffmpeg@4 quazip qt@5 iceberg poppler-qt5 sevenzip
```

### → Create a link to **qmake**
```bash
$ cd /usr/local/bin
$ ln -s ../opt/qt@5/bin/qmake .
```

### → Download [QtWebKit](http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/)
and extract *QtWebKit.7z* files to the *qt* folder
```bash
$ cd /tmp
$ curl -L -o QtWebKit.7z https://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/qtwebkit-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
$ 7zz x -o/usr/local/opt/qt@5/ QtWebKit.7z
```

### → Choose a folder and clone *OpenBoard* and *OpenBoard-Importer*
(I'm using my user home folder ~/)
```bash
$ cd ~/
$ git clone https://github.com/OpenBoard-org/OpenBoard.git
$ git clone https://github.com/OpenBoard-org/OpenBoard-Importer.git
```
### → Go to *OpenBoard-Importer* folder and build
```bash
$ cd ~/OpenBoard-Importer
$ qmake OpenBoardImporter.pro
$ make
```
### → Edit *~/OpenBoard/OpenBoard.pro*
Replace "poppler" by "poppler-qt5"
Replace "ffmpeg" by "ffmpeg@4"
Replace "-lquazip" by "-lquazip1-qt5"
Replace "QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.10" by "QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.13"

### → Go to OpenBoard folder and build
```bash
$ cd ~/OpenBoard/
$ qmake OpenBoard.pro
$ make
```
### → Edit *~/OpenBoard/release_scripts/osx/release.macx.sh*
Replace "BASE_QT_DIR=~/Qt/5.15.0/clang_64" by "BASE_QT_DIR=/usr/local/opt/qt@5/"
Replace "/usr/local/Cellar/ffmpeg/4.3.1_1/lib" by "/usr/local/opt/ffmpeg@4/"
Replace "/usr/local/Cellar/nettle/3.6" by "/usr/local/opt/nettle/"
Replace "/usr/local/Cellar/openssl@1.1/1.1.1h" by "/usr/local/opt/openssl"
Replace "/usr/local/Cellar/libvorbis/1.3.6/" by "/usr/local/opt/libvorbis/"

### → Run *release.macx.sh* to build you final *.dmg*
```bash
$ chmod +x ~/OpenBoard/release_scripts/osx/release.macx.sh
$ bash ~/OpenBoard/release_scripts/osx/release.macx.sh
```
### → If all was done successfully
Your final *OpenBoard.dmg* is on *~/OpenBoard/install/mac/OpenBoard.dmg*
If you need, your builded *.app* and debug *.dSYM* files is on *~/OpenBoard/build/macx/release/product/*

**Comment by kaamui** [comment]
https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-MacOS-(Universal)
