### ISSUE TITLE
Clock tool

### ISSUE THREAD

**Issue by si2mev** [OpenBoard-org/OpenBoard#51]
While understanding that simplicity is important. I (and my students) really miss the clock tool. I liked the analog clock and the way to keep it appear on every page.

**Comment by ramuntcho** [comment]
I understand but i'm not sure that the analog clock is really open-source (it's the clock of the swiss railways). For now, we can't add it.

**Comment by ramuntcho** [comment]
Closed because the status of the widget isn't clear.

**Comment by si2mev** [comment]
That is a pity. It shouldn't have that swiss railways theme. Just a clock. Even digital should be a very good feature.

**Comment by sahi1l** [comment]
I agree: a simple digital clock displayed in the toolbar would be very valuable when teaching a class.  Please consider adding it.
