### ISSUE TITLE
How to set custom Pen cursor and custom stylus

### ISSUE THREAD

**Issue by aanandharaja** [OpenBoard-org/OpenBoard#510]
Hi,
How to  replace the  cross hair cursor in to custom designed cursor. and i  want to customise the stylus tools.
in desktop mode stylus want to show  the erase all option, undo redo buttons. and custom created shapes.
Thankyou.

**Comment by letsfindaway** [comment]
These things are mostly not configurable in OpenBoard. Changing this would require a significant amount of programming skill.

If you feel prepared to dig into the code, you will certainly find the places where the cross hair cursor is drawn or the toolbars are populated with buttons. However you will certainly need some time to get familiar with the structure of the code.
