### ISSUE TITLE
Openboard display not appearing in the sharing list on Google Meet on KDE neon

### ISSUE THREAD

**Issue by psnayak2007** [OpenBoard-org/OpenBoard#512]

**Comment by letsfindaway** [comment]
OpenBoard is a full-screen application.This means that it does not appear as a window in the sharing list. Depending on your browser you can however also share individual screens.

I'm using Chromium for this purpose (here: openSUSE Leap 15.3, KDE, but this does not matter). The sharing menu let me select between screens and windows. Here I'm selecting "screens" and can easily share that screen where OpenBoard is displayed. This does however not work with the current version of Firefox.

Hope this helps.
