### ISSUE TITLE
Window not resizing when external display disconnected

### ISSUE THREAD

**Issue by mamarsh** [OpenBoard-org/OpenBoard#513]
I use OpenBoard when teaching, and have it displayed through the room projector. When I connect to the projector, and my display adjusts to match the projector's resolution, OpenBoard resizes properly. When I disconnect from the projector, OpenBoard does *not* resize, cutting off the top of the window, and making the menus inaccessible. I have to kill and restart the process in order to make it work again. This is on a 13" MacBook Pro, MacOS version 11.5.2, and OpenBoard version 1.6.1.

**Comment by letsfindaway** [comment]
I know it's just a workaround and does not solve your actual problem, but instead of killing you could gracefully terminate OpenBoard using Ctrl+Q (on MacOS) or Alt+F4 (on Windows, Linux).

**Comment by mamarsh** [comment]
I'm actually using the "Quit" option on the dock's context menu. :)

**Comment by letsfindaway** [comment]
Another question: is this happening with some other full screen program, too? Or is it specific to OpenBoard? You could e.g, try it with a browser playing some media in full screen mode and then attaching and removing the projector.

**Comment by letsfindaway** [comment]
I'm closing this issue here as

- it is reported for an outdated version of OpenBoard
- updated display manager probably has fixed it
- no further information from the OP
