### ISSUE TITLE
Web browser based translation service

### ISSUE THREAD

**Issue by ovari** [OpenBoard-org/OpenBoard#518]
Can a web browser based translation service be used to translate your program? For example, could [Weblate](https://hosted.weblate.org/) be an option?

What do you think?

Thank you

**Comment by kaamui** [comment]
Hi,

I don't know. qlinguist is really simple to use though

**Comment by ovari** [comment]
[Hosted Weblate](https://hosted.weblate.org/) does not require setting up, running nor maintaing a weblate server and does not cost any money for open source projects like OpenBoard.

Having OpenBoard on Hosted Weblate may increase the translations into other languages as OpenBoard will be seen by people who are translating other projects.

It seems that GitHub and Hosted Weblate can be automated. For example the developers added Gaphor added Weblate (https://github.com/gaphor/gaphor/issues/937#issuecomment-905061467).

Thank you

**Comment by ovari** [comment]
> IMHO web based translation is important for larger projects, where several people are working on a single language. For OpenBoard this is only rarely the case, so the benefit is not as large as for other projects.

For magyar (Hungarian) there seems to be more than one person working on that single language.
