### ISSUE TITLE
White flashes between slides

### ISSUE THREAD

**Issue by vicki19** [OpenBoard-org/OpenBoard#522]
Hi,
I updated to version 1.6.1 today, but now I'm having white flashes in between slides when I navigate through them. My presentation is no longer seamless. Using Windows 10 Pro. Is there a solution or a way to go back to version 1.5.4? Thanks!

**Comment by kaamui** [comment]
Hi, we have Openboard installed in hundreds of Windows machines and this issue has not been reported, so I have no idea what's happening on yours. It may still be related to openboard, but I've no idea what could explain it. Something special on your config ?
