### ISSUE TITLE
Openboard resizes pasted PDFs after closing then reopening

### ISSUE THREAD

**Issue by DM1885** [OpenBoard-org/OpenBoard#525]
Since the update to 1.6.1 if i past a part of a PDF onto the screen and size it to fit after reopening the document the PDF overfills the screen and need to be resized.

**Comment by DM1885** [comment]
Hi, I reinstalled the previous version and it is OK.  In the new version when I open the document folder the thumbnail is the wrong size. It is much larger than the originnal paste.

Regards,
David

**Comment by DM1885** [comment]
Below is a screenshot.  i sized it properly, but whn I reopened it filled the screen  I am back to using the previous version.

**Comment by letsfindaway** [comment]
> Below is a screenshot. i sized it properly, but whn I reopened it filled the screen I am back to using the previous version.

Sorry, there is no screenshot attached.
