### ISSUE TITLE
[MAC] some requests

### ISSUE THREAD

**Issue by dittoda** [OpenBoard-org/OpenBoard#529]
1. Clear Button in Desktop mode or same menu tab like in Board mode
2. Shortcuts ( for each functions and switching in Desktop, Board, Document, Web)
If you publish this app into commercial, i would buy abs. thx.

**Comment by kaamui** [comment]
Hi,

1. you can clear desktop by clicking the small (too small) arrow near the erase button or by doing a long click on it to make the submenu appear. Idem on other drawing icons. 
2. Ctrl+B for Board mode, Ctrl+D for Documents Mode, Ctrl+W for Web Mode, Ctrl+Maj+H for Desktop (but could not make it work). The community worked on the possibility to edit shortcuts via a tab in the preferences menu, but it has not been added yet and is not a priority (at this time).

OpenBoard will remain free for everyone and open-source :)
