### ISSUE TITLE
Desktop mode is not working correctly (Ubuntu 20.04)

### ISSUE THREAD

**Issue by pvguima** [OpenBoard-org/OpenBoard#530]
I recently updated to version 1.6 using the binary file for Ubuntu. But the desktop mode is not working very well. 
It just does not write on my screen. I am also having problems moving it between monitors on desktop mode, the bar only stays in one of the monitors.   

Where can I find the previous 1.5 binary codes for Ubuntu? that were working well on the previous one.

**Comment by PeterPorker3** [comment]
> I recently updated to version 1.6 using the binary file for Ubuntu. But the desktop mode is not working very well. It just does not write on my screen. I am also having problems moving it between monitors on desktop mode, the bar only stays in one of the monitors.
> 
> Where can I find the previous 1.5 binary codes for Ubuntu? that were working well on the previous one.

Have you tried 1.6.1? Are you using Wayland? I have been using OpenBoard on 20.04 and as long as you are NOT using Wayland and using version 1.6.1, it seems to work perfectly fine for me.

**Comment by faheemkhuhawar** [comment]
I confirm the desktop mode does not work properly if X11. However, with Ubuntu on Wayland, it works fine.

echo $XDG_SESSION_TYPE

**Comment by kaamui** [comment]
I'm on Ubuntu 20.04 with X11 but no issues. Maybe your issue is related to b43ffa4 that will be released with 1.6.2 (before June)

**Comment by xtarrega** [comment]
@pvguima Have you solved this problem?
I've just installed openboard in ubuntu 20.04 (with X11) and desktop mode doesn't work.

**Comment by faheemkhuhawar** [comment]
@xtarrega No solution yet. 
With multiple monitors and x11, the desktop mode does not work properly. Try switching to wayland environment if you want to use onscreen annotation feature.

**Comment by faheemkhuhawar** [comment]
updated to openboard 1.6.4, the desktop mode using multiple monitor on ubuntu 20.04 LTS still does not work.

$ echo $XDG_SESSION_TYPE
x11
