### ISSUE TITLE
OpenBoard does not build on FreeBSD

### ISSUE THREAD

**Issue by BSDer** [OpenBoard-org/OpenBoard#534]
Hi,
OpenBoard does not build on FreeBSD, so I am patching it, please see here:
https://github.com/BSDer/OpenBoard

Would you consider a pull request? Thank you.

**Comment by letsfindaway** [comment]
I took a look at your changes and I thing, technically they are fine! But how to proceed to make them available to the community? I think there are several options, at least the following:

- You could provide it here as a pull request.
- You could add an OpenBoard port to FreeBSD and use your approach as a patch in this port.

I would recommend the second for several reasons:

- If you add it here, then OpenBoard would be available for those who find this repository and have enough knowledge to build it from there. A FreeBSD port however would make OpenBoard available for a much broader range of users.
- The OpenBoard project was created to help schools in Genova. The project maintainer is paid from there. In Genova however no FreeBSD computers are used. Therefore your pull request might be of very low priority for them.
- Linux distributions make it very often similar when they create an installable package from upstream code. I'm an openSUSE user. Look at https://build.opensuse.org/package/show/Education/OpenBoard. Here you see that they are still on 1.5.4 :disappointed: and add a set or patches, mainly to adapt it to the way openSUSE (and many other distributions) want to have an installable package. Probably some of these patches are also useful for FreeBSD?!

I'm not part of the OpenBoard project, so this expresses just my personal recommendation. Please make your own decision!
