### ISSUE TITLE
Let us disable numbers on letters when there is a separate numbers row already

### ISSUE THREAD

**Issue by lgyurci** [OpenBoard-org/OpenBoard#540]
When the numbers row is enabled, the letter buttons shouldn't have numbers as their secondary functions, but even if they do, it really shouldn't default to them. My native language requires me to type a lot of these letters, and defaulting to numbers on long press really hurts my typing experience. Gboard already does this, please make it an option here too.
![The issue](https://user-images.githubusercontent.com/55853197/141696778-d4641d4d-347b-4ba4-9dfb-d7109f53aa4f.jpg)

**Comment by lgyurci** [comment]
It's also a problem on other letters with symbols. Just let us make the keyboard default to the secondary letters instead of the symbols please.

**Comment by lgyurci** [comment]
Or even disable symbols completely on letter keys

**Comment by letsfindaway** [comment]
Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.
