### ISSUE TITLE
Erase/Ink Shortcut Bug

### ISSUE THREAD

**Issue by dhakiptk** [OpenBoard-org/OpenBoard#542]
Hi, 
Thanks a lot for the wonderful software. I am using the version 1.6.1 on Ubuntu 20.04 LTS installed by downloading the debian package from https://openboard.ch/download.en.html
Following is the way to reproduce the bug
I use the hotkey CTRL+E to activate the eraser and CTRL+I to activate the ink. Once I erase and use CTRL+I to switch back to ink, a residual eraser circle is left on the screen. This does not occur when the Ink button (on the toolbar) is pressed instead of the CTRL+I hotkey.

**Comment by letsfindaway** [comment]
See also #354 reporting apparently the same behavior.
