### ISSUE TITLE
Which is the final version to work with Windows 7 x64 ?

### ISSUE THREAD

**Issue by vecuccio** [OpenBoard-org/OpenBoard#544]
Can you tell me what the last version that runs on Win7/64 is ?

**Comment by kaamui** [comment]
Hi,

Never tested, but if the 1.6.1 is not working (is it ?) you should try with the 1.5.4

**Comment by vecuccio** [comment]
Thanks, that version works.
Do you know what format of MP4 it supports for video import ? I dropped h264 and h265 files in the default movie folder and it didn't see them. What audio formats does it support too ? Does it recognize all MP3 bit rates etc ?
