### ISSUE TITLE
Shortlinks with wrong link to "change history" on Download wiki page

### ISSUE THREAD

**Issue by letsfindaway** [OpenBoard-org/OpenBoard#548]
Some recent change on the [Download](https://github.com/OpenBoard-org/OpenBoard/wiki/Downloads) wiki page introduced shortlinks using linkify.me for three of the links. One of them (the one for the change history in the first line of the wiki page) is now pointing to the wrong target location.

As the wiki is editable for everyone, I reverted these changes as I think that shortlinks are very problematic, as 

- they hide the real target from the user,
- can be misused to redirect users to malicious content,
- have no additional benefit in that place IMHO.

After reverting, the changes have however been reapplied by the author.

So I want to ask @nton7 to explain the reasoning behind this change.

**Comment by letsfindaway** [comment]
I also want to have @kaamui a look on this, as I think that replacing direct links with shortlinks is a technique which I strongly discourage.

**Comment by letsfindaway** [comment]
The above-mentioned user has vanished from Github. The account is deleted.

I have now again reverted the changes. The Download page is again in its initial state.

I leave that issue open for some days as a reminder to check for such activities and will close it when I don't see any further activity in this direction.

**Comment by letsfindaway** [comment]
No further attempts to change this page on the wiki or any other page. Closing this issue.

**Comment by kaetemi** [comment]
We had the same user doing the same on our wiki on the same day.

**Comment by rusefillc** [comment]
that's malicious change we had same in our wiki also on the Downloads page

github has to act up and improve wiki restriction rules

Feel free to chime in at https://github.com/github/feedback/discussions/10376
