### ISSUE TITLE
Display problems on Ubuntu 21.10

### ISSUE THREAD

**Issue by holgervoss** [OpenBoard-org/OpenBoard#550]
I've installed Openboard out of the repositories - the snap-installer is broken. There's a display problem while opening it and also with the "Bereitschaftsbetrieb". v 1.6.1  from your website can't solve all dependencies.

See the video!

https://nc-gartetal.de/index.php/s/dQYFKafX8CCykXo

**Comment by letsfindaway** [comment]
Hi Holger,

please note that the snap is not maintained by the OpenBoard project, but by an independent person. Perhaps you can contact the one creating the snap via the e-mail address shown on https://snapcraft.io/openboard?

The package available from this web page is build for Ubuntu 20.04. There is no official build available for 21.10. There are packages which have changed between Ubuntu 20.04 and 21.10 and on which OpenBoard depends. Therefore such problems with dependencies can be expected.

There is however also a version of OpenBoard on flathub.org: https://flathub.org/apps/details/ch.openboard.OpenBoard. This is even the current 1.6.1 release, while the snap dates back to 2018 and is of course based on an outdated version. Could you perhaps try the Flatpak provided from there? It was updated just this year in November! And looking on the people maintaining this flatpak (see https://github.com/flathub/ch.openboard.OpenBoard/graphs/contributors/ I can tell you that there are really good programmers taking care of this package!

**Comment by holgervoss** [comment]
Hi Martin! Thank you for the detailed answer and the reference with Flatpak. The display is also a bit unstable here - but slightly. And it all works!

**Comment by JBBgameich** [comment]
Last time I checked the snap was just completely empty. I've been trying to get Canonical to remove it, but they never answered.
