### ISSUE TITLE
No audio when recording

### ISSUE THREAD

**Issue by OviiiOne** [OpenBoard-org/OpenBoard#552]
I installed version 1.6.1 on my Macbook air (M1)  with Monterrey 12.1, when I use the podcast feature I select the microphone of my macbook as audio input but it does not record any audio.

I guess it's because it never asks for permission to use the microphone.

**Comment by kaamui** [comment]
Permission is asked to use the mic (normally). Did you try to give OpenBoard.app the permission manually ? Does it help ? Maybe it is related to the fact that 1.6.1 works on ARM processors using emulation. Screen capture seems to be broken too.

**Comment by OviiiOne** [comment]
I don't know how to give permissions, but back then I read that you just need to drag&drop the app on the settings app (microphone settings), it did nothing. It wasn't added.

**Comment by kaamui** [comment]
Sry I just saw that's there's not the usual -/+ button to add apps manually like in other settings. 

The expected behavior is that when you click on the record button, a popup is displayed and and ask for permission. So it might be a bug due to emulation.

**Comment by gariggio** [comment]
Same issue with 1.6.1 version on OXS 12.1 (iMac intel).
It doesn't record any audio.
No permission to use mic is asked (OSX Settings > Security & Privacy...)
