### ISSUE TITLE
Amoled theme with borders + one hand mode

### ISSUE THREAD

**Issue by SosPosos** [OpenBoard-org/OpenBoard#557]
Please make an amoled theme with borders like one in the GBoard, i just can't use one without the borders
Photo:
https://ibb.co/DGXbkJ9
dark mode OpenBoard theme looks not as good as this theme in GBoard. 
and i really need one hand mode - with large phone it feels so bad to use keyboard without one hand mode

**Comment by letsfindaway** [comment]
Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.

**Comment by SosPosos** [comment]
> Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.

oh, sorry
