### ISSUE TITLE
Text Correction aka Auto Correct issues for email address

### ISSUE THREAD

**Issue by AntaeusBastiat** [OpenBoard-org/OpenBoard#559]
Anytime I type an email address such as "email@address.com", the text correction function will correct it as "email address com". I have tried adding every variation of "@address.com" to the personal dictionary, with no luck. Unless you add the exact email address to the personal dictionary, then it will auto correct it. Is there a setting I am missing or something I am doing incorrectly, because this seems kind of strange.

**Comment by letsfindaway** [comment]
Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.
