### ISSUE TITLE
Win 10 x64 - Crash on use of Erase Tool

### ISSUE THREAD

**Issue by fuzzard** [OpenBoard-org/OpenBoard#56]
Hi,

Have tried to use the latest release version 1.3.3 on Windows 10 Clients. It appears they are compiled as a debug release and require the MSVCR100D.dll to run. Ive got around that for now by copying the dll into the OpenBoard install directory, and the program runs.

The issue i have is when i go to use the erase tool, the program will crash. You can click on the erase tool, and click on empty space, and its fine, but when you go to erase a line drawn from the Pen tool, the program immediately crashes. It happens in Desktop and Board view.

Ill grab some screenshots and crash logs when i have a chance to, just thought id log the issue to see if anyone else has experienced it.

**Comment by gjalves** [comment]
I've made a hack to fix this issue for now. Please let me know if works for you.

[hack_core_dump.patch.txt](https://github.com/OpenBoard-org/OpenBoard/files/625931/hack_core_dump.patch.txt)
