### ISSUE TITLE
openboard fails to build with poppler 22

### ISSUE THREAD

**Issue by jbicha** [OpenBoard-org/OpenBoard#560]
- openboard 1.6.1
- Ubuntu 22.04 Alpha
- poppler 22.02.0

poppler 22 now requires C++17. This makes openboard fail to build.

**Comment by letsfindaway** [comment]
For a fix see [Patch 0022](https://build.opensuse.org/package/view_file/home:letsfindaway/OpenBoard/0022-chore-use-c-17-for-pdf-on-linux-builds.patch?expand=1) on [my builds for openSUSE](https://build.opensuse.org/package/show/home:letsfindaway/OpenBoard).
