### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by JFortu** [OpenBoard-org/OpenBoard#566]
First of all, thanks for the project. I've detected that Spanish translation is not so correct sometimes. The tool "Compass" was translated into "Brújula", but the correct Spanish word is: "Compás". Similar happens with "Triángulo", that should be "Cartabón"
If there is a English-Spanish file of the terms used, I can check translations.
Regards

**Comment by kaamui** [comment]
Hi,

Please provide a pull request with the modifications you think is needed, so it can be review and integrated to OpenBoard.
