### ISSUE TITLE
1.6.1 version Ubuntu 20.04 (deb) unable to open a ubz board from file explorer

### ISSUE THREAD

**Issue by Jouski** [OpenBoard-org/OpenBoard#567]
Hello,

On Ubuntu 20.04, 1.6.1 version, when opening a ubz file from file explorer (Thunar), it lauches Openboard but with a new blank board instead of loading the selected one.

Otherwise it'still possible to open ubz documents through "import" button.

**Comment by kaamui** [comment]
Hi,

it's fixed in upcoming 1.6.2.
