### ISSUE TITLE
[Bug] double numbers

### ISSUE THREAD

**Issue by OilSubjectLoss7** [OpenBoard-org/OpenBoard#568]
The long click secondary keys at the top row are numbers instead of the special keys

Top: gboard
Bottom: Oboard
![compare](https://user-images.githubusercontent.com/19810035/156576515-eda2dc83-5a13-4548-9119-35380332dd5d.png)

**Comment by kaamui** [comment]
Hi,

wrong project => https://github.com/dslul/openboard
