### ISSUE TITLE
fatal error U1077 when compiling Openboard.pro

### ISSUE THREAD

**Issue by Messiaslogia** [OpenBoard-org/OpenBoard#575]
![Bug](https://user-images.githubusercontent.com/63260830/158443006-ee947afa-7649-4e2b-addf-4b7b88869909.png)
 
 I'm trying to compile OpenBoard.pro but I get this error. I already installed all the dependencies and tested other repositories. I'm using 
win 10 and using Qmake in version 5.15.2.
Could you help me to resolve this?

**Comment by letsfindaway** [comment]
Seems that you're trying to compile the `1.7-dev` branch. See #572 for this problem.

**Comment by letsfindaway** [comment]
Should be solved with latest pushes to `1.7-dev`. Please close this issue if this is solved for you, too.

**Comment by Messiaslogia** [comment]
Thanks a lot for the help.
