### ISSUE TITLE
Does Not work on MacOs full Screen. (M1 chip)

### ISSUE THREAD

**Issue by SaMuSaRu** [OpenBoard-org/OpenBoard#581]

**Comment by kaamui** [comment]
Hi,

can you be more precise on what is not working ? What do you call "MacOS full screen" ?

on ARM processors, OpenBoard still can be launched via Rosetta 2 (emulator)

**Comment by akhilr007** [comment]
Hey, the toolbar doesn't seem to appear in google chrome (when chrome is opened in full-screen mode).

**Comment by SaMuSaRu** [comment]
> Hey, the openboard toolbar doesn't seem to appear in google chrome (when chrome is opened in full-screen mode).

Yes that's what i meant

**Comment by SaMuSaRu** [comment]
Can you please point me to some reasons why this is happening And  which modules in code base should i look at to propose a fix.

**Comment by kaamui** [comment]
I'm not sure to understand. You may be talking about another project ? => https://github.com/openboard-team/openboard
