### ISSUE TITLE
Ability to disable clipboard manager

### ISSUE THREAD

**Issue by pinckpockett** [OpenBoard-org/OpenBoard#583]
edited: wrong project

**Comment by letsfindaway** [comment]
Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.

**Comment by pinckpockett** [comment]
> Wrong project. Your issue is most probably for https://github.com/dslul/openboard and not for this project. Please close it here and reopen it at the correct place.

Sorry about that I will do that now.
