### ISSUE TITLE
How to build Dev Repository on Windows

### ISSUE THREAD

**Issue by prabaljainn** [OpenBoard-org/OpenBoard#585]
I want to export my PDF with Dark Background as it is available on dev only, I don't know how to **build** this dev repo on **windows**

**Comment by kaamui** [comment]
Hi,

there's a wiki to help =>https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows-10

**Comment by prabaljainn** [comment]
> Hi,
> 
> there's a wiki to help =>https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows-10

Thank you Sir for your warm replies, i am also a programmer and want to contribute for openboard! But don't know how to start! 🥺☹️

Can you enlighten me for the same?

Plus when is the next release coming?

**Comment by kaamui** [comment]
next release should be available before June. 

Start with the wiki, and when your environment is set, start with making things you would like to see in OpenBoard.  If you think it could be useful for everyone, submit a pull request with your work. 

I can't promise it will be added (I work for Geneva schools and decisions are mostly made by the department of public education), but if it is minimalist (your pull request contain only the minimal code needed to purpose), deactivable and deactivated by default, it is more likely to be added (I can argue that it will not modify the behavior of the software in a way we don't want). You can look at recent pull requests like #465 or #497 to see how it works.

But be aware that even if OpenBoard is in active development, development is really slow and it can take a while before I look at a pull request.

Good luck !
