### ISSUE TITLE
quazip library path incorrect on Debian stable

### ISSUE THREAD

**Issue by habruening** [OpenBoard-org/OpenBoard#588]
On my Debian stable the quazip path is not /usr/include/quazip but /usr/include/quazip5. When I correct this in OpenBoard.pro, it builds well.

**Comment by letsfindaway** [comment]
Note that this is already addressed on the `dev` branch with commit https://github.com/OpenBoard-org/OpenBoard/commit/c8795b24d08547d69145e82a0999ea275e6cb2fe.

**Comment by habruening** [comment]
Perfect, thanks!
