### ISSUE TITLE
Point after a line

### ISSUE THREAD

**Issue by JosephA312003** [OpenBoard-org/OpenBoard#589]
Sometimes when I write with the pencil, appears some points after I leave the tablet. Most of the times appears in the initial part of the line or draw that I made. I try to change all the configurations, but it's still there. I use winfdows 11. This problem doesn't appear on other programs.

**Comment by letsfindaway** [comment]
This was already reported. See #537 for discussion and also for a solution for that problem.

**Comment by JosephA312003** [comment]
Thanks for the info. But I can't do it. I gone to the option of target and append the command "-platform windows:nowmpointer" and said me that it's not correct or that it's invalid. I tried to put on comment but said something similar. On the other hand, I tried the option of deselect "windows ink" on the wacon center; but in this case the sensibility of the draw doesn't work.
