### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by takadahugo** [OpenBoard-org/OpenBoard#595]
Hi, 
Is anybody else having issues with the integrated web browser? I can't use sites like gmail, jamboard. Openboard just crashes every time I try to access them.

Regards

OS: OS X 10.14.6
Openboard: 1.6.1

**Comment by letsfindaway** [comment]
This is a known issue  and already reported, e.g. in #435 and #473. 

OpenBoard 1.6.1 and also the upcoming 1.6.2 are using `QWebKit` for the embedded web browser, which is however outdated and no longer actively maintained. Version 1.7.0 of OpenBoard will fix this by switching to a `QWebEngine` based browser, which basically provides a Chrome web engine. See also #562 for release planning.

Version 1.7.0 is already under development in the `1.7-dev` branch of this project. If you're able to build this branch from sources you could already try it out.

**Comment by takadahugo** [comment]
Thanks for your promptly replay @letsfindaway 
I would but I couldnt find a tutorial to build on Mac OS so far, is there one available?
Regards

**Comment by Messiaslogia** [comment]
Does this also apply to Win10?
I followed the steps above and managed to install it, but when running the program it does not open.

**Comment by letsfindaway** [comment]
> Does this also apply to Win10? I followed the steps above and managed to install it, but when running the program it does not open.

In such cases it often helps to start the program from the Cmd Terminal. Here you might get some error messages, which could be helpful.
