### ISSUE TITLE
Unable to move Open Board to only the 2nd monitor

### ISSUE THREAD

**Issue by rajatjain345** [OpenBoard-org/OpenBoard#596]
Hello,

Windows 10 professional running on Lenovo Thinkpad.

**Issue 1:** Unable to drag or move the open board window to the 2nd monitor.

**Issue 2:** While using open board in multiscreen mode with one laptop display and one additional monitor, on minimizing open board in the primary screen, open board window does not minimize in the secondary monitor

Best Regards
RAJAT JAIN

**Comment by letsfindaway** [comment]
Hi Rajat,

for **Issue 1**: Have you tried to configure OpenBoard as follows:

- In the Preferences, enable switching of Control and Display screen
- In the main menu, disable multi-monitor mode

This should open OpenBoard on the secondary screen.

For **Issue 2:** I think this is by intend. Just consider presenting at a class. The teacher now wants to prepare something using other applications, e.g. for later work in Desktop mode or whatever. Currently minimizing does not affect the Display screen, so the students still see the previous content. If these windows would also be minimized, then the students would see whatever the content of these screens are, which is probably not what the teacher wants.

I think many people do not want to change the current behavior. What is your use case that you would prefer to minimize all other screens, too?
