### ISSUE TITLE
Installation on Windows 10 fails because Visual C++ is too new

### ISSUE THREAD

**Issue by FvD** [OpenBoard-org/OpenBoard#60]
I get the following error when I try to install version 1.3.3. on Windows 10. On close the installation seems to have proceeded without issue! Perhaps this warning is not needed and can be avoided.

![openboard-c version](https://cloud.githubusercontent.com/assets/2441145/18459532/953e2aec-7927-11e6-8b46-7b3a9e8c60a5.png)

**Comment by freeheel3r** [comment]
Hi,
You should be able to ignore this error without any problem. The fact that this dialog appears is an issue; however this has just been solved, and version 1.3.4 will include the fix (along with several other bug fixes).
I expect we'll be able to publish it by the end of the week.

Thanks for reporting the error though!

**Comment by FvD** [comment]
Thank you guys for keeping the Open Sankoré project alive and well. I am very happy to have found OpenBoard.
