### ISSUE TITLE
Sensitivity doesn't work properly on Huion.

### ISSUE THREAD

**Issue by HatWearingMann** [OpenBoard-org/OpenBoard#602]
I am using a HUION 610 PRO, and when I enable Windows Ink in the tablet's drivers, there are full sized dots appearing at the ends of smaller lines. Pressure doesn't work without Windows Ink in this program. 

![obraz](https://user-images.githubusercontent.com/79970290/169265961-3dc903b6-81c3-4e88-8b42-d92ed241683d.png)

When I undo (CTRL+Z) those smaller strokes, the dots at the end get removed first, and I have to undo again to get rid of the small lines. It seems like the program is registering a second, fully pressed, input right after the pen is lifted.

![obraz](https://user-images.githubusercontent.com/79970290/169266007-ef04793f-13e7-4ac4-b104-3047c635f6b5.png)

Also, disabling pressure size in the settings causes a minimal distance for the line to be registered, if it's too short, only a dot will appear. This can be fixed by disabling Windows in the driver's settings.

![obraz](https://user-images.githubusercontent.com/79970290/169268385-f86bd121-045e-4674-bc9a-d1950b384c5d.png)

**Comment by letsfindaway** [comment]
See #537 for the dots issue, which is related to the Windows Tablet driver. That issue also shows you how to avoid this.

**Comment by aditya2305** [comment]
I added '-platform windows:nowmpointer' after the shortcut properties target, but the issue remains. Any suggestions?
