### ISSUE TITLE
Code execution cannot continue because WMVCore.DLL was not found. To fix this, try reinstalling the program.

### ISSUE THREAD

**Issue by FabioTambu** [OpenBoard-org/OpenBoard#607]
Hello everyone,
when I try to start the OpenBoard program I get this warning "Code execution cannot continue because WMVCore.DLL was not found. To fix this, try reinstalling the program.".

![temp](https://user-images.githubusercontent.com/66631258/169849644-dbf375aa-d5be-4fc7-88da-925be28a7d0f.PNG)

I tried to reinstall the program and has look for how to fix it online but I couldn't fix it, could someone help me?

**Comment by kaamui** [comment]
Hi,

I found [https://answers.microsoft.com/en-us/windows/forum/all/wmvcoredll-is-missing-windows-10/73423cb8-73a5-47eb-8479-e0d1974e977a](this). Try to install [https://www.microsoft.com/en-us/download/details.aspx?id=48231](Media feature package) to see if it fixes your issue

**Comment by FabioTambu** [comment]
Hi, I have the Windows 10 Pro N version, I tried to install and the Media Feature Pack (both files that were there), after this i restarted the pc and reinstalled OpenBoard but the problem persists

**Comment by kaamui** [comment]
Please try to locate the WVMCore.DLL that was installed (probably in `C:\Windows\System32`) and copy it to `C:\Program Files\OpenBoard` folder

**Comment by FabioTambu** [comment]
I saw problem # 243 I tried to uninstall and reinstall Microsft Visual C ++ 2015 but it didn't fix

**Comment by kaamui** [comment]
I'm out of ideas. Did you try with the 32bit dll (in `System32` folder) ?
