### ISSUE TITLE
Text boxes & shapes

### ISSUE THREAD

**Issue by takadahugo** [OpenBoard-org/OpenBoard#609]
Hi 
Is it possible to write text directly inside the shapes or allow to set borders for text boxes?

Regards
Os: OS X
openboard 1.6.1

**Comment by kaamui** [comment]
Hi,

No it's not possible. The simplest way I see to do it in the actual version would be to drop the shape, and write text (using a text box) above it. Note that you also can change the z-index of a selected object.
