### ISSUE TITLE
Changed code signature in MacOS version 1.6.2?

### ISSUE THREAD

**Issue by suschizu** [OpenBoard-org/OpenBoard#616]
Hello - I've received a warning that the code signature has changed between version 1.6.1 and 1.6.2

EXPECTED 
Christian  Oienhart (32B6LPAVCU)
but FOUND 
DIP - Etat de Geneve (A6HNXYT969)

can you confirm this change?

Thanks!

**Comment by kaamui** [comment]
Hi,

yep, this is what is expected. 

Thank you for your feedback. Hope you'll enjoy the new version.
