### ISSUE TITLE
Can't capture screen

### ISSUE THREAD

**Issue by takadahugo** [OpenBoard-org/OpenBoard#619]
Hi,
I cannot capture the screen when having a PDF document, it doesn't matter what program I use to open the PDF document; it would just hide the document and show the desktop or any other program behind it. Also, if I have a web browser with multiple taps it won't let me capture the current tab, it always shows the web browser tab in the main display (I have two displays). 

Regards

Hugo

OS: Mac OS 10.14.6
Openboard 1.6.2

**Comment by kaamui** [comment]
Hi,

Please try to remove then re-add OpenBoard to the list of authorized apps to record screen (Security and privacy -> Privacy Tab)

<img width="490" alt="Capture d’écran 2022-06-07 à 12 05 31" src="https://user-images.githubusercontent.com/11720903/172354502-a262c801-64f5-47bc-91dd-1927bbe87e8d.png">

Tell me if it helped.

**Comment by takadahugo** [comment]
> Hi,
> 
> Please try to remove then re-add OpenBoard to the list of authorized apps to record screen (Security and privacy -> Privacy Tab)
> 
> <img alt="Capture d’écran 2022-06-07 à 12 05 31" width="490" src="https://user-images.githubusercontent.com/11720903/172354502-a262c801-64f5-47bc-91dd-1927bbe87e8d.png">
> 
> Tell me if it helped.

Hi,
It didnt work. Anyway I'm not trying to record the screen. Im trying to use the scissors tool to capture part of the screen as image and paste it on my openboard page. Trouble is eveytime I do it it would show what it is on the main display and not on the second display. I am attaching images of what happens. A workaround I'm using now is to put everything on the main display every time I want to capture anything.

[070622 0756.pdf](https://github.com/OpenBoard-org/OpenBoard/files/8852624/070622.0756.pdf)

[070622 0756.pdf](https://github.com/OpenBoard-org/OpenBoard/files/8852609/070622.0756.pdf)

**Comment by kaamui** [comment]
OK now I get it. 

The screenshot taken (the one you see on your main display) should appear on the secondary display. It is done to make sure "not-in-openboard" content is captured too. Then, you use the lasso to capture a portion of it. 

Expect from the screenshot appearing on the wrong screen, it is the expected behavior.

**Comment by htakada** [comment]
Can that be changed? Coz I use two screens , in one screen I have things that I keep for myself and on the second display I put everything I need for my online lessons ( openboard, pdf, websites to show , etc).
Thanks
