### ISSUE TITLE
[FeatureRequest] Add option to configure where documents are stored

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#623]
Hello everyone and the (wonderful) OpenBoard team !

I'm a teacher and I like to plan my lessons at home. I'm on a different computer than in my classroom.
So I would like to be able to sync my OpenBoard documents through the 2 computers, with a cloud system like Dropbox or NextCloud.

For that, I would need to be able to configure where the OpenBoard Documents are stored... Would it be possible ?

And let's be crazy, why not let us configure too where Videos, Pictures and Audio are stored too ? It would be a very nice adding to OpenBoard, I think :)

Maybe in 1.7.0 ? 
I let you tell me what you think about it...

**Comment by kaamui** [comment]
Hi,

You already can => https://github.com/OpenBoard-org/OpenBoard/wiki/Settings#appdatadirectory

I'm not sure how it is supposed to work though. I never found time to closely look at it, and I think some users reported that it was not working. I know it works because we use it internally, but maybe there is some specific cases where it won't work, idk

Tell me if you encounter any issue.

**Comment by SeeDborg** [comment]
Wow, nice, I'll try it.
Although it seems like a solution for high end users.

Maybe, be able to configurate it directly in the app parameters would be simpler for regular users...

**Comment by kaamui** [comment]
Would be nice indeed. I don't think it's going to happen soon though. These parameters aren't even included in the default configuration file as we don't want our users to play too much with them. Changing this parameter implies you won't find your previous documents anymore if you didn't move them when changing their location in the settings. You may believe that all your  documents are lost where they just not mentioned anymore in OpenBoard, but still physically in the disk

**Comment by SeeDborg** [comment]
Wouldn't it be possible to move all documents to the new folder if the user changes it ? 
I think it's what Windows does when you change the location of the pictures or music folder, it asks you if you want to move your files to the new location you gave.

**Comment by kaamui** [comment]
It would be possible but again, we don't want these parameters to be easily changed by our users. I think it is enough that the possibility is given using the configuration file.

**Comment by SeeDborg** [comment]
After reflexion, I think you are right... Thanks for the answers !
