### ISSUE TITLE
After installing 1.6.2 all custom apps are gone !

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#625]
Hi,
I installed OpenBoard 1.6.2 on top of an old 1.6.1.
I had several custom apps installed from http://fanch.le.cleach.free.fr/ and they completely disappeared after the installation...
For me it's not a problem, I reinstalled them pretty quickly, but I manage a large group of teachers, made them install OpenBoard 1.6.1 with the custom apps too, and I'm sure some of them will be panicking when they update to 1.6.2 !

Luckily for me, the update seems to be on Github only for now (no pop-up to update within Openboard). Before you do that, would it be possible to have a 1.6.2a which does not destroy the custom apps, please ?
I think you would just have to keep what's inside the library\applications folder...

Many thanks if you can do that !

**Comment by kaamui** [comment]
Thanks for reporting it. I'll integrate it to our internal bug tracker.

Sadly, the deployment process is too advanced to integrate anything new in the final release. I think it's a major issue though, so I'll try to make it a priority during the next "bugs evaluation session"

**Comment by SeeDborg** [comment]
Argh, it will be much trouble for me and many teachers... Thanks to think about it though :(

**Comment by kaamui** [comment]
Are you able to provide to your teacher a copy of the folder or a script + the folder that would copy the custom apps to the right place after the installation ?

**Comment by SeeDborg** [comment]
Indeed, I copied the new apps in /library/applications/
I can always try to send them a script and the folder but it's clearly not the best solution for me.

**Comment by kaamui** [comment]
> Indeed, I copied the new apps in /library/applications/ I can always try to send them a script and the folder but it's clearly not the best solution for me.

My first answer (before the "Edit" part)is no longer relevant, just copy your apps in the indicated location (interactive content). I also tested to place them directly on it without any intermediate folder and it appears to be working.
