### ISSUE TITLE
Problem after removing the ruler from the board

### ISSUE THREAD

**Issue by vivianecs** [OpenBoard-org/OpenBoard#628]
I believe update 1.6.2 have introduced a bug: after making a stroke with the ruler and then removing the ruler from the board, it is no longer possible to write freely with ink or marker. Wherever you scribble, the stroke always comes out in the original position of the stroke made with the ruler (a straight line). This does not occur if the ruler is kept in the board. (OS Win 11; second screen Galaxy Tab S7 with SPen).

**Comment by letsfindaway** [comment]
I can reproduce the problem also on Linux. Will try to look into it soon.

**Comment by kaamui** [comment]
@vivianecs thank you for reporting this critical bug ! And thank you @letsfindaway for your reactivity.
