### ISSUE TITLE
Integrated web browser

### ISSUE THREAD

**Issue by htakada** [OpenBoard-org/OpenBoard#631]
Hi, just downloaded new version, but when I try the integrated web browser it shows the desktop and opens my default browser with this link https://eduge.ch/

Is this a new feature or a bug? 

Regards

os: Mac OS 10.13
openboard: 1.6.3

**Comment by kaamui** [comment]
Hi,

It's a mistake. I uploaded the wrong version. Please use 1.6.2 instead, and I'll upload the good 1.6.3 version next monday
