### ISSUE TITLE
Open board toolbar freezes on desktop?

### ISSUE THREAD

**Issue by iwasherefirst2** [OpenBoard-org/OpenBoard#636]
I can start open board and use it. However, when I switch to desktop, the left nav is not responsive anymore:

![image](https://user-images.githubusercontent.com/1765602/174402007-865b9cf2-4b36-4cd6-9c87-7d12ffc7100b.png)
![image](https://user-images.githubusercontent.com/1765602/174402218-a2bd7503-0596-4898-a638-d1cfa481bbf8.png)

I had Ubuntu 18.04, then I updated to Ubuntu 20.04 and installed via default "Ubuntu Software" and via .deb file from https://openboard.ch/download.de.html 

Issue happened on both Ubuntu versions and for both installations.

Any idea how to fix?

**Comment by letsfindaway** [comment]
I think you hit the Qt bug described in the [Release Notes](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.3) below "Known bugs" / "Linux".

The current workaround is to set the Gnome toolbar to the bottom position so that it does not overlap the desktop palette.

**Comment by faheemkhuhawar** [comment]
Facing the same issue on ubuntu 20.04 with version 1.6.4.
