### ISSUE TITLE
[Windows 10] Laser pointer: red dot not completely visible if you use "Show Openboard" and move the laser pointer

### ISSUE THREAD

**Issue by ElsAr4e** [OpenBoard-org/OpenBoard#644]
Version: 1.6.2 AND 1.6.3
OS: Windows 10 (64-bit)

If you use Openboard and the whiteboard and select the laser pointer you can view on your screen that a part of the laser pointer is missing as soon as you move the laser pointer. (I think I had similar issues regarding the icon of the drawing pen).

However - if you use "show desktop" you don't have this issue. - Only if you use the whiteboard of OpenBoard.

Example:
![Lasermissing](https://user-images.githubusercontent.com/98536104/175772886-e96bf47d-e671-43b9-8dce-a0cffb898b26.png)

(If you use OBS-Studio to record OpenBoard you don't view this issue (the laser pointer is displayed correctly) and if take a screenshot you also can't capture this issue - So I had to artificially remove a part of the image - so you can understand my issue)

**Comment by letsfindaway** [comment]
From your description this very much looks like a graphics driver problem, especially that it does not happen with OBS or screenshots.

- Can you reproduce the issue on another computer with different hardware?
- Could you check whether there is an update available for your graphics driver?

OpenBoard definitely draws a circle for the laser pointer. So the problem is likely between OpenBoard and your monitor. The graphics driver is the most obvious candidate here.

**Comment by ElsAr4e** [comment]
I can try to install another version of OpenBoard.  (Using this computer; Windows 10; 64 bit)

But I'm afraid I can't reproduce on other devices since I am using Windows 10 32bit; (the last version that worked was Openboard 1.5.4 (I think) ?) I don't have such issues using another pc Windows 10 32 bit and OpenBoard 1.5.4.

I can view the (whole) circle for the laser pointer without a problem as long as I don't move the laser pointer using the whiteboard.

But as soon as I move it parts of the circle are gone - if I use the whiteboard. If I use the "show desktop" option I don't get this issue (Windows 10; 64 bit, Openboard 1.6.3 and 1.6.2)

**Comment by ElsAr4e** [comment]
I just installed OpenBoard 1.5.4.   (Windows 10; 64bit)
Same issue: 
However -as before - only if I use the whiteboard. If I use the laser pointer on desktop screen I don't have any issues.

So it's probably due to the graphics driver?

I am using GeForce Game Ready Driver. Version: 516.40 (Url: https://www.nvidia.com/download/driverResults.aspx/190348/en-us/ )
