### ISSUE TITLE
Bad download link

### ISSUE THREAD

**Issue by JasonNVSD** [OpenBoard-org/OpenBoard#655]
The Windows download link at http://openboard.org/download.en.html is 404.

Bad link: https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/OpenBoard_Installer_1.6.3.exe
Correct link: https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.3/OpenBoard_Installer_1.6.3.exe

**Comment by kaamui** [comment]
Thank you ! 

It is now fixed.
