### ISSUE TITLE
[Question] OpenBoard version that works with Windows 10 32-bit

### ISSUE THREAD

**Issue by ElsAr4e** [OpenBoard-org/OpenBoard#656]
I was not able to launch OpenBoard Version 1.6.x. if I use a Windows 10 32-bit tablet.

The last version that worked was 1.5.4. (similar Windows 7? https://github.com/OpenBoard-org/OpenBoard/issues/544 )

Tablet:
Windows 10 32-bit (Intel(R)_Atom(TM)_CPU__Z3735F)
2GB RAM

Is this a special issue because of OpenBoard or Windows 10 32-bit?

Are there any plans to support 32-bit in the near future (again)?

**Comment by kaamui** [comment]
Hi,

sorry for the late reply. Nope, return of 32-bit support is not planned, sorry.
