### ISSUE TITLE
Bad download link in the English language Download page

### ISSUE THREAD

**Issue by MirajMjn** [OpenBoard-org/OpenBoard#660]
The download link is wrong for the [English version of the download page](https://openboard.org/download.en.html)

For the English version of the page, it redirects to : 
https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.1/OpenBoard_Installer_1.6.3.exe ( notice the v1.6.1 )

For other language version of the page, it redirects to : 
https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.6.3/OpenBoard_Installer_1.6.3.exe ( correct one )

**Comment by letsfindaway** [comment]
This has already been reported in #655.

Thank you for pointing out the differences between language versions of that page.

**Comment by MirajMjn** [comment]
> 

apologies, I did see that and wanted to add the language details to the one previously reported but I couldn't figure out how to do that.
