### ISSUE TITLE
failed to start encoder 

### ISSUE THREAD

**Issue by Sarthak77tiwari** [OpenBoard-org/OpenBoard#663]
I am not able to record audio when I turn on screen recording without audio it works but when I start with audio it show that failed to start encoder  and recording not started

**Comment by letsfindaway** [comment]
Can you provide some more information about your environment?

- What version of OpenBoard are you using?
- What operating system are you using?
- Where did you download OpenBoard? From the official download page or are you using some community build?
- How exactly does the error message look like? Could you provide a screenshot?
- What audio input device are you using?
- How does the podcast configuration dialog look like? Could you provide a screenshot?
- Was this working before for you with another version of OpenBoard / on another computer / with another OS version ...
