### ISSUE TITLE
double % in the main keyboard panel and no _

### ISSUE THREAD

**Issue by lucamp** [OpenBoard-org/OpenBoard#666]
The main keyboard panel has two %, one if you long press "q" and the other at "f".
This happen both in English and Italian, at least.

Meanwhile, there is no "_" in the main pane; this simbol is quite useful if you write in markdown.

I suggest to use "_" when long pressing "f" (as gboard does)

![Screenshot_2022-09-16-18-36-13-00](https://user-images.githubusercontent.com/15078341/190688935-bb588ea8-fe03-4f62-b08f-f60713c35d96.jpg)

Thanks for the app
Luca

**Comment by letsfindaway** [comment]
I think you hit the wrong project. Your issue might be related to https://github.com/openboard-team/openboard.

Please close this issue here and reopen in at the right place.
