### ISSUE TITLE
In multiscreen mode, the second screen only shows the Board when switching to Web or Desktop

### ISSUE THREAD

**Issue by frohro** [OpenBoard-org/OpenBoard#667]
I'm using Ubuntu.  I wanted the second screen to show my desktop or web browser when I switch from Board to Desktop or Web.  Unfortunately, it just continues displaying the annotated document.  The only way I have figured out to allow viewers of the second screen is to close the window in the doc and drag another browser to the second screen, but then I cannot get the window back to show my annotations as the lecture continues.

**Comment by letsfindaway** [comment]
Have you seen this icon on the toolbar:
![grafik](https://user-images.githubusercontent.com/35591413/190889330-5bdfa71c-d74d-440b-94fc-5fc843e3d6df.png)
When the eye is closed, the board is still shown on the second screen. When you click on it, the eye will be open and the web browser or desktop is mirrored.
![grafik](https://user-images.githubusercontent.com/35591413/190889320-06c3f20d-f070-49fc-a309-5e1dd2b76a6c.png)
The idea is that the teacher can prepare a web site without showing that process to the students. When they are ready navigating to the proper place, they click the eye to enable mirroring.
If you want to enable mirroring by default, then you can do that in the settings (here the German version):
![grafik](https://user-images.githubusercontent.com/35591413/190889406-457e30c0-db99-49f1-a266-a6fc043f0be6.png)

**Comment by frohro** [comment]
Ah!  Thank you!  This is the tip I needed.
