### ISSUE TITLE
Missing file version in Openboard.exe Windows Binaries

### ISSUE THREAD

**Issue by hict-nvdael** [OpenBoard-org/OpenBoard#674]
Problem:
I want to deploy Openboard and therefore i need version information. The most simple way is to check the file versions.
But I noticed that Openboard doesn't add file versions in any executable.

Is it possible to add the missing information?
This is normally default in Windows executables.

**Comment by kaamui** [comment]
Hi,

I'm not sure to understand. When I install it on Windows, and go to "Programs" I can see the version of the app (1.6.4.240). Can you be more specific of what kind of information is missing in the binary ?
