### ISSUE TITLE
Export with WebWidget failed (V1.6.3 Windows)

### ISSUE THREAD

**Issue by obook** [OpenBoard-org/OpenBoard#675]
Hello,
When I export document in PDF, WebWidgets application (As GoogleMap or OpenStreetMap) presents an QTNetwork Error 301 : "Failed to load URL c:/Program Files/OpenBoard/etc/freezedWidgetWrapper.html." Also, the file freezedWidgetWrapper.html exists.
Any idea why ?

Regards,
Olivier

![Capture d’écran 2022-09-29 194457](https://user-images.githubusercontent.com/460632/193105659-9d0a5579-c6c7-4c3d-9aa1-61846f171181.png)

**Comment by letsfindaway** [comment]
Even if I'm not working on Windows I can confirm your problem. See my PR linked above.

**Comment by obook** [comment]
This bug is same with other Web based widgets, as GoogleMap, OpenStreetMap, etc ;(

**Comment by obook** [comment]
> Even if I'm not working on Windows I can confirm your problem. See my PR linked above.
> 
> Note however that even with this fix applied you just get a blank area in the exported PDF instead of the widget content. The reason is that OpenBoard activates widgets only on the currently active board page and "freezes" them otherwise to reduce memory consumption. It would probably be a good idea to replace them with a screenshot, but this is then a feature request. I would however raise this request for the upcoming 1.7.x releases of OpenBoard.

Note that it is the same problem under Linux ; the PDF contains black frames instead of widgets.
Regards.
