### ISSUE TITLE
Editable text boxes are too small (patch included)

### ISSUE THREAD

**Issue by GavinSmith0123** [OpenBoard-org/OpenBoard#682]
I find the text box created by the text tool far too small. It should be larger by default or allow the user to specify the size by clicking and dragging.

The following change to   `board/UBBoardView.cpp (UBBoardView::mouseReleaseEvent) <UBStylusTool::Text>` means that if the user clicks and drags to create a text box, the width will be as specified. If they have not done this, the box will be larger by default.

````
--- a/src/board/UBBoardView.cpp
+++ b/src/board/UBBoardView.cpp
@@ -1348,7 +1348,10 @@ void UBBoardView::mouseReleaseEvent (QMouseEvent *event)
 
                 textItem->setTextInteractionFlags(Qt::TextEditorInteraction);
                 textItem->setSelected (true);
-                textItem->setTextWidth(0);
+                if (rubberRect.width() > 100)
+                    textItem->setTextWidth(rubberRect.width());
+                else
+                    textItem->setTextWidth(1200);
                 textItem->setFocus();
             }
         }

````

This is an improvement for me, although it would be better if the 1200 was not hard coded here and depended on the current zoom level and area of the scene that was currently displayed.

**Comment by sebojolais** [comment]
I have the same experience. I spent lot of time to increase the size of the TextItem each time I need the Write text.
I improved the proposed patch in 2 ways:
- the user can specify the width of the text more accurately by dragging
- else the width is set to fill the screen from the mouse point to the right border minus 5%. It works even if the zoom factor != 1.
The patch is [here](https://github.com/OpenBoard-org/OpenBoard/pull/688);

It is an improvement for me but the best behavior should be discussed.

**Comment by GavinSmith0123** [comment]
Here is a video of what happens in SMART Notebook 11. You see that the text boxes expand as required as more text is entered into the boxes, until the boxes reach the right sight of the page, when the width becomes fixed. It's possible that this may be hard to achieve with Qt in OpenBoard, and if so, the patch from @sebojolais above is a big improvement in any case.

https://user-images.githubusercontent.com/3398468/197159220-15f6c8e3-a50d-476f-b8dc-bc41e195443e.mp4

**Comment by sebojolais** [comment]
@GavinSmith0123 It seems great. And it should be possible in Qt. 

The default behavior of a QGraphicsTextItem is to expand with the text. Have a look at the [setTextWitdth ref](https://doc.qt.io/qt-6/qgraphicstextitem.html#setTextWidth) with width = -1.
But the width locking mechanism when the text reach the right border is not implemented. But it should be also possible.
This [Qt example](https://doc.qt.io/qt-6/qtwidgets-graphicsview-diagramscene-example.html) illustrates the default behavior.

Before trying to implement the Smart Notebook11 behaviour, a good question is why OpenBoard sources had preferred set text width with 0 instead of -1 ?
Maybe there is a good reason, but I do not see it.

**Comment by GavinSmith0123** [comment]
I found that the text width was fixed immediately even with a text width of `-1`, because `UBGraphicsItem` listened on the `documentSizeChanged` signal from the `QTextDocument`, then in `UBGraphicsTextItem::documentSizeChanged` and `UBGraphicsTextItem::setTextWidth`, `setTextWidth` is called again on the `QGraphicsTextItem` which fixes it rather than keeping it as -1.

I believe alternative code would be needed in `UBGraphicsTextItem::resize` to resize, instead of calling `setTextWidth`. It would have to resize the frame around the text box too. I couldn't make the code work to do this in the time I spent on it - I suspect there may be problems with cycles of signals in that resizing the frame should resize the text box, and vice versa. ` UBGraphicsDelegateFrame::resizeDelegate` handles some of the resizing but this is only used in response to mouse input.

**Comment by sebojolais** [comment]
Lol, you demonstrate that it is never as easy as we hope.
Nevertheless kaamui closed the PR because the TextItem will be refactored and it will operate in a better way. We have to wait the new implementation.

**Comment by GavinSmith0123** [comment]
@sebojolais Here is a change that works with your change above and narrows the text box after the text box is no longer selected so that it is only as wide as needed.  This makes it easier to select and move items in the scene without oversized text boxes getting in the way.

````
--- a/src/domain/UBGraphicsTextItemDelegate.cpp
+++ b/src/domain/UBGraphicsTextItemDelegate.cpp
@@ -827,6 +827,13 @@ QVariant UBGraphicsTextItemDelegate::itemChange(QGraphicsItem::GraphicsItemChang
                 saveTextCursorFormats();
             }
         }
+        if (!value.toBool()) {
+            // text item is no longer selected.  adjust the size so
+            // it doesn't get in the way when selecting other items
+
+            delegated()->setTextWidth(
+                delegated()->document()->idealWidth());
+        }
     }
 
     return UBGraphicsItemDelegate::itemChange(change, value);
````

**Comment by sebojolais** [comment]
Nice, thank you!

**Comment by kaamui** [comment]
There is no 1.6.5 planned sorry ^^

As I already replied in another issue, we are aware of this bad behavior and will rework it when possible. Just not the priority at this time.

**Comment by sebojolais** [comment]
It seems that the Editable Text box is just reimplemented by @kaamui in the [dev branch](https://github.com/OpenBoard-org/OpenBoard/commits/dev) since this commit : [2ff8f29ce8a1227541d382e58a06dd591632d811](https://github.com/OpenBoard-org/OpenBoard/commit/2ff8f29ce8a1227541d382e58a06dd591632d811)
It works fine. My experience is better. Thank you.

**Comment by kaamui** [comment]
Thank **you** ! I implemented your idea (among other things) and I think it is of great help. I just tweaked the adapted width to something that looked like to me more understandable easily by the user, but I like the result. Glad you like it too.
