### ISSUE TITLE
Documentation for creating JavaScript based Widgets?

### ISSUE THREAD

**Issue by kortenkamp** [OpenBoard-org/OpenBoard#684]
I would like to create some new widgets that are based on JavaScript. I had a look at the existing widgets and probably can create something via copy/paste, but I wonder whether there is a better approach. I could not find documentation on creating widgets for OpenBoard / OpenSankoré / Uniboard – can anybody help?

**Comment by kortenkamp** [comment]
So, I followed the copy/paste approach so far, but now I have difficulties in debugging – is there any way to get some debugging output from widgets? Or can anybody tell me what JavaScript engine is used? Sorry for asking stupid questions…

**Comment by letsfindaway** [comment]
Unfortunately there is not much documentation about this, so copy/paste is not bad! But I want to give you some additional hints.

Basically, a widget is just a web page. The `config.xml` describes some of the properties. The most important ones are:

- `widget/id`: Choose a **unique** id.
- `widget/width`, `widget/height`: The initial size of the widget.
- `widget/content`: points to the main HTMl file.

Widgets can be as simple as the GoogleMaps widget, consisting of just a single HTML page. If you plan to localize the widget, take a look at some of the interactivities.

There is a JavaScript API by which the widgets can interoperate with the application. I have documented this API on my Wiki pages at https://github.com/letsfindaway/OpenBoard/wiki/Widget-API, **BUT**, this documentation is for the upcoming version 1.7 of OpenBoard. The functions are the same for 1.6.x, but there is one important difference: While function invocations like `window.sankore.preference` are synchronous calls for 1.6.x, they will be asynchronous for 1.7.

In fact if you compare existing widgets on the `master` branch to the `dev` branch then you will see that nearly all of them had to be changed to adapt to this behavioral change of the API.

**Comment by letsfindaway** [comment]
> So, I followed the copy/paste approach so far, but now I have difficulties in debugging – is there any way to get some debugging output from widgets? Or can anybody tell me what JavaScript engine is used? Sorry for asking stupid questions…

The JS engine changes from 1,6.x to 1.7.x. In 1.6.x it is WebKit, while in 1.7.x it will be QWebEngine, which is in fact Chromium. And also debugging will be much easier wit 1.7.x, because you will have the full developer tools of Chromium available and can single step, breakpoint etc as you like.

**Comment by kortenkamp** [comment]
OK, great – sounds like I just should wait for 1.7.x, because I suspect that this will fix the issues I see with the current widget I am implementing (it is based on [CindyJS](https://cindjs.org), and version 0.8 of CindyJS refuses to work, while version 0.7 seems to be fine.

Is there a timeline for the 1.7.x release?

**Comment by letsfindaway** [comment]
> OK, great – sounds like I just should wait for 1.7.x, because I suspect that this will fix the issues I see with the current widget I am implementing (it is based on [CindyJS](https://cindjs.org), and version 0.8 of CindyJS refuses to work, while version 0.7 seems to be fine.
> 
> Is there a timeline for the 1.7.x release?

Not really, but it will be 2023. What platform are you working on? I can provide preview builds for Linux.

**Comment by kortenkamp** [comment]
macOS… so I am probably on my own. I did not find any hints on compiling from source on macOS, but I might try it following the Linux instructions.

I still wonder why the latest CindyJS release won't work, as it works in all browsers I tested so far, including Safari.

**Comment by letsfindaway** [comment]
> I still wonder why the latest CindyJS release won't work, as it works in all browsers I tested so far, including Safari.

The WebKit version used as base for the Qt QWebKit classes is about 10 years old, probably a little bit less, but it is old. You don't have to wonder why reasonably modern JS code does not work.

**Comment by letsfindaway** [comment]
OpenBoard 1.7.0 was released quite some time ago. Also the Wiki here on GitHub contains useful documentation on how to create a web widget.
