### ISSUE TITLE
Testing translations and pull request

### ISSUE THREAD

**Issue by EmPeWe** [OpenBoard-org/OpenBoard#69]
Hi guys,

i've installed OpenBoard on Ubuntu 16.04 LTS and noticed some glitched with the german translations. So I checked out from gtihub and started to improve the translation source file. Is there a chance to test them without compilation of the whole project? I want to test my changes before I make the pull request. I also searched for an OpenBoard setting to switch the language from within the program, but didn't found it, so I switched the language environment variable to start OpenBoard in different languages. This is no big deal, but is there another option? I started my translations in dev-branch. Will my planned pull request be accepted there or do you prefer another branch? And the last question for the time being, is the type attribute within the translation tags of the source file important and what does the values "unfinished|obsolete|vanished|refurbish" mean? I don't want to compile the source, so I've made my changes with plain vim. I removed a lot of the type attributes, but now I'm uncertain, if I have done things right.

**Comment by freeheel3r** [comment]
Hi!
Thanks for helping out with translations.

>  Is there a chance to test them without compilation of the whole project?

I'm not 100% sure, but I think you can just compile the translation file (using the Qt tool `lrelease`, see [here](http://doc.qt.io/qt-5/linguist-manager.html)) and the application will use the .qm file without requiring to be rebuilt. These translations are located in `/opt/openboard/i18n`.

> I switched the language environment variable to start OpenBoard in different languages. This is no big deal, but is there another option?

For now OpenBoard only uses the system language. It is technically possible to add such an option and in fact there is some code that would allow that, with minor modification. The actual code allowing that was commented out or removed a while back though, apparently it caused problems, but I don't know any more about that. I haven't looked into it much more myself, but this feature would essentially be easy to implement but would require some thorough testing.

> I started my translations in dev-branch. Will my planned pull request be accepted there or do you prefer another branch?

That's perfect, thank you. No commits should ever be made directly to the master branch, except for merges from dev when a release is ready. 

> And the last question for the time being, is the type attribute within the translation tags of the source file important and what does the values "unfinished|obsolete|vanished|refurbish" mean?


I'm actually not quite sure about that. I think the tags are assigned by `lupdate` (which generates the .ts files) or by Qt Linguist (i.e the translator).
This is one of the rare cases where I prefer a WISIWYG editor -- Qt Linguist does a good job of simplifying to translation process, showing you unfinished / missing translations and allowing you for example to leave strings translated but not validated, stuff like that. And it will certainly set the tags correctly.
(Qt Linguist just edits the .ts files, it doesn't compile them itself)

**Comment by EmPeWe** [comment]
Thx for your support. I used lrelease to compile to qm file, moved it to the target path within /opt and successfully checked some (not all) of my translations.

**Comment by freeheel3r** [comment]
Thank you for your contribution! I've merged your changes so they'll be in the next release.
