### ISSUE TITLE
Dependencies not available

### ISSUE THREAD

**Issue by soumyatheman** [OpenBoard-org/OpenBoard#696]
The dependencies of openboard is not available in Ubuntu 22.10 kinetic kudu. Any fix? Will Ubuntu 22.10 be supported?

**Comment by letsfindaway** [comment]
> The dependencies of openboard is not available in Ubuntu 22.10 kinetic kudu. Any fix? Will Ubuntu 22.10 be supported?

Which dependency is missing? It helps answering your question if you give as much information as possible. And I expect that 22.10 will not be officially supported. In the past OpenBoard only supported the LTS versions of Ubuntu, so I assume the next after 22.04 will be 24.04.

**Comment by soumyatheman** [comment]
> > The dependencies of openboard is not available in Ubuntu 22.10 kinetic kudu. Any fix? Will Ubuntu 22.10 be supported?
> 
> Which dependency is missing? It helps answering your question if you give as much information as possible. And I expect that 22.10 will not be officially supported. In the past OpenBoard only supported the LTS versions of Ubuntu, so I assume the next after 22.04 will be 24.04.

All the dependencies are outdated. They have got an update in this new Ubuntu 22.10

**Comment by letsfindaway** [comment]
> All the dependencies are outdated. They have got an update in this new Ubuntu 22.10

You still don't tell me what you did and what error messages you got. So I still have to guess. Just to show you that this is not easy for somebody trying to help you, this is what I'm asking myself:

- Is he trying to **compile** OpenBoard from sources and has difficulties to satisfy one of the compile time dependencies? Which one? 
- Is he just **downloading and installing** OpenBoard and gets error messages during installation? Which version did he download from where? What are the error messages?
- Or was even installation successful and there are problems when **running** OpenBoard? How was OpenBoard started? From the command line or from the icon? What are the error messages?

You see, there are questions over questions for somebody trying to help you. I will therefore insert here a short recommendation on "How to ask good questions".

- Start with a short and concise description of your problem. I think here you already are on the right track, but even your first sentence has room for improvements.
- Give a detailed, step by step instruction on how to reproduce the behavior. This is the most important part, as it helps somebody trying to answer your question to go to the same situation and to analyze the issue. Here I mean actually "step-by-step". When doing something on the console, copy your complete command including the command prompt and the complete output of the command and paste it to your report as a code block. When doing something on the graphical UI provide a screenshot when appropriate. This part is completely missing in your report, and therefore it is difficult to say what actually happened to you.
- Provide information about your environment: Operating system, version of the OS, version of OpenBoard. Here again you did a better job. Just the exact version of OpenBoard is missing, e.g. something like "OpenBoard 1.6.4 for Ubuntu 22.04 downloaded from https://openboard.org/download.en.html".
- If you can think about anything else which might be special in your case, mention it! Every detail helps!

So, back to your problem. After guessing I came to the conclusion that most probably you downloaded OpenBoard for Ubuntu 22.04 and installed it on 22.10 and are now trying to start it. Here some error messages could occur. Is this correct? If yes, you see it would have been much easier for me if you told me that and a good first sentence could have been: 

> After downloading OpenBoard 1.6.4 for Ubuntu 22.04 from the GitHub release page and installing it on Ubuntu 22.10, OpenBoard complains about missing dependencies when starting it from the command line.

If no, what else are you doing?

But let me continue with my guess. In that case my recommendations are:

- **Never** try to install a package compiled for one version of Linux on another version. It is very likely to give trouble and nobody will help you to make this work. It's just a bad idea.
- You might use the **Flatpack** version of OpenBoard. See https://github.com/OpenBoard-org/OpenBoard/wiki/Downloads. A Flatpack brings all necessary dependencies and should run on a wide variety of OS versions.
- You could try to **compile** OpenBoard on your system according to the documentation in the wiki.
- You could wait until I provide a compiled preview version of OpenBoard 1.7.x on the openSUSE Build Service. See https://github.com/letsfindaway/OpenBoard/issues/89 and (also linked from there) https://build.opensuse.org/package/show/home:letsfindaway:experimental/OpenBoard. I will add Ubuntu 22.10 as soon as it is available as a build target in the build service.

Hope this helps!

**Comment by soumyatheman** [comment]
I'm extremely sorry, I was actually out of internet, and also I deleted the deb file of openboard-1.6.4 mistakenly that I downloaded from the github releases, which was for the ubuntu 22.04. After downloading the file I typed,
`sudo dpkg -i openboard_ubuntu_22.04_1.6.4_amd64.deb`
Then it showed me this
```
dpkg: dependency problems prevent configuration of openboard:
 openboard depends on libavformat58 (>= 7:4.4.2); however:
  Package libavformat58 is not installed.
 openboard depends on libavcodec58 (>= 7:4.4) | libavcodec-extra58 (>= 7:4.4); however:
  Package libavcodec58 is not installed.
  Package libavcodec-extra58 is not installed.
 openboard depends on libswresample3 (>= 7:4.4.2); however:
  Package libswresample3 is not installed.
 openboard depends on libswscale5 (>= 7:4.4.2); however:
  Package libswscale5 is not installed.
 openboard depends on libavutil56 (>= 7:4.4.2); however:
  Package libavutil56 is not installed.
 openboard depends on libquazip5-1 (>= 0.9.1); however:
  Package libquazip5-1 is not installed.
 openboard depends on libpoppler118 (>= 22.02.0); however:
  Package libpoppler118 is not installed.
 openboard depends on libqt5webkit5 (>= 5.212.0~); however:
  Package libqt5webkit5 is not installed.
 openboard depends on libqt5multimediawidgets5 (>= 5.15.3); however:
  Package libqt5multimediawidgets5 is not installed.
 openboard depends on libqt5printsupport5 (>= 5.15.3); however:
  Package libqt5printsupport5 is not installed.
 openboard depends on libqt5multimedia5 (>= 5.15.3); however:
  Package libqt5multimedia5 is not installed.
 openboard depends on libqt5xml5 (>= 5.15.3); however:
  Package libqt5xml5 is not installed.
 openboard depends on libqt5concurrent5 (>= 5.15.3); however:
  Package libqt5concurrent5 is not installed.
 openboard depends on onboard; however:
  Package onboard is not installed.
 openboard depends on libqt5multimedia5-plugins; however:
  Package libqt5multimedia5-plugins is not installed.

dpkg: error processing package openboard (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1ubuntu4) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Errors were encountered while processing:
 openboard
```
Let's take one of the dependencies, 
**libavformat58**
In ubuntu 22.10 this has been updated to libavformat59, but openboard only seeks for libavformat58.

This problem is same for all the uninstallable dependencies. I was asking if there is any fix for this? Instead of using snap, can I get the deb working in Ubuntu 22.10?

**Comment by letsfindaway** [comment]
:smile: 

This helps me a lot!! And I hope I wasn't unfriendly. 

When looking at your commands and the output, I can see several problems. Let's start:

> `sudo dpkg -i openboard_ubuntu_22.04_1.6.4_amd64.deb`

When installing a package with `dpkg` you do not allow the system to automatically resolve dependencies. `dpgg` just looks on the single package. If you want automatic resolution you have to use `sudo apt install ...`. But wait, this will most probably also fail.

> Let's take one of the dependencies,
libavformat58
In ubuntu 22.10 this has been updated to libavformat59, but openboard only seeks for libavformat58.

Yes, OpenBoard 1.6.4 depends on `libavformat58`, part of ffmpeg 4.x. `libavformat59` is part of ffmpeg 5, and this requires adaptations of the API. This API will be supported with OpenBoard 1.7.0, but not with 1.6.4. So it is likely that you would also fail to compile 1.6.4 on Ubuntu 22.10 due to that APi change.

> I was asking if there is any fix for this? Instead of using snap, can I get the deb working in Ubuntu 22.10?

Yeah, it is not a snap, but a Flatpack what I could recommend. See https://github.com/OpenBoard-org/OpenBoard/wiki/Downloads. Technologically the two are similar. But Snaps are an Ubuntu thing, while Flatpacks are FOSS. You might also have a look at https://www.omgubuntu.co.uk/how-to-install-flatpak-on-ubuntu or similar pages for instructions how to enable Flatpack and the Flathub repository on Ubuntu.

And if you don't like to use a Flatpack, then you have to use the current `dev` branch and compile it by yourself - or wait for my packages from the openSUSE Build Service. Because: No, you most probably cannot get the `deb` for 22.04 working on Ubuntu 22.10 due to the ffmpeg version change.

You see: with proper information I can give better answers :)

**Comment by soumyatheman** [comment]
Well I didn't read your whole answer the last time, sorry for that. I saw that you're angry, and I gave everything. Actually I am preparing all these for the [pacstall project](https://pacstall.dev/). By a pacscript, we'll no longer need manual finding and checking of updates of a package. Also, I am on ubuntu and I know all the differences between snap and flatpak. But donno why, I love snap over flatpaks. I have used flatpaks in fedora, they're fast and good. But sometimes I have faced some sudden problems, like crashes, system permissions and a lot. Also theming a thing, where snap and yaru loves each other a lot.

**Comment by letsfindaway** [comment]
Thanks for your explanation and the link to the pacstall project. Will you provide a pacscript for OpenBoard some time?

> I saw that you're angry, and I gave everything.

Oh no, I wasn't angry. Sorry if I gave that impression to you. I'm happy to help, but I can do this better when I have more information. I think this conversation is a nice example on how much mutual information exchange helps in understanding.

If the issue is now answered from your side you may also close the issue.

**Comment by soumyatheman** [comment]
> Thanks for your explanation and the link to the pacstall project. Will you provide a pacscript for OpenBoard some time?
I have already made one, it's easy. It just automatically fetches the openboard deb file from the official link, and install using the same command, dpkg. But sadly the installation will failed. There is nothing new.

> If the issue is now answered from your side you may also close the issue.
I would like to connect with you personally, anyway? discord or anything else?

**Comment by soumyatheman** [comment]
Telegram, I'm also there :)

**Comment by letsfindaway** [comment]
> > Thanks for your explanation and the link to the pacstall project. Will you provide a pacscript for OpenBoard some time?
> 
> I have already made one, it's easy. It just automatically fetches the openboard deb file from the official link, and install using the same command, dpkg. But sadly the installation will failed. There is nothing new.

As far as I understand the pacstall project, a pacscript should build the package from sources. This is the only way to guarantee that it will work on the target system. But now we're really off-topic from this issue.
 
> I would like to connect with you personally, anyway? discord or anything else?

I'm more the e-mail guy. Probably too old for heavy use of messengers ;) You may reach me at "me at letsfindaway.de".

**Comment by soumyatheman** [comment]
A last question: You use debian or ubuntu or any of the derivatives?

**Comment by letsfindaway** [comment]
> A last question: You use debian or ubuntu or any of the derivatives?

No. All my computes run openSUSE Leap. I'm also the package maintainer for OpenBoard on openSUSE.

**Comment by soumyatheman** [comment]
> > A last question: You use debian or ubuntu or any of the derivatives?
> 
> No. All my computes run openSUSE Leap. I'm also the package maintainer for OpenBoard on openSUSE.

I'd like to learn a lot of things specifically shell script from you. As you said you're quite old but I'm quite old. Thanks a lot for your co-operation. Closing this. Would have been better, if you had any social media
