### ISSUE TITLE
Podcast: No file written to disk (ArchLinux Wayland)

### ISSUE THREAD

**Issue by misayre** [OpenBoard-org/OpenBoard#699]
Using OpenBoard 1.6.4 on ArchLinux under Sway (Wayland). Everything is working fine, apart from podcast output to disk. 

Steps to reproduce:
1. start OpenBoard
2. start recording a podcast (publish to Youtube and Intranet are NOT ticked)
3. podcast a bit
4. stop recording

Message, Podcast was created on your desktop is shown, but no file can be found.

Terminal output right after step 1
```
Persisting document; path is "/home/tobi/.local/share/OpenBoard/document/OpenBoard Document 2022-11-03 10-27-36.211/metadata.rdf"
Invalid path data; path truncated.
Wayland does not support QWindow::requestActivate()
Wayland does not support QWindow::requestActivate()
Wayland does not support QWindow::requestActivate()
```

Terminal output after hitting record in step 2.
```
Persisting document; path is "/home/tobi/.local/share/OpenBoard/document/OpenBoard Document 2022-11-03 10-27-36.211/metadata.rdf"
[libx264 @ 0x5584dc15d780] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5584dc15d780] profile High, level 6.0, 4:2:0, 8-bit
[libx264 @ 0x5584dc15d780] 264 - core 164 r3095 baee400 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=10 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[mp4 @ 0x5584dc4f5f80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x5584dc4f5f80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```
No terminal output during step 3.

Terminal output right after hitting stop in step 4.
```
[libx264 @ 0x5584dc15d780] frame I:3     Avg QP: 6.07  size: 22759
[libx264 @ 0x5584dc15d780] frame P:21    Avg QP:14.28  size:   262
[libx264 @ 0x5584dc15d780] mb I  I16..4: 66.0%  0.5% 33.4%
[libx264 @ 0x5584dc15d780] mb P  I16..4:  0.0%  0.0%  0.1%  P16..4:  0.5%  0.0%  0.0%  0.0%  0.0%    skip:99.4%
[libx264 @ 0x5584dc15d780] 8x8 transform intra:0.5% inter:9.2%
[libx264 @ 0x5584dc15d780] coded y,uvDC,uvAC intra: 18.3% 50.6% 38.4% inter: 0.1% 0.2% 0.0%
[libx264 @ 0x5584dc15d780] i16 v,h,dc,p: 72% 28%  0%  0%
[libx264 @ 0x5584dc15d780] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 48% 41% 10%  1%  0%  0%  0%  0%  0%
[libx264 @ 0x5584dc15d780] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 44% 36% 19%  0%  0%  0%  0%  0%  0%
[libx264 @ 0x5584dc15d780] i8c dc,h,v,p: 10% 32% 58%  0%
[libx264 @ 0x5584dc15d780] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x5584dc15d780] ref P L0: 94.6%  0.1%  4.0%  1.3%
[libx264 @ 0x5584dc15d780] kb/s:19.72
[aac @ 0x5584dfada400] Qavg: 158.926
```

I was hoping a message would be thrown to terminal, where a file was created. Unfortunately that is not the case. The usual suspected directories like `$HOME/Desktop` oder `$HOME/OpenBorad` are empty.

**Comment by misayre** [comment]
I got no X11 instance installed, so no way to check that avenue. If it truly has anything to do with wayland, I will rather go the route of using OpenBoard for podcasts through a virtual machine.

Applied patches are:
Quazip: Corrects include and library path 
ffmpeg: uses extra flags -lva-x11 -lva -lxcb-shm
QChar: Corrects Check in src/core/UBTextTools.cpp: \0 to use QChar('\0')

Question: if ffmpeg is not able to record screen, would something ever get written to a file?

**Comment by letsfindaway** [comment]
> Question: if ffmpeg is not able to record screen, would something ever get written to a file?

Don't actually know. The filename is passed to ffmpeg here
https://github.com/OpenBoard-org/OpenBoard/blob/b474fa37027ba910bf236e49b7316d525c6d0821/src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp#L451
What it does after that I cannot tell.

**Comment by misayre** [comment]
As I understand I got a special situation with Wayland. For posterity until a proper solution is found I got a workaround: 
Use [wf-recorder](https://github.com/ammen99/wf-recorder) to grab the whole screen at once.
