### ISSUE TITLE
Add new lang on virtual keyboard

### ISSUE THREAD

**Issue by sachinidis** [OpenBoard-org/OpenBoard#72]
How can i add a new lang on virtual keyboard;
I want to add α Greek keyboard.
Thanks

**Comment by freeheel3r** [comment]
Hi,

If you use your system's virtual keyboard (this should be the case by default but it can be switched in the preferences, in the "Display" tab, then whatever keyboard is installed on your computer and currently selected will be used. (This should work whether you're on Windows, Linux or OS X)
