### ISSUE TITLE
XPDFRenderer.o: -1: error: Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by chfeizy** [OpenBoard-org/OpenBoard#720]
XPDFRenderer.o:-1: error: Undefined symbols for architecture x86_64:
  "error(ErrorCategory, long long, char const*, ...)", referenced from:
      XPDFRenderer::title() const in XPDFRenderer.o
  "GlobalParams::setupBaseFonts(char const*)", referenced from:
      XPDFRenderer::XPDFRenderer(QString const&, bool) in XPDFRenderer.o
  "GlobalParams::GlobalParams(char const*)", referenced from:
      XPDFRenderer::XPDFRenderer(QString const&, bool) in XPDFRenderer.o
  "GlobalParams::~GlobalParams()", referenced from:
      XPDFRenderer::XPDFRenderer(QString const&, bool) in XPDFRenderer.o
      XPDFRenderer::~XPDFRenderer() in XPDFRenderer.o
  "SplashOutputDev::startDoc(PDFDoc*)", referenced from:
      XPDFRenderer::createPDFImageHistorical(int, double, double, QRectF const&) in XPDFRenderer.o
      XPDFRenderer::CacheThread::run() in XPDFRenderer.o
  "SplashOutputDev::SplashOutputDev(SplashColorMode, int, bool, unsigned char*, bool, SplashThinLineMode, bool)", referenced from:
      XPDFRenderer::createPDFImageHistorical(int, double, double, QRectF const&) in XPDFRenderer.o
      XPDFRenderer::PdfZoomCacheData::prepareNewSplash(int, unsigned char (&) [8]) in XPDFRenderer.o
  "XRef::getDocInfo()", referenced from:
      XPDFRenderer::title() const in XPDFRenderer.o
  "Object::free()", referenced from:
      XPDFRenderer::title() const in XPDFRenderer.o
  "PDFDoc::displayPage(OutputDev*, int, double, double, int, bool, bool, bool, bool (*)(void*), void*, bool (*)(Annot*, void*), void*, bool)", referenced from:
      XPDFRenderer::createPDFImageHistorical(int, double, double, QRectF const&) in XPDFRenderer.o
      XPDFRenderer::CacheThread::run() in XPDFRenderer.o
  "PDFDoc::getNumPages()", referenced from:
      XPDFRenderer::pageCount() const in XPDFRenderer.o
  "PDFDoc::displayPageSlice(OutputDev*, int, double, double, int, bool, bool, bool, int, int, int, int, bool (*)(void*), void*, bool (*)(Annot*, void*), void*, bool)", referenced from:
      XPDFRenderer::createPDFImageHistorical(int, double, double, QRectF const&) in XPDFRenderer.o
  "PDFDoc::getPage(int)", referenced from:
      XPDFRenderer::pageSizeF(int) const in XPDFRenderer.o
      XPDFRenderer::pageRotation(int) const in XPDFRenderer.o
  "PDFDoc::PDFDoc(GooString const*, GooString const*, GooString const*, void*, std::__1::function<void ()> const&)", referenced from:
      XPDFRenderer::XPDFRenderer(QString const&, bool) in XPDFRenderer.o
  "PDFDoc::~PDFDoc()", referenced from:
      XPDFRenderer::~XPDFRenderer() in XPDFRenderer.o
  "Dict::lookup(char const*, int) const", referenced from:
      XPDFRenderer::title() const in XPDFRenderer.o
  "_globalParams", referenced from:
      XPDFRenderer::XPDFRenderer(QString const&, bool) in XPDFRenderer.o
      XPDFRenderer::~XPDFRenderer() in XPDFRenderer.o

**Comment by letsfindaway** [comment]
Hey, now you solved the compile problems, congratulations! You're now on the linker part.

It seems that you don't link `libpoppler` correctly. The project file tries to find them for MacOS here:

```ini
   LIBS        += -L/opt/local/lib -lpoppler
   INCLUDEPATH += /opt/local/include/poppler
```

Is the library available at `/opt/local/lib`?

**Comment by kaamui** [comment]
Note that it is added there when using macports to install it. Using HomeBrew, you might need to change it to /usr/local/ (if I remember well)

**Comment by chfeizy** [comment]
LIBS += -L/usr/local/opt/poppler/lib
   LIBS += -L/usr/local/opt/ffmpeg/lib
INCLUDEPATH += /usr/local/opt/ffmpeg/include
   INCLUDEPATH += /usr/local/opt/poppler/include
   INCLUDEPATH += /usr/local/opt/poppler/include/poppler
#   LIBS        += -L/opt/local/lib -lpoppler
   LIBS        += -L/opt/local/lib
#   INCLUDEPATH += /opt/local/include/poppler
