### ISSUE TITLE
Widgets not deleted in "old" documents

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#724]
Hello,

I have just encountered what I consider an important issue and I'll try to explain…
My workflow is the following : I had created a document in 2014 which is entitled something like "Today in my grade 6 class". I update this document since then by adding pages (dragged and dropped from my other "original" documents) and deleting pages (when I have finished today's work. All in all, the document has been existing for many years now, and analysing my backups, I have noticed that those documents were HUGE on my server (about 25,000 files and a few gigabytes !). Digging things a little, I have noticed that widgets kept adding into the documents even though I delete the pages (hence the 25,000 files).

Noticing the problem, I have created a brand new "today's" document and everything is now back to order (by the way, deleting my almost empty (in the GUI) old "today's document" took me quite a while !).

What I consider normal behavior should be : widgets get deleted when pages are trashed in the GUI. So whatever the creation date of a document doesn't grow a huge file on disk. File size whould reflect document size shown in the GUI.

I hope I'm not making a mistake. If so, sorry for the wrong issue ;)

By the way, I have OpenBoard 1.6.4 on Ubuntu 20.04.

Thanks !

Celfred

![Capture d’écran du 2022-12-30 23-52-44](https://user-images.githubusercontent.com/3351052/210138086-167f2288-62cd-4956-ba70-09b1b7284bff.png)

![Capture d’écran du 2022-12-30 23-53-09](https://user-images.githubusercontent.com/3351052/210138072-68ba754f-1c1c-4b08-ac94-139007350285.png)

**Comment by letsfindaway** [comment]
Thanks for reporting - and Happy New Year!

I found a similar problem some time ago, see #671. To mitigate this, I provided a pull request #689 which was merged to the development branch `dev` and will be included in the next release 1.7.0 of OpenBoard. With this version, unnecessary files and widgets will automatically be removed from a document.

**Comment by celfred** [comment]
Thanks for your reply and glad I could help.
Eager to see version 1.7.0 out !

Happy New Year to you too ;)

I guess I can go ahead and close my issue, then.
