### ISSUE TITLE
Ubuntu 22.04 .deb cannot be installed on 22.10

### ISSUE THREAD

**Issue by thediveo** [OpenBoard-org/OpenBoard#729]
```
The following packages have unmet dependencies:
 openboard : Depends: libavformat58 (>= 7:4.4.2) but it is not installable
             Depends: libavcodec58 (>= 7:4.4) but it is not installable or
                      libavcodec-extra58 (>= 7:4.4) but it is not installable
             Depends: libswresample3 (>= 7:4.4.2) but it is not installable
             Depends: libswscale5 (>= 7:4.4.2) but it is not installable
             Depends: libavutil56 (>= 7:4.4.2) but it is not installable
             Depends: libpoppler118 (>= 22.02.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

For instance, there is libavformat58, but only 59.

**Comment by letsfindaway** [comment]
That's likely to be expected when you try to install a package built for another version of the distribution. As you already have seen, the version of `ffmpeg` libraries was updated for Ubuntu 22.10 and does no longer match the versions used by Ubuntu 22.04. My recommendation: don't even try to do something like this. It calls for trouble.

What can you do? There are several options:

- Use the Flatpak version 1.6.4 from [Flathub](https://flathub.org/apps/details/ch.openboard.OpenBoard). The Flatpak brings its own set of libraries and avoids the incompatibility problem. This Flatpak is built and maintained by a community member, so it is not an official release, but expected to be in good shape.
- Use my [experimental build of the upcoming OpenBoard 1.7.0](https://build.opensuse.org/project/show/home:letsfindaway:experimental) for [Ubuntu 22.10 (download link)](https://download.opensuse.org/repositories/home:/letsfindaway:/experimental/xUbuntu_22.10/amd64/). These builds are - as the name says - experimental and contain a pre-alpha version of the next OpenBoard release. I update them from time to time to reflect the current development state and add some additional patches. See also https://github.com/letsfindaway/OpenBoard/issues/89.

The next version of Ubuntu (23.04) will also contain an `openboard` package in version 1.6.4. See here in the [Ubuntu package search](https://packages.ubuntu.com/search?keywords=openboard&searchon=names&suite=all&section=all).

**Comment by thediveo** [comment]
The experimental build of 1.7.0 works for me. Thank you very much!
