### ISSUE TITLE
Error writing – lines interrupted – Huion tablet

### ISSUE THREAD

**Issue by 7stiubeie** [OpenBoard-org/OpenBoard#730]
When writing short lines, dashed lines, the equal in mathematical texts, or other small signs, a point is formed, a small ball of black ink at the beginning of the graphic sign. Mention that I use a Huion 1060P tablet in windows 10. I can highlight with this little screenshot:  
![image](https://user-images.githubusercontent.com/122812885/212722997-5408e681-45b4-44cc-a967-07f8af7eaa9e.png)
![openboard writing error](https://user-images.githubusercontent.com/122812885/212723056-b41e0ba1-ee28-48b8-a083-fc052063fbbf.png)

**Comment by letsfindaway** [comment]
This is a known issue of the Windows Ink Tablet Driver together with Qt.

See Issue #537, and especially the explanation for the workaround at https://github.com/OpenBoard-org/OpenBoard/issues/537#issuecomment-1048487187 on how to mitigate this problem.
