### ISSUE TITLE
Rotation of Images more then +/-90°

### ISSUE THREAD

**Issue by martinhelfrich** [OpenBoard-org/OpenBoard#731]
Hi, I would like to rotate images more than +/-90° but currently this is not possible. To be precise: When I try to rotate an image by 180° it is displayed as if it was at 0° rotation.
Is this a bug or a feature? Or am I missing something?

**Comment by letsfindaway** [comment]
I don't know whether it is a bug or a feature, but I know a workaround:

- Take the resize handle at the right side of the image and drag it left, making the image narrower. Drag it further over the left edge. The image will then appear mirrored.
- Do the same with the top (or bottom) resize handle.

After that, you have the image upside down and you can rotate it the other half of the 360° ;)

Of course it is not easy not to distort the image, and it might be better if you rotate it by 180° in an external graphic program.

But let's wait for the answer of your question: bug or feature? I'm curious!

**Comment by martinhelfrich** [comment]
That is a genious work around! Thank you so much :)
And I agree, it feels like a bug. I would hope the fix is rather easy...

I am new here, who can tell us if this is a bug or feature?

**Comment by letsfindaway** [comment]
This is the project maintainer, @kaamui .

**Comment by martinhelfrich** [comment]
How can I reach @kaamui ? I would love to help with fixing / implementing this. :)

**Comment by kaamui** [comment]
I'm here ^^

Sorry guys I don't have much time and I need to check what you reported and look at the code before answering. I don't know yet what was intended and what was not.

**Comment by GavinSmith0123** [comment]
I've struggled with this as well.

The patch below disables the code that was responsible. It means that the controls may be upside down, but at least you can smoothly rotate images all the way around.

This patch applies to a private branch but it would apply to the main OpenBoard code if it hasn't changed since.

````
diff --git a/src/domain/UBGraphicsDelegateFrame.cpp b/src/domain/UBGraphicsDelegateFrame.cpp
index 8deb42b3..1a85de63 100644
--- a/src/domain/UBGraphicsDelegateFrame.cpp
+++ b/src/domain/UBGraphicsDelegateFrame.cpp
@@ -180,7 +180,8 @@ void UBGraphicsDelegateFrame::initializeTransform()
     QPointF topRight = itemTransform.map(itemRect.topRight());
     QPointF  bottomLeft = itemTransform.map(itemRect.bottomLeft());
 
-    qreal horizontalFlip = (topLeft.x() > topRight.x()) ? -1 : 1;
+    //qreal horizontalFlip = (topLeft.x() > topRight.x()) ? -1 : 1;
+    qreal horizontalFlip = 1;
     mMirrorX = horizontalFlip < 0 ;
     if(horizontalFlip < 0){
         // why this is because of the way of calculating the translations that checks which side is the most is the
@@ -193,7 +194,8 @@ void UBGraphicsDelegateFrame::initializeTransform()
         bottomLeft = itemTransform.map(itemRect.bottomRight());
     }
 
-    qreal verticalFlip = (bottomLeft.y() < topLeft.y()) ? -1 : 1;
+    //qreal verticalFlip = (bottomLeft.y() < topLeft.y()) ? -1 : 1;
+    qreal verticalFlip = 1;
     // not sure that is usefull
     mMirrorY = verticalFlip < 0;
     if(verticalFlip < 0 && !mMirrorX){
@@ -799,6 +801,7 @@ void UBGraphicsDelegateFrame::positionHandles()
     int rotateHeight = QLineF(topLeft, bottomLeft).length();
 
     // Handle the mirroring
+#if 0
     if(topLeft.x() > topRight.x()){
         QPointF topTmp = topRight;
         QPointF bottomTmp = bottomRight;
@@ -816,6 +819,7 @@ void UBGraphicsDelegateFrame::positionHandles()
         bottomRight = topRight;
         topRight = rightTmp;
     }
+#endif
 
     QLineF topLine(topLeft, topRight);
     qreal angle = topLine.angle();
@@ -995,6 +999,7 @@ QRectF UBGraphicsDelegateFrame::rotateButtonBounds() const
 
 void UBGraphicsDelegateFrame::refreshGeometry()
 {
+#if 0
     // Here we want to have the left on the left, the right on the right, the top on the top and the bottom on the bottom!
     QRectF itemRect = delegated()->boundingRect();
     QTransform itemTransform = delegated()->sceneTransform();
@@ -1007,4 +1012,5 @@ void UBGraphicsDelegateFrame::refreshGeometry()
     QLineF leftLine(topLeft, bottomLeft);
     qreal height = leftLine.length();
     setRect(topRight.x() - mFrameWidth, topLeft.y() - mFrameWidth, width + 2*mFrameWidth, height + 2*mFrameWidth);
+#endif
 }
````
