### ISSUE TITLE
Programming a sound at the end of the stopwatch

### ISSUE THREAD

**Issue by GregKLM82** [OpenBoard-org/OpenBoard#737]
Hello!
As part of my job (technopedagogue) I train teachers in the use of OpenBoard. 
Following one of these trainings a teacher submitted the following request: the possibility of programming a sound (a beep) at the end of the stopwatch and a few seconds before the end. Is this possible? 
Thank you in advance for your feedback!

**Comment by kaamui** [comment]
Hi,

It's already what the stopwatch is doing ^^

**Comment by GregKLM82** [comment]
Hello !
Thanks for your feedback! I just tested the stopwatch again, no sound is played at the end. Maybe there's a checkbox somewhere? I take this opportunity to transmit again the teachers' request to program a second sound before the end of the countdown (at 5 sec, or 10 sec, ...)
  
Thank you again for all !

**Comment by GregKLM82** [comment]
Yes, I tested my PC setup again this morning and had no issues with other apps. But the stopwatch made no sound. We tested on another PC (windows 11 pro) and had no sound either.

Here is the required information :
-Windows 11 Pro
- OpenBoard 1.6.4 (Official Download)

THANKS !
