### ISSUE TITLE
Export a part of the document in PDF

### ISSUE THREAD

**Issue by GregKLM82** [OpenBoard-org/OpenBoard#739]
Hello!
As part of my job (technopedagogue) I train teachers in the use of OpenBoard. Following one of these trainings a teacher submitted the following request: give the user the possibility to export only part of the document in pdf? Currently, the function requires exporting the entire document. 
Thank you in advance for your feedback!

**Comment by kaamui** [comment]
Hi,

Go to Documents Mode, and drag'n'drop the pages you want in a a new document. Then export it.
