### ISSUE TITLE
Adding background picture

### ISSUE THREAD

**Issue by sanjeewaTH** [OpenBoard-org/OpenBoard#740]
customize background  picture is very useful , add that feature to add picture own wish

**Comment by letsfindaway** [comment]
Just add an image to the board, using copy/paste, drag-and-drop or whatever. Then from the menu of this image select "Set as background" as shown below.

![grafik](https://user-images.githubusercontent.com/35591413/224105751-96d5d243-a22c-4a7f-926a-013fe1ade227.png)

You may also drop a PDF document on a board scene. Then the pages of the document are inserted as background on successive scenes.
