### ISSUE TITLE
Should respect picture orientation

### ISSUE THREAD

**Issue by Yvan-Masson** [OpenBoard-org/OpenBoard#744]
Hi,

When importing JPEG files into the documents and into the board, orientation metadata is not respected. This is especially annoying as it is quite difficult inside OpenBoard to rotate a picture 90° or more (see #731) .

Regards,
Yvan

**Comment by letsfindaway** [comment]
Both, this one and #731 will be fixed in 1.7.0.

**Comment by letsfindaway** [comment]
Fixed in OpenBoard 1.7.0

**Comment by Yvan-Masson** [comment]
Thanks @letsfindaway !
