### ISSUE TITLE
No long press for symbol in Macedonian

### ISSUE THREAD

**Issue by airstrip1** [OpenBoard-org/OpenBoard#749]
Hello, I have selected "always show number row" and use the long press to get a synbol on the English keyboard.
The problem is with the Macedonian keyboard:
-No long press for symbols
-The number row is both as a standalone number row, and as a long press a leather for a number options.
Tell me if this is the place for this.
Thanks.

**Comment by letsfindaway** [comment]
I think you hit the wrong project. Your issue might be related to https://github.com/openboard-team/openboard.

Please close this issue here and reopen in at the right place.

**Comment by airstrip1** [comment]
Sorry, didn't notice.
Thanks for telling me.
