### ISSUE TITLE
Compiling OpenBoard with GCC 6.x fails, but the fix is simple

### ISSUE THREAD

**Issue by jarmopi** [OpenBoard-org/OpenBoard#76]
Apparently, due to some changes in the standard library, GCC 6 cannot compile file OpenBoard/src/frameworks/UBGeometryUtils.cpp because of an ambiguous overloaded function call. The offending function is abs() on line 191. If the call is replaced with qAbs(), the error goes away.

In other words, change this

    bool overlap = abs(spanAngleInDegrees) > 360 - angle;

into this

    bool overlap = qAbs(spanAngleInDegrees) > 360 - angle;

and the compilation should succeed. This was tested with GCC 6.2.1 in Debian Stretch.

Math lib changes:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822708
http://lists.qt-project.org/pipermail/development/2016-April/025686.html

**Comment by freeheel3r** [comment]
Thank you! I've updated this.
