### ISSUE TITLE
compile 1.7-dev on OSX Catalina

### ISSUE THREAD

**Issue by htakada** [OpenBoard-org/OpenBoard#760]
Hello,

Has anybody managed to compile it on Catalina, I keep getting this error even though I followed the instructions. don't know how to fix it. Any help will be appreciated.

thanks 
![Screen Shot 2023-04-19 at 2 23 25 PM](https://user-images.githubusercontent.com/3396738/233153361-2f73eefe-c02e-4ec8-b4ce-b36620768dbb.png)

**Comment by kaamui** [comment]
Hi,

You're not on the right branch. Go to `dev` branch and it should be ok

**Comment by htakada** [comment]
Thanks ,
I was following these instructions
![Screen Shot 2023-04-24 at 4 09 09 PM](https://user-images.githubusercontent.com/3396738/234092744-bbf76dbc-01e0-4950-9248-50f19c3e60c3.png)

**Comment by letsfindaway** [comment]
Some more comments from my point of view, even if I'm not at MacOS:

- From your original screenshot, I see in the very first line<br>`-- Configuration incomplete, errors occurred!`. So I assume there is already something wrong before this. Also the error messages complaining about a missing component are an indication in this direction. So please:
  - Give us **all** commands you issued including their result, especially success or error messages.
  - Use a **code block** (see [Quoting code)](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for this, not a screenshot. Screenshots are good to demonstrate graphical problems, but for commands and results, screenshots are limited in width and height, so important information may be missing.
- You're building for Catalina, and as far as I know this is a x86 only platform. The build instructions however contain `-DCMAKE_OSX_ARCHITECTURES==x86_64;arm64"`. Is it necessary to adapt this for Catalina? But as I said: I'm not at MacOS, so this is just a guess.

**Comment by kaamui** [comment]
> Thanks , I was following these instructions ![Screen Shot 2023-04-24 at 4 09 09 PM](https://user-images.githubusercontent.com/3396738/234092744-bbf76dbc-01e0-4950-9248-50f19c3e60c3.png)

They also mention to go on the `dev` branch. The difference is that with these instructions, you can build a version that would work in both intel and arm processors. 

> You're building for Catalina, and as far as I know this is a x86 only platform

He's building on Catalina, but potentially not for Catalina only, maybe not for Catalina at all ^^

**Comment by htakada** [comment]
> > Thanks , I was following these instructions ![Screen Shot 2023-04-24 at 4 09 09 PM](https://user-images.githubusercontent.com/3396738/234092744-bbf76dbc-01e0-4950-9248-50f19c3e60c3.png)
> 
> They also mention to go on the `dev` branch. The difference is that with these instructions, you can build a version that would work in both intel and arm processors.
> 
> > You're building for Catalina, and as far as I know this is a x86 only platform
> 
> He's building on Catalina, but potentially not for Catalina only, maybe not for Catalina at all ^^

Thanks for your replies, 
I am building it just for testing, for my own use. 
I run Catalina on an Intel laptop.
I saw two build instructions, I assumed the first one was for ARM and the second one for intel, that's why I chose to follow the second one. 
Regards
