### ISSUE TITLE
Please add appimage support

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [OpenBoard-org/OpenBoard#770]
Good morning . 
Can you please add appimage automatical release build . it will help to start it on arch or any another linux distr.

**Comment by letsfindaway** [comment]
As an alternative, there is a [Flatpak version of OpenBoard at Flathub](https://flathub.org/de/apps/ch.openboard.OpenBoard) created and maintained by a community member. Typically he updates the Flatpak shortly after release of a new version here. Like an AppImage, the Flatpak also runs on virtually every Linux distribution.
