### ISSUE TITLE
frozen object after an URL copy paste

### ISSUE THREAD

**Issue by kaamui** [OpenBoard-org/OpenBoard#774]
After copy/pasting an URL onto the board, the created object cannot be interacted with through its grey selection frame. 

Related to #716

**Comment by letsfindaway** [comment]
At least I can now tell you why this happens:

- When you paste the URL, you press `Ctrl+V`.
- The `Ctrl` is also recognized by the `UBBoardView::keyPressEvent()`. Here it sets multiselection to `true`: https://github.com/OpenBoard-org/OpenBoard/blob/b474fa37027ba910bf236e49b7316d525c6d0821/src/board/UBBoardView.cpp#L235-L238
- When handling the mouse press event in `UBBoardView::handleItemMousePress()`, this is detected by the following code: https://github.com/OpenBoard-org/OpenBoard/blob/b474fa37027ba910bf236e49b7316d525c6d0821/src/board/UBBoardView.cpp#L782-L783
- This means that the mouse press event is ignored.

Things return to normal once this flag is reset.

So we now have to work on a proper solution. What is actually wrong? Why is multiselection not disabled when `Ctrl` is released again after pasting?
