### ISSUE TITLE
Alphabetical sorting for documents

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#79]
Hello,

I am discovering OpenBoard (switching from OpenSankoré), and 1 feature that would keep the 'KISS' philosophy of OpenBoard that seems missing is the alphabetical sorting of documents in the Document tab. For the moment, the sorting is based upon the created date (from what I've tested). Why not simply alphabetical sorting by default ? I have a feeling this would not be too much dev work and it could stay as simple as it is now : no other option (forget about the created date sorting that doesn't represent much). Whenever a document is created/moved/renamed, it is placed according to the alphabet order. What would you think of this ?
I am importing a lot of documents and having a big mess in my lists because of the date sorting ;)
Congratulations for your work as a whole !

**Comment by freeheel3r** [comment]
Hi,
Thanks for your feedback. We are planning to improve this document view in future releases, mainly by allowing different ways of sorting the list.

While I can't really speak to the original motivations for this system, I'm afraid that if we changed to alphabetical sorting, other users would complain. I'm sure some people like the fact that they can find the last document they created at the top of the list.

So instead we'll switch the list view to something a bit more "standard", with a choice between alphabetical and chronological sorting at least.

**Comment by celfred** [comment]
Thanks a lot for this quick reply.
I completely understand that changing things without giving the possibility to stay as it is now would lead to other user's complains :)
Good if the alphabetical/chronological switch is planned for a future version. There's no hurry at all. I'll be patient ;)

**Comment by kaamui** [comment]
Added in 1.5.3
