### ISSUE TITLE
Will this program ever be supported on the Universal Windows Platform (UWP)?

### ISSUE THREAD

**Issue by SecularSteve** [OpenBoard-org/OpenBoard#790]
We have a "Microsoft Surface Hub" Workstation at our workplace, and having a feasible open licence-free alternative to the packaged Microsoft Whiteboard seems like a good trade off.

The problem is that Surface Hub devices only support UWP apps, not MSIX. Something about safety and stability. Even the Developer mode doesn't let me install it.

What I'm suggesting is a UWP edition/installation package of OpenBoard compatible with Surface Hub Workspaces/devices.

If this is impossible because of either the licencing, or the way the software's made, I'll stick to Microsoft Whiteboard. I mean, it's more barebones, but it's the only way we can use a whiteboard on this device.

Tried installing it on the Hub once, didn't work no matter what I did.
If this is something that can't simply be resolved, I'll take it with a grain of salt, and move on.

**Comment by letsfindaway** [comment]
I doubt that there will be a UWP version.

On https://www.qt.io/blog/qt6-development-hosts-and-targets under the heading **Development hosts and targets in Qt 5.15 that are not planned in Qt 6** you can find the following sentence:

> Additionally, it will no longer be possible to create UWP applications on Windows 10.

If this is true, then starting with Qt 6 there will no longer be UWP support for Qt - and OpenBoard will definitely at some point in time have to move forward to Qt 6.

See also 
- https://forum.qt.io/topic/143921/will-the-qt6-support-uwp-platform
- https://www.developer-tech.com/news/2021/oct/20/microsoft-universal-windows-platform-finally-being-sunset/
- https://www.thurrott.com/dev/258377/microsoft-officially-deprecates-uwp
