### ISSUE TITLE
Add option to disable the slash button

### ISSUE THREAD

**Issue by a-0-dev** [OpenBoard-org/OpenBoard#792]
I rarely need to write a slash on my phone, so having the dedicated button basically just robs screen real estate.

I would highly appreciate if you could add an option to disable this button (it would still be available on the "symbols" tab of the keyboard) in the settings, where the options to disable other buttons are also located.

Thanks for your work on this app!

**Comment by letsfindaway** [comment]
I think you hit the wrong project. Your issue might be related to https://github.com/openboard-team/openboard.

Please close this issue here and reopen in at the right place.
