### ISSUE TITLE
Proposed updates to the wiki

### ISSUE THREAD

**Issue by letsfindaway** [OpenBoard-org/OpenBoard#802]
i shortly went through the wiki and checked mainly the links, but also the content. Here a list of things which should be updated:

- [x] **Home**: Link to OpenSankore: Page no longer exists. Link now leads to a hosting provider.
- [x] **Home**: Twitter link goes to non-existing account.
- [x] **Home**: Download link uses `DIP-SEM`. Redirection works, but...
- [x] **Downloads**: Link under "Source" to build instructions is wrong.
- [ ] **Downloads**: Probably mention that a `openboard` package is also part of the official Debian package repository and therefore also available for Ubuntu and other Debian derivates? Version might depend on the package maintainer there and the distros release cycle. And these packages don't install to `/opt`, but to `/usr` as any other distro packages. Most up-to-date release version is always at `openboard.org`, of course.
- [x] **Build from source**: Chapter for Debian stretch is obsolete.

**Comment by kaamui** [comment]
Hi,

I'm not sure I want to promote Debian's official package that is providing 1.6.1 packages. I'll let it as-is for now.

**Comment by letsfindaway** [comment]
That's fine with me.

Just FJY: Ubuntu 22.04 is on 1.6.1, but 23.04 already has 1.6.4 (https://packages.ubuntu.com/search?keywords=openboard&searchon=names). For Debian, Debian 12 (stable, bookworm) and 13 (testing, trixie) already have 1.6.4 (https://packages.debian.org/search?suite=all&arch=any&searchon=names&keywords=openboard).

And the Wiki fixes of course also have to be applied to the French version.
