### ISSUE TITLE
1.7-a.230829 : can't resize the mask tool

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#804]
Everything is in the title.

As you can see, impossible to resize the tool :
<img width="686" alt="image" src="https://github.com/OpenBoard-org/OpenBoard/assets/7523821/5e723e43-304b-481f-b11e-7f82ee0b14dd">

**Comment by kaamui** [comment]
Hi,

Yep, it's already fixed in dev. 

But thank you for the time you take to test the app !
