### ISSUE TITLE
Unable to install on ubuntu 20.4

### ISSUE THREAD

**Issue by GuptaNavneet** [OpenBoard-org/OpenBoard#807]
`lsb_release -a`

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

`sudo apt-get install ./openboard_ubuntu_20.04_1.6.4_amd64.deb`
The following packages have unmet dependencies:
 openboard : Depends: libquazip5-1 (>= 0.7.6) but it is not installable
             Depends: onboard but it is not installable
E: Unable to correct problems, you have held broken packages.

`sudo apt-get install libquazip5-1`
E: Unable to locate package libquazip5-1

`sudo apt-get install onboard`
E: Unable to locate package onboard

I have also checked with 
`sudo apt-get update`
`sudo apt-get upgrade`

**Comment by letsfindaway** [comment]
`libquazip5-1` is definitely part of Ubuntu 20.04 focal. See here: https://packages.ubuntu.com/focal/libquazip5-1. Same with `onboard`: https://packages.ubuntu.com/focal/onboard.

So you have to find out why it is not found on your system. It is most probably a misconfiguration of the apt sources. Could this help?
https://askubuntu.com/questions/378558/unable-to-locate-package-while-trying-to-install-packages-with-apt
