### ISSUE TITLE
Font color on dark background

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#81]
I mostly use dark background for my projected documents in class.
When I use the pen, everything works fine : white ink is set by default (first selected color). If I switch to white background, the ink turns black automatically. If I switch back, the color switches as well. Cool.
If I use the text box, though, the default text color is black, so invisible (like the caret, by the way). I manually select 'white'. Although it's a little annoying to do this all the time, my text is then just fine, BUT here are the consequences : 
- If I switch to a white background, the text stays white (normal), and is then invisible. Could it be an 'automatic' 'black/white' switch and stay a unique color ONLY if a color has been manually selected ?
- If I export my page to generate a PDF, the white text is invisible again. Maybe PDF export could force a white to black conversion ?

**Comment by freeheel3r** [comment]
That seems like a good idea to me, and potentially fairly easy to implement, if as you suggest it's only applied for white / black text.

We'd just have to figure out the specifics of when and how to apply the colour change but on the surface it looks quite feasible.

Thanks for the suggestion!

**Comment by celfred** [comment]
Sad to see it hasn't been introduced in 1.4.0.
But I fully understand though that everything people ask can't be taken into account right away, don't worry :)
I wish I could be able to help in developpement and make pull requests. (maybe some day...)
Thanks for your work.

**Comment by petsuter** [comment]
Isn't this rather a regression / defect than a missing enhancement? Looking at the code it seems it was previously implemented but then got [commented out](https://github.com/OpenBoard-org/OpenBoard/commit/f13cceb40fb8563e3b2423f402ae92defefc21bd#diff-3a87695dac4c820c10937fa355b1b4a7L54) and the [comment was then removed](https://github.com/OpenBoard-org/OpenBoard/commit/f16c06f9b8fca6cd62744f2cd9a74c1c2f1c3a1e#diff-3a87695dac4c820c10937fa355b1b4a7L54).

**Comment by celfred** [comment]
Just a little follow-up since I notice that this does not work either in 1.5.1 :( If I have a dark background and want to add some text, I have to manually select white color (which then stays white if I export in PDF...)

**Comment by kaamui** [comment]
Hello,

This will be added on 1.5.4. For the PDF export, if I find time to look at it, I'll try to handle it too.

Thank you for your patience :)
