### ISSUE TITLE
Is there a Guide to update external web widget?

### ISSUE THREAD

**Issue by sebojolais** [OpenBoard-org/OpenBoard#820]
Hi,
I used to work with OpenBoard and with some external web apps. Somone comes from the web and others are homemade. They have to be updated in order to support OpenBoard 1.7 and higher.
ls there a guide or a doc that explain what we have to modify in the web app code?
Thank you in advance for the answer.

**Comment by letsfindaway** [comment]
I already had some documentation about the new widget API in my wiki pages and now collected some more information to help you upgrading your widgets here:

https://github.com/letsfindaway/OpenBoard/wiki/Guide-for-widget-update

Please feel free to ask me for advice if you have any further questions.

**Comment by sebojolais** [comment]
Let me say you two words : thank you!
Your work on this nice project is so valuable.
