### ISSUE TITLE
Multilanguage typing support

### ISSUE THREAD

**Issue by Doxorn** [OpenBoard-org/OpenBoard#821]
Hi, I am actively using 3 languages, sometimes mixing 2 in the same sentence.
Support for multilanguage typing would be appreciated for both suggestions and for long press characters.
For example if I have English, Hungarian, Slovak and Norwegian keyboards enabled I'd get the options "s,ß,š" when I long press S and "o,ó,ö,ő,ø" when I long press O.

Thank you

**Comment by letsfindaway** [comment]
I think you hit the wrong project. Your issue might be related to https://github.com/openboard-team/openboard.

Please close this issue here and reopen in at the right place.
