### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by OrionRandD** [OpenBoard-org/OpenBoard#822]
Documentation and Support

Here are some resources that might help you

    New ! [OpenBoard 1.6 User's Guide](http://openboard.ch/download/Tutoriel_OpenBoard_1.6EN.pdf) (PDF, 3.1Mb)
    New ! [OpenBoard 1.6 in one page](http://openboard.ch/download/OpenBoard1.6_interface-EN.pdf) (PDF, <527Ko)
    New ! [OpenBoard 1.6 : document mode cheatsheet](http://openboard.ch/download/OpenBoard1.6_Mode_Doc_in_1_pageEN.pdf) (PDF, 2.4Mb)
    [OpenBoard Video Tutorials Youtube Channel](https://www.youtube.com/channel/UCM_moFB68dqpSLPZ-jV40Ow) (in french)
    [Demonstration of an interactive projection system using OpenBoard in Geneva secondary schools](http://edu.ge.ch/ecolenumerique/videos/422-un-systeme-de-projection-interactif-qui-illumine-la-classe) (in french, web page and video)
    [OpenBoard Bulletin Board](http://openboard.ch/forum/) (only in french at this time, but feel free to post in english)

Technical Documentation

    [OpenBoard settings](https://github.com/OpenBoard-org/OpenBoard/wiki/Settings) (on GitHub)

    [OpenBoard on GitHub](https://github.com/OpenBoard-org/OpenBoard)

This link is broken:

 [Demonstration of an interactive projection system using OpenBoard in Geneva secondary schools](http://edu.ge.ch/ecolenumerique
and points to:
https://edu.ge.ch/ecolenumerique/videos/422-un-systeme-de-projection-interactif-qui-illumine-la-classe

:(

**Comment by kaamui** [comment]
The site has been recently updated and should no longer suggest broken links
