### ISSUE TITLE
file couldn't be accessed on each launch

### ISSUE THREAD

**Issue by novazur972** [OpenBoard-org/OpenBoard#836]
I am not an OpenBoard user. I install it (Gentoo Linux) for my wife who is a teacher. But I notice that each time I launch, I get an error "Your file couldn't be accessed".
![1](https://github.com/OpenBoard-org/OpenBoard/assets/33202357/f4a0196f-d748-4ac4-9bdc-5ce5e8e30081)
I used git master branch.
To believe that he has memorized something that he can no longer find. However, I deleted everything I found:
rm -rf ~/OpenBoard/ ~/.local/share/Open*
But that doesn't change anything:
could not find any pages for the document "/home/chris/.local/share/OpenBoard/document/OpenBoard Document 2023-12-02 12-26-27.467"
Persisting document; path is "/home/chris/.local/share/OpenBoard/document/OpenBoard Document 2023-12-02 12-26-27.467/metadata.rdf"
Persisting document; path is "/home/chris/.local/share/OpenBoard/document/OpenBoard Document 2023-12-02 12-26-27.467/metadata.rdf"

Some other config file to remove please?

**Comment by letsfindaway** [comment]
It seems that your package did not put the files for the hints and tips at the proper location, or did not package them at all.

In the meantime you can uncheck the "Visible next time" checkbox.

Questions:
- Did you package the "startupHints" folder?
- If yes, where is it located in the package? It must be parallel to "library".
- If no, change your packaging to include these additional files.

**Comment by novazur972** [comment]
You're totally right.
I tried to adapt the ebuild taken from https://github.com/cloc3/OpenBoard but I obviously didn't add startupHints since I didn't know.
I added `doins -r "${RESOURCES}/startupHints"` and now it's perfect.
![1](https://github.com/OpenBoard-org/OpenBoard/assets/33202357/460b6d35-4e6f-490b-a0d8-6107c942330c)
Thank you so much.
