### ISSUE TITLE
extended screen interactive

### ISSUE THREAD

**Issue by novazur972** [OpenBoard-org/OpenBoard#838]
Is there a way to make the extended screen interactive with some hidden option (in the git master branch)?
And if not, is this planned as a feature in the future or not?
This seems particularly important to me for certain users, as we can see it asked several times on the forum.
Thanks in advance.

**Comment by novazur972** [comment]
> No, there is no such option.

Ok :(
Thanks.

> I cannot answer this part of your question.

Even "Is this planned as a feature in the future or not?"?

**Comment by letsfindaway** [comment]
> > I cannot answer this part of your question.
> 
> Even "Is this planned as a feature in the future or not?"?

I'm not a member of the project, but just a contributor. So I have no detailed insight to the feature planning.

**Comment by novazur972** [comment]
> I'm not a member of the project, but just a contributor. So I have no detailed insight to the feature planning.

Ok.
And the contributors don't respond here?

**Comment by letsfindaway** [comment]
> > I'm not a member of the project, but just a contributor. So I have no detailed insight to the feature planning.
> 
> Ok. And the contributors don't respond here?

I'm a voluntary contributor and I try to respond if I can and have time. 

But please understand that the project manager now - shortly before release - has plenty of other tasks. He has quite limited time for this project and many other things to do. The pilot test is currently underway in some Geneva schools. He must supervise these tests on three platforms (Windows, MacOS, Ubuntu), answer the questions of the teachers, prepare the release notes, update documentation, prepare the update of the web page... So he's currently most probably not responding to issues on the issue tracker here.

**Comment by kaamui** [comment]
Sorry about that, and thank you @letsfindaway for the time you give to the project. 

After 1.7.0 release, and some meetings internally, I plan to update the roadmap on the wiki so everyone see what's our plans (there's no secret, it's just the lack of time)

The 1.7.1 (and probably 1.7.2 and 1.7.3) will be bugfix releases only. We don't plan any feature as the one you ask, and it doesn't fit any of the ways OpenBoard is used in our classrooms.

I see a configuration where it could be very cool (if the secondary display is on a tactile screen) but as it's not how our classrooms are configured, it will not be prioritized. 

1.8 will probably contain editable shortcuts from the preferences, more colors (and a way to set custom ones more quickly, directly on the board menu), not a lot more has been discussed for it at this point.

**Comment by novazur972** [comment]
Now I have my answer.
Thanks.
