### ISSUE TITLE
1.7.0 : can't save any file or import pdf

### ISSUE THREAD

**Issue by SeeDborg** [OpenBoard-org/OpenBoard#845]
I can't get any document to be saved. Everything is restarted when I quit and relaunch the software.
The documents screen seems kinda weird to me : 
<img width="377" alt="image" src="https://github.com/OpenBoard-org/OpenBoard/assets/7523821/05bc2f4a-27a3-4770-ba62-2040a97f93f6">

Same issue if I try to import a pdf file, nothing happens...

**Comment by kaamui** [comment]
looks like an issue with read/write rights. Did you launch it as root (you should not) ?

**Comment by SeeDborg** [comment]
Woups, it was indeed my fault... Sorry for the inconvenience, you can delete the post :)
