### ISSUE TITLE
Paste picture (CF_DIB) to page failed under Windows10 - OpenBoard  1.7.0

### ISSUE THREAD

**Issue by obook** [OpenBoard-org/OpenBoard#848]
Paste a picture from clipboard by CTRL+V do not any effect with OpenBoard 1.7.0 under Windows 10 : no picture.
It seems that Copy/Paste from another OpenBoard page, will works.

OB.

**Comment by SeeDborg** [comment]
Same problem here on Windows 11.

**Comment by SeeDborg** [comment]
Will this issue be fixed in a future 1.7.1 version ?
(and when can we expect this version to be released ?)

Copy/paste was a feature I used very often in 1.6...

**Comment by kaamui** [comment]
Hi, 

thank you for reporting it. Copy/paste is actually working, but the random position that is generated for the new image has absurd values on Windows, so you don't see them.

It will be fixed for 1.7.1, that should be out within one or two months.

commit : fe81a52

**Comment by obook** [comment]
Yes, fixed in Version 1.7.1rc-240202.
Thank you.

**Comment by HaxelPG** [comment]
I want to paste this image copied from PowerPoint
![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/69f1cffc-b238-41cc-a185-fa740a016e37)

and in Openboard it appears this way
![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/e40c12ef-470c-4db0-aeaf-2deb9e08f815)

It must be considered that the copied image is not a screenshot, it is a copy of the PowerPoint slide objects. This problem did not occur in Openboard 1.6.4, that is the version I am currently using but I would like to update to use the new features.

Another detail to consider is the size of the page.

![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/90dd3f80-1541-4709-84c0-e32c96a92d04)

It shows 0.9x, as you increase the size with the Ctrl key + mouse wheel, it is assumed that it would continue to be 1.0x

![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/6efa8a17-38a3-4df3-bc3b-cfbd9240dc03)

But when applying the command once again it does not go to 1.1x but remains, I believe, 1.0x

![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/94f6724a-822a-429c-ab14-9d6bbfcbff5f)

Although I notice that the size of the sheet has increased, if I apply once more

![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/d49e8c62-df9d-43b8-b1e7-a4d7adc068ab)

1.1x still does not appear, I suppose it is still 1.0x but the size of the sheet continues to increase, applying once again and 1.1x appears

![image](https://github.com/OpenBoard-org/OpenBoard/assets/102131423/02273f78-1520-477f-a233-03189a586d1e)

**Comment by novy400** [comment]
Hello ,Thanks for your job. I have a same problem on W11 I've noticed that the Version 1.7.1rc-240202 fixe this issue but do you know when this release will be downloadable ?

**Comment by letsfindaway** [comment]
> Hello ,Thanks for your job. I have a same problem on W11 I've noticed that the Version 1.7.1rc-240202 fixe this issue but do you know when this release will be downloadable ?

You can find the installer on the bottom of the release page:

https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.7.1rc-240202
