### ISSUE TITLE
libwebp.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by devxbasit** [OpenBoard-org/OpenBoard#851]
As soon I open the app, I get the below error 

**/opt/openboard/OpenBoard: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory**

![image](https://github.com/OpenBoard-org/OpenBoard/assets/24441401/5247c4d6-b773-47cd-8b57-1c5de18f9c25)

System Info: 
![image](https://github.com/OpenBoard-org/OpenBoard/assets/24441401/6c110a4f-782b-473b-aa03-6f18f46c1432)

**Comment by letsfindaway** [comment]
The released package was built for Ubuntu 22.04. Official packages are provided for LTS versions of Ubuntu only. You're using 23.10, which is probably using other library versions. Your options:

- Use the Flatpak from https://flathub.org/apps/details/ch.openboard.OpenBoard.
- Use my experimental build from https://build.opensuse.org/projects/home:letsfindaway:experimental/packages/OpenBoard/repositories/xUbuntu_23.10/binaries. See also https://github.com/letsfindaway/OpenBoard/issues/89.
- Compile OpenBoard by yourself.
