### ISSUE TITLE
where is the location of the temporary file?

### ISSUE THREAD

**Issue by helloworld-taueng** [OpenBoard-org/OpenBoard#854]
Hi,

If you open the software, it can create a temporary file. Draw something and quit. Then, when you open it again, select the previous document that was saved. Where is it?
My OS is Ubuntu 22.04.

Thank you!

**Comment by letsfindaway** [comment]
On Linux, all documents are stored at `~/.local/share/OpenBoard/document`. Each document has its own sub-folder, where the individual pages and objects are stored.
