### ISSUE TITLE
[Feature Request] Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [OpenBoard-org/OpenBoard#858]
**Is your feature request related to a problem? Please describe.**
GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Describe the solution you'd like**
It would be nice if the app's code were moved to GitLab or Codeberg.

**Comment by kaamui** [comment]
Hi,

No it is not planned.
