### ISSUE TITLE
[Question] How can I donate?

### ISSUE THREAD

**Issue by julianfairfax** [OpenBoard-org/OpenBoard#859]
This app is amazing and I would like to support it, even if it's just a little. Where can I donate?

**Comment by kaamui** [comment]
Hi,

Thank you for your kind words and your support. 

OpenBoard is maintained by the Department of Public Education of the State of Geneva, and we don't plan to provide a way to make donations to help maintain it. 

But really appreciate it thank you again ! Your kind words is all we need ! :)
