### ISSUE TITLE
Does this allow mutli-touch functionality on the tv's?[Question]

### ISSUE THREAD

**Issue by devinx1** [OpenBoard-org/OpenBoard#860]

**Comment by letsfindaway** [comment]
No, OpenBoard only supports single touch. Even things like "zoom with two fingers" are currently not supported.

**Comment by kaamui** [comment]
Hi,

I'll just add that it is not planned at all because it is not a need expressed by our teachers in general.

**Comment by ThomasLucky13** [comment]
Hi,
Our teachers need this functionality, so I added it. Here is a link to my [PR](https://github.com/OpenBoard-org/OpenBoard/pull/963).
It allows several people to draw at once on Board mode with tools Pen and Marker.
