### ISSUE TITLE
[Feature Request] Cloud access to the data directory

### ISSUE THREAD

**Issue by ytorroja** [OpenBoard-org/OpenBoard#865]
First of all, thanks a lot for your explendid software. 

I've tried to find if this feature has been previously requested, but I didn´t find it.

Request:
Would it be possible to use a url address as a way to access a remote folder? (for example, I use owncloud in my university, and I can create folders with read/write public/private links, that could be used as data folder for Openboard)

Rationale: 
I use Openboard at the University, becauseI think is the best whiteboard option. But normally I have classes in different places (with different computers), so I have to use a portable installation with the data folder in the usb drive. The problem is that, as usb drive appears in different drive letters (D:, E:, F:  -btw: I use Windows- ), I have to always edit the config file to have access to my data folder. On the other hand, usb drives are not very reliable.

Thanks again for mantainig this software up!

**Comment by kaamui** [comment]
Hi,

you can define the data Directory using the DataDirectory parameter in the config file. Look at this wiki to see how to modify it : https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration#appdatadirectory

If you can provide OpenBoard a path where it can look at and find the standard structure of the DataDirectory, it should work. 

At Geneva, we use samba clients for example, to connect a folder to a distant storage, and modify the config file to point to this folder. When a teacher changes from a classroom to another one, he finds his files like they were when he left them in the previous classroom. Note that it implies that your custom config file (pointing to your custom folder and not the one of another teacher) is loaded when you are logging to the computer.

If you already have a private space accessible from any of your classrooms computers, you can probably use that to do what you want. If on Windows, you'll probably need to give the absolute path (with the driver letter) and to escape backslashes.

**Comment by ytorroja** [comment]
Hi,

Thaks a lot for your answer. You are completly right the best solution
is based on mounting network resources as local folders: I hadn't
explore that posibility enough. In my case, the problem is that
classroom computers do not have user accounts (there is a general
account for all of us) and then, again, I should have to edit the
config file to point to the mounted folder (in case other teachers had
modified that file). That can be avoided if I use a portable
installation of OpenBoard, but my main concern really is leaving my
folders mounted when I finish my class (you know, allways running from
one class to another :):) ). Anyhow, I think I'll try to solve the
problem somehow the way you say.

Thanks a lot again for your answer!!

2024-01-10 22:30 GMT+01:00, kaamui ***@***.***>:
