### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by soudjoud** [OpenBoard-org/OpenBoard#872]
- [ ] **@utgyg###** Describe the bug

#### Actual behavior
*A clear and concise description of what actually happened*

### Additional resources
*PDF, images, sounds... anything useful to reproduce the bug*

### Context

  - reproducibility : `systematic` `not systematic`
  - OpenBoard version :
      - bug happens with : `1.6.4` `1.7.0` `1.7.1a-x.y.z`
      - bug doesn't happen with : `1.6.4` `1.7.0` `1.7.1a-x.y.z`
      - didn't check : `1.6.4` `1.7.0` `1.7.1a-x.y.z`
  - OS : 
      - bug happens with : `Windows` `Linux` `macOS`
      - bug doesn't happen with : `Windows` `Linux` `macOS`
      - didn't check : `Windows` `Linux` `macOS` 
  - Installation source : `OpenBoard download page` `Linux distribution repository`, `own build` `flatpak` `AppImage`
  - If you built OpenBoard from source, please provide the branch you're working on : `master`
  
### Additional context

- OS(es) detailed version (for the ones you reproduced the bug on) 
    - Linux : ` `
    - Windows : ` `
    - macOS : ` `
- number and resolution of monitors : ` `
- if used, manufacturer and model of graphic tablet input device : ` `

**Comment by letsfindaway** [comment]
no content
