### ISSUE TITLE
Where is En version manual？

### ISSUE THREAD

**Issue by ggl74** [OpenBoard-org/OpenBoard#878]
I can not dowload En version manual on this website,
https://openboard.ch/documentation.en.html

All three manuals are seem in French？

**Comment by kaamui** [comment]
Hi,

Thanks for reporting it. Please consider asking questions relative to the website on its own repository : https://github.com/OpenBoard-org/OpenBoard-Website

I'll fix it but please note that they are not up-to-date with 1.7 changes.

**Comment by kaamui** [comment]
English (for `en` and `de`) and Italian links have been restored
