### ISSUE TITLE
Error al pegar

### ISSUE THREAD

**Issue by HaxelPG** [OpenBoard-org/OpenBoard#891]
En Openboard Version 1.7.0 al momento de pegar desde el portapapeles no aparece el objeto pegado en la pagina mostrada, en la versión 1.7.1rc-240202 al momento de pegar las fuentes de distorsionan.

**Comment by letsfindaway** [comment]
It would help others trying to support you if you observe a few rules when writing an issue here:

- Please write in English. Many people (myself included) don't speak Spanish. Use a translator if you're not sure of your English.
- Search in the issue list: have others already reported the same problem? In your case #848 looks similar.
- Use the template provided and fill in as much information as possible. In your case: From #848 I assume it is Windows, but you did not tell.
- Describe the problem as detailed as possible. Provide a step-by-step guide to reproduce it.  "Distorted" is not specific enough. Provide a screenshot to visualize your issue.

Thanks for your understanding!

Take the time to describe your problem. Then others will also take the time to help you.
