### ISSUE TITLE
[Question]Which SVG Format Does OpenBoard Support?

### ISSUE THREAD

**Issue by PMsoE** [OpenBoard-org/OpenBoard#907]
Hi, recently I started to use [Typst](https://typst.app/), similar functionality to LaTeX, to produce math expressions in SVG and found out OpenBoard cannot handle SVG files Typst generates. After some experiments I found out symbol tag is the culprit and replacing it to g tag seems to solve the problem. But now I'm wondering which SVG format OpenBoard supports. Any pointers would be appreciated. Thank you.

e.g. pi generated by Typst:
![pi](https://github.com/OpenBoard-org/OpenBoard/assets/161705114/c9d1055b-00e7-4bbb-a1e0-70b9a3d9239d)

**Comment by letsfindaway** [comment]
OpenBoard uses the SVG renderer of Qt. Qt supports the static features of SVG 1.2 Tiny. See https://doc.qt.io/qt-5/svgrendering.html.

On the linked page you also find further links to the W3C specifications of that SVG subset.

**Comment by letsfindaway** [comment]
But I have another idea: We also have a full fledged web browser in OpenBoard based on Chromium. You can also use this to render SVG:

- From the application palette, drag the "Html" application on the board.
- Then paste the content of your SVG file in the input field. It is not necessary to surround it with some HTML, just the SVG is sufficient.
- Press "Preview".

The application still provides some gray background behind the SVG, but here you should have the full SVG support of Chromium. I tested it with some animations - it is working.

**Comment by letsfindaway** [comment]
And: have you seen the LaTeX2SVG app in the pre-release [v1.7.1rc-240202](https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.7.1rc-240202) (download link on the bottom of that page)? It is probably a good and built-in replacement for Typst and produces SVG images which are nicely rendered by Qt.

**Comment by PMsoE** [comment]
Thanks a lot. I will try the pre-release.
