### ISSUE TITLE
Remove the cross

### ISSUE THREAD

**Issue by matr0nix** [OpenBoard-org/OpenBoard#91]
Hello,

It's not a bug, but is it possible to remove the cross (the cursor) ? It's usefull when you use a mouse, but not with a pencil.

Thank you

**Comment by freeheel3r** [comment]
Hi,
There's no setting for this, no.
However, if you want to build OpenBoard from source, you can easily modify the code that specifies which cursors are used. It is in [src/gui/UBResources.cpp](https://github.com/OpenBoard-org/OpenBoard/blob/master/src/gui/UBResources.cpp#L69), and the possible cursor shapes are listed in the Qt documentation [here](http://doc.qt.io/qt-5/qt.html#CursorShape-enum).

**Comment by klorophatu** [comment]
I really wish this would become a simple checkbox in the program preferences. Some schools have been using this software and the cross cursor is very annoying. @watsaig

**Comment by letsfindaway** [comment]
First of all: commenting a closed issue is likely not to be recognized by anyone. But I did!

I think you can get what you want quite easily. It is not a checkbox, but accessible from the settings.

* Go to the Openboard > settings menu
* Select the "Pen" tab
* At the bottom, there is somethink like (here in german)
![image](https://user-images.githubusercontent.com/35591413/118091210-da2bc780-b3ca-11eb-815f-d08e46563f63.png)
* In the first line, keep the checkmark selected, but change px to "1".

This tells OpenBoard to replace the crosshair cursor by a circle in the diameter of the pen already for very thin pens, and at least for me this works perfectly on a tablet.
