### ISSUE TITLE
[Building/Packaging] Cmake error: Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

### ISSUE THREAD

**Issue by BingoZha** [OpenBoard-org/OpenBoard#915]
I tried to use cmake-gui to generate solution and the error occurred.

**Versions**
- OpenBoard version 1.7.1rc-240308
- Qt version 6.5.3
- third-party : latest
- OS: windows11
- vs version: 2022

**Error messages**
Version 1.7.1-rc.240308
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
Using Qt6
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  cmake/DependencyPoppler.cmake:11 (find_package)
  CMakeLists.txt:111 (include)

I found that Poppler_FOUND is false, should i need to set Poppler_DIR? how?

**Comment by letsfindaway** [comment]
Please consult https://github.com/OpenBoard-org/OpenBoard/wiki/CMake-Build-System-for-Linux for further information on the `cmake` build system.

Please note that the project assets (installers and packages) are all built using the `qmake` build system. CMake builds are a community contribution (well, in fact my work) to help building OpenBoard for other Linux distros and are currently only usable on Linux. The CMake files are not prepared to be used for Windows or MacOS.

Build instructions for Windows can be found here: https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows

**Comment by BingoZha** [comment]
> Please consult https://github.com/OpenBoard-org/OpenBoard/wiki/CMake-Build-System-for-Linux for further information on the `cmake` build system and in which case you should use `qmake` or `cmake`.
> 
> Please note that the project assets (installers and packages) are all built using the `qmake` build system. CMake builds are a community contribution (well, in fact my work) to help building OpenBoard for other Linux distros and are currently only usable on Linux. The CMake files are not prepared to be used for Windows or MacOS.
> 
> Build instructions for Windows can be found here: https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows

Thank for your help.I used qmake/nmake and qt creator to compile project perfectly, I just want to debug in visual studio,so i tried to use cmake compile in windows.
