### ISSUE TITLE
Screen annotation mode

### ISSUE THREAD

**Issue by pgilfernandez** [OpenBoard-org/OpenBoard#92]
Sometimes when you are teaching you need to show a software, web page, etc. and you want to do some annotations over the screen itself while continuing using the computer in "desktop mode" but not as the current OpenBoard one.
I think it would be very handy to have one mode similar to "desktop mode" but that behaves like a normal "screen annotation" software ([example 1](http://ink2go.org/), [example 2](http://krugazor.eu/highlight/), [example 3](https://www.youtube.com/watch?v=rwd47ezrkXM)).
I think it's just a matter of how to config OpenBoard to do that tasks without the real need to hard code new features...
Of course it would be necessary to set some new shortcuts, let the user go easily from "board mode" to "desktop mode" to "screen annotation mode" with shortcuts, etc...

I think it would be a killer feature!

**Comment by freeheel3r** [comment]
I don't think I understand -- how is that different from desktop mode?

**Comment by pgilfernandez** [comment]
Pretty similar, yes, but when I start drawing in "desktop mode" I cannot turn to a clean screen with OpenBoard tools to the screen side and continue browsing the web browser or using the software. Maybe it's just a matter of adding a "delete all" button in the side toolbar...
... or maybe it's a bug in macOS...

Thanks!

**Comment by freeheel3r** [comment]
Oh. You can delete everything at once by long-clicking on the Eraser button, then clicking the right-most icon that pops up:
![image](https://user-images.githubusercontent.com/686868/27047282-8c264dfc-4f75-11e7-8240-1a6aece68198.png)

**Comment by pgilfernandez** [comment]
Hi,
Yes, I tried it and it works, thanks.

Anyway I think it would be nice to have the "erase all annotations" button in the main toolbar as well as the line tool that is missing.

Finally, it would be great in there is the option to use keyboard shortcuts or hotkeys to quickly access the tools in order to speed up the class explanation (you loose time selecting tools, deleting screen, etc...)

Thanks!
