### ISSUE TITLE
[Question]Problem with background and applications when saving file as .pdf

### ISSUE THREAD

**Issue by okropka** [OpenBoard-org/OpenBoard#924]
Hello, in the new version of OpenBoard, .pdf files do not save the background and some applications, for example the number line, ruler or set square. Students cannot see the full lesson notes. Best regards, Malgorzata Zmyslowska, mathematics teacher
[test 1.pdf](https://github.com/OpenBoard-org/OpenBoard/files/14736758/test.1.pdf)
[test 1 oryginal.pdf](https://github.com/OpenBoard-org/OpenBoard/files/14736763/test.1.oryginal.pdf)

**Comment by letsfindaway** [comment]
At least for the axes this is an error. They have to be included in the export. Other tools like the Compass are intentionally omitted from the export. For the ruler one could argue for both, but I think here also was the intention to omit such supporting tools on export.

**Comment by letsfindaway** [comment]
... and for the background export: there is an option to enable this!

- Locate your user configuration file according to this wiki page: [Configuration](https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration)
- Add an entry according to this wiki page: [Parameters](https://github.com/OpenBoard-org/OpenBoard/wiki/Parameters#pdf-section)

```ini
[PDF]
ExportBackgroundGrid=true
ExportBackgroundColor=true
```

The first setting enables export of the grid, the second export of the light or dark color.

**Comment by letsfindaway** [comment]
The just-released version 1.7.2 of OpenBoard fixes the problem exporting axes. For the background grid I already gave the hint how to enable this. And for the ruler and other tools this is intentionally. If you need specifically this possibility, then please open a feature request for it and describe your use case and needs.
