### ISSUE TITLE
Videos para YouTube ¿Se pueden hacer sin pedir permiso?

### ISSUE THREAD

**Issue by Muntane1989** [OpenBoard-org/OpenBoard#928]
Hola a todos, soy profesor de matemática y voy a realizar videos para subirlos a YouTube, estoy buscando una plataforma para hacerlo y quiero saber si tengo que pedir permiso en algún lado para poder usarlo en mis videos, desde ya muchas gracias.

**Comment by letsfindaway** [comment]
OpenBoard is free software. You can use it to create videos for whatever purpose without asking for permission.

Enjoy it!
