### ISSUE TITLE
[Question] Is This app free to use?

### ISSUE THREAD

**Issue by bazzazi** [OpenBoard-org/OpenBoard#930]
Is it legal to use this app in youtube educational videos?
is it free to use?

**Comment by letsfindaway** [comment]
Duplicate issue.

Your question was already answered here https://github.com/OpenBoard-org/OpenBoard/issues/929#issuecomment-2028029047 and here https://github.com/OpenBoard-org/OpenBoard/issues/928#issuecomment-2027303714
