### ISSUE TITLE
What is the latest version of OpenBoard that works with Windows 7?

### ISSUE THREAD

**Issue by williamhunt** [OpenBoard-org/OpenBoard#933]

**Comment by letsfindaway** [comment]
Are you referring to a 32bit version? Then 1.5.4 is the latest: https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.5.4

If you're referring to a 64bit version, then you have to try. Windows 7 is no longer supported for years and the OpenBoard project is not testing new releases with Windows 7.

See also #544 and #656
