### ISSUE TITLE
Compilation error on Debian Stretch

### ISSUE THREAD

**Issue by rafoo** [OpenBoard-org/OpenBoard#94]
English version below.

Bonsoir, je tente de compiler OpenBoard sur Debian 9 (Stretch) sur une architecture i686 (pas supportée par le paquet Ubuntu qui est pour amd64). En suivant les instructions du Readme, j'ai pu installer les dépendances du dépôt OpenBoard-ThirdParty mais je bloquais au qmake d'OpenBoard jusqu'à tomber sur https://github.com/OpenBoard-org/OpenBoard/wiki/Install. Je bloque désormais au make d'OpenBoard qui produit l'erreur copiée en fin de message.

Pour info, j'utilise Qt 5.7.1 et OpenSSL 1.1.0.

Good evening, I am trying to compile OpenBoard on Debian 9 (Stretch) on a i686 architecture (not suported by the Ubuntu package for amd64). Following the instructions on the Readme, I managed to install the dependencies from the OpenBoard-ThirdParty repository but I used to be blocked at OpenBoard's qmake until I found https://github.com/OpenBoard-org/OpenBoard/wiki/Install. I am now blocked at OpenBoard's make producing the following error message.

I use Qt5.7.1 and OpenSSL 1.1.0.

```
g++ -c -pipe -fopenmp -O2 -w -D_REENTRANT -fPIC -DQUAZIP_STATIC -DNO_THIRD_PARTY_WARNINGS -DUBVERSION="\"1.3.6."\" -DUBVERSION_RC=1,3,6,240,0 -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -Isrc -I../OpenBoard-ThirdParty/zlib/1.2.8/include -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04 -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04/goo -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04/splash -Isrc/web/browser -Isrc/pdf-merger -I../OpenBoard-ThirdParty/quazip -I../OpenBoard-ThirdParty/zlib/1.2.8/include -I../OpenBoard-ThirdParty/quazip/quazip-0.7.1 -I../OpenBoard-ThirdParty/qt/singleapplication -I../OpenBoard-ThirdParty/qt/singleapplication -I../OpenBoard-ThirdParty/qt/lockedfile -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtWebKit -isystem /usr/include/i386-linux-gnu/qt5/QtSvg -isystem /usr/include/i386-linux-gnu/qt5/QtUiTools -isystem /usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtMultimedia -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtXmlPatterns -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Ibuild/linux/release/moc -Ibuild/linux/release/ui -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o build/linux/release/objects/UBApplication.o src/core/UBApplication.cpp
In file included from src/core/UBApplication.cpp:66:0:
src/frameworks/UBCryptoUtils.h:63:24: error: field ‘mAesEncryptContext’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
         EVP_CIPHER_CTX mAesEncryptContext;
                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from src/frameworks/UBCryptoUtils.h:34,
                 from src/core/UBApplication.cpp:66:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
In file included from src/core/UBApplication.cpp:66:0:
src/frameworks/UBCryptoUtils.h:64:24: error: field ‘mAesDecryptContext’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
         EVP_CIPHER_CTX mAesDecryptContext;
                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from src/frameworks/UBCryptoUtils.h:34,
                 from src/core/UBApplication.cpp:66:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
Makefile.Release:3530 : la recette pour la cible « build/linux/release/objects/UBApplication.o » a échouée
```

**Comment by freeheel3r** [comment]
Bonjour/Hi,
Please see issue #89 , which seems to be the same as this one.
good luck!

**Comment by rafoo** [comment]
Thank you for pointing issue #89, I have managed to install OpenBoard. Here is what I did:
- remove the `libssl-dev` package,
- install the `libcrypto1.0.2-dev` package
- install OpenSSL version 1.0.2l from source
  - download tarball from https://www.openssl.org/source/openssl-1.0.2l.tar.gz
  - uncompress it using `tar zxvf openssl-1.0.2l.tar.gz`
  - configure using `./config -Wl,-rpath=/usr/local/ssl/lib` as suggested on https://wiki.openssl.org/index.php/Compilation_and_Installation
  - `make`
  - `sudo make install`
- patch OpenBoard.pro as follow:
```
diff --git a/OpenBoard.pro b/OpenBoard.pro
index 673e51d7..09b399bc 100644
--- a/OpenBoard.pro
+++ b/OpenBoard.pro
@@ -44,6 +44,7 @@ QT += printsupport
 QT += core
 
 INCLUDEPATH += src
+INCLUDEPATH = "/usr/local/ssl/include" + $${INCLUDEPATH}
 
 include($$THIRD_PARTY_PATH/libs.pri)
 include(src/adaptors/adaptors.pri)
@@ -161,7 +162,7 @@ macx {
    LIBS += -framework Carbon
    LIBS += -framework AVFoundation
    LIBS += -framework CoreMedia
-   LIBS += -lcrypto
+   LIBS += -l:libcrypto.so.1.0.2
 
    CONFIG(release, debug|release):CONFIG += x86_64
    CONFIG(debug, debug|release):CONFIG += x86_64
@@ -400,7 +401,7 @@ macx {
 
 linux-g++* {
     CONFIG += link_prl
-    LIBS += -lcrypto
+    LIBS += -l:libcrypto.so.1.0.2
     #LIBS += -lprofiler
     LIBS += -lX11
     QMAKE_CFLAGS += -fopenmp
```
- follow OpenBoard compilation instructions

**Comment by chbmeyer** [comment]
Hello there,

I see this Issue is closed now, but I couldn't build OpenBoard on Debian stretch (9.1) with obove guide.
There is no package called libcrypto1.0.2-dev in stretch, some build dependencies are missing and it isn't neccessary to build OpenSSL from sources.
Beside of this the package.sh script to build the final .deb gave errors like:
```
dpkg-query: error: --print-avail needs a valid package name but 'zlib1g' is not:
ambiguous package name 'zlib1g' with more than one installed instance
```
Anyway. Here is what I did to build OpenBoard with Debian 9 Stretch (with Multiarch enabled):

# HowTo build OpenBoard for Debian 9 (stretch)
## 1. Install the build environment (as root):
\# `apt-get install make gcc g++ git`
\# `apt-get install qt5-default libqt5svg5-dev libqt5webkit5-dev libqt5xmlpatterns5-dev qtscript5-dev libpaper-dev libmotif-dev qtmultimedia5-dev qttools5-dev libssl1.0-dev`

## 2. Get OpenBoard (as normal user):
$ `mkdir ~/OpenBoard`
$ `cd ~/OpenBoard/`
$ `git clone https://github.com/OpenBoard-Org/OpenBoard.git`
$ `git clone https://github.com/OpenBoard-Org/OpenBoard-Importer.git`
$ `git clone https://github.com/OpenBoard-Org/OpenBoard-ThirdParty.git`

## 3. Patch the ssl issue (as normal user):
\# Patch from rafoo at https://github.com/OpenBoard-org/OpenBoard/issues/94 , replace lcrypto by libcrypto.so.1.0.2:
$ `sed -i -e 's:lcrypto:l\:libcrypto.so.1.0.2:' ./OpenBoard/OpenBoard.pro`
$ `sed -i -e 's:^INCLUDEPATH += src$:INCLUDEPATH += src\nINCLUDEPATH = "/usr/local/ssl/include" + $${INCLUDEPATH}:' ./OpenBoard/OpenBoard.pro`

## 4. Build the package
### 4.1 First build Third-Party stuff
(yes, this is really neccessary)

$ `cd OpenBoard-ThirdParty/freetype/`
$ `qmake freetype.pro -spec linux-g++`
$ `make`

$ `cd ../quazip`
$ `qmake quazip.pro -spec linux-g++`
$ `make`

$ `cd ../xpdf/xpdf-3.04`
$ `./configure --with-freetype2-library="../../freetype/lib/linux" --with-freetype2-includes="../../freetype/freetype-2.6.1/include"`
$ `cd ..`
$ `qmake xpdf.pro -spec linux-g++`
$ `make`

$ `cd ../../OpenBoard-Importer`
$ `qmake OpenBoardImporter.pro -spec linux-g++`
$ `make`

\# Dont' forget to go back to the maindir
$ `cd ..`

### 4.2. Build OpenBoard (as normal user):
$ `./OpenBoard/release_scripts/linux/build.sh`

### 4.3. Build the Debian package (as root):
\# `./OpenBoard/release_scripts/linux/package.sh`
When you do not get any errors you are done.

I have multiarch enabled and I got many errors like this one:
```
dpkg-query: error: --print-avail needs a valid package name but 'zlib1g' is not:
ambiguous package name 'zlib1g' with more than one installed instance
```
So I had to fix the script `package.sh`:

### 4.4. Patch package.sh for multiarch support:
\# `sed -i -e 's:dpkg -p \${tab\[\$i\]}:dpkg -p \${tab\[\$i\]}\:$ARCHITECTURE:' ./OpenBoard/release_scripts/linux/package.sh`

and then run
\# `./OpenBoard/release_scripts/linux/package.sh` again.
The installable Debian package can be found here:

./OpenBoard/install/linux/openboard_debian_9.1_1.3.6_amd64.deb

**Comment by mehmetaksakal** [comment]
Have you tried libssl1.0-dev?

**Comment by chbmeyer** [comment]
@mehmetaksakal I think you missunderstood me. Beside other things, this is what I did to get it work and what I summarized to the little "HowTo".  There is no need to build OpenSSL from sources.
Thank you for your help.

**Comment by lebardix** [comment]
a little error on Patch package.sh for multiarch support:

sed -i -e 's:dpkg -p \${tab\[\$i\]}:dpkg -p \${tab\[\$i\]}\:$ARCHITECTURE:' ./OpenBoard/release_scripts/linux/package.sh

replace option -p with -s

sed -i -e 's:dpkg -p \${tab\[\$i\]}:dpkg **-s** \${tab\[\$i\]}\:$ARCHITECTURE:' ./OpenBoard/release_scripts/linux/package.sh

**Comment by lebardix** [comment]
@chbmeyer  hi,
in debian 9.2, after build with your comment, I have some problems with install gdebi ./OpenBoard/install/linux/openboard_debian_9.2_1.3.6_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Ce paquet ne peut pas être installé
Dependency is not satisfiable: libqt5svg5 (>= 5.7.1)

but libqt5svg5 allready installed
```
dpkg -s libqt5svg5
Package: libqt5svg5
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 464
Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: qtsvg-opensource-src (5.7.1~20161021-2)
Version: 5.7.1~20161021-2+b2
Provides: qtsvg-abi-5-6-0
Depends: libc6 (>= 2.14), libqt5core5a (>= 5.7.1~20161021+dfsg~), libqt5gui5 (>= 5.7.1~20161021+dfsg~), libqt5widgets5 (>= 5.7.1~20161021+dfsg~), libstdc++6 (>= 5), qtbase-abi-5-7-1, zlib1g (>= 1:1.1.4)
Pre-Depends: dpkg (>= 1.15.6~)
Description: Qt 5 SVG module
 Qt is a cross-platform C++ application framework. Qt's primary feature
 is its rich set of widgets that provide standard GUI functionality.
 .
 The QtSvg module provides classes for displaying the contents of SVG files.
 .
 Scalable Vector Graphics (SVG) is a language for describing two-dimensional
 graphics and graphical applications in XML.
Homepage: http://qt-project.org/
```
where is the problem ? did you except this ?
thanks

**Comment by lebardix** [comment]
To resolve installation dependency issues, leave Full Version names

```
diff --git a/release_scripts/linux/package.sh b/release_scripts/linux/package.sh
index f64ddec3..88d50340 100755
--- a/release_scripts/linux/package.sh
+++ b/release_scripts/linux/package.sh
@@ -348,7 +348,7 @@ for ((i=0;i<${#tab[@]};i++)); do
         echo -n ",    " >> "$CONTROL_FILE"
     fi
     
-    echo -n "${tab[$i]} (>= "`dpkg -p ${tab[$i]} | grep "Version: " | awk '{      print $2 }' | sed -e 's/\([:. 0-9?]*\).*/\1/g' | sed -e 's/\.$//'`") " >> "$CONTROL_FILE"
+    echo -n "${tab[$i]} (>= "`dpkg -p ${tab[$i]} | grep "Version: " | awk '{      print $2 }' `") " >> "$CONTROL_FILE"
 done
 echo -n ",  onboard" >> "$CONTROL_FILE"
```

**Comment by mehmetaksakal** [comment]
@chbmeyer I was reffering to the 3th step of your guide. If you just have libssl1.0-dev installed then the packagemanager should make symlinks so you don't have to patch.

**Comment by chbmeyer** [comment]
@ mehmetaksakal 
[Debian Wiki](https://wiki.debian.org/OpenSSL-1.1) says: "We have a mix of libssl1.0 and libssl1.1 users. ... The OpenSSL 1.0 package should be removed in the Buster cycle."

I didn't care about installed libssl versions and used a freshly installed Debian Stretch.
Building OpenBoard failed at this point so I had to fix it.

$ ls /usr/*/*/lcrypto*
ls: cannot access '/usr/*/*/lcrypto*': No such file or directory
$ ls /usr/*/*/libcrypto*
/usr/lib/i386-linux-gnu/libcrypto.so.1.1  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
/usr/lib/x86_64-linux-gnu/libcrypto.a     /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libcrypto.so

$ dpkg -l libssl*
un  libssl-dev           <keine>         <keine>         (keine Beschreibung vorhanden)
ii  libssl1.0-dev:amd64  1.0.2l-2        amd64           Secure Sockets Layer toolkit - development fi
ii  libssl1.0.2:amd64    1.0.2l-2        amd64           Secure Sockets Layer toolkit - shared librari
ii  libssl1.1:amd64      1.1.0f-3        amd64           Secure Sockets Layer toolkit - shared librari
ii  libssl1.1:i386       1.1.0f-3        i386            Secure Sockets Layer toolkit - shared librari

**Comment by the-cad** [comment]
Hello to everybody,
I tried to compile the .deb for OpenBoard the whole day - first thanks to the work and the how-tos here.
Finally I was able to build the .deb-file but I got the same problem as lebardix commented on Okt 27. Unfortunately I have no idea what to do with the code posted by lebardix one day later.
Can anybody help me how I can install OpenBoard when gdebi says, that the dependency (libqt5svg5 (>= 5.7.1)) is said to be missing although it is installed???
Thanks for help!!!!

**Comment by the-cad** [comment]
Sorry - I forgot: I'm using Debian 6.3.0 - 18 amd64

**Comment by chbmeyer** [comment]
Debian 6 is rather old.
IIRC I changed the program version of several dependecys. Just try to
remove the version in the debian config of openboard.

It just should be libqt5svg5 without :"(>= 5.7.1)".

Please report back.

**Comment by the-cad** [comment]
Wrong Number, sorry - Debian Stretch 9.3.0 - amd64
I have no Idea how I can remove the version - where do I find the debian config file???

**Comment by the-cad** [comment]
SOLVED
If anybody faces the same problem, just do this:
#Create a temporary folder:
mkdir debcontent
 
# unpack the deb-package {OpenBoardxxx.deb} to folder debcontent ..
dpkg-deb --extract {OpenBoardxxx.deb} debcontent
 
# extract control-file from the package..
dpkg-deb --control {OpenBoardxxx.deb} debcontent/DEBIAN
 
# edit control-file e.g. remove versions ..
nano debcontent/DEBIAN/control
 
# build new package ..
dpkg --build debcontent {OpenBoardYYYYEDIT.deb}

Installing the new package should now work - it did for me

**Comment by aderbalbotelho** [comment]
Compilation error in debian 9.4

./OpenBoard/release_scripts/linux/build.sh

(...)

g++ -c -m64 -pipe -std=c++11 -fopenmp -O2 -w -D_REENTRANT -fPIC -DQUAZIP_STATIC -DNO_THIRD_PARTY_WARNINGS -DUBVERSION="\"1.4.0."\" -DUBVERSION_RC=1,4,0,240,0 -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I/usr/local/ssl/include -I+ -Isrc -I../OpenBoard-ThirdParty/zlib/1.2.8/include -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04 -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04/goo -I../OpenBoard-ThirdParty/xpdf/xpdf-3.04/splash -Isrc/web/browser -Isrc/pdf-merger -I../OpenBoard-ThirdParty/quazip -I../OpenBoard-ThirdParty/zlib/1.2.8/include -I../OpenBoard-ThirdParty/quazip/quazip-0.7.1 -I../OpenBoard-ThirdParty/qt/singleapplication -I../OpenBoard-ThirdParty/qt/singleapplication -I../OpenBoard-ThirdParty/qt/lockedfile -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/linux/release/moc -Ibuild/linux/release/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/linux/release/objects/UBGraphicsRuler.o src/tools/UBGraphicsRuler.cpp
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp: In member function ‘bool UBFFmpegVideoEncoder::init()’:
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:415:33: error: ‘swr_alloc’ was not declared in this scope
         mSwrContext = swr_alloc();
                                 ^
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:430:35: error: ‘swr_init’ was not declared in this scope
         ret = swr_init(mSwrContext);
                                   ^
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp: In member function ‘void UBFFmpegVideoEncoder::processAudio(QByteArray&)’:
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:550:74: error: ‘swr_get_out_samples’ was not declared in this scope
     int outSamplesCount = swr_get_out_samples(mSwrContext, inSamplesCount);
                                                                          ^
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:567:67: error: ‘swr_convert’ was not declared in this scope
                       (const uint8_t **)&inSamples, inSamplesCount);
                                                                   ^
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp: In member function ‘void UBFFmpegVideoEncoder::finishEncoding()’:
src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp:650:30: error: ‘swr_free’ was not declared in this scope
         swr_free(&mSwrContext);
                              ^
Makefile.Release:5915: recipe for target 'build/linux/release/objects/UBFFmpegVideoEncoder.o' failed
make[1]: *** [build/linux/release/objects/UBFFmpegVideoEncoder.o] Error 1
make[1]: ** Esperando que outros processos terminem.
make[1]: Leaving directory '/home/educatux/Openboard/OpenBoard'
Makefile:48: recipe for target 'release-install' failed
make: *** [release-install] Error 2
error: OpenBoard build failed
educatux@EducatuX:~/Openboard$

**Comment by Arvil** [comment]
@aderbalbotelho  This seems to work for me (on Ubuntu Bionic but this should not make any difference) :
```
diff --git a/src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp b/src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp
index 320464dd..5155ed32 100644
--- a/src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp
+++ b/src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp
@@ -20,6 +20,7 @@
  */
 
 #include "UBFFmpegVideoEncoder.h"
+#include "libswresample/swresample.h"
 
 // Due to the whole FFmpeg / libAV silliness, we have to support libavresample instead
 // of libswresapmle on some platforms, as well as now-obsolete function names
```

**Comment by chbmeyer** [comment]
@Arvil: Thanks for your patch including swresample. I found it helpfull for debian, too. Beside this there are tons of multimedia dev-things needed for openboard 1.4

@lebardix : your patch doesn't work any more, the code in package.sh has changed. Now you have to change the variable depdVer from:
depdVer=$(apt-cache show ${tab[$i]} | grep "Version: " | head -1 | awk '{ print $2 }' | sed -e 's/\([:. 0-9?]*\).*/\1/g' | sed -e 's/\.$//')
to:
depdVer=$(apt-cache show ${tab[$i]} | grep "Version: " | head -1 | awk '{ print $2 }')

Because of that I updated my Comment above, now it works again for me:
https://github.com/OpenBoard-org/OpenBoard/issues/94#issuecomment-336723307

**Comment by sunweaver** [comment]
Note, that I have started packaging OpenBoard for Debian: https://salsa.debian.org/debian-edu-pkg-team/openboard/
