### ISSUE TITLE
Get Error Message when I click on keyboard icon

### ISSUE THREAD

**Issue by erick13791** [OpenBoard-org/OpenBoard#945]
When I click on:

<img width="92" alt="image" src="https://github.com/OpenBoard-org/OpenBoard/assets/113171581/33f0d8f7-63b5-4fb1-8cb1-87a5e7336f80">

I get the following error message on Macbook Pro

<img width="360" alt="image" src="https://github.com/OpenBoard-org/OpenBoard/assets/113171581/dd068134-b6d4-4852-b503-5117485e504e">

**Comment by sebojolais** [comment]
I answer you just to propose a workaround, not a solution to your error message.

In OpenBoard, there are two kind of virtual keyboards:
- one that comes from the OS
- and a second built internally in OB.

And You can switch between the 2 modes.
In your case, it seems that you set the keyboard from MacOS. This one throw an error.
Try with the second one should work around the error.

Menu `OpenBoard` -> `Preferences` -> `Display` tab -> `Virtual Keyboard` section -> uncheck `Use system keyboard (recommended)`

**Comment by kaamui** [comment]
Hi @erick13791,

 sorry for the late reply : 

You need to go to System Preferences -> KeyBoard -> Tab "Input Methods" and check the "display the input methods in the menus toolbar".
