### ISSUE TITLE
[Building/Packaging] missing .desktop file

### ISSUE THREAD

**Issue by Eloitor** [OpenBoard-org/OpenBoard#952]
**Describe the problem**
A desktop file is missing.

**Suggestions, solutions**

OpenBoard.desktop
```
[Desktop Entry]
Encoding=UTF-8
Name=OpenBoard
Comment=OpenBoard, an interactive white board application.
Exec=OpenBoard %f
Icon=/opt/openboard/OpenBoard.png
StartupNotify=true
Terminal=false
Type=Application
MimeType=application/ubz
Categories=Education;
```

**Comment by MechDR** [comment]
The .deb file installs in `/opt/oopenboard`, so the icon location should be `/opt/openboard/OpenBoard.png`. I just made the name and the location of the Void package be the same as the package name (`/opt/OpenBoard`), so it's correct, but for Void.

**Comment by Eloitor** [comment]
Updated, thanks
