### ISSUE TITLE
Sofware Open Board

### ISSUE THREAD

**Issue by NguyenVu1985** [OpenBoard-org/OpenBoard#957]
I want to ask Open Board with a dedicated version for 4K interactive TV sreen. How will pay sofware CO?
vuzodiac@gmail.com
tamvh@zodiac.com.vn

**Comment by kaamui** [comment]
Hi,

Sorry if I didn't understand what you were asking for. There is only one version of OpenBoard that is officially supported, and provided for Windows, Ubuntu 20&22 and macOS. 

In terms of hardware, This OpenBoard version officially supports and is tested with Wacom Cintiq devices. We don't aim to spend time on interactive TV screens support.
