### ISSUE TITLE
[Building/Packaging] OpenBoard 1.7.1 fails to build on Arch Linux due to poppler version 24.05.0 requiring C++'20

### ISSUE THREAD

**Issue by maehne** [OpenBoard-org/OpenBoard#958]
**Describe the problem**

OpenBoard 1.7.1 fails to build on Arch Linux using the AUR package [openboard](https://aur.archlinux.org/packages/openboard). Root cause is that its `CMakeLists.txt` sets in line 83 `CXX_STANDARD` to 17. However, poppler version 24.05.0 requires `CXX_STANDARD` set to 20, as can be seen [here](https://gitlab.freedesktop.org/poppler/poppler/-/commit/d8ae3ba659c71b4f5913ecf74d525461bb831366).

**Versions**

- OpenBoard version 1.7.1
- Qt version 6.7.0
- poppler version 24.05.0
- Version for other third-party libraries e.g. poppler, ffmpeg as appropriate

**Build commands**

OpenBoard gets build in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openboard) using the following `cmake` commands:

```bash
  cmake -B build -S "$srcdir"/$_src_folder \
    -DCMAKE_BUILD_TYPE=None \
    -DQT_VERSION=${QT_VER} \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -Wno-dev
  cmake --build build
```
**Error messages**

```
yay -S --asdeps openboard
AUR Explicit (1): openboard-1.7.1-1
:: PKGBUILD up to date, skipping download: openboard
  1 openboard                        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/mht1/.cache/yay/openboard
HEAD is now at 7e976c7 Update to 1.7.1 and switch to cmake community build
Removing openboard-1.7.0-3-x86_64.pkg.tar.zst
Removing openboard-1.7.1-1-x86_64.pkg.tar.zst
Removing v1.7.0.tar.gz
Removing v1.7.1.tar.gz
  1 openboard                        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: openboard 1.7.1-1 (Fr 10 Mai 2024 10:22:50)
==> Retrieving sources...
  -> Downloading v1.7.1.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 60.1M    0 60.1M    0     0  5603k      0 --:--:--  0:00:10 --:--:-- 5726k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    v1.7.1.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: openboard
==> Making package: openboard 1.7.1-1 (Fr 10 Mai 2024 10:23:03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v1.7.1.tar.gz
==> Validating source files with sha256sums...
    v1.7.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v1.7.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: openboard 1.7.1-1 (Fr 10 Mai 2024 10:23:05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
-- Version 1.7.1
-- The CXX compiler identification is GNU 14.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Using Qt6
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Found OpenSSL: /usr/lib/libcrypto.so (found suitable version "3.3.0", minimum required is "1.1")
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for modules 'poppler;poppler-cpp'
--   Found poppler, version 24.05.0
--   Found poppler-cpp, version 24.05.0
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")
-- Checking for modules 'libavcodec;libavformat;libavutil;libswresample;libswscale'
--   Found libavcodec, version 60.31.102
--   Found libavformat, version 60.16.100
--   Found libavutil, version 58.29.100
--   Found libswresample, version 4.12.100
--   Found libswscale, version 7.5.100
-- OpenBoard ETC_PREFIX is /etc/openboard
-- OpenBoard APP_PREFIX is /usr/share/openboard
-- OpenBoard TPL_PREFIX is /usr/share/openboard/template
-- Configuring done (2.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/mht1/.cache/yay/openboard/src/build
[  0%] Built target SingleApplication_autogen_timestamp_deps
[  0%] Automatic MOC and UIC for target SingleApplication
[  0%] Built target SingleApplication_autogen
[  1%] Building CXX object src/singleapplication/CMakeFiles/SingleApplication.dir/SingleApplication_autogen/mocs_compilation.cpp.o
[  1%] Building CXX object src/singleapplication/CMakeFiles/SingleApplication.dir/singleapplication.cpp.o
[  1%] Building CXX object src/singleapplication/CMakeFiles/SingleApplication.dir/
[...]
[ 24%] Building CXX object CMakeFiles/openboard.dir/src/adaptors/UBImportImage.cpp.o
[ 24%] Building CXX object CMakeFiles/openboard.dir/src/adaptors/UBImportPDF.cpp.o
In file included from /usr/include/poppler/Object.h:44,
                 from /home/mht1/.cache/yay/openboard/src/build/openboard_autogen/QM7XBKFLFB/../../../OpenBoard-1.7.1/src/pdf/XPDFRenderer.h:41,
                 from /home/mht1/.cache/yay/openboard/src/build/openboard_autogen/QM7XBKFLFB/moc_XPDFRenderer.cpp:9,
                 from /home/mht1/.cache/yay/openboard/src/build/openboard_autogen/mocs_compilation.cpp:108:
/usr/include/poppler/goo/GooString.h:241:24: error: ‘starts_with’ has not been declared in ‘std::string’
  241 |     using std::string::starts_with;
      |                        ^~~~~~~~~~~
/usr/include/poppler/goo/GooString.h:244:24: error: ‘ends_with’ has not been declared in ‘std::string’
  244 |     using std::string::ends_with;
      |                        ^~~~~~~~~
[ 25%] Building CXX object CMakeFiles/openboard.dir/src/adaptors/UBMetadataDcSubsetAdaptor.cpp.o
[...]
make[1]: *** [CMakeFiles/Makefile2:430: CMakeFiles/openboard.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: openboard-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
openboard - exit status 4
```

**Suggestions, solutions**

The compilation problem can be fixed simply in OpenBoard's `CMakeLists.txt` by setting in line 83 `CXX_STANDARD` to 20.

**Comment by SarjyantShrestha** [comment]
Thanks for this fix, but it failed to build due to another error.

```
[  4%] Building CXX object CMakeFiles/openboard.dir/src/domain/UBGraphicsWidgetItem.cpp.o
/home/rapzy/build/OpenBoard/src/domain/UBGraphicsWidgetItem.cpp:134:1: error: no matching function for call to ‘QMap<QString, QString>::QMap(<brace-enclosed initializer list>)’
  134 | };
      | ^
In file included from /usr/include/qt/QtCore/qvariant.h:47,
                 from /usr/include/qt/QtCore/qabstractitemmodel.h:43,
                 from /usr/include/qt/QtCore/QtCore:10,
                 from /usr/include/qt/QtNetwork/QtNetworkDepends:3,
                 from /usr/include/qt/QtNetwork/QtNetwork:3,
                 from /home/rapzy/build/OpenBoard/src/domain/UBGraphicsWidgetItem.cpp:30:
/usr/include/qt/QtCore/qmap.h:1097:22: note: candidate: ‘QMap<K, V>::QMap(const std::map<T, U>&) [with Key = QString; T = QString]’
 1097 | Q_OUTOFLINE_TEMPLATE QMap<Key, T>::QMap(const std::map<Key, T> &other)
      |                      ^~~~~~~~~~~~
/usr/include/qt/QtCore/qmap.h:1097:22: note:   candidate expects 1 argument, 46 provided
/usr/include/qt/QtCore/qmap.h:341:12: note: candidate: ‘QMap<K, V>::QMap(QMap<K, V>&&) [with Key = QString; T = QString]’
  341 |     inline QMap(QMap<Key, T> &&other) noexcept
      |            ^~~~
/usr/include/qt/QtCore/qmap.h:341:12: note:   candidate expects 1 argument, 46 provided
/usr/include/qt/QtCore/qmap.h:629:8: note: candidate: ‘QMap<K, V>::QMap(const QMap<K, V>&) [with Key = QString; T = QString]’
  629 | inline QMap<Key, T>::QMap(const QMap<Key, T> &other)
      |        ^~~~~~~~~~~~
/usr/include/qt/QtCore/qmap.h:629:8: note:   candidate expects 1 argument, 46 provided
/usr/include/qt/QtCore/qmap.h:330:12: note: candidate: ‘QMap<K, V>::QMap(std::initializer_list<std::pair<_T1, _T2> >) [with Key = QString; T = QString]’
  330 |     inline QMap(std::initializer_list<std::pair<Key,T> > list)
      |            ^~~~
/usr/include/qt/QtCore/qmap.h:330:12: note:   candidate expects 1 argument, 46 provided
/usr/include/qt/QtCore/qmap.h:329:12: note: candidate: ‘QMap<K, V>::QMap() [with Key = QString; T = QString]’
  329 |     inline QMap() noexcept : d(static_cast<QMapData<Key, T> *>(const_cast<QMapDataBase *>(&QMapDataBase::shared_null))) { }
      |            ^~~~
/usr/include/qt/QtCore/qmap.h:329:12: note:   candidate expects 0 arguments, 46 provided
make[2]: *** [CMakeFiles/openboard.dir/build.make:1647: CMakeFiles/openboard.dir/src/domain/UBGraphicsWidgetItem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:430: CMakeFiles/openboard.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by letsfindaway** [comment]
I got the same error when trying the proposed fix for an Arch build and I don't actually understand this. `QMap` has a constructor for an initializer list and this is even considered in the error message. But the initializer list is interpreted as "46 arguments", even if it is actually just one.

**Comment by Vekhir** [comment]
> Thanks for this fix, but it failed to build due to another error.

For clarity, this second error affects Qt5. Building with Qt6 is fine with the fix.

**Comment by letsfindaway** [comment]
There is a very similar initialization some lines ago in the same file (lines 66-73), which works. The only difference to the next initialization is that the value strings have a `u8` prefix.

The `QMap` constructor for the initializer_list requires the template class T as value, i.e. a `QString`. So there have to be some implicit conversions from `u8""` to `QString`.

A reason could be the different interpretation of such string literals since C++20. See https://en.cppreference.com/w/cpp/language/string_literal in the table at "Explanation". It was a `const char*` before, and is now a `const char8_t*`. According to https://en.cppreference.com/w/c/string/multibyte/char8_t, this is an `const unsigned char`, so the `const` makes the difference.

I think as long as our source files are in UTF8 encoding the prefix could just be omitted. I don't know whether there was a reason to use it. @kaamui : any hints? The Qt documentation has a note:

> Note: Some compilers have bugs encoding strings containing characters outside the US-ASCII character set. Make sure you prefix your string with u in those cases. It is optional otherwise.

Did you hit this problem?

**Comment by Vekhir** [comment]
@letsfindaway 
Your idea with QString conversion brought me to the [`QStringLiteral`](https://doc.qt.io/qt-5/qstring.html#QStringLiteral) macro. It claims to not do any conversion at all while providing the necessary interface for QString.

Long story short, replacing `u8"..."` with `QStringLiteral(u"...")` compiles fine. Note the `u` inside the argument.
Just replacing `u8` with `u` encounters the same error, using `u8` in the argument has an error due to conflicting encodings and omitting the `u` is [not recommended](https://bugreports.qt.io/browse/QTWEBSITE-1078) as it's necessary for some compilers (like [MSVC](https://lists.qt-project.org/pipermail/interest/2023-January/038809.html)).

Would you support a PR in this direction?

**Comment by kaamui** [comment]
> I think as long as our source files are in UTF8 encoding the prefix could just be omitted. I don't know whether there was a reason to use it. @kaamui : any hints? The Qt documentation has a note:
> 
> > Note: Some compilers have bugs encoding strings containing characters outside the US-ASCII character set. Make sure you prefix your string with u in those cases. It is optional otherwise.
> 
> Did you hit this problem?

Yes. I think I hit a MSVC error, something like "characters too large for enclosing character literal type".

**Comment by letsfindaway** [comment]
> @letsfindaway Your idea with QString conversion brought me to the [`QStringLiteral`](https://doc.qt.io/qt-5/qstring.html#QStringLiteral) macro. It claims to not do any conversion at all while providing the necessary interface for QString.
> 
> Long story short, replacing `u8"..."` with `QStringLiteral(u"...")` compiles fine. Note the `u` inside the argument. Just replacing `u8` with `u` encounters the same error, using `u8` in the argument has an error due to conflicting encodings and omitting the `u` is [not recommended](https://bugreports.qt.io/browse/QTWEBSITE-1078) as it's necessary for some compilers (like [MSVC](https://lists.qt-project.org/pipermail/interest/2023-January/038809.html)).
> 
> Would you support a PR in this direction?

I think the `QStringLiteral` macro is a very good approach solving all compatibility problems. So yes, I would support such a PR.

**Comment by Vekhir** [comment]
Done in #962 (fix: Add compatibility with C++20)

**Comment by kaamui** [comment]
Merged

**Comment by Vekhir** [comment]
@kaamui This issue is not quite fixed, since OpenBoard uses C++17. There is #961, which allows overriding this default to e.g. use C++20 when using the `cmake` build system.

**Comment by kaamui** [comment]
@Vekhir ping me when you and @letsfindaway agree it can be merged too and I'll merge it right away.

**Comment by letsfindaway** [comment]
@kaamui please merge #961.

**Comment by kaamui** [comment]
Done.
