### ISSUE TITLE
Can we change the color or transparency of the MASK in applications?

### ISSUE THREAD

**Issue by htakada** [OpenBoard-org/OpenBoard#966]
Hi,
I've just upgtrtaded to 1.7.1 and noticed that the MASK app now is just grey and transparent, 
Can we make it black again ?
Regards

![Screenshot 2024-05-16 at 10 20 03](https://github.com/OpenBoard-org/OpenBoard/assets/3396738/62ed03ca-1689-484d-a8bc-8f72a9d0d47b)

**Comment by kaamui** [comment]
OK I think I have a workaround for you : go to Preferences, click on the "List of screens used for Control, Display and Previous pages" input, and explicitly set the available displays to the only one that your want to use, by clicking on the top left rectangle appearing on the said screen.

You should then have the behavior that you want, like if you had only one screen connected.

**Comment by htakada** [comment]
Thank you!! it worked

**Comment by kaamui** [comment]
A fix will be available in 1.7.2. Thanks again for reporting !

f92baa3
