### ISSUE TITLE
How to use OpenBoard-ThirdParty?

### ISSUE THREAD

**Issue by probonopd** [OpenBoard-org/OpenBoard#97]
Trying to build this on Travis CI, running into issues:

```
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/libs.pri: No such file or directory
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/quazip/quazip.pri: No such file or directory
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/qt/singleapplication/qtsingleapplication.pri: No such file or directory
```

https://www.travis-ci.org/probonopd/OpenBoard/builds/264123598#L515-L518

How to use OpenBoard-ThirdParty?

> First, obtain the third party libraries from the OpenBoard-ThirdParty repository, and build them (instructions are provided for each library).

is a bit ambiguous.

EDIT: After some seraching, I found that https://github.com/OpenBoard-org/OpenBoard-ThirdParty exists. It could be made a git submodule. https://github.com/blog/2104-working-with-submodules

**Comment by freeheel3r** [comment]
Hi,

You can find build instructions here: https://github.com/OpenBoard-org/OpenBoard/wiki/Install

And there are scripts for deploying OpenBoard, you can find them in the[ release_scripts/linux ](https://github.com/OpenBoard-org/OpenBoard/tree/master/release_scripts/linux)folder of the repository. They might be of some help to you.

That said, Travis may be of somewhat limited use given that there are no unit tests currently.

**Comment by probonopd** [comment]
Thanks. I am using it to generate an #AppImage for each git push. That alone should be useful, e.g., for manual testing.

**Comment by probonopd** [comment]
What do I have to do that ../OpenBoard-ThirdParty/qt/singleapplication` contains something?
https://www.travis-ci.org/probonopd/OpenBoard/builds/264147768

**Comment by freeheel3r** [comment]
Hi, sorry for my late reply.

I don't understand what you mean by:

> What do I have to do that ../OpenBoard-ThirdParty/qt/singleapplication contains something?

You don't have to do anything with that library, it is included and built by OpenBoard (see [OpenBoard.pro](https://github.com/OpenBoard-org/OpenBoard/blob/master/OpenBoard.pro#L74))

So you don't have to call 'make install' or anything.

There seems to be a problem with your paths, based on the result of calling qmake on OpenBoard.pro:

```
qmake PREFIX=/usr OpenBoard.pro -spec linux-g++-64
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/libs.pri: No such file or directory
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/quazip/quazip.pri: No such file or directory
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/qt/singleapplication/qtsingleapplication.pri: No such file or directory
Cannot read /home/travis/build/probonopd/OpenBoard-ThirdParty/qt/lockedfile/qtlockedfile.pri: No such file or directory
```

The OpenBoard, OpenBoard-ThirdParty and OpenBoard-Importer directories are assumed to be at the same level. If that isn't the case, you'd want to edit [line 4 of OpenBoard.pro](https://github.com/probonopd/OpenBoard/blob/patch-1/OpenBoard.pro#L4).

Good luck!

**Comment by probonopd** [comment]
Thanks @freeheel3r. Can you spot what I am doing wrong (or missing) in https://github.com/probonopd/OpenBoard/blob/patch-1/.travis.yml?

**Comment by freeheel3r** [comment]
I'm not familiar with Travis or where / how it clones the current repository, but it looks like you cloned OpenBoard-ThirdParty into the OpenBoard folder.

You should either edit the path I mentioned in OpenBoard.pro so that qmake can find the third party libraries, or make sure that you have the OpenBoard and OpenBoard-ThirdParty folders at the same level, not one within another.

**Comment by probonopd** [comment]
I am not sure it is possible to `git clone` two different repositories into the same directory. At the very least, it would  be very non-standard. I think the clean way to do this would be using git submodules.

**Comment by freeheel3r** [comment]
Sure, which is why we *don't* clone them into the same directory.

You need this;
```
- OpenBoard/
- OpenBoard-ThirdParty/
- OpenBoard-Importer/
```

Based on your .yml I believe you have this:

```
- OpenBoard/
| - OpenBoard-ThirdParty/
```

**Comment by probonopd** [comment]
Thanks, that clarifies it!
