### ISSUE TITLE
Latex-Based Formula Editor

### ISSUE THREAD

**Issue by carlosdelfino** [OpenBoard-org/OpenBoard#976]
It would be interesting to have a formula editor based on LATEX, where the LATEX commands for composing formulas would be typed into a text field and this would interpret such commands for composing formulas in real time.

Microsoft Word's formula editor is very similar to what I'm suggesting.

It is a very valid resource for those who teach classes that depend on mathematics to represent transferred knowledge.

**Comment by kaamui** [comment]
Hi,

there is an application called Latex2SVG in OpenBoard (on the OpenBoard library (the right palette in Board Mode), you can find a folder named "Applications". Latex2SVG can be found in. 

The application is quite new and not polished at all, but it is functional : 

1. write your formula
2. it automatically generates an SVG that you can drag and drop on the board
3. close the application when you're done.

Note that the application is based on MathJax : https://docs.mathjax.org/en/latest/basic/mathematics.html
mhchem extension is also enabled for chemistry
