### ISSUE TITLE
Openboard on Ubuntu MATE 16.04 LTS (Raspberry Pi)

### ISSUE THREAD

**Issue by Jayce08** [OpenBoard-org/OpenBoard#98]
Does this work on Ubuntu MATE 16.04 LTS (Raspberry PI). I want to confirm as I saw websites that listed Openboard as debian package.

**Comment by freeheel3r** [comment]
Hi,
Sorry for the late reply. It does work on 16.04, but the packages are compiled for 64 bit architectures. You would need to build OpenBoard yourself to get it working on the Pi (which has an ARM processor).

If you're up to the challenge, this page may help: https://github.com/OpenBoard-org/OpenBoard/wiki/Install#linux

And please report back if you get it to work, you're not the first to ask about this so I'm sure others would appreciate a solution!

**Comment by mehmetaksakal** [comment]
I've done this and can confirm it works. It's as easy as installing all the qt libraries and running the build scripts.

**Comment by mehmetaksakal** [comment]
So here's the step-by-step on how-to build OpenBoard on Armbian, Raspbian or an Ubuntu variant. 

1. Setup your Linux distro on the device, if you need help doing this use Google. Frankly if you do not know how-to correctly setup a distro already, you should reconsider build OpenBoard from source.

2. First lets create a working directory.

`cd ~
mkdir openboard
cd openboard`

3. Setup our build envoirement. Not sure if all these are needed but it's what I used.

`sudo apt-get install build-essential libfontconfig1 mesa-common-dev libglu1-mesa-dev
sudo apt-get install qttools5-dev qtcreator qtdeclarative5-dev qt5-default libqt5multimediawidgets5 qtmultimedia5-dev libqt5webkit5 libqt5webkit5-dev libqt5xmlpatterns5 libqt5xmlpatterns5-dev qtscript5-dev libqt5svg5 libqt5svg5-dev
sudo apt-get install libmotif-common libmotif-dev libpaper-dev libpaper-utils zip`

4. Clone the OpenBoard repositories

`git clone https://github.com/OpenBoard-org/OpenBoard.git
git clone https://github.com/OpenBoard-org/OpenBoard-Importer.git
git clone https://github.com/OpenBoard-org/OpenBoard-ThirdParty.git`

5. Build the 3th party libraries, instructions can be [found here](https://github.com/OpenBoard-org/OpenBoard-ThirdParty/blob/master/README), which are.

`cd freetype
qmake freetype.pro -spec linux-g++
make
cd ..

cd quazip
qmake quazip.pro -spec linux-g++
make
cd ..

cd xpdf/xpdf-3.04
./configure --with-freetype2-library="../../freetype/lib/linux" --with-freetype2-includes="../../freetype/freetype-2.6.1/include"
cd ..
qmake xpdf.pro -spec linux-g++
make
cd ../../`

6. Modify the build script so it points to the correct directory

`cd OpenBoard/release_scripts/linux/`

and run this command

`qtchooser -print-env`

this will printout the QT env variables, the QTTOOLDIR should look like this:

`QTTOOLDIR="/usr/lib/arm-linux-gnueabihf/qt5/bin"`

Copy the path minus the "/bin" at the end. Then edit build.sh:

`nano ./build.sh`

Change the line QT_PATH to reflect your envoirement, should look something like this:

`QT_PATH="/usr/lib/arm-linux-gnueabihf/qt5"`

7. Run the build script using "./build.sh" and after the the packaging script "./package.sh". If your compiler stops with an internal error then you're running out of memory.  Setup a swapfile and rerun the build script.

**Comment by mehmetaksakal** [comment]
And [here's the deb package](https://1drv.ms/u/s!AidUxeS_WEG9-Gzu81z3LLBss6ow) built on Raspbian Stretch 9.

```
uname -a
Linux raspberrypi 4.9.41+ #1023 Tue Aug 8 15:47:12 BST 2017 armv6l GNU/Linux
```

```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
qmake -version
QMake version 3.0
Using Qt version 5.7.1 in /usr/lib/arm-linux-gnueabihf
```

**Comment by mehmetaksakal** [comment]
For people using some other SBC, [here's the deb package](https://1drv.ms/u/s!AidUxeS_WEG9-HSRCzK211x65peC) built on Ubuntu Xenial 16.04.3 and QT 5.5.1

```
uname -a
Linux orangepione 3.4.113-sun8i #18 SMP PREEMPT Thu Jun 15 02:16:06 CEST 2017 armv7l armv7l armv7l GNU/Linux
```
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```
qmake -version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/arm-linux-gnueabihf
```
Built on 27 september 2017:

- first build, limited testing.

**Comment by mehmetaksakal** [comment]
I have many of these board so if these two packages aren't giving you love then post you device and distro details here and I'll look into it **IF and WHEN I have the time**. If by for some luck I do not own your device, you might think about sponsoring me one so I can look into it.

**Comment by nephx** [comment]
Do you have by any chance a package for a Raspberry Pi 3 (armhf)? I want to use this one as on onboard computer for a Promethean AcivePanel. I have not build any packages on a Pi before so I was glad to find your message here...

**Comment by nephx** [comment]
I tried to build opentable myself on the raspberry and everything workes fine up to generating the package. This is the output:
root@raspberrypi:/home/pi/openboard/OpenBoard/release_scripts/linux# ./package.sh
-->  Copying product directory and resources:
	
-->  Copying importer:
	
-->  Stripping importer and main executable:
	
-->  Copying Qt translations:
	
-->  Generating control files for package:
	
dpkg-query: package 'libpaper1' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libx11-6' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5webkit5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5svg5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5multimediawidgets5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5printsupport5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5widgets5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5multimedia5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5gui5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5xmlpatterns5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5network5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5xml5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5script5' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libqt5core5a' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libgles2-mesa' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libgomp1' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'libgcc-6-dev' is not available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
-->  Building package:
	
dpkg-deb: error: parsing file 'debianPackage/DEBIAN/control' near line 10 package 'openboard:armv7l':
 'Depends' field, reference to 'libpaper1': error in version: version string is empty
-->  OpenBoard:
	Package built

**Comment by nazamov** [comment]
Hello everyone!
I need to Open board deb package built on Ubuntu Xenial 16.04.3 and QT 5.5.1,
but now in this location https://1drv.ms/u/s!AidUxeS_WEG9-HSRCzK211x65peC it unavailable.
https://github.com/mehmetaksakal do have that?
If yes, please give me link.
 Thank you very much!

**Comment by nazamov** [comment]
I just tryed to build it, but raspberi crashed while building :((

**Comment by mehmetaksakal** [comment]
The link is up and still working, please check your internet connection or provider. 

I compiled with the latest version of Raspbian Jessie (fully updated) and the latest release of OpenBoard using the instructions provided above and it still works as described. Seeing as it is a rPi and a clean Raspbian setup you can replicate is easily.

Note, compiling will take about a day, so it could be you should just wait longer. If you're having problems with your board I suggest looking into the logs and try resolving those before trying to compile.

**Comment by nazamov** [comment]
Hello!
@mehmetaksakal thanks for answer and comment , but in this link https://1drv.ms/u/s!AidUxeS_WEG9-HSRCzK211x65peC OneDrive says me: This item may be missing or unavailable, or I don't have permission to see that :(.
I fixed all bugs, but after 15-20 hour compiling it shows me unclear error :(.
Аfter correcting the error, I need to wait another 15-20 hours and that is very bad.
What will you advise me?
Thanks!!!

**Comment by ferekin** [comment]
Any chance of another upload for the Raspbian compiled version? Thanks!
