### ISSUE TITLE
How to install in Ipad (iOS)

### ISSUE THREAD

**Issue by EkaSanatani** [OpenBoard-org/OpenBoard#996]
Good day.
Does anyone have instructions on how to install OpenBoard in iPad. 
I've already download the file but couldn't get it installed. 
Thanks

**Comment by letsfindaway** [comment]
Your question rises several other questions for me:

- What file did you download? There are installers for Linux, Windows and MacOS, but OpenBoard does not provide an installer for iPad and OpenBoard does not run on an iPad.
- Are you sure you are on the right project? This is the OpenBoard whiteboard application. I know that there is another project for an Android keyboard which unfortunately had chosen the same name. But they are Android, so again probably no luck with an iPad.

**Comment by EkaSanatani** [comment]
Thanks
