### ISSUE TITLE
[Question] OpenBoard sur MacOS / Erreur lors de l’ouverture du clavier virtuel

### ISSUE THREAD

**Issue by tomtom7810** [OpenBoard-org/OpenBoard#998]
Bonjour

quand je clique sur le bouton de clavier dans OpenBoard sur Mac, j’obtiens l’erreur suivante :

![Image 03-06-2024 à 18 17](https://github.com/OpenBoard-org/OpenBoard/assets/94376384/46b5c132-fc06-49b5-8853-8bac4787f053)

j’ai bien la version la plus récente d’openboard et la version la plus récente de MacOS.

dans les paramètres de macOS d’accessibilité, j’ai bien autoriser openboard

![Image 03-06-2024 à 18 20](https://github.com/OpenBoard-org/OpenBoard/assets/94376384/11840fe1-9261-4cbd-9de5-6cd82db97133)

Pouvez vous m’aider ?

merci

**Comment by kaamui** [comment]
Hello,

il faut activer dans Préférences Système -> Clavier -> onglet "Méthodes de siasie" la case "Afficher le menu de saisie dans la barre des menus"

**Comment by tomtom7810** [comment]
Merci beaucoup pour cette réponse !
Cela resoud mon problème !
